/* Everything that makes this sim Pharmacology lives in this one file; the rest is the
   shared Paper Sim pipeline (template + build + this). 722.544 has NO Canvas quizzes —
   the archive report says so outright — so there are no captures and no parsed bank:
   every question comes from content/authored-*.js (generated by port-intro-pharm.mjs)
   and the page says so, loudly. */

export const PATHS = { bank: null, cap: null };
export const QUIZ = {};
export const ROUTE = [];
export const NO_MOCK = [];
export const EXCLUDE = [];
export const NO_IMAGE_OK = [];

export const META = {
  id: 'pharm-final',
  prefix: 'phf.',
  title: 'Pharm · Paper Sim — Final exam',
  h1: 'Pharm · Paper Sim',
  short: 'Pharm Paper Sim',
  paper: 'Introduction to Pharmacology',
  bankOf: 'this tool’s',
  who: 'Joan',
  aiCtx: 'I’m a first-year nursing student in New Zealand sitting the final exam for Introduction to Pharmacology (multi-choice plus short answers; my lecturer said a short answer is a definition plus an example in 3–4 lines, and that she will not ask about specific drugs).',
  sitting: { what: 'the Pharmacology final', date: '2026-11-06', when: 'Fri 6 Nov, afternoon (time not confirmed yet)', cohortClose: null },
  /* the real paper: 80 min · 50 pts · 30 MCQ + short answers (course calendar). The NUMBER of
     short answers has never been published. 50 − 30 = 20 marks is this tool's arithmetic and
     assumes one mark per MCQ — the page says so rather than inventing a count. */
  shape: { closed: 30, saq: null, saqMarks: 20, minutes: 80, mini: 12 },
  shapeNote: 'The real paper is <b>80 min · 50 marks · 30 multi-choice + short answers</b>. How many short answers has never been published, so the mock deals written questions up to <b>20 marks</b> — that is 50 − 30, assuming one mark per multi-choice. If Joan gives a count in the revision sessions (21, 27, 28 Oct), this changes.',
  saqHint: 'one point each. Joan’s own format (16 Sep): <b>a definition plus an example, 3–4 lines</b>, and no specific-drug questions — if a question here asks for more than that, it is over-training, not her paper',
  sys: {
    found: 'Foundations (Module 1)',
    calc: 'Calculations (Module 2)',
    pkpd: 'Pharmacokinetics & dynamics (Modules 3–4)',
    admin: 'Administration & education (Module 5)',
    life: 'Across the lifespan (Module 6)',
    law: 'Legal, ethical & development (Module 7)',
    imm: 'Allergy & anaphylaxis (Module 8)',
  },
  sysShort: { found: 'Foundations', calc: 'Calcs', pkpd: 'PK/PD', admin: 'Admin', life: 'Lifespan', law: 'Legal', imm: 'Allergy' },
  hue: { found: 210, calc: 38, pkpd: 268, admin: 158, life: 28, law: 340, imm: 190 },
  quizOrder: ['concepts1', 'concepts2', 'calcs', 'pk1', 'pk2', 'pd', 'admin', 'educ', 'elderly', 'lifespan', 'legal', 'devmkt', 'allergy'],
  playlist: null,
  banner: '<b>There is no lecturer question bank for this paper.</b> Pharmacology has never had a Canvas quiz. Every question here was written by this tool from the course’s 14 lecture decks — each one names the slide its answer comes from. It trains the content; it is not Joan’s wording.',
  pickIntro: 'One row per lecture topic — the tool’s questions, multi-choice then written.',
  help: {
    what: 'A practice paper for <b>Introduction to Pharmacology</b> in the same format as the other Paper Sims: drill a topic, learn with the answer shown as you go, or sit a mock in the real paper’s shape. The final is <b>Fri 6 Nov 2026 (afternoon, time not confirmed) · 80 min · 50 marks · 30 multi-choice + short answers · 50% of the paper</b>. Joan said on 16 Sep that a short answer is <b>a definition plus an example in 3–4 lines</b>, and that she will <b>not ask about specific drugs</b> — beyond the four you already know inside out (two for the practical, two for the essay).',
    noBank: '<b>Nothing here was captured from Canvas, because there is nothing to capture:</b> this paper has never had a Canvas quiz.',
    authored: 'All 289 questions — 100 multi-choice and 189 written — were written by the intro-pharm study hub from the 14 lecture decks and carried across unchanged. Each names the slide that supplies its answer, and each multi-choice carries a short explanation that is the tool’s, not Joan’s. <b>The written questions pre-date her 16 Sep description of the exam</b>: many are longer, multi-part questions, and some name specific drugs. They over-train rather than mis-train, but they are not her format yet — short definition-plus-example questions written from her recorded lectures are the next thing to be added. ',
    held: 'Three parts of the course are thin or missing in this bank because the material was not in the Canvas export: <b>Module 8 Vaccines & Immunology</b> (only the ASCIA anaphylaxis plan — the lecture is 7 Oct), <b>Module 9 Licit/Illicit drugs & Toxicology</b> (nothing) and <b>Module 10 CAM/Rongoā</b> (nothing). They are examinable ("all modules"). A clean run here does not cover them.',
  },
  focusCopy: {
    pending: 'The checklist for this paper — every topic, what you must be able to DO, how Joan asks it (definition + example) and where it stops — is not built yet. Two things it will say that matter now: <b>Modules 8, 9 and 10 are barely in this bank</b> (the material was not on Canvas when it was built), and <b>Deck 13, Drug Development & Marketing, was never lectured</b> — it was set as a self-directed online package and is still examinable.',
  },
};
