/* Everything that makes this sim Pharmacology lives in this one file; the rest is the
   shared Paper Sim pipeline (template + build + this). 722.544 has NO Canvas quizzes —
   the archive report says so outright — so there are no captures and no parsed bank:
   every question comes from content/authored-*.js (generated by port-intro-pharm.mjs)
   and the page says so, loudly. */

export const PATHS = { bank: null, cap: null };
export const QUIZ = {};
export const ROUTE = [];
export const NO_MOCK = [];
export const EXCLUDE = [];
export const NO_IMAGE_OK = [];

export const META = {
  id: 'pharm-final',
  prefix: 'phf.',
  title: 'Pharm · Paper Sim — Final exam',
  h1: 'Pharm · Paper Sim',
  short: 'Pharm Paper Sim',
  paper: 'Introduction to Pharmacology',
  bankOf: 'this tool’s',
  who: 'Joan',
  aiCtx: 'I’m a first-year nursing student in New Zealand sitting the final exam for Introduction to Pharmacology (multi-choice plus short answers; my lecturer said a short answer is a definition plus an example in 3–4 lines, and that she will not ask about specific drugs).',
  sitting: { what: 'the Pharmacology final', date: '2026-11-06', when: 'Fri 6 Nov, afternoon (time not confirmed yet)', cohortClose: null },
  /* the real paper: 80 min · 50 pts · 30 MCQ + short answers (course calendar). The NUMBER of
     short answers has never been published. 50 − 30 = 20 marks is this tool's arithmetic and
     assumes one mark per MCQ — the page says so rather than inventing a count. */
  shape: { closed: 30, saq: null, saqMarks: 20, minutes: 80, mini: 12 },
  shapeNote: 'The real paper is <b>80 min · 50 marks · 30 multi-choice + short answers</b>. How many short answers has never been published, so the mock deals written questions up to <b>20 marks</b> — that is 50 − 30, assuming one mark per multi-choice. If Joan gives a count in the revision sessions (21, 27, 28 Oct), this changes.',
  saqHint: 'one point each. Joan’s own format (16 Sep): <b>a definition plus an example, 3–4 lines</b>, no specific-drug questions',
  sys: {
    found: 'Foundations (Module 1)',
    calc: 'Calculations (Module 2)',
    pkpd: 'Pharmacokinetics & dynamics (Modules 3–4)',
    admin: 'Administration & education (Module 5)',
    life: 'Across the lifespan (Module 6)',
    law: 'Legal, ethical & development (Module 7)',
    imm: 'Allergy & anaphylaxis (Module 8)',
    cam: 'Rongoā & CAM (Module 10)',
  },
  sysShort: { found: 'Foundations', calc: 'Calcs', pkpd: 'PK/PD', admin: 'Admin', life: 'Lifespan', law: 'Legal', imm: 'Allergy', cam: 'Rongoā' },
  hue: { found: 210, calc: 38, pkpd: 268, admin: 158, life: 28, law: 340, imm: 190, cam: 120 },
  /* the rows in Joan's stated format come first: they are the closest thing here to her paper */
  quizOrder: ['joan-found', 'joan-pkpd', 'joan-admin', 'joan-life', 'joan-law', 'joan-ethics', 'joan-devmkt', 'joan-cam', 'concepts1', 'concepts2', 'calcs', 'pk1', 'pk2', 'pd', 'admin', 'educ', 'elderly', 'lifespan', 'legal', 'devmkt', 'allergy'],
  playlist: null,
  banner: '<b>There is no lecturer question bank for this paper.</b> Pharmacology has never had a Canvas quiz. Every question here was written by this tool — from the course’s lecture decks, Joan’s own Escape Room answer sheet and her recorded 16 Sep lecture — and each one names the slide or lecture moment its answer comes from. It trains the content; it is not Joan’s wording.',
  pickIntro: 'The first rows are short answers <b>in the format Joan described</b> (a definition plus an example). Below them, one row per lecture topic — the tool’s questions, multi-choice then written.',
  help: {
    what: 'A practice paper for <b>Introduction to Pharmacology</b> in the same format as the other Paper Sims: drill a topic, learn with the answer shown as you go, or sit a mock in the real paper’s shape. The final is <b>Fri 6 Nov 2026 (afternoon, time not confirmed) · 80 min · 50 marks · 30 multi-choice + short answers · 50% of the paper</b>. Joan said on 16 Sep that a short answer is <b>a definition plus an example in 3–4 lines</b>, and that she will <b>not ask about specific drugs</b> — beyond your own four (the two in your med-admin practical and the two in your essay), which you should know inside out.',
    noBank: '<b>Nothing here was captured from Canvas, because there is nothing to capture:</b> this paper has never had a Canvas quiz.',
    authored: '<b>75 short answers are written in the format Joan described on 16 Sep — a definition plus an example, 2–3 marks, no question about a specific drug</b> (the rows named “In Joan’s format”). They come from her own Escape Room answer sheet, her recorded Legal &amp; Ethical lecture (cited by timestamp), the Drug Development deck she set as a self-directed package, the Rongoā Māori deck, and the definitions in the Module 1–6 decks. The questions and model answers are the tool’s, not hers. The other 289 questions — 100 multi-choice and 189 written — were written by the intro-pharm study hub from the 14 lecture decks and carried across unchanged; each names the slide that supplies its answer. Those written questions pre-date her description of the exam: they all stay under Pick my rep, but <b>a mock leaves out</b> any that carry 4+ marks, name a specific drug, ask for the lecture’s own drug examples, or are worked calculations. ',
    held: '<b>This bank covers Modules 1–7 — everything taught before the break — plus the Rongoā Māori lecture. Three modules have not been taught yet</b>, so there is nothing to build them from: <b>Module 8 Immunology, Vaccines &amp; Allergy</b> (lecture Wed 7 Oct; only the ASCIA anaphylaxis plan is here), <b>Module 10 Socioeconomic Factors &amp; Complementary/Alternative Medicines</b> (Wed 14 Oct — a self-directed <i>Canvas quiz</i>, which would be the first real lecturer questions this paper has ever had: sit it and save the graded page; its <b>Rongoā Māori</b> part was lectured on 15 Sep and is in this bank, written from its deck) and <b>Module 9 Licit &amp; Illicit Drugs &amp; Toxicology</b> (Tue 20 Oct). All three are examinable ("all modules"). Exam revision sessions with formative mini exams: <b>Wed 21, Tue 27 and Wed 28 Oct</b> — the closest thing to the real paper; capture them.',
  },
  focusCopy: {
    pending: 'The checklist for this paper — every topic, what you must be able to DO, how Joan asks it (definition + example) and where it stops — is not built yet. What it has to say first: <b>this bank is Modules 1–7. Modules 8, 9 and 10 are taught after the break</b> (Immunology 7 Oct · Socioeconomic &amp; CAM 14 Oct, as a Canvas quiz — its Rongoā Māori lecture of 15 Sep is already here · Licit/Illicit &amp; Toxicology 20 Oct), and <b>Deck 13, Drug Development &amp; Marketing, was never lectured</b> — it was set as a self-directed online package and is still examinable. Her three revision sessions (21, 27, 28 Oct) each carry a formative mini exam.',
  },
};
