/* Short versions of the 75 short answers IN JOAN'S FORMAT (a definition plus an example; content/joan/). The tool wrote
   every one of those questions and model answers; each is cut here to one fact a line, a few words each, grouped under
   the question's own parts, with a memory hook. Gated by shorts.mjs (see content/shorts.js). */
const G = (q, ...facts) => ({ q, facts: facts.map(([t, of, fix]) => (fix ? { t, of, fix } : { t, of })) });

export const JOAN = [
  /* ── Foundations ── */
  { quiz: 'joan-found', k: 'what is the meaning of contraindication', title: 'Contraindication',
    hook: 'CONTRA = against: a reason NOT to give it.',
    groups: [
      G('Definition',
        ['A situation where a medication should **not be used**', 0],
        ['… because it **may be harmful** to the person', 0]),
      G('Example',
        ['A known **severe allergy** to that medicine', 1],
        ['Or a medicine that can **harm the foetus** in a **pregnant** woman', 1]),
    ] },
  { quiz: 'joan-found', k: 'what is a precaution in relation', title: 'Precaution vs contraindication',
    hook: 'Contraindication = NO. Precaution = yes, but CAREFULLY.',
    groups: [
      G('Definition, and the difference',
        ['A warning to use it with **special care**', 0],
        ['A **heightened risk of adverse effects**', 0],
        ['Unlike a contraindication, it **may still be used**: **monitoring** or a **dose adjustment**', 0]),
      G('Example',
        ['**Reduced kidney function** in an **older adult**', 1],
        ['Still given, at a **lower dose**, with monitoring', 1]),
    ] },
  { quiz: 'joan-found', k: 'define a medication interaction and give', title: 'Medication interaction',
    hook: 'Something else changes what the medicine does.',
    groups: [
      G('Definition',
        ['The medicine’s **effect** is **altered by another substance or condition**', 0],
        ['Another **medication**, a **food**, a **complementary** medicine, an illness', 0]),
      G('Example',
        ['A **herbal remedy** or food changes how much is **absorbed or broken down**', 1],
        ['… making it **stronger or weaker**', 1],
        ['So the nurse **asks about everything** the person takes', 1]),
    ] },
  { quiz: 'joan-found', k: 'distinguish a medicine s generic name', title: 'Generic name vs brand name',
    hook: 'One generic name; many brand names.',
    groups: [
      G('The difference',
        ['**Generic**: the **official name of the active ingredient**; **one per medicine**', 0],
        ['**Brand**: **owned by the company**; a medicine **may have several**', 0]),
      G('Why it matters',
        ['Knowing only brands, a patient may **take both** of **the same medicine**', 1],
        ['Teaching by **generic name** **reduces error**', 1]),
    ] },
  { quiz: 'joan-found', k: 'distinguish the roles of medsafe and', title: 'Medsafe vs PHARMAC',
    hook: 'Medsafe: is it SAFE? PHARMAC: will we PAY for it?',
    groups: [
      G('Medsafe',
        ['The **safety authority**: it **regulates**', 0],
        ['e.g. is a new medicine **safe** and good enough **quality** to be **approved**?', 0]),
      G('PHARMAC',
        ['Decides which medicines are **funded** (**subsidised**)', 1],
        ['… within a **fixed budget**; e.g. **which brand** is subsidised', 1]),
    ] },
  { quiz: 'joan-found', k: 'distinguish a local effect from a', title: 'Local vs systemic effect',
    hook: 'Local = right where it goes on. Systemic = through the blood.',
    groups: [
      G('Local',
        ['At the **immediate site of administration**', 0],
        ['e.g. a **cream** on a skin rash; **eye drops**', 0]),
      G('Systemic',
        ['**Absorbed into the circulation** and **distributed** to where it acts', 1],
        ['e.g. a **tablet swallowed** for a headache', 1]),
    ] },
  { quiz: 'joan-found', k: 'what is an excipient give an', title: 'Excipients',
    hook: 'Everything in the tablet that is NOT the medicine.',
    groups: [
      G('Definition',
        ['An **inert** (**inactive**) ingredient in a formulation', 0],
        ['**Fillers**, **binders**, **colours**, flavours', 0]),
      G('Example, and why the nurse cares',
        ['The **gelatine** in a **capsule shell**', 1],
        ['It matters if **vegetarian**, **vegan** or for **religious reasons**', 1],
        ['So the nurse checks: **Code of Conduct Principle 2**', 1]),
    ] },
  { quiz: 'joan-found', k: 'what is an enteric coating and', title: 'Enteric coating',
    hook: 'Survives the stomach, dissolves in the gut. Crush it and that is gone.',
    groups: [
      G('What it is',
        ['It stops the tablet **dissolving in the stomach**', 0],
        ['It **dissolves in the intestine**', 0]),
      G('What it is for',
        ['**Protecting the medicine** from **stomach acid**', 0],
        ['Or **protecting the stomach**, or **delaying its action**', 0]),
      G('What goes wrong if it is ignored',
        ['**Crushing** it **destroys the coating**', 1],
        ['**Absorbed too fast**, or **irritates the stomach**', 1],
        ['**Check with a pharmacist** first', 1]),
    ] },

  /* ── Pharmacokinetics & dynamics ── */
  { quiz: 'joan-pkpd', k: 'define pharmacokinetics and give an example', title: 'Pharmacokinetics',
    hook: 'What the BODY does to the drug: A-D-M-E.',
    groups: [
      G('Definition',
        ['“**What the body does to the drug**”', 0],
        ['**Absorption**, **distribution**, **metabolism**, **excretion** (**ADME**)', 0]),
      G('Example (any one process)',
        ['**Absorption**: a swallowed tablet **entering the bloodstream** from the gut', 1],
        ['**Metabolism**: the **liver** modifying it; **excretion**: the **kidneys**', 1]),
    ] },
  { quiz: 'joan-pkpd', k: 'define absorption and give an example', title: 'Absorption',
    hook: 'Getting into the blood. IV skips it.',
    groups: [
      G('Definition',
        ['**Unchanged drug** reaches the **bloodstream**', 0],
        ['… after it has been given and has **dissolved**', 0]),
      G('A route that does not need it',
        ['**Intravenous**: straight **into the bloodstream**', 1],
        ['Nothing to absorb, so the effect is **rapid**', 1]),
    ] },
  { quiz: 'joan-pkpd', k: 'define bioavailability and give an example', title: 'Bioavailability',
    hook: 'How much actually arrives. IV = all of it.',
    groups: [
      G('Definition',
        ['How much of the dose **actually reaches the bloodstream**', 0]),
      G('Two routes compared',
        ['**Intravenous = 100%**', 1],
        ['By mouth it is **lower**: some **not absorbed**, some **broken down by the liver**', 1]),
    ] },
  { quiz: 'joan-pkpd', k: 'explain the hepatic first pass effect', title: 'The hepatic first-pass effect',
    hook: 'Swallowed → gut → LIVER first → then the body.',
    groups: [
      G('Definition',
        ['Taken **by mouth**, it **passes through the liver** first', 0],
        ['The **liver breaks down part of it**', 0],
        ['Only **a portion of the dose** arrives unchanged', 0]),
      G('Consequence',
        ['e.g. **100 mg** swallowed → only **20 mg** reaches the circulation', 1],
        ['So **oral doses** are often **larger than IV doses**', 1],
        ['**Sublingual**, **transdermal** or **IV** routes **avoid it**', 1]),
    ] },
  { quiz: 'joan-pkpd', k: 'what is plasma protein binding and', title: 'Plasma protein binding',
    hook: 'Only the FREE drug works.',
    groups: [
      G('Definition',
        ['Many drugs **bind** reversibly to **plasma proteins**, mainly **albumin**', 0],
        ['Only the **free** (**unbound**) drug can act', 0]),
      G('Why it matters, with an example',
        ['Two medicines **compete for the same binding site**', 1],
        ['Or **low albumin** in a **malnourished** older adult', 1],
        ['More **free drug** → more effect, **risk of toxicity**', 1]),
    ] },
  { quiz: 'joan-pkpd', k: 'define drug metabolism and give an', title: 'Drug metabolism',
    hook: 'The liver changes it so the body can get rid of it.',
    groups: [
      G('Definition',
        ['**Biological transformation** of a drug, by **enzymes**', 0],
        ['Mainly in the **liver**; into a **less active**, **more water-soluble** compound', 0]),
      G('Something that changes it',
        ['An **enzyme inhibitor** slows it: levels rise, **toxicity**', 1],
        ['An **enzyme inducer** speeds it: a **higher dose** may be needed', 1],
        ['**Alcohol**, **smoking**, diet, **liver disease** can all change it', 1]),
    ] },
  { quiz: 'joan-pkpd', k: 'define half life and give an', title: 'Half-life',
    hook: 'Half gone each half-life; about five of them and it is all gone.',
    groups: [
      G('Definition',
        ['The time for the **plasma concentration** to **fall by one half**', 0],
        ['Not how long the **whole drug** stays in the body', 0]),
      G('How it is used',
        ['Cleared after about **5 half-lives**', 1],
        ['**Steady state** after **3–5 half-lives** of regular dosing', 1],
        ['It sets the **dosing interval**', 1]),
    ] },
  { quiz: 'joan-pkpd', k: 'define the therapeutic range and give', title: 'The therapeutic range',
    hook: 'Enough to work, not enough to poison.',
    groups: [
      G('Definition',
        ['The **plasma concentration** range that gives the **desired effect** without **toxicity**', 0],
        ['Above the **minimum effective concentration**, below the **toxic** one', 0]),
      G('When it is monitored',
        ['**Therapeutic drug monitoring** for a **narrow therapeutic range**', 1],
        ['Blood levels at **peak and trough**', 1]),
    ] },
  { quiz: 'joan-pkpd', k: 'define pharmacodynamics and give an example', title: 'Pharmacodynamics',
    hook: 'What the DRUG does to the body.',
    groups: [
      G('Definition',
        ['“**What the drug does to the body**”', 0],
        ['**Drug–target interactions**, **mechanisms of action**, the **effects**', 0]),
      G('Example',
        ['A medicine **binding to a receptor** on **airway muscle**', 1],
        ['… making it **relax**, so **breathing becomes easier**', 1]),
    ] },
  { quiz: 'joan-pkpd', k: 'distinguish an agonist from an antagonist', title: 'Agonist vs antagonist',
    hook: 'Agonist: the key fits AND opens. Antagonist: it fits, the door stays shut.',
    groups: [
      G('Agonist',
        ['**Binds to and activates** a receptor', 0],
        ['Like the **body’s own chemical**: the key **opens the door**', 0],
        ['e.g. a **reliever inhaler** activating **beta receptors**', 0]),
      G('Antagonist',
        ['**Binds** and **blocks** it, **without producing a response**', 1],
        ['e.g. a **beta blocker**: stops the body’s **adrenaline** binding', 1]),
    ] },
  { quiz: 'joan-pkpd', k: 'distinguish potency from efficacy with an', title: 'Potency vs efficacy',
    hook: 'Potency = HOW MUCH you need. Efficacy = HOW FAR it can go.',
    groups: [
      G('The definitions',
        ['**Potency**: the **amount of drug needed** for a given effect', 0],
        ['More potent: the same effect at a **lower dose**', 0],
        ['**Efficacy**: the **ability of the drug to produce a response**', 0],
        ['**Maximal efficacy**: the **greatest response possible**', 0]),
      G('Example',
        ['Two pain relievers: **5 mg** vs **500 mg** for mild pain: **different potency**', 1],
        ['Only one relieves **severe pain** at any dose: **greater efficacy**', 1]),
    ] },
  { quiz: 'joan-pkpd', k: 'define an adverse effect and give', title: 'Adverse effect vs adverse drug event',
    hook: 'Effect = the drug did it. Event = something around the drug did.',
    groups: [
      G('Adverse effect',
        ['A **harmful effect** suspected to be **caused by a medicine**', 0],
        ['The preferred term for “**side effect**”', 0],
        ['e.g. **nausea** (mild); **liver injury**, **severe allergy** (serious)', 0]),
      G('How an adverse drug event differs',
        ['An **injury related to the drug**', 1],
        ['… **not always due to the drug itself**: e.g. an **error** in **prescribing**', 1]),
    ] },

  /* ── Administration & safety ── */
  { quiz: 'joan-admin', k: 'define a medication error and give', title: 'Medication error vs adverse effect',
    hook: 'Error = a person slipped. Adverse effect = the medicine did it.',
    groups: [
      G('Definition',
        ['Any **preventable event** that may cause **inappropriate medication use** or **patient harm**', 0],
        ['… while the medicine is **in the control** of staff or patient', 0],
        ['e.g. a **dose given twice**; a known **allergy** ignored', 0]),
      G('How it differs from an adverse effect',
        ['Adverse effect: harm from **the medicine itself**, **even when used correctly**', 1],
        ['Error: harm from **human action**, a lapse in the **rights and checks**', 1]),
    ] },
  { quiz: 'joan-admin', k: 'what is the right to refuse', title: 'The right to refuse',
    hook: 'Explain, document, tell, discard: never pressure, never hide it.',
    groups: [
      G('What it is',
        ['A patient **has the right to refuse** a medication', 0],
        ['(Unless under the **Mental Health Act**): **informed consent** and **autonomy**', 0]),
      G('What the nurse does',
        ['**Explains the consequences** of not taking it', 1],
        ['**Documents the refusal** and the reason; **informs the prescriber**', 1],
        ['**Discards the refused dose**; **no pressure**, **no hiding it in food**', 1]),
    ] },
  { quiz: 'joan-admin', k: 'what does the right indication require', title: 'The right indication',
    hook: 'Know WHY before you give it.',
    groups: [
      G('What it requires',
        ['The nurse is **accountable** for knowing **why** it is given', 0],
        ['Is it for the **right reason for this patient**?', 0]),
      G('Example',
        ['A **PRN** (as-needed) medicine', 1],
        ['**Assess the patient** first: is the **reason it was charted** actually present?', 1]),
    ] },
  { quiz: 'joan-admin', k: 'what is carm and who can', title: 'CARM: what it is, who reports',
    hook: 'A reaction? Document it, flag it, report it to CARM.',
    groups: [
      G('What it is, and who reports',
        ['The **Centre for Adverse Reactions Monitoring**', 0],
        ['NZ’s database of **suspected adverse reactions** to medicines and **vaccines**', 0],
        ['**Health professionals**, **patients and whānau** can all report', 0]),
      G('Example to report',
        ['A **widespread rash** and **facial swelling** after **starting a new medicine**', 1],
        ['It is **documented**, an **alert** placed on the record, and **reported**', 1]),
    ] },

  /* ── Across the lifespan ── */
  { quiz: 'joan-life', k: 'define polypharmacy and give an example', title: 'Polypharmacy',
    hook: 'Five or more, and the risks multiply.',
    groups: [
      G('Definition',
        ['The **concurrent use of multiple medications**, usually **five or more**', 0],
        ['It implies **too many**, or **unnecessary**, medicines', 0]),
      G('A risk it raises (any one)',
        ['**Drug–drug interactions** and **adverse effects**', 1],
        ['**Falls**; not taking them **as prescribed**; **death**', 1]),
    ] },
  { quiz: 'joan-life', k: 'how is an older person defined', title: 'The older person, and why age matters',
    hook: '65+: the kidneys slow down, and drugs build up.',
    groups: [
      G('Definition',
        ['Aged **65 years and over**', 0],
        ['**Young-old** 65–79; **old-old** 80+', 0],
        ['**Frail elderly**: 65+ with a **debilitating condition**', 0]),
      G('Why age matters',
        ['**Kidney function declines**, so the medicine **stays in the body longer**', 1],
        ['It can **build up to toxic levels**, so doses are **often lower**', 1]),
    ] },
  { quiz: 'joan-life', k: 'when may a tablet be crushed', title: 'When a tablet may be crushed',
    hook: 'The pharmacist says yes AND it helps the patient.',
    groups: [
      G('When',
        ['Only when a **pharmacist has advised** it is safe to', 0],
        ['**And** it is in the **patient’s best interest**', 0]),
      G('The harm crushing can cause',
        ['Crushing an **enteric-coated** or **modified-release** tablet', 1],
        ['**Releases the whole dose at once**: **absorbed too rapidly**', 1],
        ['Or it becomes **less effective**', 1]),
    ] },
  { quiz: 'joan-life', k: 'define a teratogen and give an', title: 'Teratogens',
    hook: 'First trimester = organs forming = highest risk.',
    groups: [
      G('Definition',
        ['A substance that can cause **developmental abnormalities** in a **foetus**', 0],
        ['**Birth defects**, **developmental delay**, intellectual disability', 0]),
      G('Example',
        ['Some **prescription medicines**; **herbal products**, **alcohol**, **nicotine**', 1]),
      G('When the risk is highest',
        ['The **first trimester** (**weeks 0–12**)', 1],
        ['… when the **organs are forming**', 1]),
    ] },
  { quiz: 'joan-life', k: 'on what does the transfer of', title: 'Medicines in breast milk',
    hook: 'Blood level, milk amount, fat-solubility. Keep the parent well.',
    groups: [
      G('What the transfer depends on',
        ['The parent’s **plasma concentration** of the drug', 0],
        ['The **amount of milk** the infant takes', 0],
        ['The drug’s **lipid solubility**', 0]),
      G('The guiding principle',
        ['**Maintaining the parent’s health is essential**', 1],
        ['Not **automatically** stopped: the prescriber **weighs the risk** to the infant', 1]),
    ] },
  { quiz: 'joan-life', k: 'children are just small adults explain', title: 'Children are not small adults',
    hook: 'Different bodies, so doses by the kilo.',
    groups: [
      G('Why it is false',
        ['Children are **physiologically different** and **constantly developing**', 0],
        ['About **75% water**, less fat; **immature protective barriers**', 0],
        ['Poorer **temperature** and **homeostatic control**', 0]),
      G('Example',
        ['The dose comes from **body weight** (**mg per kg**)', 1],
        ['**Never** by simply **scaling down an adult dose**', 1]),
    ] },

  /* ── Legal & ethical ── */
  { quiz: 'joan-law', k: 'what is a controlled drug give', title: 'Controlled drugs',
    hook: 'Misuse of Drugs Act: abuse risk = double-locked.',
    groups: [
      G('Definition',
        ['A medicine under **special legal restriction**: **Misuse of Drugs Act 1975**', 0],
        ['Because of its **potential for abuse**, **dependence** and harm', 0],
        ['All controlled drugs are prescribed; **not all prescribed drugs are controlled**', 0]),
      G('How they are handled on a ward',
        ['**Opioids** like **morphine** (**Class B**)', 1],
        ['Kept in a **double-locked safe** inside a locked room', 1],
        ['**Restricted key-holders**; **penalties** for unlawful use', 1]),
    ] },
  { quiz: 'joan-law', k: 'describe the three classes of controlled', title: 'The three classes of controlled drug',
    hook: 'A = never prescribed. B = locked-up opioids. C = lower risk, still locked.',
    groups: [
      G('Class A',
        ['**Very high risk of harm**; **never prescribed**', 0],
        ['e.g. **heroin**, **methamphetamine**', 0]),
      G('Class B',
        ['**Drugs of dependence**, **high risk of harm**; a **double-locked safe**', 1],
        ['e.g. **morphine** and the other **opioids**', 1]),
      G('Class C',
        ['**Lower potential for abuse**, **moderate risk of harm**', 2],
        ['Prescribed normally but **still locked away**: e.g. **codeine**, **diazepam**', 2]),
    ] },
  { quiz: 'joan-law', k: 'name the four legal classifications of', title: 'The four legal classes of medicine',
    hook: 'Prescription → Restricted → Pharmacy-only → General sale.',
    groups: [
      G('The four classes',
        ['**Prescription medicine**: only on a **prescription** or **standing order**', 0],
        ['**Restricted** (**pharmacist-only**): the pharmacist must **explain it**', 0],
        ['**Pharmacy-only medicine**: sold in a **pharmacy** or **hospital**', 1],
        ['**General sale**: sold from **any retail outlet**', 1]),
      G('Example (any one)',
        ['**Amoxicillin** is **prescription-only**', 2],
        ['**Paracetamol** is **general sale**: a **supermarket** sells it', 2]),
    ] },
  { quiz: 'joan-law', k: 'distinguish an act a regulation and', title: 'Act, regulation and policy',
    hook: 'Parliament makes the Act; regulations say how; your employer sets policy.',
    groups: [
      G('An Act',
        ['A **law made by Parliament**', 0],
        ['e.g. the **Medicines Act 1981**; the **Misuse of Drugs Act 1975**', 0]),
      G('A regulation',
        ['Made **underneath an Act**: **how it is enforced**', 1],
        ['e.g. the **Medicines Regulations 1984**', 1]),
      G('A policy',
        ['An **enforceable rule within one organisation**', 2],
        ['e.g. a **hospital’s medication policy**; nurses must **know their own**', 2]),
    ] },
  { quiz: 'joan-law', k: 'explain why a nurse may not', title: 'Why a nurse can’t give on own judgement',
    hook: 'No prescription, no standing order, no medicine.',
    groups: [
      G('The principle',
        ['Only as directed by an **authorised prescriber** or a **standing order**', 0],
        ['The **dose, frequency and route**; **nurses do not prescribe**', 0]),
      G('Example',
        ['Blood glucose **18 mmol/L**: the nurse **cannot decide to give insulin**', 1],
        ['**Contact the prescriber**', 1],
        ['Even “**take a couple of paracetamol**” is **prescribing**', 1]),
    ] },
  { quiz: 'joan-law', k: 'what does it mean to insist', title: 'Insisting on proper prescribing',
    hook: 'Unclear? Ask. Don’t guess, don’t withhold.',
    groups: [
      G('What it means',
        ['A **legal duty to question** an **incomplete or unclear prescription**', 0],
        ['Ask the prescriber: **not to guess**, and **not to withhold**', 0]),
      G('Example',
        ['The **route is missing**, the **allergies** unchecked, the writing unreadable', 1],
        ['→ **go back to the prescriber**', 1]),
    ] },
  { quiz: 'joan-law', k: 'what is the purpose of the', title: 'The HPCAA 2003: purpose, one requirement',
    hook: 'Protect the public: competent, fit, in scope.',
    groups: [
      G('Purpose',
        ['To **protect public safety**', 0],
        ['Practitioners **competent** and **fit to practise**, within a **scope of practice**', 0]),
      G('One requirement (any one)',
        ['Work **within the scope** set by the **Nursing Council**', 1],
        ['Renew an **annual practising certificate** (**APC**)', 1],
        ['Show **continuing clinical and cultural competence**', 1]),
    ] },
  { quiz: 'joan-law', k: 'define scope of practice and give', title: 'Scope of practice',
    hook: 'What you are educated, competent and authorised to do.',
    groups: [
      G('Definition',
        ['The area a practitioner is **educated, competent and authorised** to work in', 0],
        ['Set by the **Nursing Council** under the **HPCAA**', 0],
        ['About **demonstrated competence**, **not a list of tasks**', 0]),
      G('Outside an RN’s scope (any one)',
        ['**Prescribing** (unless a **designated RN prescriber**)', 1],
        ['**Dispensing**: that is the **pharmacist’s role**', 1]),
    ] },
  { quiz: 'joan-law', k: 'what does fitness to practise mean', title: 'Fitness to practise',
    hook: 'Qualified, healthy enough, good conduct. Not the gym.',
    groups: [
      G('What it means',
        ['The necessary **qualifications and training**', 0],
        ['**No untreated** physical or **mental condition** impedes the work', 0],
        ['Of **good conduct and standing**: **not physical fitness**', 0]),
      G('Something that puts it in doubt (any one)',
        ['An **arrest** for **possessing an illegal drug**', 1],
        ['**Dishonesty** or **cheating** as a student', 1]),
    ] },
  { quiz: 'joan-law', k: 'distinguish the nursing council of new', title: 'Nursing Council vs NZNO',
    hook: 'The Council REGULATES (Code of Conduct). NZNO SUPPORTS (Code of Ethics).',
    groups: [
      G('Nursing Council (NCNZ)',
        ['The **regulatory authority** under the **HPCAA**', 0],
        ['**Registers**, audits, **disciplines**, can **de-register** nurses', 0],
        ['Its document: the **Code of Conduct**, **enforceable**', 0]),
      G('NZNO',
        ['A **union** with **voluntary membership**', 1],
        ['It **represents and supports** nurses', 1],
        ['Its document: the **Code of Ethics** (2019), a **guideline**', 1]),
      G('Example of the difference',
        ['Hiding an error: the nurse can be **disciplined by NCNZ**', 2],
        ['NZNO is where that nurse turns for **advice and representation**', 2]),
    ] },

  /* ── Conduct, competence & ethics ── */
  { quiz: 'joan-ethics', k: 'what does pou mean in the', title: 'The six pou of competence',
    hook: 'Six posts hold up the house of competent practice.',
    groups: [
      G('What a pou is',
        ['A **pillar** or **post**: the six **hold up** competent practice', 0]),
      G('The six pou',
        ['**Māori Health**; **Cultural Safety**', 1],
        ['**Whanaungatanga & Communication**', 1],
        ['**Pūkengatanga & Evidence-Informed Practice**', 1],
        ['**Manaakitanga & People-Centred Care**', 1],
        ['**Rangatiratanga & Leadership**', 1]),
      G('One being compromised',
        ['A patient took **his own opioid**; the nurse **does not tell** the prescriber', 2],
        ['That compromises **Whanaungatanga & Communication**', 2]),
    ] },
  { quiz: 'joan-ethics', k: 'state one principle of the nursing', title: 'A Code of Conduct principle and medicines',
    hook: 'Integrity: report errors. Safe care: double-check. Culture: check what is in it.',
    groups: [
      G('One principle (any one of eight)',
        ['**Principle 7**: act with **integrity** to justify trust', 0],
        ['**Principle 4**: **safe and competent care**', 0],
        ['**Principle 2**: respect **cultural needs and values**', 0]),
      G('How it applies to medicines',
        ['P7: **report a medication error** honestly and **immediately**', 1],
        ['P4: **double-check with another nurse** for a new medicine', 1],
        ['P2: check the **excipients**, e.g. a **gelatine capsule**', 1]),
    ] },
  { quiz: 'joan-ethics', k: 'explain the nurse s duty of', title: 'Privacy, and a phone enquiry',
    hook: 'You can’t see who is calling, so you can’t tell them.',
    groups: [
      G('The duty',
        ['**Code of Conduct Principle 5**: **protect personal health information**', 0],
        ['Share it only for **appropriate professional purposes**', 0],
        ['Notes are read only by **those caring for that patient**', 0]),
      G('The phone example',
        ['“Sorry, we **can’t give patient information over the phone**”', 1],
        ['You **cannot verify who is calling**; offer to **ring back**', 1]),
    ] },
  { quiz: 'joan-ethics', k: 'define veracity and give an example', title: 'Veracity',
    hook: 'Tell the truth: about the medicine, and about your mistakes.',
    groups: [
      G('Definition',
        ['**Truthfulness**: **honest**, **accurate, clear and transparent** information', 0],
        ['A value in the **NZNO Code of Ethics**', 0]),
      G('Example',
        ['Telling a patient **what a medicine is for** and its **side effects**', 1],
        ['Or **owning up to a medication error** straight away', 1]),
    ] },
  { quiz: 'joan-ethics', k: 'define autonomy and give an example', title: 'Autonomy',
    hook: 'Their body, their choice, even when it is no.',
    groups: [
      G('Definition',
        ['The **right of choice**', 0],
        ['**Informed, voluntary consent**, **without coercion**', 0],
        ['Including the **right to refuse** and to **withdraw** at any time', 0]),
      G('Example',
        ['A **competent patient declines** a medicine', 1],
        ['The nurse checks they **understand the consequences**, **respects the refusal**, **documents it**', 1]),
    ] },
  { quiz: 'joan-ethics', k: 'define rangatiratanga as a value in', title: 'Rangatiratanga',
    hook: 'Self-determination: give the facts, respect the choice.',
    groups: [
      G('Definition',
        ['**Self-determination**', 0],
        ['The right to decide about **their own bodies and health**', 0],
        ['Including **refusing care entirely**', 0]),
      G('A bedside example',
        ['Support the patient and whānau to **decide for themselves**', 1],
        ['**Respecting the choice**, even when the nurse **would have chosen differently**', 1]),
    ] },
  { quiz: 'joan-ethics', k: 'define beneficence and non maleficence and', title: 'Beneficence and non-maleficence',
    hook: 'Do good; do no harm; but a competent “no” wins.',
    groups: [
      G('Beneficence',
        ['**Do good**: promote the person’s **wellbeing**', 0]),
      G('Non-maleficence',
        ['**Do no harm**: avoid **physical, emotional or cultural harm**', 1],
        ['**Minimising risk**', 1]),
      G('A conflict',
        ['The medicine would do good (**beneficence**), but the patient **refuses** it (**autonomy**)', 2],
        ['The nurse **may not override a competent refusal**', 2]),
    ] },
  { quiz: 'joan-ethics', k: 'what does prn mean and why', title: 'PRN, and why it is an ethical problem',
    hook: 'As necessary: says who?',
    groups: [
      G('What PRN means',
        ['**Pro re nata**: “**as necessary**”', 0]),
      G('Why it is an ethical problem',
        ['It is **subjective**: **as necessary to whom**, and **who decides**?', 0],
        ['The **nurse’s judgement and beliefs** shape it', 0]),
      G('Example',
        ['**Pain relief** charted PRN', 1],
        ['It can depend on whether the nurse **believes their pain**', 1],
        ['There is **no machine that measures it**', 1],
        ['**Fear of causing addiction** makes some **give less**', 1]),
    ] },
  { quiz: 'joan-ethics', k: 'why is concealing a medication error', title: 'Why hiding an error is worse',
    hook: 'An error is an accident. Hiding it is a choice.',
    groups: [
      G('The reason',
        ['An error is usually **accidental**: **report it**, **reflect**, **be supervised**', 0],
        ['**Concealment is deliberate**: it **denies the patient monitoring and treatment**', 0],
        ['It **breaches integrity** (**Principle 7**): **professional misconduct**', 0]),
      G('Example',
        ['“**Nurse D**” took **two days to report**; the **patient died**', 1],
        ['Found **guilty of professional misconduct**: **suspended**, **fined**, supervised', 1]),
    ] },
  { quiz: 'joan-ethics', k: 'explain why patients should be taught', title: 'Why teach the generic name',
    hook: 'Brand-only knowledge = the same drug twice.',
    groups: [
      G('The reason',
        ['One medicine may have **several brand names**', 0],
        ['Knowing **only the brand**, a patient **cannot tell staff** what they take', 0],
        ['So the **same medicine can be given twice**', 0]),
      G('Example',
        ['A man knew his opioid **only by its brand name**', 1],
        ['He said he had **never had morphine**; he was given a **second dose**', 1],
        ['He became **drowsy, confused and nauseated**', 1]),
    ] },

  /* ── Drug development & marketing ── */
  { quiz: 'joan-devmkt', k: 'define bioequivalence and explain why it', title: 'Bioequivalence',
    hook: 'Same ingredient, same rate, same amount = swappable.',
    groups: [
      G('Definition',
        ['The **same active ingredient** reaches the bloodstream', 0],
        ['At the **same rate** and to the **same extent**', 0]),
      G('Why it matters, with an example',
        ['A **generic** may only be **substituted** for a brand if **bioequivalent**', 1],
        ['So the patient gets the **same therapeutic effect**', 1],
        ['e.g. dispensing the **funded generic** instead of the original brand', 1]),
    ] },
  { quiz: 'joan-devmkt', k: 'why is bringing a new medicine', title: 'Why new medicines are slow and costly',
    hook: '10–20 years, millions of dollars: nobody wants another thalidomide.',
    groups: [
      G('Why',
        ['Must **prove the medicine works**, its **side effects are known**, **safe in humans**', 0],
        ['About **10–20 years** and **millions of dollars**', 0],
        ['Only about **5 in 5,000** compounds reach human testing', 0]),
      G('The event behind the caution',
        ['**Thalidomide**: given to **pregnant women** in the **1950s**', 1],
        ['It caused **birth defects**', 1]),
    ] },
  { quiz: 'joan-devmkt', k: 'name the five key phases of', title: 'Drug development: the five phases',
    hook: 'Discover → Preclinical → Clinical trials → Medsafe review → Post-market.',
    groups: [
      G('In order',
        ['1 **Discovery and development**: lab research for **promising compounds**', 0],
        ['2 **Preclinical research**: **safety testing** before any human', 0],
        ['3 **Clinical trials**: studies **in people**', 1],
        ['4 **Medsafe review**: **approved or rejected**', 1],
        ['5 **Post-market monitoring**: e.g. reactions reported to **CARM**', 2]),
    ] },
  { quiz: 'joan-devmkt', k: 'describe the purpose of phase 1', title: 'Phase 1 of a clinical trial',
    hook: 'Phase 1 = is it SAFE, and what dose?',
    groups: [
      G('Purpose',
        ['**Safety and dosage**', 0],
        ['A **small group of 20–100** people, often **healthy volunteers**', 0]),
      G('What is measured',
        ['**Adverse effects** at **gradually increasing doses**', 1],
        ['To find the **dose range** that is **tolerated**', 1]),
    ] },
  { quiz: 'joan-devmkt', k: 'what is the difference between phase', title: 'Phase 2 vs Phase 3',
    hook: 'Phase 2: does it WORK? Phase 3: prove it, in thousands.',
    groups: [
      G('Phase 2',
        ['Tests **efficacy and side effects**', 0],
        ['In **several hundred** people **who have the condition**', 0]),
      G('Phase 3',
        ['**Confirms safety and effectiveness** in a **large population**', 1],
        ['**300 to 3,000** people, over **one to four years**, before approval', 1]),
    ] },
  { quiz: 'joan-devmkt', k: 'what is phase 4 of clinical', title: 'Phase 4: post-market monitoring',
    hook: 'Rare harms only show up across a whole population.',
    groups: [
      G('What it is',
        ['**Post-market monitoring** of **long-term safety**', 0],
        ['**Several thousand patients**, over years, **after Medsafe approval**', 0]),
      G('Why it exists, with an example',
        ['**Rare or delayed adverse effects** only show at **population scale**', 1],
        ['e.g. a medicine **withdrawn** after **post-market reports**', 1]),
    ] },
  { quiz: 'joan-devmkt', k: 'name the three bodies that must', title: 'Three bodies that approve a trial',
    hook: 'Medsafe (the medicine), SCOTT (the science), HDEC (the ethics).',
    groups: [
      G('Each body, and what it checks',
        ['**Medsafe**: the **preclinical studies**, **chemical stability** and **quality**', 0],
        ['**SCOTT**: the **science**, the **safety** of the **trial design**', 1],
        ['SCOTT = **Standing Committee on Therapeutic Trials**', 1],
        ['**HDEC**: **ethical compliance**', 2],
        ['HDEC = **Health and Disability Ethics Committees**', 2]),
    ] },
  { quiz: 'joan-devmkt', k: 'what is medsafe s role after', title: 'Medsafe after approval',
    hook: 'Approval is not the end: CARM keeps watching.',
    groups: [
      G('Its role',
        ['Ongoing **post-market surveillance**', 0],
        ['**Tracking adverse events**; updating the **risk and benefit** information', 0]),
      G('Example',
        ['**Adverse reactions reported** to **CARM** feed it', 1],
        ['… by **nurses**, **doctors** or **patients**', 1]),
    ] },
  { quiz: 'joan-devmkt', k: 'define informed consent in a clinical', title: 'Informed consent in a clinical trial',
    hook: 'Voluntary, competent, informed, and you can leave.',
    groups: [
      G('Definition',
        ['Consent that is **voluntary, competent and adequately informed**', 0],
        ['It can be **withdrawn at any time**', 0]),
      G('One thing they must understand',
        ['The **risks and potential benefits**', 1],
        ['That taking part is **voluntary**', 1],
        ['That **research is not** personalised **treatment**', 1]),
    ] },
  { quiz: 'joan-devmkt', k: 'when is the use of a', title: 'When a placebo is ethical',
    hook: 'No proven treatment exists, so nobody loses one.',
    groups: [
      G('When it is acceptable',
        ['**No proven treatment exists** for the condition', 0],
        ['Or it is **methodologically necessary** and **does not cause serious harm**', 0]),
      G('Example',
        ['A **placebo arm** for a condition with **no effective therapy yet**', 1],
        ['**Nobody is denied a treatment that works**', 1]),
    ] },
  { quiz: 'joan-devmkt', k: 'what ethical problem does randomisation raise', title: 'The ethical problem with randomisation',
    hook: 'Fair only while nobody knows which is better.',
    groups: [
      G('The problem',
        ['Randomising increases **validity**', 0],
        ['But it **may deny** a participant the **best currently known treatment**', 0]),
      G('When it is justified',
        ['Only with **genuine professional uncertainty** about which is better', 1],
        ['e.g. a **new medicine** vs **standard care**', 1]),
    ] },
  { quiz: 'joan-devmkt', k: 'give one reason vulnerable patients need', title: 'Protecting vulnerable patients in trials',
    hook: 'Protect them, but don’t take away their choice.',
    groups: [
      G('Why they need protection',
        ['A history of **serious abuses** in human research', 0],
        ['Strict rules push trials to countries with **weaker protections**', 0]),
      G('How it can go too far',
        ['**Over-protection** can **conflict with autonomy**', 1],
        ['e.g. a patient with **life-threatening cancer** **denied the choice** of a trial', 1]),
    ] },
  { quiz: 'joan-devmkt', k: 'what is direct to consumer advertising', title: 'Direct-to-consumer advertising',
    hook: 'Prescription-medicine ads aimed at the public: rare worldwide.',
    groups: [
      G('What it is',
        ['It promotes a **branded prescription medicine** **to the public**', 0]),
      G('Why NZ is unusual',
        ['**One of only two developed countries** that **permit it**', 1],
        ['Most restrict it to **health professionals**', 1],
        ['It can **drive demand** for medicines that **may not be appropriate**', 1]),
    ] },
  { quiz: 'joan-devmkt', k: 'what is a reminder advertisement for', title: 'Reminder advertisements',
    hook: 'Just the name: it keeps the brand familiar.',
    groups: [
      G('What it is',
        ['It mentions the **medicine’s name only**', 0],
        ['**Without saying what it treats**: it keeps the **brand familiar**', 0]),
      G('Example',
        ['A **billboard** or **pen** with only the **product name and logo**', 1]),
    ] },
  { quiz: 'joan-devmkt', k: 'what is health seeking disease awareness', title: 'Health-seeking (disease awareness) ads',
    hook: 'Looks like education, can work like an ad.',
    groups: [
      G('What it is',
        ['It educates about a **health condition**, **rather than a product**', 0],
        ['e.g. “**talk to your doctor about**…”', 0]),
      G('Why it can be a concern',
        ['It may **steer people towards a related brand**', 1],
        ['**Driving demand** while looking like **neutral health education**', 1]),
    ] },
  { quiz: 'joan-devmkt', k: 'name two requirements of the therapeutic', title: 'The Therapeutic and Health Advertising Code',
    hook: 'Evidence, truth, safety information. The ASA enforces it.',
    groups: [
      G('Who administers it',
        ['The **Advertising Standards Authority**', 0],
        ['**Anyone can complain**', 0]),
      G('Two requirements',
        ['Claims **substantiated with credible evidence**', 1],
        ['**Truthful**, **not misleading**, no **exaggerated benefits**', 1],
        ['**Key safety information** included', 1]),
    ] },
  { quiz: 'joan-devmkt', k: 'how can a nurse accidentally advertise', title: 'A nurse can advertise without meaning to',
    hook: 'Say the generic name, never “this brand is best”.',
    groups: [
      G('How',
        ['Advertising includes **what is said aloud**', 0],
        ['**Praising one brand** over another can **count as advertising**', 0]),
      G('How to avoid it, with an example',
        ['Talk in **generic names**; give **factual, balanced** information', 1],
        ['Name the **generic pain reliever**, not “this brand **is the best**”', 1]),
    ] },

  /* ── Rongoā Māori ── */
  { quiz: 'joan-cam', k: 'define rongo m ori and give', title: 'Rongoā Māori: its three parts',
    hook: 'Mirimiri, karakia, rongoā rākau: hands, prayer, plants.',
    groups: [
      G('Definition',
        ['**Traditional Māori healing**', 0],
        ['With a **strong spiritual element**: a **Māori model of health**', 0]),
      G('Its three parts',
        ['**Mirimiri**: **massage** / body work', 1],
        ['**Karakia**: **prayer**', 1],
        ['**Rongoā rākau**: **native plant-based remedies**, e.g. a **balm**', 1]),
    ] },
  { quiz: 'joan-cam', k: 'who is responsible for a traditional', title: 'Who is responsible for a rongoā remedy',
    hook: 'The practitioner owns the remedy; the nurse brings everyone together.',
    groups: [
      G('Who is responsible',
        ['The **tohunga** or **rongoā practitioner**', 0],
        ['**Karakia and kawa differ** between tribal areas', 0],
        ['The nurse **does not prescribe or prepare it**', 0]),
      G('What the nurse does',
        ['**Arranges a discussion** with everyone involved', 1],
        ['So the client can make an **informed decision**', 1]),
    ] },
  { quiz: 'joan-cam', k: 'list three issues a nurse should', title: 'Rongoā with prescribed medicines: issues',
    hook: 'Who, what, side effects, interactions, evidence.',
    groups: [
      G('Any three issues',
        ['The **knowledge and experience** of the practitioner', 0],
        ['Is it **appropriate for the client’s condition**?', 0],
        ['**Potential side effects**', 0],
        ['**Potential interactions** with prescribed medicines', 1],
        ['Any **evidence-based information** about it?', 1]),
      G('Why one matters',
        ['A **plant tonic** used to **lower blood sugar**, with **diabetes medicine**', 2],
        ['It could **add to its effect**', 2],
        ['Tell the **prescriber**; **blood glucose needs watching**', 2]),
    ] },
  { quiz: 'joan-cam', k: 'distinguish the biomedical view of medicine', title: 'Biomedical vs wholistic',
    hook: 'Fix the faulty part, or care for the whole person.',
    groups: [
      G('The difference',
        ['**Biomedical**: illness is a **fault in one part**; a **targeted** fix', 0],
        ['**Wholistic**: the person is **treated as a whole**: body, mind, spirit, whānau', 0]),
      G('A wholistic model',
        ['**Te Whare Tapa Whā**', 1],
        ['**Taha tinana**, **hinengaro**, **wairua**, **whānau**', 1]),
    ] },
  { quiz: 'joan-cam', k: 'what is integrated medicine give an', title: 'Integrated medicine',
    hook: 'Both systems, one goal, sharing what they know.',
    groups: [
      G('Definition',
        ['**Evidence-based complementary** therapies with **conventional** (biomedical) care', 0],
        ['**Sharing evidence** for the **common goal** of better health', 0],
        ['**Large gaps in the evidence** remain', 0]),
      G('Example',
        ['**Mirimiri and karakia** alongside **prescribed treatment**', 1],
        ['The team and practitioner each **aware** of the other', 1]),
    ] },
  { quiz: 'joan-cam', k: 'what is tikanga rongo ministry of', title: 'Tikanga ā Rongoā (2014)',
    hook: 'A voluntary benchmark for safe, quality rongoā.',
    groups: [
      G('What it is',
        ['A **voluntary standard**, made **with the rongoā sector**', 0],
        ['**Requirements for providers** of rongoā services: a **benchmark of excellence**', 0]),
      G('What it is for',
        ['**Safe, quality rongoā care** for **tūroro** (patients)', 1],
        ['**Consistent quality** between providers; growing the **rongoā workforce**', 1]),
    ] },
  { quiz: 'joan-cam', k: 'health is described as a taonga', title: 'Health as a taonga',
    hook: 'A treasure Te Tiriti promised, and a seven-year gap.',
    groups: [
      G('What it means',
        ['Te Tiriti guaranteed Māori the **same rights and privileges**', 0],
        ['Māori kept **tino rangatiratanga** over their **taonga** (treasures)', 0],
        ['Health is a taonga: a **right to equal health outcomes**', 0]),
      G('A statistic',
        ['**Life expectancy** is **7.1 years shorter** for Māori', 1]),
    ] },
  { quiz: 'joan-cam', k: 'what is te maramataka and how', title: 'Te maramataka',
    hook: 'The moon’s phases guide energy, mood and rest.',
    groups: [
      G('What it is',
        ['The **Māori lunar calendar**', 0],
        ['A way of **attuning with the environment**', 0]),
      G('How it is used in health',
        ['Each phase has its own **energy, mood and activity levels**', 1],
        ['**Plan activity and rest** around it', 1]),
    ] },
];
