/* Short versions of the topic rows' written answers, Modules 5–8 (patient education, the older adult, the lifespan,
   legal & ethical, drug development & marketing, anaphylaxis). The tool wrote every one of those questions and model
   answers (ported from intro-pharm); each is cut here to one fact a line, grouped under the question's parts, with a
   memory hook. Gated by shorts.mjs (see content/shorts.js). */
const G = (q, ...facts) => ({ q, facts: facts.map(([t, of, fix]) => (fix ? { t, of, fix } : { t, of })) });

export const TOPICS_B = [
  /* ── M5 · Patient education ── */
  { quiz: 'educ', k: 'define a medication error and explain how', title: 'Medication errors: definition, examples',
    hook: 'Preventable, human, and usually a missed Right or Check.',
    groups: [
      G('Definition',
        ['Any **preventable event** that may cause **inappropriate medication use** or **harm**', 0],
        ['Unlike an adverse effect, it is **harm arising from human action**', 1]),
      G('Four examples',
        ['A drug given despite a **known allergy**', 2],
        ['A **wrong dosage dispensed**', 2],
        ['Errors in the **medication calculation**; **deciphering handwriting** wrongly', 3],
        ['**Documentation errors**: a **dose being duplicated**', 4]),
      G('The root',
        ['Most trace back to the **8 Rights + 2 Checks**', 5]),
    ] },
  { quiz: 'educ', k: 'name six ways to prevent medication errors', title: 'Six ways to prevent medication errors',
    hook: 'Label, dose, decimal, change, new drug, bad writing.',
    groups: [
      G('The six, each with its reason',
        ['**Check labels**: **similar names** or containers', 0],
        ['Does the **dose sound right**? Usually **one or two tablets**', 1],
        ['**Check the decimal point**: **0.1, 1.0 or 10**?', 2],
        ['**Question sudden changes** in dose', 3],
        ['**Learn about new medications** first: the **NZ Formulary**', 4],
        ['Do not try to **decipher illegible writing**: **ask the prescriber**', 5]),
    ] },
  { quiz: 'educ', k: 'describe the five steps for managing and', title: 'Managing a medication error: five steps',
    hook: 'Own it, tell, write, protect the patient, report.',
    groups: [
      G('The five steps',
        ['1 **Acknowledge** it **immediately**', 0],
        ['2 **Report promptly**, e.g. to the **charge nurse**', 1],
        ['3 **Document** it **accurately and objectively**', 2],
        ['4 **Minimise harm**, e.g. **monitoring**', 3],
        ['5 Complete an **incident report**', 4]),
    ] },
  { quiz: 'educ', k: 'what are the consequences of intentional concealment', title: 'Concealing a medication error',
    hook: 'Hiding it hurts the patient, and ends in discipline.',
    groups: [
      G('What it is',
        ['**Not telling** someone when you **know you made an error**', 0]),
      G('The consequences',
        ['The patient is **more at risk of injury, illness or death**', 1],
        ['You face **disciplinary action**', 2]),
    ] },
  { quiz: 'educ', k: 'explain nursing liability for medication errors', title: 'Nursing liability for medication errors',
    hook: 'What you do, what you don’t, what you hand on, what you give.',
    groups: [
      G('Who is liable',
        ['**Prescribers**, **pharmacists** and **nurses** can all be **held responsible**', 0]),
      G('For nurses',
        ['Liable for their **actions and omissions**', 1],
        ['Liable for the **duties they delegate**', 2],
        ['**Personally responsible** for **every medication they administer**', 3]),
    ] },
  { quiz: 'educ', k: 'name the three steps to meeting health', title: 'Health literacy: Ask, Build, Check',
    hook: 'Ask what they already know before you teach.',
    groups: [
      G('The three steps',
        ['**Ask**, **Build**, **Check**', 0]),
      G('Step 1: Ask, and why',
        ['**Ask questions** to find out **what people know**', 1],
        ['Connect new information to their **prior knowledge**', 2],
        ['**Avoid repeating** what they know, or they **disengage**', 3],
        ['Ask **who**: the individual, or **whānau**', 4],
        ['**Open-ended questions**; ask for a **demonstration**', 5]),
    ] },
  { quiz: 'educ', k: 'what does step 2 build involve', title: 'Health literacy step 2: Build',
    hook: 'Their words, pauses, plain language, pictures.',
    groups: [
      G('Build',
        ['**Connect new information** to what they **already know**', 0],
        ['Use the **words and phrases** the person used', 1],
        ['**Pause** after new information', 2],
        ['Explain the **next steps**: effects, **adverse effects**, **follow-up**', 3],
        ['**Explain and repeat** key terms, e.g. the **generic medication name**', 4],
        ['**Avoid medical jargon**: “**sore tummy**”', 5],
        ['Use **visual resources**; **highlight** key ideas', 6]),
    ] },
  { quiz: 'educ', k: 'what does step 3 check involve and', title: 'Health literacy step 3: Check',
    hook: 'Teach-back tests YOU, not them.',
    groups: [
      G('Check',
        ['Check how clear **your communication** was', 0],
        ['Don’t rely on **nodding**; avoid “**Do you understand?**”', 1],
        ['Use **teach back**: they explain **in their own words**', 2],
        ['Use **prompts**; **take responsibility** if you were unclear', 3]),
      G('Whose responsibility clarity is',
        ['**Not a test** of their **intelligence**: the responsibility **lies with you**', 4],
        ['Not recalled? Go **back to Step 2** and explain it **a different way**', 5]),
    ] },
  { quiz: 'educ', k: 'name the five principles of te tiriti', title: 'Te Tiriti: five principles',
    hook: 'Self-determination, equity, active protection, options, partnership.',
    groups: [
      G('The five principles',
        ['**Tino Rangatiratanga**: **self-determination**', 0],
        ['**Mana Taurite**: **equity**', 1],
        ['**Whakamarumarutia**: **active protection**', 2],
        ['**Kōwhiringa**: **options**', 3],
        ['**Pātuitanga**: **partnership**', 4],
        ['The “**three Ps**” (1986) are **outdated**', 5]),
    ] },
  { quiz: 'educ', k: 'give one practical medication education example for', title: 'Te Tiriti in medication education',
    hook: 'Ask how they feel, give time, respect rongoā, offer options, plan together.',
    groups: [
      G('One example each',
        ['**Tino Rangatiratanga**: ask “**How do you feel** about starting this?”', 0],
        ['**Mana Taurite**: **more time** for those who need it; **advocacy**', 1],
        ['**Whakamarumarutia**: **respect rongoā Māori** alongside prescribed medicine', 2],
        ['**Kōwhiringa**: **offer alternatives** (timing, formulation)', 3],
        ['**Pātuitanga**: **co-create a management plan**', 4]),
    ] },
  { quiz: 'educ', k: 'what should a nurse teach a parent', title: 'Teaching parents about children’s medicines',
    hook: 'Out of reach, measure properly, ask before crushing, never force.',
    groups: [
      G('What to teach',
        ['Store medicines **out of reach and out of sight**', 0],
        ['Use a **proper measuring cup, spoon or syringe**', 1],
        ['**Check with your pharmacist before crushing** or cutting', 2],
        ['**Do not force** a child: **vomiting**, **choking**', 3],
        ['Try an **ice block** to numb the taste; **praise and a reward**', 4]),
    ] },
  { quiz: 'educ', k: 'how should medication education be adapted for toddlers', title: 'Teaching toddlers and children',
    hook: 'Simple words, a story, the truth, and never “lollies”.',
    groups: [
      G('How to adapt it',
        ['**Age-appropriate language**: “**sore tummy**”', 0],
        ['Say it will **help them feel better**', 1],
        ['Use **similes or stories**: antibiotics as **soldiers** fighting **germs**', 2],
        ['**Do not lie**: an immunisation is **going to feel sore**', 3],
        ['**Never** call medicine **lollies**: **risk of overdose**', 4],
        ['Give **simple choices**', 5]),
    ] },
  { quiz: 'educ', k: 'how should medication education be adapted for teenagers', title: 'Teaching teenagers',
    hook: 'Explain how it works, use it right, watch for effects, never share.',
    groups: [
      G('How to adapt it',
        ['Explain the **mechanism of action** simply: why it is **relevant** to them', 0],
        ['**Correct use** (route and dose) is **essential**', 1],
        ['How to **look out for adverse effects**', 2],
        ['Do **alcohol or drugs** affect it?', 3],
        ['Medicines should **never be shared**', 4],
        ['Encourage them to **ask questions**: they are **developing independence**', 5]),
    ] },
  { quiz: 'educ', k: 'how should medication education be adapted for older', title: 'Teaching older adults',
    hook: 'Self-management, senses, energy, whānau (with consent), dignity.',
    groups: [
      G('How to adapt it',
        ['Educate for **self-management and adherence**: purpose, dose, timing', 0],
        ['**Sensory needs**: **extra time**, **hearing aids and glasses**, **large-print**', 1],
        ['Plan around **fatigue and energy levels**', 2],
        ['Involve **whānau** and **carers**, as long as the older adult **gives consent**', 3],
        ['Uphold **dignity and autonomy**', 4]),
    ] },

  /* ── M6 · The older adult ── */
  { quiz: 'elderly', k: 'how is an older person defined in', title: 'Defining an older person',
    hook: '65+: young-old, old-old, frail.',
    groups: [
      G('Definition',
        ['Aged **65 years and over**', 0]),
      G('The sub-categories',
        ['**Young-old**: **65–79**', 1],
        ['**Old-old**: **80+**', 2],
        ['**Frail elderly**: 65+ with a **debilitating condition**', 3]),
      G('Note',
        ['**Wide variations** in ageing; **age-related changes** are not **disease-related changes**', 4]),
    ] },
  { quiz: 'elderly', k: 'give the figures for medication use in', title: 'Older adults and medicines: the figures',
    hook: '12% of the people, 31% of the prescriptions.',
    groups: [
      G('The figures',
        ['Over-65s: about **12% of the population**', 0],
        ['… but **31% of prescribed medications**', 1],
        ['On average **4–5 prescribed** medicines **plus 2 over-the-counter**', 5]),
      G('Three reasons',
        ['**Increased severity of chronic illness**', 2],
        ['**Multiple pathologies**', 3],
        ['**Excessive prescribing**', 4]),
    ] },
  { quiz: 'elderly', k: 'describe the age related changes to drug absorption', title: 'Ageing and absorption',
    hook: 'Everything slows, but it rarely matters.',
    groups: [
      G('The changes',
        ['**Slowed gastric emptying**', 0],
        ['**Reduced GI motility**: **slower absorption**', 1],
        ['**Decreased intestinal surface area**', 2]),
      G('Clinical significance',
        ['They can **delay** absorption, but are **often not clinically significant**', 3]),
    ] },
  { quiz: 'elderly', k: 'describe the three age related changes to', title: 'Ageing and distribution',
    hook: 'More fat, less water, less protein.',
    groups: [
      G('The three changes',
        ['**Increased body fat**: **fat-soluble** drugs act **longer**', 0],
        ['**Reduced total body water**: water-soluble drugs **shorter and stronger**', 1],
        ['**Lower protein binding**: **more free (active) drug**', 2]),
      G('Why it matters',
        ['It changes the **duration of action** and **potential toxicity**', 3]),
    ] },
  { quiz: 'elderly', k: 'describe the age related changes to drug metabolism', title: 'Ageing and metabolism',
    hook: 'A slower liver, and heart failure slows it more.',
    groups: [
      G('The changes',
        ['**Slowed liver metabolism** and **reduced blood flow**', 0],
        ['Some reactions **slowed** (**oxidation**); some **unaffected** (**conjugation**)', 1],
        ['**Heart failure** impairs the liver more: **accumulation and toxicity**', 2]),
    ] },
  { quiz: 'elderly', k: 'describe the age related changes to renal', title: 'Ageing and renal excretion',
    hook: 'Fewer nephrons, slower clearance, higher levels.',
    groups: [
      G('The changes',
        ['**Nephron loss**, **reduced blood flow**, **lower glomerular filtration rate**', 0],
        ['**Slower elimination** of renally cleared drugs', 0]),
      G('The consequence',
        ['Raises **plasma drug levels**; extends **half-lives**', 1],
        ['**Increased risk of toxicity**', 1],
        ['**Heart failure** can reduce **renal perfusion** further', 2],
        ['**Renal function tests** and **therapeutic drug monitoring**', 3]),
    ] },
  { quiz: 'elderly', k: 'explain the pharmacodynamic changes of ageing', title: 'Pharmacodynamic changes of ageing',
    hook: 'Fewer or changed receptors: effects go up or down.',
    groups: [
      G('The changes',
        ['**Increased or decreased** drug effects, by drug and receptor', 0],
        ['**Fewer receptors** at the target site', 1],
        ['**Altered receptor responsiveness**: **second-messenger** changes', 2],
        ['**Down-regulation** from **prolonged exposure**', 3]),
    ] },
  { quiz: 'elderly', k: 'name the six most common adverse effects', title: 'Six common adverse effects in older adults',
    hook: 'Falls, dizzy on standing, delirium, kidneys, gut bleeds, brain bleeds.',
    groups: [
      G('The six',
        ['**Falls**', 0],
        ['**Orthostatic hypotension**', 1],
        ['**Delirium**', 2],
        ['**Renal failure**', 3],
        ['**Gastrointestinal bleeding**', 4],
        ['**Intracranial bleeding**', 5]),
    ] },
  { quiz: 'elderly', k: 'give the four reasons adverse drug reactions', title: 'Why ADRs rise in older adults',
    hook: 'PK, PD, polypharmacy, poor prescribing.',
    groups: [
      G('The four reasons',
        ['**Pharmacokinetic changes**: altered distribution, **reduced clearance**', 0],
        ['**Pharmacodynamic changes**: **increased receptor sensitivity** (CNS, heart)', 1],
        ['A higher burden of **illness and polypharmacy**: more **interactions**', 2],
        ['**Inappropriate prescribing** and **poor monitoring**', 3]),
    ] },
  { quiz: 'elderly', k: 'what is the beers criteria and give', title: 'The Beers Criteria',
    hook: 'A list of drugs to avoid, or use carefully, in older adults.',
    groups: [
      G('What it is',
        ['A tool: drugs to be **avoided** or **used with caution** in **older adults**', 0]),
      G('The two examples',
        ['**NSAIDs**: avoid **chronic use**: **gastrointestinal bleeding**, **ulceration**', 1],
        ['**Digoxin**: not **first-line** for **atrial fibrillation**', 2],
        ['… **nausea**, **dysrhythmias**, **visual disorders**, **hallucinations**', 2]),
    ] },
  { quiz: 'elderly', k: 'under what two conditions may a medication', title: 'When a medicine may be crushed',
    hook: 'The pharmacist says yes AND it is in the patient’s best interest.',
    groups: [
      G('What crushing can cause',
        ['**Less effective**, **ineffective**, or **dangerous**', 0],
        ['e.g. **enteric-coated** but then **rapidly absorbed**', 0]),
      G('The two conditions',
        ['A **pharmacist advises** it **does not compromise** the medicine', 1],
        ['**And** it is in the patient’s **best interest**', 2]),
    ] },
  { quiz: 'elderly', k: 'define polypharmacy and list the five risks', title: 'Polypharmacy: five risks',
    hook: 'Five or more drugs; five risks.',
    groups: [
      G('Definition',
        ['The **concurrent use of multiple medications**, usually **5 or more**', 0],
        ['It implies **too many**, or **unnecessary**, drugs', 1]),
      G('The five risks',
        ['**Adverse effects**', 2],
        ['**Drug–drug interactions**', 3],
        ['**Non-adherence**', 4],
        ['**Falls**', 5],
        ['**Mortality**', 6]),
    ] },
  { quiz: 'elderly', k: 'give the auckland retirement village prevalence figures', title: 'Polypharmacy in Auckland retirement villages',
    hook: 'Half on five or more; one in twenty on ten or more.',
    groups: [
      G('The study',
        ['**578** residents of **33** Auckland villages; median age **81.6**', 0]),
      G('The figures',
        ['**51.8%**: **polypharmacy** (5+ medicines)', 1],
        ['**5.7%**: **hyperpolypharmacy** (10+)', 2],
        ['A mean of **4.8 regular** medicines plus **0.7 as-required**', 3]),
    ] },
  { quiz: 'elderly', k: 'give six reasons polypharmacy occurs', title: 'Why polypharmacy happens',
    hook: 'More illness, more prescribers, ads, easy pills, no reviews, duplicates.',
    groups: [
      G('Any six',
        ['More **co-morbidities**', 0],
        ['**Multiple prescribers**: a GP and a clinic', 1],
        ['Medicines **can be advertised** in NZ', 2],
        ['**Easier to access** than lifestyle change', 3],
        ['Medicines **not being reviewed regularly** (a GP consult is **15 minutes**)', 4],
        ['**Duplicate medications** (brand names)', 5],
        ['**Traditional therapies** alongside', 6],
        ['The **prescribing cascade**', 7]),
    ] },
  { quiz: 'elderly', k: 'name five strategies to manage polypharmacy', title: 'Managing polypharmacy: five strategies',
    hook: 'Review, tools, deprescribe, involve the patient, document.',
    groups: [
      G('The five',
        ['**Systematic medication review**', 0],
        ['**Validated prescribing tools**: the **Beers Criteria**', 1],
        ['**Deprescribing**', 2],
        ['**Patient-centred decision-making**', 3],
        ['**Good quality documentation**', 4]),
      G('The nurse’s part',
        ['In the **multi-disciplinary team**, or as an **advocate** for review', 5]),
    ] },
  { quiz: 'elderly', k: 'besides older adults which groups are at', title: 'Other groups at risk of polypharmacy',
    hook: 'Not just the old: kids, disability, cognition, mental health, institutions, language.',
    groups: [
      G('The point',
        ['Older adults are the **highest-risk** group, but it is **not only** theirs', 0]),
      G('The other groups',
        ['**Infants and children** with complex conditions', 1],
        ['**People with disabilities**', 2],
        ['**Cognitive impairment**', 3],
        ['**Chronic mental health conditions**', 4],
        ['**Institutional settings**: **prison**, residential care', 5],
        ['**Language or communication barriers**', 6]),
    ] },
  { quiz: 'elderly', k: 'give four pieces of key legislation and', title: 'Aged-care medicine law and guidance',
    hook: 'Old People’s Home Regs, HPCAA, the Code of Rights, the Care Guides, NCNZ.',
    groups: [
      G('Any four',
        ['**Old People’s Home Regulations** (1987)', 0],
        ['**Health Practitioners Competence Assurance Act** (2003)', 1],
        ['The **Code of Health and Disability Services Consumers’ Rights**', 2],
        ['**Medicines Care Guides for Residential Aged Care** (2011)', 3],
        ['NCNZ **Standards of Practice** and **Code of Conduct**', 4]),
    ] },
  { quiz: 'elderly', k: 'distinguish errors of commission from errors of', title: 'Errors of commission vs omission',
    hook: 'Commission = DOING it wrong. Omission = NOT doing it.',
    groups: [
      G('Commission (doing)',
        ['An error of **doing**', 0],
        ['e.g. the **wrong dose**; **look-alike packaging**', 0],
        ['e.g. medicine from **someone else**; **expired medication**', 1]),
      G('Omission (not doing)',
        ['An error of **not doing**', 2],
        ['e.g. **forgetting to take** it; **too low a dose**', 2],
        ['e.g. **forgetting instructions**; a dose at the **wrong time**', 3]),
    ] },

  /* ── M6 · Across the lifespan ── */
  { quiz: 'lifespan', k: 'why does this session focus on pharmacokinetics', title: 'Why the session focuses on PK',
    hook: 'PK can be predicted; PD in pregnancy and children cannot.',
    groups: [
      G('Why',
        ['There are **PK and PD changes** in pregnancy and children', 0],
        ['**Pharmacokinetic changes** are **easier to predict**', 1],
        ['**Pharmacodynamic changes** are **more complex**, **highly variable**, **poorly defined**', 2]),
    ] },
  { quiz: 'lifespan', k: 'how do medications reach and affect the', title: 'How medicines reach the foetus',
    hook: 'Whatever the parent absorbs can reach the baby; the earliest weeks are worst.',
    groups: [
      G('How they reach it',
        ['Anything absorbed can reach it via the **maternal circulation**', 0]),
      G('How it is managed',
        ['Use should be **limited**: the **benefit** must outweigh any **risk to the foetus**', 1],
        ['When **trying to get pregnant**, **talk to a health professional** first', 2]),
      G('The most vulnerable time',
        ['The **first few weeks** of development', 3]),
    ] },
  { quiz: 'lifespan', k: 'describe the pharmacokinetic changes of pregnancy under', title: 'Pregnancy under ADME',
    hook: 'A slower gut, more blood and fat, a changed liver, faster kidneys.',
    groups: [
      G('Absorption',
        ['**Delayed gastric emptying**, **reduced gut motility**', 0],
        ['**Vomiting** can prevent full absorption', 0]),
      G('Distribution',
        ['Increased **maternal plasma volume** **dilutes** the drug', 1],
        ['More **body fat** stores **lipophilic** drugs; drugs **diffuse across the placenta**', 1]),
      G('Metabolism',
        ['Maternal enzymes change: **caffeine** metabolism **slower**, **paracetamol** **faster**', 2],
        ['The foetus has **immature enzymes**: **longer drug effects**', 3]),
      G('Excretion',
        ['**Increased renal blood flow** **increases elimination**', 4],
        ['It may need **higher or more frequent doses**', 4]),
    ] },
  { quiz: 'lifespan', k: 'define a teratogen state the highest risk', title: 'Teratogens: definition, timing, sources',
    hook: 'The first 12 weeks, when the organs form.',
    groups: [
      G('Definition',
        ['Any substance that can cause **developmental abnormalities** in a **foetus**', 0]),
      G('Highest risk',
        ['The **first trimester** (**weeks 0–12**)', 1]),
      G('Four sources',
        ['**Prescription drugs**, **OTC medicines**, **herbal products**', 2],
        ['**Alcohol**, **nicotine**, **drugs of misuse**', 2]),
      G('What they cause',
        ['**Birth defects**, **developmental delay**, **intellectual disability**', 3]),
    ] },
  { quiz: 'lifespan', k: 'give the four teratogen examples from the', title: 'Four teratogens: timing and defects',
    hook: 'Alcohol, cocaine, isotretinoin, tetracycline.',
    groups: [
      G('The four',
        ['**Alcohol** <12 weeks: **fetal alcohol syndrome**, **heart defects**', 0],
        ['**Cocaine** (2nd–3rd trimester): **premature labour**, **intracranial bleeding**', 1],
        ['**Isotretinoin** (acne): **hydrocephalus**, **foetal death**', 2],
        ['**Tetracycline** >20 weeks: **stained teeth**, **bone growth defects**', 3]),
    ] },
  { quiz: 'lifespan', k: 'describe the effects of alcohol nicotine cannabis', title: 'Drugs of dependence and the foetus',
    hook: 'Fat-soluble drugs cross the placenta.',
    groups: [
      G('Why they reach the foetus',
        ['Most are **lipid-soluble**, so they **cross the placenta**', 0]),
      G('Each drug',
        ['**Alcohol**: **Foetal Alcohol Spectrum Disorder**', 1],
        ['**Nicotine**: **pregnancy loss**, **preterm birth**, **low birthweight**', 2],
        ['**Cannabis**: **long-term risks** not yet known', 3],
        ['**Caffeine**: **safe in small amounts**; **reduced clearance**', 4],
        ['**Opioid dependence**: newborn **withdrawal**: **tremors**, **seizures**', 5]),
    ] },
  { quiz: 'lifespan', k: 'what is the medication pregnancy category system', title: 'Pregnancy categories: A and X',
    hook: 'A is safe (paracetamol); X is never in pregnancy.',
    groups: [
      G('The scale',
        ['From A (**no harm**) through B, C, D to X (**high risk**, **contraindicated**)', 0]),
      G('A and X',
        ['**Category A**: taken by **a large number** of pregnant people', 1],
        ['… **without any proven increase** in harm; e.g. **paracetamol**', 1],
        ['**Category X**: **the most dangerous**; **should not be used** in any possible pregnancy', 2]),
    ] },
  { quiz: 'lifespan', k: 'on what three factors does medication transfer', title: 'Medicines in breast milk: three factors',
    hook: 'Blood level, milk amount, fat-solubility. Keep the parent well.',
    groups: [
      G('The three factors',
        ['**Maternal drug plasma concentration**', 1],
        ['**Amount of milk** consumed', 2],
        ['**Lipid solubility** of the drug', 3]),
      G('The guiding principle',
        ['Most medicines **can enter breast milk**', 0],
        ['**Maintaining maternal health is essential**: don’t **automatically** stop', 4]),
    ] },
  { quiz: 'lifespan', k: 'which drugs concentrate most in breastmilk what', title: 'Drugs in breast milk, and the advice',
    hook: 'Fat-soluble nerve drugs concentrate; plan around alcohol; no meth.',
    groups: [
      G('Which concentrate',
        ['**Lipid-soluble** drugs that **affect the nervous system** (**morphine**, **codeine**)', 0]),
      G('Effects on the infant',
        ['**Sedation**; a **reduced suckling reflex**, **poor feeding**', 1]),
      G('The advice',
        ['**Alcohol**: **plan feeds** to minimise exposure', 2],
        ['**Caffeine**: **safe in moderate amounts**', 3],
        ['**Nicotine**: raises **SUDI** risk; **nicotine-replacement therapy**', 4],
        ['**Methamphetamine**: breastfeeding is **not recommended**', 5]),
    ] },
  { quiz: 'lifespan', k: 'what three risks does a prescriber balance', title: 'Breastfeeding: what the prescriber balances',
    hook: 'The benefits of feeding, the risk to baby, the risk to the parent.',
    groups: [
      G('The three',
        ['The **benefits of continued breastfeeding**', 0],
        ['The **risks of infant medication exposure**', 1],
        ['The **risks to the breastfeeding parent** if **essential medications are stopped**', 2]),
      G('In practice',
        ['Most can be **used with caution**: **evaluate individually**', 3]),
    ] },
  { quiz: 'lifespan', k: 'children are just miniature adults true or', title: 'Children are not miniature adults',
    hook: 'False: fewer barriers, poor heat and balance control, more water.',
    groups: [
      G('The answer',
        ['**False**: children are **physiologically different**', 0]),
      G('Four reasons',
        ['**Lack of protective mechanisms and barriers**', 1],
        ['**Poor temperature regulation**', 2],
        ['**Poor homeostatic mechanisms**', 3],
        ['**Different body composition**: **higher body water (75%)**, less fat', 4]),
    ] },
  { quiz: 'lifespan', k: 'give the age definitions for preterm full', title: 'Age definitions: preterm to adolescent',
    hook: '<36 weeks, 36–40, under 4 weeks, to 1 year, to 12, to 16.',
    groups: [
      G('The definitions',
        ['**Preterm**: born at **less than 36 weeks**', 0],
        ['**Full term**: **36 to 40+ weeks**', 1],
        ['**Neonate**: **less than 4 weeks** old', 2],
        ['**Infant**: **5 weeks to 1 year**', 3],
        ['**Child**: **1 to 12 years**', 4],
        ['**Adolescent**: **12 to 16 years**', 5]),
    ] },
  { quiz: 'lifespan', k: 'describe the pharmacokinetics of the neonate', title: 'Neonatal pharmacokinetics',
    hook: 'Everything immature: more in, slower out, into the brain.',
    groups: [
      G('The features',
        ['**Thin skin** and **low stomach acid** can **increase drug absorption**', 0],
        ['**Poor thermoregulation**; a **dehydration** risk', 1],
        ['**Immature** metabolising **enzymes** (e.g. **paracetamol**)', 2],
        ['**Immature kidneys** → **slower drug clearance**, **prolonged half-life**', 3],
        ['**Immature blood–brain barrier** → **CNS toxicity** risk', 4]),
    ] },
  { quiz: 'lifespan', k: 'describe the pharmacokinetics of infants and children', title: 'PK in infants and children',
    hook: 'Slow kidneys to 1, a fast liver to 10, doses by the kilo.',
    groups: [
      G('How it changes with age',
        ['Under **12 months**: **renal excretion is slower**, a **longer half-life**', 0],
        ['**By 1 year**: absorption, distribution, excretion **similar to adults**', 1],
        ['**Hepatic metabolism** is **faster** until about **10 years**', 2]),
      G('What it means for doses',
        ['More **body water** → a **lower concentration** of water-soluble drugs', 3],
        ['Doses are **weight-based** (**mg/kg**)', 4],
        ['Formulation: **taste masking**; an **inability to swallow tablets**', 5]),
    ] },
  { quiz: 'lifespan', k: 'why should paracetamol elixir not be given', title: 'Paracetamol under 3 months or 5 kg',
    hook: 'A narrow range, an immature liver, a toxic build-up.',
    groups: [
      G('Why',
        ['**Narrow therapeutic range**: a **higher risk of overdose**', 0],
        ['**Delayed development** of **hepatic enzymes**: **decreased rate of metabolism**', 1],
        ['More **toxic metabolites** → **liver injury**', 2]),
      G('From 3 months',
        ['An **mg/kg dose** may be given', 3]),
    ] },
  { quiz: 'lifespan', k: 'tama is 3 years old and weighs', title: 'Tama’s paracetamol dose',
    hook: '15 mg per kg × 17.7 kg.',
    groups: [
      G('Working',
        ['A single dose: **15 mg/kg**', 0],
        ['**15 × 17.7 = 265.5 mg**', 1],
        ['From **250 mg/5 mL**: **5.3 mL**', 2]),
      G('Why an adult dose is unsafe',
        ['An adult dose is **1000 mg**: **nearly four times** his', 3]),
    ] },
  { quiz: 'lifespan', k: 'list seven considerations when administering medications to', title: 'Giving medicines to children: seven points',
    hook: 'Dose, form, consent and assent, words, play, honesty, help.',
    groups: [
      G('The seven',
        ['An **appropriate dose** prescribed', 0],
        ['A **developmentally appropriate formulation** and route', 1],
        ['**Informed consent** from the guardian, plus the child’s **assent**', 2],
        ['**Communication** and **appropriate terminology**', 3],
        ['**Simple choices**, **distraction and play**', 4],
        ['**Honesty**', 5],
        ['**Secure assistance**, e.g. a **parent**', 6]),
    ] },

  /* ── M7 · Legal & ethical ── */
  { quiz: 'legal', k: 'define act regulation amendment policy and guideline', title: 'Act, regulation, amendment, policy, guideline',
    hook: 'Parliament → how → updates → your workplace → best advice.',
    groups: [
      G('The five terms',
        ['**Act**: **laws made by parliament**', 0],
        ['**Regulation**: under an Act: **how the Acts are enforced**', 1],
        ['**Amendment**: **changes** to an Act or Regulation', 2],
        ['**Policy**: **enforceable rules** within an organisation', 3],
        ['**Guideline**: **best practice advice**', 4]),
    ] },
  { quiz: 'legal', k: 'name the three key acts governing medications', title: 'Three key Acts for medicines',
    hook: 'Medicines 1981, Misuse of Drugs 1975, HPCAA 2003.',
    groups: [
      G('The Acts, and their regulations',
        ['**Medicines Act 1981** + **Medicines Regulations 1984**', 0],
        ['**Misuse of Drugs Act 1975** + **Regulations 1977**', 1],
        ['**Health Practitioners Competence Assurance Act 2003**', 2]),
    ] },
  { quiz: 'legal', k: 'what does the medicines act 1981 cover', title: 'What the Medicines Act 1981 does',
    hook: 'Covers, classifies, sets the rules, names the prescribers.',
    groups: [
      G('Five points',
        ['Covers **all medicines**', 0],
        ['Includes **cosmetics** and **supplements** with **therapeutic claims**', 1],
        ['**Classifies medicines**: prescription to general sale', 2],
        ['Rules for **clinical trials**, **manufacturing**, **advertising** and **sale**', 3],
        ['**Defines who can prescribe**', 4]),
    ] },
  { quiz: 'legal', k: 'what does the misuse of drugs act', title: 'What the Misuse of Drugs Act 1975 does',
    hook: 'Classes, prescribing, penalties, precursors; locked and double-locked.',
    groups: [
      G('Four points',
        ['**Defines drug classes**: **controlled** vs uncontrolled', 0],
        ['**Regulates prescribing** of controlled drugs', 1],
        ['**Penalties** and **police enforcement powers**', 2],
        ['**Controls precursor substances**', 3]),
      G('The two storage rules',
        ['Medication rooms **locked when not in use**', 4],
        ['Controlled drugs **double-locked**', 5]),
    ] },
  { quiz: 'legal', k: 'describe the three classes of controlled drug', title: 'Classes A, B and C',
    hook: 'A = never prescribed; B = double-locked; C = prescribed normally.',
    groups: [
      G('Class A',
        ['**High potential for abuse**; **very high risk of harm**', 0],
        ['**Not prescribed** for medical use: **heroin**, **cocaine**, **methamphetamine**', 0]),
      G('Class B',
        ['**Drugs of dependence**; **high risk of harm**; a **double-locked safe**', 1],
        ['e.g. **morphine**, **methylphenidate** (**Ritalin**)', 1]),
      G('Class C',
        ['**Lower potential for abuse**; **moderate risk of harm**', 2],
        ['**Prescribed “normally”**: **codeine**, **diazepam**', 2]),
    ] },
  { quiz: 'legal', k: 'define possession and supply under the misuse', title: 'Possession and supply',
    hook: 'Having it vs handing it on.',
    groups: [
      G('The rule',
        ['Unlawful to **use, possess or supply** without **legal authority**', 0]),
      G('The two terms',
        ['**Possession**: having it **in your control**: pocket, bag, car', 1],
        ['Only some may lawfully possess: **health professionals**, **emergency services**', 1],
        ['**Supply**: **making a drug available** to someone: **giving or selling**', 2]),
    ] },
  { quiz: 'legal', k: 'name the four regulators of nz medications', title: 'Four regulators of NZ medicines',
    hook: 'Medsafe safety, PHARMAC funding, HRC trials, CARM reactions.',
    groups: [
      G('Each, and its job',
        ['**Medsafe**: **safety and quality**', 0],
        ['**PHARMAC**: **funding and subsidy** decisions', 1],
        ['**Health Research Council**: **clinical trial approval**', 2],
        ['**CARM**: monitors **adverse reactions**', 3]),
    ] },
  { quiz: 'legal', k: 'what is the purpose of the hpcaa', title: 'The HPCAA: purpose, four requirements',
    hook: 'Scope, APC, competence, accountability.',
    groups: [
      G('Purpose',
        ['**Protects public safety**: **ongoing competence** and **fitness to practise**', 0],
        ['Limits **restricted activities** to registered practitioners', 0]),
      G('Four requirements',
        ['A **scope of practice**, set by the **Nursing Council**', 1],
        ['An **Annual Practising Certificate** (**APC**)', 2],
        ['**Clinical and cultural competence** (portfolios)', 3],
        ['**Legal accountability** through **disciplinary pathways**', 4]),
    ] },
  { quiz: 'legal', k: 'name the six pou of the ncnz', title: 'The six pou of competence',
    hook: 'Māori health, cultural safety, relationships, knowledge, care, leadership.',
    groups: [
      G('The six pou',
        ['**Māori Health**', 0],
        ['**Cultural Safety**', 1],
        ['**Whanaungatanga and Communication**', 2],
        ['**Pūkengatanga and Evidence-Informed Nursing Practice**', 3],
        ['**Manaakitanga and People-Centred Care**', 4],
        ['**Rangatiratanga and Leadership**', 5]),
    ] },
  { quiz: 'legal', k: 'define cultural safety as the nursing council', title: 'Cultural safety (Nursing Council)',
    hook: 'Decided by THAT person or family, not the nurse.',
    groups: [
      G('Definition',
        ['Effective practice with a person or family from **another culture**', 0],
        ['**Determined by that person or family**', 0]),
      G('Culture includes',
        ['**Age**, **gender**, **sexual orientation**, **occupation**, **socioeconomic status**', 1],
        ['**Ethnic origin**, **migrant experience**, **religious** belief, **disability**', 2]),
      G('The nurse',
        ['Has done **reflection on their own cultural identity**', 3]),
    ] },
  { quiz: 'legal', k: 'how does the rn scope of practice', title: 'RN scope and medicines: six points',
    hook: 'Law, judgement, talk, Te Tiriti, delegate, own it.',
    groups: [
      G('Six points',
        ['**Follow laws and policies** to administer safely', 0],
        ['**Clinical judgement** on needs and responses', 1],
        ['**Communicate** with **prescribers**, **pharmacists**, patients', 2],
        ['Uphold **Te Tiriti** and **cultural safety**', 3],
        ['**Delegate** medication tasks **appropriately**', 4],
        ['**Professionally accountable** for **every medication**', 5]),
    ] },
  { quiz: 'legal', k: 'list the eight principles of the ncnz', title: 'The Code of Conduct: eight principles',
    hook: 'Dignity, culture, partnership, safe care, privacy, colleagues, integrity, public trust.',
    groups: [
      G('The eight principles',
        ['1 Respect **dignity and individuality**', 0],
        ['2 Respect **cultural needs and values**', 1],
        ['3 **Work in partnership**', 2],
        ['4 **Safe and competent care**', 3],
        ['5 **Privacy and confidentiality**', 4],
        ['6 **Work respectfully with colleagues**', 5],
        ['7 **Act with integrity**', 6],
        ['8 Maintain **public trust**', 7]),
    ] },
  { quiz: 'legal', k: 'give a pharmacology example for code of', title: 'Code of Conduct principles 2, 4 and 7',
    hook: 'Check the ingredients, double-check, report honestly.',
    groups: [
      G('One example each',
        ['**Principle 2**: check ingredients like **gelatin capsules**', 0],
        ['**Principle 4**: **double-checking with another nurse** first', 1],
        ['**Principle 7**: **report medication errors honestly** and **immediately**', 2]),
    ] },
  { quiz: 'legal', k: 'name the seven m ori values in', title: 'NZNO ethics: seven Māori values',
    hook: 'Rangatiratanga, Manaakitanga, Tika, Whanaungatanga, Wairuatanga, Kotahitanga, Kaitiakitanga.',
    groups: [
      G('The seven values',
        ['**Rangatiratanga**: **self-determination**', 0],
        ['**Manaakitanga**: **mana is upheld** through **kindness, respect and care**', 1],
        ['**Tika**: **what is right and proper**', 2],
        ['**Whanaungatanga**: **relationships**, **whānau connections**', 3],
        ['**Wairuatanga**: **spiritual existence** is essential', 4],
        ['**Kotahitanga**: **unity** and **collective action**', 5],
        ['**Kaitiakitanga**: **guardianship**: **protect** land and resources', 6]),
    ] },
  { quiz: 'legal', k: 'name the nine western values in the', title: 'NZNO ethics: nine Western values',
    hook: 'Autonomy, do good, do no harm, justice, privacy, truth, faithfulness, environment, professionalism.',
    groups: [
      G('The nine values',
        ['**Autonomy**: **informed choices**', 0],
        ['**Beneficence**: **doing good**', 1],
        ['**Non-maleficence**: **causing no harm**', 2],
        ['**Justice**: treating people **fairly and equitably**', 3],
        ['**Confidentiality**: **protecting the privacy** of information', 4],
        ['**Veracity**: **truthful and honest**', 5],
        ['**Fidelity**: **keep promises**, **maintain trust**', 6],
        ['**Guardianship of environment and resources**', 7],
        ['**Being professional**: **accountability**, **integrity**, **competence**', 8]),
    ] },
  { quiz: 'legal', k: 'state the three exceptions to veracity and', title: 'Exceptions to veracity and confidentiality',
    hook: 'Truth can wait for harm, choice or emergency; secrets give way to risk.',
    groups: [
      G('Veracity exceptions',
        ['**Therapeutic privilege**: withholding to **prevent serious harm**', 0],
        ['**Patient preference**: they ask **not to know**', 1],
        ['**Emergencies**: e.g. **unconscious**, needing life-saving treatment', 2]),
      G('Confidentiality may be broken for',
        ['**Risk of harm to self** (self-inflicted)', 3],
        ['Risk of harm to self **by another**', 4],
        ['**Risk of harm to another person**', 5]),
    ] },
  { quiz: 'legal', k: 'summarise the four key documents by type', title: 'Four key documents compared',
    hook: 'HPCAA is law; the Council’s standards and code are enforced; NZNO’s ethics guide.',
    groups: [
      G('The four',
        ['**HPCAA 2003**: **legislation**; **Parliament**; **enforceable**', 0],
        ['**Standards of Competence**: what nurses must **be able to do**; needed for an **APC**', 1],
        ['**Code of Conduct**: how nurses **must behave**; NCNZ can **discipline**', 2],
        ['**NZNO Code of Ethics**: how to **act ethically**; a **guideline**', 3]),
    ] },
  { quiz: 'legal', k: 'summarise the three legal cases against nurses', title: 'Three cases against nurses',
    hook: 'Stole it, stole it, hid it: all three lost their practice.',
    groups: [
      G('Nurse P (2005)',
        ['Took **morphine** capsules for **his own use**; replaced them with **sucrose**', 0],
        ['**Convicted of theft**; **de-registered**', 0]),
      G('Nurse H (2006)',
        ['**Stole** vials of **morphine, pethidine and fentanyl**', 1],
        ['**Registration cancelled**', 2]),
      G('Nurse D (2013)',
        ['The **wrong medication**; **took two days to report**; the **patient died**', 3],
        ['**Guilty of professional misconduct**: **suspended**, **fined**', 4]),
    ] },
  { quiz: 'legal', k: 'what does medication legislation mean for the', title: 'What medicine law means for an RN',
    hook: 'No prescribing, valid scripts only, know the rules, no misuse, own your mistakes.',
    groups: [
      G('Five points',
        ['Nurses **cannot prescribe**', 0],
        ['Prescription medicines only with a **valid prescription**', 1],
        ['Know the **legislation** and your **organisation’s policies**', 2],
        ['**Misuse of that access** is **unsafe and illegal**', 3],
        ['**Always admit mistakes**; **ask for help**', 4]),
    ] },

  /* ── M7 · Drug development & marketing ── */
  { quiz: 'devmkt', k: 'give the cost timescale and attrition figures', title: 'Drug development: cost, time, attrition',
    hook: 'Millions of dollars, 10–20 years, 5 in 5000.',
    groups: [
      G('The figures',
        ['**Millions of dollars**', 0],
        ['**10–20 years**', 1],
        ['Only **5 in 5000** compounds reach **human testing**', 2]),
    ] },
  { quiz: 'devmkt', k: 'name the five key phases of the', title: 'The drug development pathway',
    hook: 'Discover → Preclinical → Clinical trials → Medsafe review → Post-market.',
    groups: [
      G('The five phases',
        ['**Discovery & Development**: **promising compounds**', 0],
        ['**Preclinical research**: **safety testing** before humans', 1],
        ['**Clinical Trials**: studies **involving people**', 2],
        ['**Medsafe Review**: **approve or reject**', 3],
        ['**Post-Market Monitoring**: **safety surveillance** after release', 4]),
    ] },
  { quiz: 'devmkt', k: 'which three bodies must a developer apply', title: 'Three bodies before a trial starts',
    hook: 'Medsafe, SCOTT, HDEC.',
    groups: [
      G('Each, and what it assesses',
        ['**Medsafe**: **preclinical studies**, **pharmacokinetics and pharmacodynamics**, **quality**', 0],
        ['**SCOTT**: the **science**, **safety** and **trial design**', 1],
        ['**HDEC**: **ethical compliance**', 2]),
      G('What developers submit',
        ['**Animal study data**, **prior human research**, **study plans**', 3]),
    ] },
  { quiz: 'devmkt', k: 'describe the four phases of clinical research', title: 'The four phases of clinical research',
    hook: 'A funnel: 70%, 33%, then 25–30% get through.',
    groups: [
      G('The four phases',
        ['**Phase 1**: **safety and dosage**; **20–100** people; ~**70%** progress', 0],
        ['**Phase 2**: **efficacy and side effects**; **several hundred**; ~**33%**', 1],
        ['**Phase 3**: **confirming safety**; **300–3000**; **25–30%**', 2],
        ['**Phase 4**: **long-term safety**; **several thousand**; years', 3],
        ['The phases act like a **funnel**', 4]),
    ] },
  { quiz: 'devmkt', k: 'what five things do developers determine when', title: 'Designing a clinical trial: five decisions',
    hook: 'Who, how many, how long, how fair, what dose, what data.',
    groups: [
      G('The five',
        ['**Who qualifies**: **inclusion and exclusion criteria**', 0],
        ['**Sample size** and **study duration**', 1],
        ['Ways to **reduce bias**: **control groups**', 2],
        ['**Dosage and administration**', 3],
        ['**Data collection and analysis**', 4]),
    ] },
  { quiz: 'devmkt', k: 'name the four key ethical issues in', title: 'Ethics in clinical trials',
    hook: 'Today’s patient vs tomorrow’s: consent, placebo, randomising, the vulnerable.',
    groups: [
      G('The central tension',
        ['**Care for current patients** vs **advance science** for **future patients**', 0]),
      G('The four issues',
        ['**Informed consent**', 1],
        ['**Use of placebos**', 2],
        ['**Use of randomisation**', 3],
        ['**Protection of vulnerable patients**', 4],
        ['Human research has a history of **serious abuses**', 5]),
    ] },
  { quiz: 'devmkt', k: 'what must informed consent for a clinical', title: 'Informed consent in a trial',
    hook: 'Voluntary, competent, informed; you can always leave.',
    groups: [
      G('What consent must be',
        ['**Voluntary, competent, and adequately informed**', 0],
        ['It can be **withdrawn at any time**', 5]),
      G('What they must understand',
        ['The **risks and potential benefits**', 1],
        ['**All study procedures**', 2],
        ['Participation is **voluntary**', 3],
        ['Research is **not** the same as **personalised treatment**', 4]),
    ] },
  { quiz: 'devmkt', k: 'when is placebo use ethically acceptable and', title: 'When a placebo is acceptable',
    hook: 'Only when nobody loses a proven treatment.',
    groups: [
      G('What a placebo is for',
        ['Given to **control** participants to show the **effect of a new drug**', 0]),
      G('Problematic',
        ['If recipients **risk harm** or **worsening**', 1]),
      G('Acceptable',
        ['When **no proven treatment exists**', 2],
        ['Or **necessary for methodology**, without **serious harm**', 3]),
    ] },
  { quiz: 'devmkt', k: 'what ethical issues does randomisation raise', title: 'The ethics of randomisation',
    hook: 'Fair only while nobody knows which is better.',
    groups: [
      G('Why it is used',
        ['Randomising to treatment or placebo increases **validity**', 0]),
      G('The ethical issues',
        ['It may **deny** the **currently best-known treatment**', 1],
        ['Needs **genuine professional justification** that neither is **known to be better**', 2]),
    ] },
  { quiz: 'devmkt', k: 'what issues arise in protecting vulnerable patients', title: 'Protecting vulnerable trial participants',
    hook: 'Too strict pushes trials offshore; too protective removes the choice.',
    groups: [
      G('The issues',
        ['Strict rules push trials to **low-protection countries**', 0],
        ['**Over-protection** can **conflict with autonomy**', 1],
        ['Trials may **reimburse participants**', 2],
        ['Higher concern in **cancer treatment trials**', 3]),
    ] },
  { quiz: 'devmkt', k: 'name the five types of medication advertising', title: 'Five types of medicine advertising',
    hook: 'Direct-to-consumer, disease awareness, reminder, professional, digital.',
    groups: [
      G('The five',
        ['**Direct-to-consumer**: **branded prescription medicines** to the **public**', 0],
        ['**Health-seeking** (**disease awareness**): about a **condition**', 1],
        ['**Reminder** ads: the **drug name only**', 2],
        ['**Professional/journal ads**: for **healthcare professionals**', 3],
        ['**Digital & social media**: **influencers**; stresses **benefits** over risks', 4]),
    ] },
  { quiz: 'devmkt', k: 'what is unusual about medication advertising in', title: 'What is unusual about NZ',
    hook: 'Only NZ and the USA allow it.',
    groups: [
      G('The answer',
        ['One of **only two developed countries** that allow ads **direct to the consumer**', 0],
        ['The other is the **USA**', 1]),
    ] },
  { quiz: 'devmkt', k: 'what does the therapeutic and health advertising', title: 'The advertising code: its rules',
    hook: 'True, proven, balanced, safe, genuine, approved.',
    groups: [
      G('The requirements',
        ['**Responsible, truthful**, **not misleading**', 0],
        ['Claims **substantiated** with **credible evidence**', 1],
        ['Must not **exaggerate the benefits**', 2],
        ['**Key safety information** included', 3],
        ['**Testimonials** must be **genuine**', 4],
        ['**Endorsements** can’t imply **guaranteed outcomes**', 5],
        ['**Unapproved medicines** can’t be advertised, **even to health professionals**', 6]),
    ] },
  { quiz: 'devmkt', k: 'how can a health professional accidentally breach', title: 'Accidental advertising, and the exemption',
    hook: 'Praise a brand out loud = advertising; generic advice = exempt.',
    groups: [
      G('How',
        ['Advertising includes **verbal advertising**', 0],
        ['**Recommending or praising** one **brand** over another', 0],
        ['Brand information must be **factual** and **balanced**', 1]),
      G('What is exempt',
        ['**Individualised advice**, using **generic names**', 2]),
    ] },

  /* ── M8 · Anaphylaxis (ASCIA plan) ── */
  { quiz: 'allergy', k: 'list the six steps of the ascia', title: 'The ASCIA anaphylaxis plan, six steps',
    hook: 'Flat, adrenaline, 111, family, more at 5 minutes, hospital for 4 hours.',
    groups: [
      G('In order',
        ['1 **Lay the person flat**: **do not** let them **stand or walk**', 0],
        ['2 **Give the adrenaline device**', 1],
        ['3 **Phone ambulance**: **111**', 2],
        ['4 **Phone family** or an emergency contact', 3],
        ['5 **Further adrenaline** if **no response after 5 minutes**', 4],
        ['6 To **hospital** for **at least 4 hours** of observation', 5]),
    ] },
  { quiz: 'allergy', k: 'what are the positioning rules in step', title: 'Anaphylaxis positioning, and exceptions',
    hook: 'Flat, unless unconscious, pregnant, struggling to breathe, or a small child.',
    groups: [
      G('The rule',
        ['Lay them **flat**: **do not** allow them to **stand or walk**', 0]),
      G('The three exceptions',
        ['**Unconscious or pregnant**: the **recovery position** (pregnant: **left side**)', 1],
        ['If **breathing is difficult**: **sit with legs outstretched**', 2],
        ['**Hold young children flat**, not upright', 3]),
    ] },
  { quiz: 'allergy', k: 'name the seven signs of anaphylaxis on', title: 'Seven signs of anaphylaxis',
    hook: 'Breathing, throat, voice, wheeze, collapse, a floppy child, the tongue.',
    groups: [
      G('The seven signs',
        ['**Difficult or noisy breathing**', 0],
        ['**Swelling or tightness in the throat**', 1],
        ['**Difficulty talking** or a **hoarse voice**', 2],
        ['**Wheeze** or **persistent cough**', 3],
        ['**Persistent dizziness** or **collapse**', 4],
        ['**Pale and floppy** (young children)', 5],
        ['**Swelling of the tongue**', 6]),
    ] },
  { quiz: 'allergy', k: 'name the signs and the actions for', title: 'A mild to moderate allergic reaction',
    hook: 'Stay, find the adrenaline, antihistamine, call the family.',
    groups: [
      G('Signs',
        ['**Swelling of lips, face and eyes**; **hives or welts**; **tingling mouth**', 0],
        ['**Abdominal pain and vomiting**: **anaphylaxis** signs for **insect allergy**', 1]),
      G('Actions',
        ['**Stay with the person**; **call for help**', 2],
        ['**Locate the adrenaline** device', 3],
        ['Give an **antihistamine**; phone the **family**', 4],
        ['Insect: **flick out the sting**; tick: **freeze the tick**', 5]),
    ] },
  { quiz: 'allergy', k: 'a person with known asthma and food', title: 'Asthma + allergy: adrenaline first',
    hook: 'If in doubt, give the adrenaline.',
    groups: [
      G('What is given first',
        ['The **adrenaline device first**, then the **asthma reliever**', 0],
        ['Known asthma + allergy, exposed, **sudden breathing difficulty**', 1]),
      G('Why it matters',
        ['Anaphylaxis can occur **without skin symptoms**', 2],
        ['**If in doubt, give the adrenaline device**', 3]),
    ] },
  { quiz: 'allergy', k: 'when should cpr be commenced and what', title: 'CPR, and an accidental injection',
    hook: 'Unresponsive = CPR. A wasted device = use another.',
    groups: [
      G('CPR',
        ['**Commence CPR** if **unresponsive** or **not breathing normally**', 0]),
      G('A device accidentally activated',
        ['**Use another adrenaline device** if available', 1],
        ['Accidentally injected: contact the **poisons information centre**', 2]),
    ] },
];
