/* Short versions of the topic rows' written answers, Modules 1–5 (concepts, calculations, pharmacokinetics,
   pharmacodynamics, administration). The tool wrote every one of those questions and model answers (ported from
   intro-pharm); each is cut here to one fact a line, grouped under the question's parts, with a memory hook.
   Gated by shorts.mjs (see content/shorts.js). */
const G = (q, ...facts) => ({ q, facts: facts.map(([t, of, fix]) => (fix ? { t, of, fix } : { t, of })) });

export const TOPICS_A = [
  /* ── M1 · What pharmacology is ── */
  { quiz: 'concepts1', k: 'define pharmacology and explain why knowledge of', title: 'Pharmacology, and why it matters to an RN',
    hook: 'Give it, own it, teach it, check it, and one day prescribe it.',
    groups: [
      G('Define pharmacology',
        ['The **study of drugs**: their **sources**, **nature**, **actions**, **effects**, **uses**', 0]),
      G('Why it matters (any four)',
        ['Nurses **administer medication** as a **daily** routine', 1],
        ['**Legally and ethically responsible** for giving them **safely**', 2],
        ['Nurses **provide education** to **patients and whānau**', 3],
        ['Nurses **evaluate the outcome**, including **adverse effects**', 4],
        ['With further training, nurses may **prescribe and dispense**', 5]),
    ] },
  { quiz: 'concepts1', k: 'define medication name the six things a', title: 'What a medication is, and six uses',
    hook: 'Please Don’t Rush To Cure All: Prevent, Diagnose, Relieve, Treat, Cure, Affect.',
    groups: [
      G('Define it',
        ['Any substance used to **prevent, diagnose, relieve, treat, or cure** disease', 0],
        ['… or to **affect the structure or function** of the body', 0]),
      G('The six uses, each with its example',
        ['**Prevent**: **Hepatitis B immunisation**', 1],
        ['**Diagnose**: **contrast media** on X-ray or CT', 2],
        ['**Relieve** symptoms, not the cause: **paracetamol** for pain', 3],
        ['**Treat**, not cure: **omeprazole** to heal an ulcer', 4],
        ['**Cure**: **antifungal cream** for **ringworm**', 5],
        ['**Affect structure or function**: the **oral contraceptive pill**', 6]),
    ] },
  { quiz: 'concepts1', k: 'name the four branches of pharmacology covered', title: 'The four branches of pharmacology',
    hook: 'Kinetics: body → drug. Dynamics: drug → body. Therapeutics: to the patient. Toxicology: harm.',
    groups: [
      G('The four branches',
        ['**Pharmacokinetics**: “**what the body does to the drug**”', 0],
        ['**Pharmacodynamics**: “**what the drug does to the body**”, and how', 1],
        ['**Pharmacotherapeutics**: applying medications to an **individual patient**', 2],
        ['**Toxicology**: the **harmful effects** of chemicals, medications included', 3]),
    ] },
  { quiz: 'concepts1', k: 'three things a nurse must know before', title: 'Three things to know before giving a medicine',
    hook: 'How to give it, why, and what could go wrong.',
    groups: [
      G('The three things',
        ['How to **safely administer** it', 0],
        ['Its **intended effect** (**purpose**)', 1],
        ['Possible **adverse effects**, including **allergies**', 2],
        ['Be **well informed** about each medicine **before administering** it', 3]),
    ] },
  { quiz: 'concepts1', k: 'explain the difference between a contraindication and', title: 'Contraindication vs precaution',
    hook: 'Contraindication = NO. Precaution = yes, but CAREFULLY.',
    groups: [
      G('Contraindication',
        ['The medication should **not be used**: it **may be harmful**', 0]),
      G('Precaution',
        ['Use with **special care**: a **heightened risk of adverse effects**', 1],
        ['It **may still be used**, with **careful monitoring** or **dose adjustment**', 2]),
    ] },
  { quiz: 'concepts1', k: 'what is a medication drug interaction name', title: 'Medication interactions: four categories',
    hook: 'Drugs, food, CAM, conditions.',
    groups: [
      G('Definition',
        ['The medication’s **effect** is **altered by another substance or condition**', 0]),
      G('The four categories',
        ['**Other medications**', 1],
        ['**Foods**', 2],
        ['**Complementary and alternative medicines**', 3],
        ['**Medical conditions**', 4]),
    ] },
  { quiz: 'concepts1', k: 'distinguish the roles of pharmac and medsafe', title: 'PHARMAC vs Medsafe',
    hook: 'PHARMAC: will we PAY for it? Medsafe: is it SAFE?',
    groups: [
      G('PHARMAC',
        ['Decides which medicines are **funded** (**subsidised**)', 0],
        ['… within a **fixed budget**', 0]),
      G('Medsafe',
        ['The **Medicines and Medical Devices Safety Authority**', 1],
        ['It **regulates**: **safe** and **high-quality**', 1]),
    ] },
  { quiz: 'concepts1', k: 'all medications are known by at least', title: 'The three names of a medication',
    hook: 'Chemical (for chemists), generic (official), brand (for sale).',
    groups: [
      G('Chemical name',
        ['Describes the **atomic and molecular structure**; used by **chemists**', 0],
        ['Paracetamol: **4-hydroxyacetanilide**', 0]),
      G('Generic name',
        ['The **official name**, approved by the **regulating authority**', 1],
        ['For paracetamol, the generic name is **paracetamol**', 1]),
      G('Brand (proprietary) name',
        ['**Selected and copyrighted** by the **company** that markets it', 2],
        ['Paracetamol: **Panadol**, **Pamol**', 2]),
    ] },
  { quiz: 'concepts1', k: 'why are prescribers in aotearoa nz encouraged', title: 'Prescribing generically, and two exceptions',
    hook: 'Fewer errors, lower cost; except modified-release and non-bioequivalent brands.',
    groups: [
      G('Why prescribe generically',
        ['**Reduces the risk of error**: many **brand names** for one medicine', 0],
        ['**More cost-effective**: **subsidised medication brands** are dispensed', 1]),
      G('The two exceptions',
        ['A **special modified-release form**', 2],
        ['Brands that **do not show bioequivalence**: e.g. **epilepsy**', 3]),
    ] },
  { quiz: 'concepts1', k: 'define bioequivalence and explain its role in', title: 'Bioequivalence and its role',
    hook: 'Same ingredient, same dose, same rate, same effect.',
    groups: [
      G('Definition',
        ['Two medicines, **same active ingredient**, at the **same dose**', 0],
        ['Reach the bloodstream at a **similar rate and extent**', 1],
        ['**And** lead to **similar effects**', 2]),
      G('Its role in drug development',
        ['A **new branded version** must **demonstrate bioequivalence** before sale', 3],
        ['Some brands are **more affordable** (for **PHARMAC** too)', 4]),
    ] },
  { quiz: 'concepts1', k: 'name three generic name suffixes taught in', title: 'Three generic-name suffixes',
    hook: '-olol slows the heart, -statin lowers cholesterol, -cillin kills bugs.',
    groups: [
      G('Suffix → class',
        ['**-olol**: **beta blockers**, e.g. **atenolol**', 0],
        ['**-statin**: **cholesterol-lowering**, e.g. **atorvastatin**', 1],
        ['**-cillin**: **penicillin antibiotics**, e.g. **amoxicillin**', 2]),
    ] },

  /* ── M1 · Drug names, sources & schedules ── */
  { quiz: 'concepts2', k: 'name the three classification systems this course', title: 'Three ways to classify a medicine',
    hook: 'What it is FOR, how it WORKS, what the LAW says.',
    groups: [
      G('The three systems, each with an example',
        ['**Clinical use**: what it is **prescribed for**, e.g. **analgesics**', 0],
        ['**Mechanism of action**: **how it produces its effect**, e.g. **proton pump inhibitors**', 1],
        ['**Legal**: by **NZ Medicines law**, e.g. **prescription**, **general sale**', 2]),
    ] },
  { quiz: 'concepts2', k: 'aspirin is used as the lecture s', title: 'Aspirin: four clinical-use classes',
    hook: 'Pain, fever, inflammation, clots.',
    groups: [
      G('The four classes',
        ['**Analgesic**: pain relief', 0],
        ['**Antipyretic**: reduces fever', 1],
        ['**Anti-inflammatory**', 2],
        ['**Antithrombotic**: prevents clotting', 3]),
    ] },
  { quiz: 'concepts2', k: 'list the four legal classifications of medicines', title: 'The four legal classes, with examples',
    hook: 'Prescription → Restricted → Pharmacy-only → General sale (the last three = OTC).',
    groups: [
      G('The four classes',
        ['**Prescription**: needs a **prescription** or **standing order**; e.g. **amoxicillin**', 0],
        ['**Restricted** (**pharmacist-only**): the pharmacist must **explain it**; e.g. **clotrimazole cream**', 1],
        ['**Pharmacy-only**: a **pharmacy** or **hospital**; e.g. **oxymetazoline** nasal spray', 2],
        ['**General sales**: **any retail outlet**; e.g. **paracetamol**, **ibuprofen**', 3],
        ['The last three are “**over the counter**” (**OTC**)', 4]),
    ] },
  { quiz: 'concepts2', k: 'name the two free new zealand websites', title: 'Two free NZ medicine information sites',
    hook: 'Medsafe for data sheets; the NZF for dosing and interactions.',
    groups: [
      G('Medsafe',
        ['**Data Sheets** for **health professionals**', 0],
        ['**Consumer Medicine Information** sheets for consumers', 0]),
      G('The New Zealand Formulary (NZF)',
        ['An **adult** section and a **child** section (0–18)', 1],
        ['**Normal dosing**; whether **PHARMAC-subsidised**; an **interactions checker**', 2]),
    ] },
  { quiz: 'concepts2', k: 'the deck lists four kinds of source', title: 'Four sources to use with caution',
    hook: '.com sites, news, AI, social media.',
    groups: [
      G('The four, and why',
        ['**.com websites**: often **American terminology**', 0],
        ['**News releases**: **clickbait**; is the author **qualified**?', 1],
        ['**Artificial intelligence**: “**uses patterns rather than science**”', 2],
        ['**Social media**', 3]),
    ] },
  { quiz: 'concepts2', k: 'what three things does the route of', title: 'What the route of administration affects',
    hook: 'How fast, how strong, and where.',
    groups: [
      G('The three things',
        ['The **rate of onset** of action', 0],
        ['The **magnitude** of the **response**', 1],
        ['For some routes, the **location of the response**', 2]),
    ] },
  { quiz: 'concepts2', k: 'name the five major groups of administration', title: 'Five route groups; local vs systemic',
    hook: 'Oral, parenteral, rectal, inhalation, topical.',
    groups: [
      G('The five route groups',
        ['**Oral** (**enteral**: the GI tract)', 0],
        ['**Parenteral** (**not through the GI tract**)', 1],
        ['**Rectal**', 2],
        ['**Inhalation**', 3],
        ['**Topical**', 4]),
      G('Local vs systemic',
        ['**Local**: at the **immediate site of administration**', 5],
        ['**Systemic**: **absorbed** into the **circulation**, **distributed** to where it acts', 6]),
    ] },
  { quiz: 'concepts2', k: 'give the advantages and disadvantages of the', title: 'The IV route: pros and cons',
    hook: 'Fast and big, but no taking it back.',
    groups: [
      G('Advantages',
        ['**Rapid effects**: onset is **immediate**', 0],
        ['A **large volume** can be given', 1],
        ['**Reduced risk of tissue irritation**: **immediately diluted** in the blood', 2]),
      G('Disadvantages',
        ['**Dangerous**: **not easy to retrieve, stop or slow**', 3],
        ['May need **hospitalisation**; **higher cost**', 4],
        ['**Risk of infection** and **adverse effects**', 5]),
    ] },
  { quiz: 'concepts2', k: 'compare the intramuscular and subcutaneous routes absorption', title: 'IM vs subcutaneous',
    hook: 'IM: into muscle, faster. SC: under the skin into fat, slow and steady.',
    groups: [
      G('Intramuscular (IM)',
        ['Injected **into muscle**; absorbed via its **blood vessels**', 0],
        ['**Faster than oral**', 0],
        ['Pro: **slower absorption** possible, e.g. **Depo-Provera**; an **EpiPen**', 1],
        ['Con: **pain and nerve damage**; **variable absorption**', 2]),
      G('Subcutaneous (SC)',
        ['**Beneath the skin**, into **connective tissue or fat**', 3],
        ['Faster than oral but **less reliable**', 3],
        ['Pro: a **sustained effect**, e.g. **insulin**; can **self-medicate**', 4],
        ['Con: **non-irritating drugs** only; **small volumes**', 5]),
    ] },
  { quiz: 'concepts2', k: 'why can the lungs absorb medication so', title: 'Why the lungs absorb medicines well',
    hook: 'A huge surface, lots of capillaries, and it must be a mist.',
    groups: [
      G('Why',
        ['A **large surface area**', 0],
        ['**Many capillaries** next to the **alveolar membranes**', 1]),
      G('The physical form',
        ['**Gases** or **fine mists** (**aerosols**): **inhalers**, **nebulisers**', 2]),
    ] },
  { quiz: 'concepts2', k: 'explain dissolution and rank the oral formulations', title: 'Dissolution, fastest to slowest',
    hook: 'Liquid first, coated last: elixir, suspension, powder, capsule, tablet, coated.',
    groups: [
      G('Dissolution',
        ['The drug **goes into a solution**', 0],
        ['Solids must **disintegrate**, then **dissolve**', 0],
        ['**Faster dissolution = faster absorption**; **liquid medications** are fastest', 1]),
      G('Fastest to slowest',
        ['**Elixirs and syrups** → **suspensions** → **powders**', 2],
        ['→ **capsules** → **tablets** → **coated tablets** (slowest)', 2]),
    ] },
  { quiz: 'concepts2', k: 'give the four reasons an enteric coating', title: 'Four reasons for an enteric coating',
    hook: 'Protect the drug, keep it strong, spare the stomach, slow it down.',
    groups: [
      G('The four reasons',
        ['Prevents **decomposition** of sensitive drugs by **gastric secretions**', 0],
        ['Prevents **dilution** of the drug', 1],
        ['Prevents **nausea and vomiting**', 2],
        ['Provides **delayed action**', 3]),
      G('How',
        ['It **prevents dissolution in the stomach**; it **dissolves in the intestine**', 4]),
    ] },
  { quiz: 'concepts2', k: 'what are excipients and name four kinds', title: 'Excipients: four kinds in a tablet',
    hook: 'Binders stick, disintegrators break, lubricants slide, fillers bulk.',
    groups: [
      G('What they are',
        ['**Inert chemicals** in a formulation', 0],
        ['The active medicine may be a **very small fraction** of the tablet', 1]),
      G('Four kinds in a tablet',
        ['**Binders**: stick the powder together', 2],
        ['**Disintegrators**: assist **dissolution**', 2],
        ['**Lubricants**: make **manufacturing** easier', 2],
        ['**Fillers**: a convenient **tablet size**', 2]),
    ] },
  { quiz: 'concepts2', k: 'distinguish a hard capsule from a soft', title: 'Hard vs soft capsules',
    hook: 'Hard = powder inside, can open. Soft = liquid inside, fast.',
    groups: [
      G('Both',
        ['A **gelatin shell** around the medication', 0]),
      G('Hard capsule',
        ['The drug as a **solid** (**powder**, **granule**)', 1],
        ['**Can be opened** and emptied if needed', 1]),
      G('Soft capsule (softgel)',
        ['The drug as a **liquid solution**', 2],
        ['Useful when **fast action** is needed', 2]),
    ] },
  { quiz: 'concepts2', k: 'give the meaning of prn mane nocte', title: 'Timing abbreviations',
    hook: 'Say them aloud: prn, mane, nocte, od, bd, tds, qid, q4h, ac, pc, stat.',
    groups: [
      G('What each means',
        ['**prn** = **if necessary**; **mane** = **in the morning**; **nocte** = **at night**', 0],
        ['**od** = **once daily**; **bd** = **twice a day**', 1],
        ['**tds** = **three times a day**; **qid** = **four times a day**', [1, 2]],
        ['**q4h** = **every four hours**', 2],
        ['**ac** = **before meals**; **pc** = **after meals**; **stat** = **immediately**', 3]),
    ] },
  { quiz: 'concepts2', k: 'give the meaning of the route abbreviations', title: 'Route abbreviations, NKA and NKDA',
    hook: 'PO mouth, SL tongue, SC skin, IM muscle, IV vein, PR rectum.',
    groups: [
      G('The routes',
        ['**PO** = **orally**; **SL** = **sublingual** (under the tongue)', 0],
        ['**SC** = **subcutaneous**', 0],
        ['**IM** = **intramuscular**; **IV** = **intravenous**; **PR** = **rectally**', 1]),
      G('Allergies',
        ['**NKA** = **no known allergies**', 2],
        ['**NKDA** = **no known drug allergies**', 2]),
    ] },

  /* ── M2 · Medication calculations ── */
  { quiz: 'calcs', k: 'state the main medication calculation formula say', title: 'The main medication formula',
    hook: 'Want ÷ Got × Volume.',
    groups: [
      G('The formula',
        ['(**What you want** ÷ **what you have got**) × **volume**', 0]),
      G('Each term',
        ['Want = **prescribed**, **charted**, **ordered**', 1],
        ['Got = **in stock**, **on hand**', 2],
        ['Volume = what the stock **strength comes in** (1 tablet, 5 mL)', 3]),
      G('What it works for',
        ['**Oral tablets and capsules**; **oral liquids**', 4],
        ['**Injected medicines**: **SC**, **IM**, **direct IV**', 4],
        ['Writing the volume **over 1** is also accurate', 5]),
    ] },
  { quiz: 'calcs', k: 'list the five steps of the medication', title: 'The Medication Calculation Checklist',
    hook: 'Quiet, units, formula, sanity check, double check.',
    groups: [
      G('The five steps',
        ['1 **No distractions**', 0],
        ['2 Are the **units the same**?', 1],
        ['3 **Formula**', 2],
        ['4 Does the answer **look correct**?', 3],
        ['5 **Double check**', 4]),
    ] },
  { quiz: 'calcs', k: 'a patient has been prescribed digoxin 0', title: 'Digoxin: mg to mcg, then tablets',
    hook: 'Units first: 0.25 mg = 250 mcg.',
    groups: [
      G('Working',
        ['Convert first: **0.25 mg × 1000 = 250 mcg**', 0],
        ['**250 mcg ÷ 62.5 mcg × 1 tablet**', 1],
        ['= **4 tablets**', 2]),
    ] },
  { quiz: 'calcs', k: 'a child is prescribed paracetamol 250 mg', title: 'Paracetamol suspension volume',
    hook: 'Want 250, got 200 in 5 mL.',
    groups: [
      G('Working',
        ['Units match (**mg and mg**): no conversion', 0],
        ['**250 mg ÷ 200 mg × 5 mL**', 1],
        ['= **6.25 mL**', 2]),
    ] },
  { quiz: 'calcs', k: 'te atawhai is prescribed furosemide 0 1', title: 'Furosemide: g to mg, then volume',
    hook: 'Units first: 0.1 g = 100 mg.',
    groups: [
      G('Working',
        ['Convert: **0.1 g × 1000 = 100 mg**', 0],
        ['**100 mg ÷ 20 mg × 2 mL**', 1],
        ['= **10 mL**', 2]),
    ] },
  { quiz: 'calcs', k: 'state the body weight dosing formula and', title: 'Body-weight dosing: Wei’s ampicillin',
    hook: 'Dose per kg × kg.',
    groups: [
      G('The formula',
        ['**Dose per kg** × **body weight** = the dose', 0],
        ['Read “/” as “**per**”: 10 mg/kg = 10 mg **per kilogram**', 1]),
      G('Wei',
        ['**10 mg/kg × 30 kg = 300 mg**', 2]),
    ] },
  { quiz: 'calcs', k: 'naveen weighs 40 kg and is prescribed', title: 'Naveen’s prednisone: three steps',
    hook: 'Per day, then per dose, then tablets.',
    groups: [
      G('The three steps',
        ['1 **Daily dose**: **40 kg × 1 mg/kg/day = 40 mg**', 0],
        ['2 **Single dose**: **40 mg ÷ 2 doses = 20 mg**', 1],
        ['3 Tablets: **20 mg ÷ 5 mg × 1 tablet = 4 tablets**', 2]),
    ] },
  { quiz: 'calcs', k: 'state the iv drip rate formula and', title: 'Drip rate: formula, factor vs rate',
    hook: 'The factor = how BIG a drop is. The rate = how FAST they fall.',
    groups: [
      G('The formula',
        ['**Volume** (mL) × **drop factor** ÷ **time (hours) × 60**', 0]),
      G('Drop factor vs drip rate',
        ['**Drop factor**: **drops/mL**, how **big** the drops are', 1],
        ['Fixed by the **giving set**; you are always given it', 1],
        ['**Drip rate**: **drops/min**, how **fast** they are delivered', 2],
        ['The nurse **calculates** it; it is **per minute**', [2, 3]]),
    ] },
  { quiz: 'calcs', k: 'tania is prescribed sodium chloride 0 9', title: 'Tania’s drip rate',
    hook: 'Top, bottom, divide, round.',
    groups: [
      G('Working',
        ['Top: **1000 mL × 60 drops/mL = 60,000 drops**', 0],
        ['Bottom: **12 hr × 60 = 720 minutes**', 1],
        ['**60,000 ÷ 720 = 83.33**', 2],
        ['Round **down** → **83 drops per minute**', 3]),
    ] },
  { quiz: 'calcs', k: 'mr willis is prescribed sodium chloride 0', title: 'Mr Willis’s drip rate',
    hook: 'Litres to mL first.',
    groups: [
      G('Working',
        ['Convert: **1 L = 1000 mL**', 0],
        ['Top **20,000 drops**; bottom **300 minutes**', 1],
        ['**20,000 ÷ 300 = 66.66**', 2],
        ['Round **up** → **67 drops per minute**', 3]),
    ] },
  { quiz: 'calcs', k: 'explain the order of operations trap in the drip', title: 'The drip-rate order-of-operations trap',
    hook: 'Multiply the top, multiply the bottom, THEN divide.',
    groups: [
      G('The trap',
        ['Do the top and bottom **multiplications first**, **before dividing**', 0],
        ['Typing **1000 × 60 ÷ 12 × 60** gives **300,000 drops/min**', 1],
        ['… because it did **60 ÷ 12 first**', 2]),
      G('The right order',
        ['**60,000** on top; **720** on the bottom', 3],
        ['**60,000 ÷ 720 = 83.33** drops/min', 3]),
    ] },
  { quiz: 'calcs', k: 'what does the ratio 1 1000 mean', title: 'Adrenaline 1:1000',
    hook: '1 g in 1000 mL = 1 mg in 1 mL.',
    groups: [
      G('What it means',
        ['**1:1000** = **1 mg in 1 mL**', 0]),
      G('How it is derived',
        ['Literally **1 g in 1000 mL**', 1],
        ['**1 g × 1000 = 1000 mg**: 1000 mg:1000 mL', 2],
        ['**Dividing both sides by 1000** → **1 mg:1 mL**', 3],
        ['Use the **mg/mL** on the packaging for calculations', 4]),
    ] },
  { quiz: 'calcs', k: 'mrs dell needs adrenaline 0 7 mg', title: 'Mrs Dell’s adrenaline',
    hook: '1:1000 is 1 mg/mL, so mg = mL.',
    groups: [
      G('Working',
        ['**1:1000** = **1 mg/1 mL**; use the standard formula', 0],
        ['**0.7 mg ÷ 1 mg × 1 mL**', 1],
        ['= **0.7 mL**', 2]),
    ] },
  { quiz: 'calcs', k: 'mr singh is prescribed 4 mg of', title: 'Mr Singh’s diluted morphine',
    hook: 'Add first: 1 + 9 = 10 mL.',
    groups: [
      G('Working',
        ['Do the **addition first**: ampoule + water = **10 mL total**', 0],
        ['The syringe holds **5 mg in 10 mL**', 1],
        ['**4 mg ÷ 5 mg × 10 mL = 8 mL**', 2]),
    ] },
  { quiz: 'calcs', k: 'explain the order of operations trap in a', title: 'The dilution order-of-operations trap',
    hook: 'Add the volumes BEFORE the formula.',
    groups: [
      G('The trap',
        ['Do the **addition first**, before the formula', 0],
        ['**3 ÷ 10 × 9 + 1** gives **3.7 mL**: an **overdose**', 1],
        ['… the calculator **adds the 1 last**', 1]),
      G('The right order',
        ['**9 mL + 1 mL = 10 mL**', 2],
        ['**3 mg ÷ 10 mg × 10 mL = 3 mL**', 2]),
    ] },
  { quiz: 'calcs', k: '5 year old sophie is charted amoxicillin', title: 'Sophie’s amoxicillin, and the trap',
    hook: 'The volume is the 5 mL the strength comes in, never the bottle.',
    groups: [
      G('Working',
        ['Want **400 mg**; got **250 mg**; volume **5 mL**, **not 150 mL**', 0],
        ['**400 mg ÷ 250 mg × 5 mL = 8 mL**', 1]),
      G('The trap',
        ['Using the **whole bottle** gives **240 mL**', 2],
        ['The checklist should stop it: a **very unusual dose**', 2],
        ['The whole bottle works only with an **extra step**; it **risks error**', 3]),
    ] },
  { quiz: 'calcs', k: 'state the two rounding rules for this', title: 'The two rounding rules',
    hook: 'Never round a dose; always round a drip.',
    groups: [
      G('The two rules',
        ['**Do not round** medication **volumes** or **tablet numbers**', 0],
        ['**Do round IV drip rates**: you count **whole drops**', 1]),
      G('How to round a drip rate',
        ['**.4 or lower** rounds **down**; **.5 or higher** rounds **up**', 2],
        ['e.g. **66.666** drops → **67 drops/min**', 2]),
    ] },
  { quiz: 'calcs', k: 'what is a red herring in a', title: 'Red herrings in calculations',
    hook: 'Not every number in the question belongs in the formula.',
    groups: [
      G('What it is',
        ['A **name or number** that **does not relate** to your formula', 0]),
      G('The deck’s two examples',
        ['The IV fluid’s **concentration** (**Dextrose 5%**) when finding a **drip rate**', 1],
        ['The **frequency** (**tds**) when finding a **single dose**', 2]),
    ] },

  /* ── M3 · Pharmacokinetics (1) ── */
  { quiz: 'pk1', k: 'define pharmacokinetics and name its four processes', title: 'Pharmacokinetics: the four processes',
    hook: 'In, around, changed, out: ADME.',
    groups: [
      G('Definition',
        ['“**What the body does to the drug**”', 0],
        ['The **passage of a drug through the body**', 0]),
      G('The four processes',
        ['**Absorption**: the **entry** of a drug **into the bloodstream**', 1],
        ['**Distribution**: between the **blood and body tissues**', 2],
        ['**Metabolism**: **modification**, usually by the **liver**', 3],
        ['**Excretion**: **removal** from the body', 4]),
    ] },
  { quiz: 'pk1', k: 'define absorption which route does not require', title: 'Absorption, and the route that skips it',
    hook: 'IV goes straight in: nothing to absorb.',
    groups: [
      G('Definition',
        ['**Unchanged drug** reaches the **bloodstream**', 0],
        ['… after **administration and dissolution**', 0]),
      G('The route that does not need it',
        ['Every route **except the intravenous**', 1],
        ['**IV** medications **enter the bloodstream directly**', 2]),
    ] },
  { quiz: 'pk1', k: 'name the seven factors affecting absorption listed', title: 'Seven factors affecting absorption',
    hook: 'Route, blood flow, membrane, formulation, solubility, gut, pH.',
    groups: [
      G('The seven factors',
        ['**Route** of administration', 0],
        ['**Blood flow** at the site', 1],
        ['**Nature of the membrane**', 2],
        ['**Medication formulation**', 3],
        ['**Solubility** of the drug', 4],
        ['**GI tract status**', 5],
        ['**pH of the small intestine**', 6]),
    ] },
  { quiz: 'pk1', k: 'explain how the nature of the membrane', title: 'How the membrane affects absorption',
    hook: 'Bigger and thinner = faster.',
    groups: [
      G('Surface area',
        ['**Greater surface area = greater absorption**', 0],
        ['e.g. the **small intestine** (**villi**) vs the **oral mucosa**', 0]),
      G('Thickness',
        ['A **thinner** membrane = **faster** absorption', 1],
        ['e.g. the **single layer** of the small intestine’s **epithelium**', 1],
        ['**Multi-layered**, e.g. the **palms**: **slower**', 2]),
    ] },
  { quiz: 'pk1', k: 'why are lipid soluble drugs absorbed more', title: 'Why lipid-soluble drugs absorb faster',
    hook: 'Membranes are fat, so fat-soluble drugs slip through.',
    groups: [
      G('Why',
        ['**Solubility**: being **dissolved into a solution**', 0],
        ['Cell membranes are a **lipid bilayer**', 1],
        ['So **lipid-soluble** drugs are **rapidly absorbed**; **water-soluble** poorly', 2]),
    ] },
  { quiz: 'pk1', k: 'describe how blood flow affects absorption and', title: 'Blood flow and absorption',
    hook: 'More blood, faster in. Shock slows an IM injection.',
    groups: [
      G('How',
        ['Absorption **depends on the blood flow** at the site', 0],
        ['**High blood supply** → faster, e.g. **sublingual**', 1],
        ['**Low blood supply** → slower, e.g. **topical**', 2]),
      G('A disease example',
        ['**Poor peripheral circulation** in **shock** slows **intramuscular injections**', 3]),
    ] },
  { quiz: 'pk1', k: 'give two examples of food affecting drug', title: 'Food affecting absorption: two examples',
    hook: 'Milk with tetracycline; tea with iron.',
    groups: [
      G('Two examples',
        ['**Dairy** binds **tetracyclines** and can **prevent absorption**', 0],
        ['**Tannins** in **tea and coffee** bind **iron**', 1]),
    ] },
  { quiz: 'pk1', k: 'define bioavailability what is it for an', title: 'Bioavailability: IV and oral',
    hook: 'IV 100%; by mouth, what gets absorbed AND survives the liver.',
    groups: [
      G('Definition',
        ['How much drug **actually reaches the bloodstream**', 0]),
      G('IV',
        ['**Intravenous** medications: **bioavailability = 100%**', 1]),
      G('Oral: two things decide it',
        ['How much is **absorbed in the GI tract**', 2],
        ['How much **escapes** being **broken down by the liver**', 3]),
    ] },
  { quiz: 'pk1', k: 'explain the hepatic first pass effect and', title: 'First-pass effect: the 100 mg example',
    hook: '100 in, 20 lost in the gut, 60 lost in the liver: 20% arrives.',
    groups: [
      G('What it is',
        ['Taken **orally**: absorbed from the gut, then a **first pass through the liver**', 0],
        ['The liver **acts like a filter**: only **a portion** arrives unchanged', 1]),
      G('The 100 mg example',
        ['**100 mg** tablet: **20 mg is not absorbed**; **80 mg reaches the liver**', 2],
        ['The liver **breaks down 60 mg**: only **20 mg** gets through', 3],
        ['A **bioavailability of 20%**', 4]),
    ] },
  { quiz: 'pk1', k: 'explain plasma protein binding and why it', title: 'Plasma protein binding and competition',
    hook: 'Bound drug waits; free drug works.',
    groups: [
      G('Binding',
        ['Many drugs **bind reversibly** to **plasma proteins**, mainly **albumin**', 0],
        ['Only **free** (**unbound**) drug reaches the **tissues** to act', 1]),
      G('Why it matters',
        ['Some are **highly protein-bound**: **warfarin**, **99%**', 2],
        ['**Binding is dynamic**: freed drug moves to **replace what is lost**', 3],
        ['Two drugs can **compete for the same binding site**', 4],
        ['… which can **increase the amount of free drug**', 4]),
    ] },
  { quiz: 'pk1', k: 'compare the blood brain barrier and the', title: 'Blood–brain barrier vs placental barrier',
    hook: 'The brain is picky; the placenta lets almost anything through.',
    groups: [
      G('Blood–brain barrier',
        ['**Limits entry** into the brain; lets **oxygen and glucose** through', 0],
        ['Only **small, lipid-soluble** drugs pass', 1],
        ['**Tightly joined** capillary cells; a **thick basement membrane**', 1],
        ['Can be **disrupted in illness**, e.g. **meningitis**', 2]),
      G('Placental barrier',
        ['Separates **maternal and foetal blood**', 3],
        ['**Non-selective**: it allows **many different drugs** to cross', 3],
        ['**Lipid-soluble drugs cross** easily', 4]),
    ] },
  { quiz: 'pk1', k: 'name three tissues where drugs get concentrated', title: 'Where drugs concentrate',
    hook: 'Bone, fat, thyroid.',
    groups: [
      G('Three tissues, with examples',
        ['**Bone**: **tetracycline**, which can **discolour children’s teeth**', 0],
        ['**Adipose** (fat): **lipid-soluble** drugs, e.g. **diazepam**', 1],
        ['**Thyroid gland**: medicines containing **iodine**', 2]),
    ] },

  /* ── M3 · Pharmacokinetics (2) ── */
  { quiz: 'pk2', k: 'define drug metabolism name the main organ', title: 'Drug metabolism: organs and metabolites',
    hook: 'The liver makes drugs weaker, wetter and safer, mostly.',
    groups: [
      G('Definition',
        ['**Biological transformation** into an **inactive and water-soluble** compound', 0],
        ['Carried out by **enzymes**', 0]),
      G('The organs',
        ['The main organ: the **liver**', 1],
        ['Also the **kidneys**, **lungs**, **intestinal mucosa**', 1]),
      G('A metabolite is usually',
        ['**More water-soluble**, **less active**, **less toxic**', 2],
        ['Exceptions: some drugs are **activated** by the liver; a few turn **toxic**', 3]),
    ] },
  { quiz: 'pk2', k: 'name the five sources of inter individual', title: 'Why metabolism varies between people',
    hook: 'Genes, environment, disease, age & gender, hormones.',
    groups: [
      G('The five sources',
        ['**Genetics**', 0],
        ['**Environmental factors**', 1],
        ['**Disease states**', 2],
        ['**Age and gender**', 3],
        ['**Hormonal changes**', 4]),
    ] },
  { quiz: 'pk2', k: 'contrast enzyme inducers and enzyme inhibitors including', title: 'Enzyme inducers vs inhibitors',
    hook: 'Inducer = faster breakdown, less drug. Inhibitor = slower breakdown, more drug.',
    groups: [
      G('Enzyme inducer',
        ['**Accelerates metabolism**: **decreases the amount of drug** in the blood', 0],
        ['A **higher dose** may be needed', 1]),
      G('Enzyme inhibitor',
        ['**Slows down metabolism**: **increases the amount of drug** in the blood', 2],
        ['**Toxicity may increase**', 3]),
      G('What causes either',
        ['**Diet**, **co-administered drugs**, **alcohol**, **smoking**', 4]),
    ] },
  { quiz: 'pk2', k: 'explain how heart failure and cirrhosis each', title: 'Heart failure, cirrhosis and metabolism',
    hook: 'A sick liver, or poor blood to it = more active drug.',
    groups: [
      G('Heart failure',
        ['**Decreased liver perfusion** → **reduced liver enzyme activity**', 0],
        ['→ **more active drug in the blood**', 0]),
      G('Cirrhosis',
        ['**Liver scarring** → **reduced clearance**', 1],
        ['→ **more active drug in the blood**', 1]),
      G('What it means for care',
        ['**Reduced doses**; **close monitoring**', 2],
        ['Consider **contraindications** and **alternative medications**', 2]),
    ] },
  { quiz: 'pk2', k: 'name the main medication routes that avoid', title: 'Routes that avoid first-pass metabolism',
    hook: 'Anything that doesn’t go down the gut into the portal vein.',
    groups: [
      G('The routes',
        ['**Sublingual** and **buccal**', 0],
        ['**IV**, **IM**, **SC**', [1, 2, 3]],
        ['**Inhalation**; **intranasal**', [4, 5]],
        ['**Transdermal** patches; **rectal**', [6, 7]]),
      G('Why',
        ['They **do not travel through the portal vein**', 8]),
    ] },
  { quiz: 'pk2', k: 'list the routes of drug excretion naming', title: 'Routes of drug excretion',
    hook: 'Kidneys first; then bile, breath, bowel, milk, sweat.',
    groups: [
      G('The routes',
        ['**Kidneys** (**main organ**) → **urine**', 0],
        ['**Liver** → **bile** → **faeces**', 1],
        ['**Lungs** → **expired air** (the breath test)', 2],
        ['**Bowel**; **breast milk**', [3, 4]],
        ['**Sweat and saliva** (minimal)', 5]),
    ] },
  { quiz: 'pk2', k: 'name the four factors affecting drug excretion', title: 'Four factors in kidney excretion',
    hook: 'Water-soluble out; fat-soluble back in; bound stays; bad kidneys keep it.',
    groups: [
      G('The four factors',
        ['**Water-soluble** drugs: **better excretion**', 0],
        ['**Lipid-soluble** drugs: **poorly excreted**, **reabsorbed**', 1],
        ['**Protein-bound** drugs: **not excreted**, **circulate longer**', 2],
        ['**Impaired renal function**: **reduced excretion**', 3],
        ['It matters in **renal failure**, **neonates**, the **elderly**', 3]),
    ] },
  { quiz: 'pk2', k: 'distinguish excretion elimination and clearance', title: 'Excretion, elimination and clearance',
    hook: 'Excretion = out. Elimination = metabolised + out. Clearance = how fast.',
    groups: [
      G('The three terms',
        ['**Excretion**: **physical removal** from the body', 0],
        ['**Elimination** = **metabolism + excretion**', 1],
        ['Eliminated once **metabolised into an inactive metabolite**', 2],
        ['**Clearance**: the **rate (speed) of elimination**; it is **irreversible**', 3]),
    ] },
  { quiz: 'pk2', k: 'compare hepatic clearance and renal clearance', title: 'Hepatic vs renal clearance',
    hook: 'Liver: metabolise (and a little bile). Kidney: urine (some comes back).',
    groups: [
      G('Hepatic clearance',
        ['In the **liver**: **metabolism** (major) and excretion in the **bile** (minor)', 0],
        ['High hepatic clearance: **all of the drug** through the liver is **metabolised**', 1]),
      G('Renal clearance',
        ['In the **kidneys**: **excretion into the urine**', 2],
        ['**Some reabsorption** back into the **plasma**', 2]),
    ] },
  { quiz: 'pk2', k: 'define half life and steady state and', title: 'Half-life and steady state',
    hook: 'Half gone each half-life; in = out after 3–5 of them.',
    groups: [
      G('Half-life',
        ['Time for the **plasma drug concentration** to fall **by one-half**', 0],
        ['Tells us **how fast the drug leaves** the body', 0]),
      G('Steady state',
        ['The **rate of drug in** = the **rate of drug out**', 1],
        ['Reached after about **3–5 half-lives**', 2]),
    ] },
  { quiz: 'pk2', k: 'what is a dosing regimen for and', title: 'What a dosing regimen is for',
    hook: 'Keep the level in range, for this drug and this patient.',
    groups: [
      G('What it is for',
        ['ADME affects **how much** reaches the blood and **how long it acts**', 0],
        ['A regimen keeps levels **within the therapeutic range**', 1]),
      G('What it is individualised against',
        ['**Each medication** (in **clinical trials**)', 2],
        ['**Each patient**: **age**, **interactions**, **liver** and **kidney function**', 2],
        ['e.g. **amoxicillin**, **500 mg** orally **every 8 hours** for **5 days**', 3]),
    ] },
  { quiz: 'pk2', k: 'define the therapeutic range and explain therapeutic', title: 'Therapeutic range and drug monitoring',
    hook: 'Effective but not toxic: check the peak and the trough.',
    groups: [
      G('Therapeutic range',
        ['The **plasma concentration range** giving the **desired therapeutic effect** (**efficacy**)', 0],
        ['… **without causing toxicity** (**safety**)', 0]),
      G('Therapeutic drug monitoring',
        ['For drugs with a **narrow therapeutic range**, e.g. **warfarin**', 1],
        ['Measures the **peak** and **trough** concentration', 2],
        ['Keeps the level **safe and effective**', 3]),
    ] },
  { quiz: 'pk2', k: 'summarise the pharmacokinetics of paracetamol under all', title: 'Paracetamol under ADME',
    hook: 'Fast in, spreads wide, the liver makes a toxic bit, out in the urine.',
    groups: [
      G('Absorption',
        ['**Rapidly absorbed** by mouth', 0],
        ['**Delayed** by slower **gastric emptying** (**food**)', 0]),
      G('Distribution',
        ['**Distributed widely**; only a **small proportion is protein-bound**', 1]),
      G('Metabolism',
        ['Mainly in the **liver**', 2],
        ['A **hepatotoxic metabolite** can build up after **overdose**: **liver damage**', 2]),
      G('Excretion',
        ['**Metabolites** in the **urine**; **half-life** **1–3 hours**', 3],
        ['Most of a dose is gone **within 24 hours**', 4]),
    ] },

  /* ── M4 · Pharmacodynamics ── */
  { quiz: 'pd', k: 'define pharmacodynamics and state the four questions', title: 'Pharmacodynamics: the four questions',
    hook: 'Where, how, what changes, and over time.',
    groups: [
      G('Definition',
        ['**Drug–target interactions**, **mechanisms of action**, **biological effects**', 0],
        ['“**What the drug does to the body**”', 0]),
      G('The four questions',
        ['**Where** exactly does it act?', 1],
        ['**How** does it act?', 2],
        ['What **changes in function** will it cause?', 3],
        ['What happens to its effects **with time**?', 4]),
    ] },
  { quiz: 'pd', k: 'distinguish selectivity from specificity and give the', title: 'Selectivity vs specificity',
    hook: 'Selectivity counts TARGETS; specificity counts EFFECTS.',
    groups: [
      G('Selectivity',
        ['The number of **targets** a drug interacts with', 0],
        ['**High selectivity**: prefers **one target**', 0]),
      G('Specificity',
        ['The number of **effects** it produces', 1],
        ['**No drug is completely specific**', 2]),
      G('Example',
        ['**Salbutamol**: selective for **beta-2 receptors** in **lung tissue**', 3],
        ['… **little effect** on the **heart**', 3]),
    ] },
  { quiz: 'pd', k: 'define affinity efficacy and potency', title: 'Affinity, efficacy and potency',
    hook: 'How tightly it grips, how hard it pushes, how much you need.',
    groups: [
      G('The three terms',
        ['**Affinity**: **how strongly the drug binds** to its target', 0],
        ['**Efficacy**: its ability to **activate its target** and **produce a biological response**', 1],
        ['**Maximal efficacy**: the **upper limit** of the drug’s action', 1],
        ['**Potency**: the **amount of drug required** for a given effect', 2],
        ['**High potency** = the same effect at a **lower dose**', 2]),
    ] },
  { quiz: 'pd', k: 'name the four main regulatory proteins drugs', title: 'Four drug targets, with examples',
    hook: 'Transporters, ion channels, enzymes, receptors.',
    groups: [
      G('The four targets',
        ['**Transporter**: **fluoxetine** blocks the **serotonin transporter**', 0],
        ['**Ion channel**: **amlodipine** blocks **calcium** entry', 1],
        ['**Enzyme**: **ibuprofen** inhibits **COX enzymes**', 2],
        ['**Receptor**: a protein a drug **binds to**, triggering a **signal**', 3]),
    ] },
  { quiz: 'pd', k: 'explain the difference between an agonist and', title: 'Agonist vs antagonist: lock and key',
    hook: 'Agonist: the key opens the door. Antagonist: the key fits but won’t turn.',
    groups: [
      G('Agonist',
        ['**Binds to and activates** a receptor', 0],
        ['Has **affinity** and **efficacy**: the key **opens the door**', 1],
        ['e.g. **salbutamol** relaxes the **airways**', 1]),
      G('Antagonist',
        ['Binds and **blocks access**, but **does not elicit a response**', 2],
        ['Has **affinity** but **no efficacy**: the door **will not open**', 3],
        ['e.g. **metoprolol**, a **beta blocker**', 3]),
    ] },
  { quiz: 'pd', k: 'explain receptor up regulation and down regulation', title: 'Receptor up- and down-regulation',
    hook: 'Blocked → more receptors. Over-stimulated → fewer.',
    groups: [
      G('The idea',
        ['Cells can **change how many receptors** they have', 0]),
      G('Up-regulation',
        ['**More receptors**: the cell is **more sensitive**', 1],
        ['When receptors are repeatedly **blocked**', 1],
        ['e.g. **rebound hypertension** after stopping **beta-blockers**', 2]),
      G('Down-regulation',
        ['**Fewer receptors**: the cell is **less responsive**', 3],
        ['When receptors are repeatedly **stimulated**', 3],
        ['e.g. **chronic opioid use** → **tolerance**', 4]),
    ] },
  { quiz: 'pd', k: 'what are non specific drug actions give', title: 'Non-specific drug actions',
    hook: 'No target: chemistry, physics or the environment does the work.',
    groups: [
      G('What they are',
        ['Drugs that do not rely on **specific targets**', 0],
        ['They act through **chemical reactions**, **physical properties** or the **environment**', 0]),
      G('Two examples',
        ['**Activated charcoal** **absorbs toxins** from the gut', 1],
        ['**Calcium carbonate** chews **neutralise stomach acid**', 2]),
    ] },
  { quiz: 'pd', k: 'describe the dose response relationship', title: 'The dose–response relationship',
    hook: 'Little, then more, then the ceiling.',
    groups: [
      G('What it describes',
        ['How the **size of a drug’s effect** changes as the **dose** changes', 0]),
      G('The curve',
        ['At **low doses**: **little or no effect**', 1],
        ['As the dose **increases**, the **response increases**', 2],
        ['Then **maximal efficacy**: more drug **will not increase the effect**', 3]),
    ] },
  { quiz: 'pd', k: 'define the therapeutic range in pharmacodynamic terms', title: 'Therapeutic range: MEC and MTC',
    hook: 'Between the lowest that works and the lowest that harms.',
    groups: [
      G('The range',
        ['A measure of the **safety margin**: between **efficacy and toxicity**', 0],
        ['A **wider range** = a **safer drug**', 1]),
      G('Its two edges',
        ['**MEC**: the **lowest plasma concentration** that is **therapeutic** (beneficial)', 2],
        ['**MTC**: the lowest concentration where **toxic** (harmful) **effects begin**', 3]),
    ] },
  { quiz: 'pd', k: 'explain how pharmacokinetics and pharmacodynamics are linked', title: 'How PK and PD are linked',
    hook: 'How much gets there decides how fast, how strong, how long.',
    groups: [
      G('The link',
        ['The **rate** and **extent** of the response **depends** on **pharmacokinetics**', 0],
        ['PK decides **how much drug reaches the site of action**', 1],
        ['That shapes the **onset, intensity and duration** of the effect', 2],
        ['PK explains why **responses change over time**', 3]),
    ] },
  { quiz: 'pd', k: 'define an adverse effect and distinguish it', title: 'Adverse effect vs adverse drug event',
    hook: 'Effect = caused by the drug. Event = around the drug (often human error).',
    groups: [
      G('Adverse effect',
        ['A **harmful effect** suspected to be **caused by a medicine or vaccine**', 0],
        ['**All medications** cause them in **some people**', 1],
        ['**Mild** (nausea) to **serious** (liver injury); some occur **unexpectedly**', 2],
        ['Also called **side effects**; **adverse effect** is **preferred**', 3]),
      G('Adverse drug event',
        ['An **injury related to the drug**, **not always due to** it', 4],
        ['e.g. **errors in prescribing**, dispensing or administration', 4]),
    ] },
  { quiz: 'pd', k: 'list the six person related risk factors', title: 'Six person-related risk factors',
    hook: 'Age, sex, organs, genes, history, polypharmacy.',
    groups: [
      G('The six',
        ['**Age**: **neonates** or **older persons**', 0],
        ['**Sex**: **female** more susceptible', 1],
        ['**Organ health**: **kidney or liver disease**', 2],
        ['**Genetic factors**', 3],
        ['**History of prior adverse effects**', 4],
        ['**Polypharmacy** (**five drugs or more**)', 5]),
    ] },
  { quiz: 'pd', k: 'list the five drug related risk factors', title: 'Five drug-related risk factors',
    hook: 'Chemistry, class, route, dose, duration.',
    groups: [
      G('The five',
        ['**Chemical characteristics**: **large molecules**, **low selectivity**', 0],
        ['**Drug class**: e.g. **anticoagulants**: **bleeding risk**', 1],
        ['**Route**: **oral** has a **lower allergy risk** than **IV**', 2],
        ['**Dose**: **higher doses** increase risk', 3],
        ['**Duration and frequency**', 4]),
    ] },
  { quiz: 'pd', k: 'give the lecture s two examples of', title: 'Two pharmacodynamic interactions',
    hook: 'Two blood thinners add up; a blocker cancels a reliever.',
    groups: [
      G('What they are',
        ['One drug **directly alters the effect** of another', 0]),
      G('Warfarin + aspirin',
        ['**Increased risk of bleeding**', 1],
        ['Both **inhibit clotting**: an **additive effect**', 1]),
      G('Metoprolol + salbutamol',
        ['**Reduced effect of salbutamol** in asthma', 2],
        ['Salbutamol is an **agonist**; metoprolol **blocks beta receptors** (**antagonist**)', 2]),
    ] },
  { quiz: 'pd', k: 'what is carm who may report to', title: 'CARM: what it is and why it matters',
    hook: 'Document every reaction; report it; CARM follows up the serious ones.',
    groups: [
      G('What it is',
        ['The **Centre for Adverse Reactions Monitoring**', 0]),
      G('Why it matters',
        ['**Document all adverse effects**: patients may need **alerts**', 1],
        ['Reports go to an **online database**; CARM assesses **serious and fatal** events', 2]),
      G('Who can report',
        ['**Health professionals**, **patients and whānau**', 3]),
    ] },

  /* ── M5 · Medication administration ── */
  { quiz: 'admin', k: 'name the five authorised prescribers and the', title: 'Authorised and designated prescribers',
    hook: 'Doctors, NPs, dentists, optometrists, midwives; then trained pharmacists and RNs.',
    groups: [
      G('The five authorised prescribers',
        ['**Doctors**, **nurse practitioners**, **dentists**', 0],
        ['**Optometrists**, **registered midwives**', 0]),
      G('Designated prescribers',
        ['**Pharmacist prescribers**', 1],
        ['**Registered nurse prescribers**: **community health**, **diabetes health**, **primary health**', [2, 3, 4]],
        ['They complete **additional post-graduate training**', 5]),
    ] },
  { quiz: 'admin', k: 'what can and cannot a registered nurse', title: 'What an RN can and cannot do',
    hook: 'Give, monitor, teach; never prescribe or change the order.',
    groups: [
      G('The RN’s role',
        ['**Administer and monitor** medications; **assess** patients', 0],
        ['Maintain **documentation**, **safe medication practices**; **educate** patients and whānau', 0]),
      G('Cannot',
        ['**Cannot prescribe** (unless a **designated nurse prescriber**)', 1],
        ['**Cannot modify prescriptions**', 2]),
      G('Can',
        ['**Can administer under standing orders**', 3],
        ['**May** give on a prescriber’s **verbal order** (phone, emergency)', 4]),
      G('Responsibility',
        ['**Personally responsible** for **every medication they administer**', 5]),
    ] },
  { quiz: 'admin', k: 'list the 8 rights and the 2', title: 'The 8 Rights and 2 Checks',
    hook: 'Patient, medication, dose, time, route; refuse, indication, documentation; + expiry, allergies.',
    groups: [
      G('The 8 Rights',
        ['Right **patient**, **medication**, **dose**, **time**, **route**', 0],
        ['Right **to refuse**', 1],
        ['Right **indication**', 2],
        ['Right **documentation**', 3]),
      G('The 2 Checks',
        ['Check **expiry**', 4],
        ['Check **allergies**', 5]),
    ] },
  { quiz: 'admin', k: 'how is patient identity checked before giving', title: 'Checking patient identity',
    hook: 'Three identifiers, every time: band + name + DOB, or a photo.',
    groups: [
      G('The rule',
        ['Use **three identifiers**', 0],
        ['The **NHI** is part of it in Aotearoa', 1]),
      G('In hospital',
        ['Check the **identification band**', 2],
        ['Ask them to state their **full name and date of birth**', 2]),
      G('In aged care',
        ['Residents may not wear bands: e.g. **photographic verification**', 3]),
    ] },
  { quiz: 'admin', k: 'when are the three medication checks performed', title: 'The three medication checks',
    hook: 'Before preparing, after preparing, before putting it back.',
    groups: [
      G('The three checks (label against chart)',
        ['Check the **label** against the **medication chart**', 0],
        ['1 **Before preparing**', 1],
        ['2 **After preparing**', 2],
        ['3 **Before replacing the container**', 3]),
      G('The rule',
        ['**Only administer medications that you prepare**', 4]),
      G('The aged-care version',
        ['From **storage**; against the **order**; **re-check** **prior to administering**', 5]),
    ] },
  { quiz: 'admin', k: 'what must a nurse do about the', title: 'The right dose',
    hook: 'Know the range, calculate, measure, cut only scored, ask before crushing.',
    groups: [
      G('The points',
        ['Know the **usual dose range**; if unsure, check the **NZ Formulary**', 0],
        ['Use **medication calculations**', 1],
        ['**Prepare** medications **accurately**: **syringes**, **graduated cups**', 2],
        ['Cut with a **tablet cutter**, only if it has a **score mark**', 3],
        ['**Check with a pharmacist before crushing**', 4],
        ['Ask the prescriber for a better **formulation**, e.g. **a liquid**', 5]),
    ] },
  { quiz: 'admin', k: 'explain the right time including the tolerance', title: 'The right time',
    hook: 'Prescribed time and frequency, within 30 minutes, in 24-hour time.',
    groups: [
      G('The rule',
        ['The **prescribed time AND frequency**', 0],
        ['It depends on **food**, **drug monitoring**, the **last dose**', 1],
        ['Some are **time-critical**, e.g. **insulin before meals**', 2]),
      G('The tolerance',
        ['Regular medicines: **within 30 minutes** of the time', 3]),
      G('prn timing, and the clock',
        ['**prn** needs **clinical judgement**, e.g. a **pain assessment**', 4],
        ['Always use **24-hour time**', 5]),
    ] },
  { quiz: 'admin', k: 'what must the nurse do if no', title: 'No route on the prescription',
    hook: 'No route, no dose: withhold and call.',
    groups: [
      G('The rule',
        ['The order **must include a route**, **appropriate** for drug and patient', 0]),
      G('What the nurse does',
        ['**Withhold the medication**', 1],
        ['**Contact the prescriber** for **clarification**', 2],
        ['Can’t take it by that route? **Discuss with the prescriber**', 3]),
    ] },
  { quiz: 'admin', k: 'describe the nurse s actions when a', title: 'When a patient refuses',
    hook: 'Explain, document, inform, discard.',
    groups: [
      G('The right',
        ['They may refuse, unless under the **Mental Health Act**', 0]),
      G('The nurse’s actions',
        ['**Explain the consequences**, e.g. more symptoms', 1],
        ['**Document** the patient’s **reason for refusal**', 2],
        ['**Inform** the **next shift RN**, the **prescriber**, maybe whānau', 3],
        ['**Discard refused medications**: **do not store them**', 4]),
    ] },
  { quiz: 'admin', k: 'what does right indication require of the', title: 'The right indication',
    hook: 'Know WHY, especially for prn.',
    groups: [
      G('What it requires',
        ['The nurse is **accountable** and needs **knowledge about the indication**', 0],
        ['Is it being given for the **right reason**?', 1],
        ['Especially for **prn medications**: **nurse-led assessment**', 2]),
    ] },
  { quiz: 'admin', k: 'state the rules for right documentation including', title: 'The rules of right documentation',
    hook: 'Right after, never before; say why if not given.',
    groups: [
      G('The rules',
        ['Record **immediately after administration**: **date, time, dose, who**', 0],
        ['**Never document before** you have given it', 1],
        ['A dose **not given**: document it **and the reason why**', 2],
        ['**prn**: the **assessment before** and the **evaluation after**', 3],
        ['**Discuss and document any errors**', 4]),
    ] },
  { quiz: 'admin', k: 'explain the expiry date check including the', title: 'The expiry date check',
    hook: 'The end of the month; not if repackaged or badly stored.',
    groups: [
      G('What it is',
        ['How long a medication is **effective and safe**', 0],
        ['Labelled **exp**, **use by** or **use before**', 1],
        ['Month only (e.g. **July 2030**): **the end of that month**', 2]),
      G('When you cannot rely on it',
        ['It has been **repackaged**', 3],
        ['It has **not been stored as recommended**, e.g. **kept in the fridge**', 4],
        ['Pharmacist-repackaged: **no longer than 12 months** after dispensing', 5]),
    ] },
  { quiz: 'admin', k: 'describe the allergy check including the two', title: 'The allergy check',
    hook: 'Charted AND asked. NKA / NKDA.',
    groups: [
      G('The check',
        ['Allergies are also called **hypersensitivities**', 0],
        ['**Documented in the medication chart**', 1],
        ['**And** the nurse should **ask the patient**', 2],
        ['An allergy is a **contraindication**', 4]),
      G('The two acronyms',
        ['**NKA** = **no known allergies**', 3],
        ['**NKDA** = **no known drug allergies**', 3]),
    ] },
  { quiz: 'admin', k: 'where does medication administration fit into the', title: 'Medicines in the nursing process',
    hook: 'Assess, decide, plan and give, evaluate: ADPIE with medicines.',
    groups: [
      G('Assessment',
        ['A **health history**: **pregnancy**, **liver disease**', 0],
        ['What they are **taking**; any **allergies**', 0],
        ['Any **challenges**: **memory**, **opening containers**; **cultural needs**', 1]),
      G('Diagnosis',
        ['Decide the **importance** of what you gathered, and its **implications**', 2]),
      G('Planning & implementing',
        ['Use the **8 Rights**; **prn** and **standing order** medicines appropriately', 3],
        ['**Advocate** (a **medication review**); **educate**', 3]),
      G('Evaluation',
        ['The **therapeutic response**; any **adverse effects**', 4],
        ['Their **knowledge** of the medicine; their ability to **self-manage** it', 4]),
    ] },
  { quiz: 'admin', k: 'what must the national medication chart contain', title: 'What the National Medication Chart holds',
    hook: 'Who the patient is; what, how much, how, when; and who signed.',
    groups: [
      G('Patient identification',
        ['**Full name**, **NHI number**, **date of birth**', 0],
        ['**Allergies and adverse reactions**', 0],
        ['When relevant: **weight**, **height**, **gestational age**', 1]),
      G('Prescriber requirements',
        ['The **date** written; **medication name**; **dose and units**', 2],
        ['**Route**; **frequency** or **administration times**', 3],
        ['The **prescriber’s signature**', 4]),
    ] },
  { quiz: 'admin', k: 'name the five special sections of the', title: 'The chart’s five special sections',
    hook: 'Once-only, verbal, prn, fluids, oxygen.',
    groups: [
      G('The five sections',
        ['**Once-only medicines**', 0],
        ['**Verbal orders**', 1],
        ['**PRN medicines**', 2],
        ['**Fluid and infusion orders**', 3],
        ['**Oxygen and medical gases**', 4]),
      G('The RN’s own charting',
        ['A **signature/initials for each dose**', 5],
        ['**Non-administration codes** when a dose is not given', 5],
        ['Students also need the “**check**” **initial**', 6]),
    ] },
];
