/* The chart drills: whole orders to read, scenarios about the chart’s rules and codes, and orders with one
   dangerous way of writing to spot.
   The doses are TYPICAL ADULT EXAMPLES chosen so the lines look like a real chart — they are practice in
   reading, never a guide to what to give. The page says so.

   ORDERS: { id, sec, med, dose, route, freq, ind?, max?, note?, read, bad: [[wrong reading, why it is wrong]×3],
             tk: [term ids to decode], tip?, src? }
   sec: 'reg' regular · 'prn' as required · 'once' once-only/stat · 'fluid' fluid & infusion · 'o2' oxygen.
   Every wrong reading is the right sentence with ONE thing changed (the build diffs them and fails if not, and if
   the lengths drift apart) — so the right reading can never be spotted by its wording, only by reading the line. */
export const ORDERS = [
  /* ── regular ── */
  { id: 'o-meto', sec: 'reg', med: 'Metoprolol', dose: '25 mg', route: 'PO', freq: 'BD', note: 'Withhold if HR < 60 or SBP < 100',
    read: 'Give 25 milligrams of metoprolol by mouth twice a day — withhold it if the heart rate is under 60 or the systolic BP is under 100.',
    bad: [['Give 25 milligrams of metoprolol by mouth twice a day — withhold it if the heart rate is over 60 or the systolic BP is over 100.', '< means LESS than: the dose is held when the obs are too LOW.'],
      ['Give 25 milligrams of metoprolol by mouth three times a day — withhold it if the heart rate is under 60 or the systolic BP is under 100.', 'BD is twice a day; three times is TDS.'],
      ['Give 25 micrograms of metoprolol by mouth twice a day — withhold it if the heart rate is under 60 or the systolic BP is under 100.', 'mg is milligrams — a microgram is a thousand times smaller.']],
    tk: ['po', 'bd', 'lt', 'hr', 'sbp', 'holdparam'], tip: 'Take the heart rate and blood pressure before you give it — the hold parameter only works if you look.' },
  { id: 'o-enox', sec: 'reg', med: 'Enoxaparin', dose: '40 mg', route: 'SC', freq: 'daily', ind: 'VTE prophylaxis',
    read: 'Give 40 milligrams of enoxaparin under the skin once a day, to prevent blood clots.',
    bad: [['Give 40 milligrams of enoxaparin under the tongue once a day, to prevent blood clots.', 'SC is subcutaneous — under the skin. Under the tongue is SL: the exact misreading that makes “subcut” the safer way to write it.'],
      ['Give 40 milligrams of enoxaparin into a muscle once a day, to prevent blood clots.', 'SC is under the skin, not into a muscle (IM).'],
      ['Give 40 milligrams of enoxaparin under the skin twice a day, to prevent blood clots.', '“daily” means once a day.']],
    tk: ['sc', 'vte', 'pfs'] },
  { id: 'o-para-reg', sec: 'reg', med: 'Paracetamol', dose: '1 g', route: 'PO', freq: 'QID', max: '4 g/24 h',
    read: 'Give 1 gram of paracetamol by mouth four times a day — never more than 4 grams in 24 hours.',
    bad: [['Give 1 gram of paracetamol by mouth every 4 hours — never more than 4 grams in 24 hours.', 'QID is four times a day. Every 4 hours (q4h) would be up to 6 doses — 6 g, over the maximum.'],
      ['Give 1 milligram of paracetamol by mouth four times a day — never more than 4 milligrams in 24 hours.', 'g is grams: 1 g = 1000 mg.'],
      ['Give 1 gram of paracetamol rectally four times a day — never more than 4 grams in 24 hours.', 'PO is by mouth; rectally is PR.']],
    tk: ['po', 'qid', 'g', 'max24'] },
  { id: 'o-omep', sec: 'reg', med: 'Omeprazole', dose: '20 mg', route: 'PO', freq: 'mane', ind: 'GORD',
    read: 'Give 20 milligrams of omeprazole by mouth every morning, for reflux.',
    bad: [['Give 20 milligrams of omeprazole by mouth every night, for reflux.', 'mane is the morning; night is nocte.'],
      ['Give 20 milligrams of omeprazole by mouth at midday, for reflux.', 'mane is the morning; midday is midi.'],
      ['Give 20 milligrams of omeprazole by mouth every morning, for heart failure.', 'GORD is gastro-oesophageal reflux disease; heart failure is CHF.']],
    tk: ['po', 'mane', 'gord'] },
  { id: 'o-ator', sec: 'reg', med: 'Atorvastatin', dose: '40 mg', route: 'PO', freq: 'nocte',
    read: 'Give 40 milligrams of atorvastatin by mouth every night.',
    bad: [['Give 40 milligrams of atorvastatin by mouth every morning.', 'nocte is at night; the morning is mane.'],
      ['Give 40 milligrams of atorvastatin by mouth at night, if needed.', 'Nothing here says PRN — it is a regular dose, every night.'],
      ['Give 40 milligrams of atorvastatin by mouth every second night.', 'nocte means every night, not alternate nights.']],
    tk: ['po', 'nocte'] },
  { id: 'o-amox', sec: 'reg', med: 'Amoxicillin', dose: '500 mg', route: 'PO', freq: 'TDS × 5/7', ind: 'UTI',
    read: 'Give 500 milligrams of amoxicillin by mouth three times a day for 5 days, for a urinary tract infection.',
    bad: [['Give 500 milligrams of amoxicillin by mouth twice a day for 5 days, for a urinary tract infection.', 'TDS is three times a day; twice is BD.'],
      ['Give 500 milligrams of amoxicillin by mouth three times a day for 5 weeks, for a urinary tract infection.', '/7 counts days. Weeks would be /52.'],
      ['Give 500 milligrams of amoxicillin by mouth three times a day until 5 doses are in, for a urinary tract infection.', '5/7 is five DAYS, not five doses — 15 doses in all.']],
    tk: ['po', 'tds', 'd7', 'uti'] },
  { id: 'o-cefaz', sec: 'reg', med: 'Cefazolin', dose: '2 g', route: 'IV', freq: 'q8h',
    read: 'Give 2 grams of cefazolin into a vein every 8 hours.',
    bad: [['Give 2 grams of cefazolin into a vein 8 times a day.', 'q means “every”: q8h is every 8 hours — 3 doses a day, not 8.'],
      ['Give 2 grams of cefazolin into a muscle every 8 hours.', 'IV is into a vein; into a muscle is IM.'],
      ['Give 2 milligrams of cefazolin into a vein every 8 hours.', 'g is grams, a thousand times more than mg.']],
    tk: ['iv', 'q8h', 'g', 'timecrit'], tip: 'By the clock — e.g. 0600, 1400 and 2200 — to keep the level steady. IV antibiotics are on most time-critical lists.' },
  { id: 'o-metf', sec: 'reg', med: 'Metformin', dose: '500 mg', route: 'PO', freq: 'BD pc', ind: 'T2DM',
    read: 'Give 500 milligrams of metformin by mouth twice a day after meals, for type 2 diabetes.',
    bad: [['Give 500 milligrams of metformin by mouth twice a day before meals, for type 2 diabetes.', 'pc is after food; before is ac.'],
      ['Give 500 milligrams of metformin by mouth three times a day after meals, for type 2 diabetes.', 'BD is twice a day.'],
      ['Give 500 milligrams of metformin by mouth twice a day after meals, for type 1 diabetes.', 'T2DM is type 2 diabetes.']],
    tk: ['po', 'bd', 'pc', 't2dm'] },
  { id: 'o-levo', sec: 'reg', med: 'Levothyroxine', dose: '100 mcg', route: 'PO', freq: 'mane ac',
    read: 'Give 100 micrograms of levothyroxine by mouth every morning before breakfast.',
    bad: [['Give 100 milligrams of levothyroxine by mouth every morning before breakfast.', 'mcg is micrograms — reading it as mg is a thousand-fold overdose.'],
      ['Give 100 micrograms of levothyroxine by mouth every morning after breakfast.', 'ac is before food; after is pc.'],
      ['Give 100 micrograms of levothyroxine by mouth every night before supper.', 'mane is the morning.']],
    tk: ['mcg', 'po', 'mane', 'ac'] },
  { id: 'o-furo', sec: 'reg', med: 'Furosemide', dose: '40 mg', route: 'PO', freq: 'mane', note: 'Check K⁺ and daily Wt',
    read: 'Give 40 milligrams of furosemide by mouth every morning, and watch the potassium result and the daily weight.',
    bad: [['Give 40 milligrams of furosemide by mouth every night, and watch the potassium result and the daily weight.', 'mane is the morning — a diuretic in the morning, so the patient is not up all night.'],
      ['Give 40 milligrams of furosemide into a vein every morning, and watch the potassium result and the daily weight.', 'PO is by mouth.'],
      ['Give 40 milligrams of furosemide by mouth every morning, and watch the pulse and the temperature.', 'K⁺ is potassium; Wt is weight.']],
    tk: ['po', 'mane', 'k', 'wt'] },
  { id: 'o-glarg', sec: 'reg', med: 'Insulin glargine', dose: '20 units', route: 'SC', freq: 'nocte',
    read: 'Give 20 units of insulin glargine under the skin every night.',
    bad: [['Give 20 units of insulin glargine into a vein every night.', 'SC is under the skin — IV insulin is a different, specialist order.'],
      ['Give 20 millilitres of insulin glargine under the skin every night.', 'Insulin is dosed in units, not millilitres.'],
      ['Give 20 units of insulin glargine under the skin every morning.', 'nocte is at night.']],
    tk: ['units', 'sc', 'nocte', 'pI'] },
  { id: 'o-aspart', sec: 'reg', med: 'Insulin aspart', dose: '6 units', route: 'SC', freq: 'TDS ac',
    read: 'Give 6 units of insulin aspart under the skin three times a day, before each meal.',
    bad: [['Give 6 units of insulin aspart under the skin three times a day, after each meal.', 'ac is before food.'],
      ['Give 60 units of insulin aspart under the skin three times a day, before each meal.', 'The dose is 6 units.'],
      ['Give 6 units of insulin aspart under the skin twice a day, before each meal.', 'TDS is three times a day.']],
    tk: ['units', 'sc', 'tds', 'ac', 'timecrit'], tip: 'Mealtime insulin is time-critical: it has to go in before the food does. Check the BGL first.' },
  { id: 'o-asp', sec: 'reg', med: 'Aspirin', dose: '100 mg', route: 'PO', freq: 'daily',
    read: 'Give 100 milligrams of aspirin by mouth once a day.',
    bad: [['Give 100 milligrams of aspirin by mouth every other day.', '“daily” is every day.'],
      ['Give 100 micrograms of aspirin by mouth once a day.', 'mg is milligrams.'],
      ['Give 100 milligrams of aspirin by mouth once a day, for pain.', 'Nothing says what it is for — at this dose it is a regular daily medicine, not a painkiller.']],
    tk: ['po', 'mg'] },
  { id: 'o-dig', sec: 'reg', med: 'Digoxin', dose: '62.5 mcg', route: 'PO', freq: 'mane', note: 'Apical pulse first — withhold if < 60',
    read: 'Give 62.5 micrograms of digoxin by mouth every morning — count the apical pulse first and withhold it if it is under 60.',
    bad: [['Give 62.5 milligrams of digoxin by mouth every morning — count the apical pulse first and withhold it if it is under 60.', 'mcg is micrograms — a thousand times less than mg.'],
      ['Give 62.5 micrograms of digoxin by mouth every morning — count the apical pulse first and withhold it if it is over 60.', '< means less than.'],
      ['Give 62.5 micrograms of digoxin by mouth every morning — take the blood pressure first and withhold it if it is under 60.', 'The note asks for the apical pulse — a full minute with a stethoscope over the heart.']],
    tk: ['mcg', 'po', 'mane', 'apical', 'lt'], src: 'Medication Calculations 2026 slides 23–24 (62.5 mcg tablets)' },
  { id: 'o-symb', sec: 'reg', med: 'Budesonide/formoterol 200/6', dose: '2 puffs', route: 'INH', freq: 'BD',
    read: 'Breathe in 2 puffs from an inhaler twice a day.',
    bad: [['Breathe in 2 puffs from an inhaler every 4 hours.', 'BD is twice a day.'],
      ['Breathe in 2 puffs from a nebuliser twice a day.', 'INH is from an inhaler; a nebuliser is NEB.'],
      ['Breathe in 2 puffs from an inhaler once a day.', 'BD is twice a day.']],
    tk: ['inh', 'bd', 'mdi', 'spacer'] },
  { id: 'o-latan', sec: 'reg', med: 'Latanoprost 0.005%', dose: '1 drop', route: 'both eyes', freq: 'nocte',
    read: 'Put 1 drop into both eyes every night.',
    bad: [['Put 1 drop into both ears every night.', 'It says eyes.'],
      ['Put 1 drop into the right eye every night.', 'Both eyes. (Written in full on purpose: OD, OS and OU are on the danger list.)'],
      ['Put 1 drop into both eyes every morning.', 'nocte is at night.']],
    tk: ['nocte', 'gtt', 'OU'] },
  { id: 'o-pred', sec: 'reg', med: 'Prednisone', dose: '40 mg', route: 'PO', freq: 'mane × 5/7',
    read: 'Give 40 milligrams of prednisone by mouth every morning for 5 days.',
    bad: [['Give 40 milligrams of prednisone by mouth every morning for 5 weeks.', '/7 counts days.'],
      ['Give 40 milligrams of prednisone by mouth in total, spread over 5 days.', '40 mg is each morning’s dose — 200 mg across the course.'],
      ['Give 40 milligrams of prednisone by mouth every night for 5 days.', 'mane is the morning.']],
    tk: ['po', 'mane', 'd7', 'tallman'], tip: 'Prednisone and prednisolone are different medicines with look-alike names — the reason for Tall Man lettering.' },
  { id: 'o-omepng', sec: 'reg', med: 'Omeprazole (dispersible)', dose: '20 mg', route: 'NG', freq: 'daily',
    read: 'Give 20 milligrams of dispersible omeprazole down the nasogastric tube once a day.',
    bad: [['Give 20 milligrams of dispersible omeprazole as a nasal spray once a day.', 'NG is a tube through the nose into the stomach — not a nasal spray.'],
      ['Give 20 milligrams of dispersible omeprazole by mouth, to swallow, once a day.', 'NG is down the tube — the patient may not be able to swallow.'],
      ['Give 20 milligrams of dispersible omeprazole down the nasogastric tube every second day.', '“daily” is every day.']],
    tk: ['ng', 'disp'], tip: 'Only liquids, or forms a pharmacist has cleared, go down a tube — flushed before and after.' },
  { id: 'o-fent', sec: 'reg', med: 'Fentanyl patch', dose: '25 mcg/h', route: 'TD', freq: 'every 72 h',
    read: 'Apply a patch that releases 25 micrograms of fentanyl an hour, and replace it every 72 hours (3 days).',
    bad: [['Apply a patch that releases 25 milligrams of fentanyl an hour, and replace it every 72 hours (3 days).', 'mcg is micrograms.'],
      ['Apply a patch that releases 25 micrograms of fentanyl an hour, and replace it every 7 days.', 'Every 72 hours is every 3 days.'],
      ['Apply a patch that releases 25 micrograms of fentanyl a day, and replace it every 72 hours (3 days).', '/h is per HOUR.']],
    tk: ['mcg', 'td', 'pN'], tip: 'Record where the patch is and take the old one off — two on at once is an overdose.' },
  /* ── as required ── */
  { id: 'o-para-prn', sec: 'prn', med: 'Paracetamol', dose: '1 g', route: 'PO/PR', freq: 'q4–6h PRN', ind: 'pain / fever', max: '4 g/24 h',
    read: 'Only when needed for pain or fever, give 1 gram of paracetamol by mouth or rectally, 4–6 hours apart — no more than 4 grams in 24 hours.',
    bad: [['Regularly, whatever the symptoms, give 1 gram of paracetamol by mouth or rectally, 4–6 hours apart — no more than 4 grams in 24 hours.', 'PRN means only when needed.'],
      ['Only when needed for pain or fever, give 1 gram of paracetamol by mouth or rectally, 4–6 hours apart — no more than 4 grams a dose.', 'The 4 g is the most in any 24 HOURS; each dose is 1 g.'],
      ['Only when needed for pain or fever, give 1 gram of paracetamol by mouth or vaginally, 4–6 hours apart — no more than 4 grams in 24 hours.', 'PR is rectally; vaginally is PV.']],
    tk: ['po', 'pr', 'q4h', 'prn', 'max24'] },
  { id: 'o-morph', sec: 'prn', med: 'Morphine', dose: '2.5–5 mg', route: 'SC', freq: 'q2h PRN', ind: 'pain',
    read: 'Only when needed for pain, give 2.5 to 5 milligrams of morphine under the skin, at least 2 hours apart.',
    bad: [['Regularly, in pain or not, give 2.5 to 5 milligrams of morphine under the skin, at least 2 hours apart.', 'PRN — only when needed, after you assess.'],
      ['Only when needed for pain, give 25 to 50 milligrams of morphine under the skin, at least 2 hours apart.', 'The range is 2.5 to 5 mg.'],
      ['Only when needed for pain, give 2.5 to 5 milligrams of morphine into a vein, at least 2 hours apart.', 'SC is under the skin.']],
    tk: ['sc', 'q2h', 'prn', 'pN', 'sedscore', 'rr'], tip: 'A range dose: you pick within 2.5–5 mg from your assessment. Check sedation and breathing before and after.' },
  { id: 'o-oxy', sec: 'prn', med: 'Oxycodone IR', dose: '5 mg', route: 'PO', freq: 'q4h PRN', ind: 'pain',
    read: 'Only when needed for pain, give 5 milligrams of immediate-release oxycodone by mouth, at least 4 hours apart.',
    bad: [['Only when needed for pain, give 5 milligrams of slow-release oxycodone by mouth, at least 4 hours apart.', 'IR is immediate release. Mixing up the IR and SR forms of the same opioid is a real, serious error.'],
      ['Only when needed for pain, give 5 milligrams of immediate-release oxycodone by mouth, four times a day.', 'q4h is every 4 hours — up to 6 doses in 24 hours.'],
      ['Regularly, in pain or not, give 5 milligrams of immediate-release oxycodone by mouth, at least 4 hours apart.', 'PRN — only when needed.']],
    tk: ['ir', 'po', 'q4h', 'prn', 'pN'] },
  { id: 'o-ondan', sec: 'prn', med: 'Ondansetron', dose: '4 mg', route: 'ODT', freq: 'q8h PRN', ind: 'N/V',
    read: 'Only when needed for nausea or vomiting, let a 4 milligram ondansetron tablet melt on the tongue, at least 8 hours apart.',
    bad: [['Only when needed for nausea or vomiting, have a 4 milligram ondansetron tablet swallowed whole with water, at least 8 hours apart.', 'ODT melts on the tongue — no water needed, which is the point when someone is nauseated.'],
      ['Regularly, sick or not, let a 4 milligram ondansetron tablet melt on the tongue, at least 8 hours apart.', 'PRN — only when needed.'],
      ['Only when needed for nausea or vomiting, let a 4 milligram ondansetron tablet melt on the tongue, up to 8 times a day.', 'q8h is every 8 hours.']],
    tk: ['odt', 'q8h', 'prn', 'nv'] },
  { id: 'o-salb', sec: 'prn', med: 'Salbutamol', dose: '2.5–5 mg', route: 'NEB', freq: 'q4h PRN', ind: 'wheeze / SOB',
    read: 'Only when needed for wheeze or breathlessness, nebulise 2.5 to 5 milligrams of salbutamol, at least 4 hours apart.',
    bad: [['Only when needed for wheeze or breathlessness, give 2.5 to 5 milligrams of salbutamol from a puffer, at least 4 hours apart.', 'NEB is a nebuliser, not an inhaler.'],
      ['Only when needed for wheeze or breathlessness, nebulise 2.5 to 5 milligrams of salbutamol, four times a day.', 'q4h is every 4 hours.'],
      ['Regularly, wheezy or not, nebulise 2.5 to 5 milligrams of salbutamol, at least 4 hours apart.', 'PRN — only when needed.']],
    tk: ['neb', 'q4h', 'prn', 'sob', 'nebule'] },
  { id: 'o-gtn', sec: 'prn', med: 'GTN spray', dose: '400 mcg', route: 'SL', freq: 'PRN — may repeat after 5 min, max 3 doses', ind: 'chest pain',
    read: 'For chest pain, spray 400 micrograms of GTN under the tongue — it may be repeated after 5 minutes, up to 3 doses.',
    bad: [['For chest pain, spray 400 milligrams of GTN under the tongue — it may be repeated after 5 minutes, up to 3 doses.', 'mcg is micrograms.'],
      ['For chest pain, spray 400 micrograms of GTN against the cheek — it may be repeated after 5 minutes, up to 3 doses.', 'SL is under the tongue; the cheek is buccal.'],
      ['For chest pain, spray 400 micrograms of GTN under the tongue — it may be repeated after 5 hours, up to 3 doses.', 'After 5 MINUTES.']],
    tk: ['mcg', 'sl', 'prn'], src: 'Pharmacology Concepts (2) 2026 slide 31 (GTN spray, the sublingual example)' },
  { id: 'o-lact', sec: 'prn', med: 'Lactulose', dose: '20 mL', route: 'PO', freq: 'BD PRN', ind: 'constipation',
    read: 'Only when needed for constipation, give 20 millilitres of lactulose by mouth, up to twice a day.',
    bad: [['Only when needed for constipation, give 20 milligrams of lactulose by mouth, up to twice a day.', 'It is a liquid: mL is millilitres.'],
      ['Regularly, constipated or not, give 20 millilitres of lactulose by mouth, up to twice a day.', 'PRN — only when needed.'],
      ['Only when needed for constipation, give 20 millilitres of lactulose by mouth, up to three times a day.', 'BD is twice a day.']],
    tk: ['ml', 'po', 'bd', 'prn', 'bo'] },
  { id: 'o-bisa', sec: 'prn', med: 'Bisacodyl', dose: '10 mg', route: 'PR', freq: 'mane PRN', ind: 'constipation',
    read: 'Only when needed for constipation, insert a 10 milligram bisacodyl suppository into the rectum in the morning.',
    bad: [['Only when needed for constipation, insert a 10 milligram bisacodyl suppository into the rectum at night.', 'mane is the morning.'],
      ['Only when needed for constipation, insert a 10 milligram bisacodyl suppository into the vagina in the morning.', 'PR is rectally; vaginally is PV.'],
      ['Every morning, constipated or not, insert a 10 milligram bisacodyl suppository into the rectum.', 'PRN — only when needed.']],
    tk: ['pr', 'mane', 'prn', 'supp'] },
  { id: 'o-hypo', sec: 'prn', med: 'Glucose gel 40%', dose: '15 g', route: 'PO', freq: 'PRN', ind: 'BGL < 4 mmol/L (hypo protocol)',
    read: 'If the blood glucose is under 4 mmol/L, give 15 grams of glucose gel by mouth, following the hypo protocol.',
    bad: [['If the blood glucose is over 4 mmol/L, give 15 grams of glucose gel by mouth, following the hypo protocol.', '< means LESS than — this treats a LOW glucose.'],
      ['If the blood glucose is under 4 mmol/L, give 15 milligrams of glucose gel by mouth, following the hypo protocol.', '15 g is grams.'],
      ['Whatever the blood glucose, give 15 grams of glucose gel by mouth, following the hypo protocol.', 'PRN — only when the glucose is low.']],
    tk: ['bgl', 'lt', 'hypo', 'prn'] },
  /* ── once-only ── */
  { id: 'o-adr', sec: 'once', med: 'Adrenaline 1:1000', dose: '0.5 mg (0.5 mL)', route: 'IM', freq: 'stat', ind: 'anaphylaxis',
    read: 'Now, once: inject 0.5 milligrams of adrenaline (0.5 mL of 1:1000) into a muscle, for anaphylaxis.',
    bad: [['Now, once: inject 0.5 milligrams of adrenaline (0.5 mL of 1:1000) into a vein, for anaphylaxis.', 'IM is into a muscle — IV adrenaline is a different, specialist dose.'],
      ['Now, once: inject 0.5 milligrams of adrenaline (0.5 mL of 1:10 000) into a muscle, for anaphylaxis.', '1:1000 is ten times stronger than 1:10 000 — 0.5 mL of 1:10 000 is only 0.05 mg.'],
      ['Whenever needed: inject 0.5 milligrams of adrenaline (0.5 mL of 1:1000) into a muscle, for anaphylaxis.', 'stat is one dose, now.']],
    tk: ['r1000', 'im', 'stat', 'anaphylaxis'], src: 'ASCIA Action Plan for Anaphylaxis (2026); Medication Calculations 2026 slide 57' },
  { id: 'o-furoiv', sec: 'once', med: 'Furosemide', dose: '40 mg', route: 'IV', freq: 'stat',
    read: 'Now, once: give 40 milligrams of furosemide into a vein.',
    bad: [['Every morning: give 40 milligrams of furosemide into a vein.', 'stat is one dose, now.'],
      ['Now, once: give 40 milligrams of furosemide into a muscle.', 'IV is into a vein.'],
      ['Now, once: give 4 milligrams of furosemide into a vein.', 'The dose is 40 mg.']],
    tk: ['iv', 'stat'] },
  /* ── fluids and infusions ── */
  { id: 'o-nacl', sec: 'fluid', med: 'Sodium chloride 0.9%', dose: '1000 mL', route: 'IV', freq: 'over 8 h (125 mL/h)',
    read: 'Run 1 litre of sodium chloride 0.9% into a vein over 8 hours — 125 mL an hour.',
    bad: [['Run 1 litre of sodium chloride 0.9% into a vein at 1000 mL an hour, for 8 hours.', '1000 mL is the whole bag and 125 mL/h the rate — 1000 mL an hour for 8 hours would be 8 litres.'],
      ['Run 1 litre of glucose 5% into a vein over 8 hours — 125 mL an hour.', 'NaCl 0.9% is sodium chloride — “normal saline”.'],
      ['Run 125 mL of sodium chloride 0.9% into a vein over 8 hours, in total.', '125 mL is the amount per hour; the order is for the whole 1000 mL.']],
    tk: ['nacl', 'iv', 'mlh', 'ivi'] },
  { id: 'o-dex', sec: 'fluid', med: 'Glucose 5%', dose: '500 mL', route: 'IV', freq: 'over 6 h — giving set 20 drops/mL',
    read: 'Run 500 mL of glucose 5% over 6 hours at 28 drops a minute: (500 × 20) ÷ (6 × 60) = 27.8, rounded up.',
    bad: [['Run 500 mL of glucose 5% over 6 hours at 27 drops a minute: (500 × 20) ÷ (6 × 60) = 27.8, rounded down.', 'Round .5 and above UP: 27.8 → 28.'],
      ['Run 500 mL of glucose 5% over 6 hours at 28 mL an hour: (500 × 20) ÷ (6 × 60) = 27.8, rounded up.', 'This sum gives drops per minute, not mL/h (500 ÷ 6 is about 83 mL/h).'],
      ['Run 500 mL of glucose 5% over 6 hours at 83 drops a minute: 500 ÷ 6 = 83.3, rounded down.', '83 is mL per hour. Drops per minute needs the drop factor: (500 × 20) ÷ 360 = 28.']],
    tk: ['gluc5', 'gttmin', 'gttml', 'redherring'], src: 'Medication Calculations 2026 slides 69 & 72 (worked example 15)',
    /* a calculation line: the wrong method changes every number after it, so this one may differ in more places (the length check still holds) */
    maxRuns: 5 },
  { id: 'o-kcl', sec: 'fluid', med: 'KCl 20 mmol in NaCl 0.9%', dose: '1000 mL', route: 'IV', freq: 'over 8 h',
    read: 'Run 1 litre of sodium chloride 0.9% with 20 mmol of potassium chloride added, over 8 hours.',
    bad: [['Run 1 litre of sodium chloride 0.9% with 20 mmol of potassium chloride added, over 8 minutes.', 'Over 8 HOURS — potassium run fast can stop the heart.'],
      ['Run 1 litre of sodium chloride 0.9% with 20 milligrams of potassium chloride added, over 8 hours.', 'Potassium is dosed in mmol (millimoles).'],
      ['Run 1 litre of glucose 5% with 20 mmol of potassium chloride added, over 8 hours.', 'The fluid is NaCl 0.9% — sodium chloride.']],
    tk: ['kcl', 'mmol', 'nacl', 'pP'], tip: 'Concentrated potassium is never pushed — only diluted in the bag and run slowly, exactly as prescribed.' },
  /* ── oxygen ── */
  { id: 'o-o2np', sec: 'o2', med: 'Oxygen', dose: '2 L/min', route: 'NP', freq: 'continuous', ind: 'target SpO₂ 92–96%',
    read: 'Give oxygen through nasal prongs at 2 litres a minute, keeping the saturation between 92 and 96%.',
    bad: [['Give oxygen through a Hudson mask at 2 litres a minute, keeping the saturation between 92 and 96%.', 'NP is nasal prongs — and a Hudson mask needs at least 5 L/min.'],
      ['Give oxygen through nasal prongs at 2 litres an hour, keeping the saturation between 92 and 96%.', 'L/min is litres per MINUTE.'],
      ['Give oxygen through nasal prongs at 2 litres a minute, keeping the saturation above 96%.', 'The target range is 92–96%.']],
    tk: ['np', 'lmin', 'spo2', 'targetsat'] },
  { id: 'o-o2copd', sec: 'o2', med: 'Oxygen', dose: '1–2 L/min', route: 'NP', freq: 'continuous', ind: 'COPD — target SpO₂ 88–92%',
    read: 'Give oxygen through nasal prongs at 1 to 2 litres a minute, keeping the saturation between 88 and 92%.',
    bad: [['Give oxygen through nasal prongs at 1 to 2 litres a minute, keeping the saturation between 92 and 96%.', 'This order’s target is 88–92% — for some people with COPD, more oxygen is not better.'],
      ['Give oxygen through a non-rebreather mask at 1 to 2 litres a minute, keeping the saturation between 88 and 92%.', 'NP is nasal prongs; a non-rebreather (NRB) runs at 10–15 L/min.'],
      ['Give oxygen through nasal prongs at 12 litres a minute, keeping the saturation between 88 and 92%.', 'The flow is 1 to 2 L/min.']],
    tk: ['np', 'lmin', 'copd', 'targetsat'] },
];

/* Chart rules & codes — scenarios. k: 'sec' (options = the chart’s sections), 'code' (options = the not-given
   codes), or 'mcq' (its own options, the first is the answer — the page shuffles them; the build fails if the
   answer is much longer than the others, the classic way a right answer gives itself away). */
export const SECTION_OPTS = ['Regular medicines', 'PRN (as required)', 'Once-only (stat)', 'Verbal orders', 'Fluid & infusion orders', 'Oxygen & medical gases'];
export const CODE_OPTS = ['A — Absent', 'F — Fasting', 'L — On leave', 'N — Not available', 'R — Refused', 'S — Self-administered', 'V — Vomiting', 'W — Withheld'];
const MA1 = 'Med Admin (1) 2026, ';
export const SCENES = [
  { id: 's-adr', k: 'sec', q: 'Adrenaline 0.5 mg IM stat — anaphylaxis.', a: 'Once-only (stat)', why: 'A stat dose is a single dose, now — the once-only section.', src: MA1 + 'slides 54–55' },
  { id: 's-phone', k: 'sec', q: 'The registrar phones the ward: “Give furosemide 40 mg IV now — I’ll sign it when I’m up.”', a: 'Verbal orders',
    why: 'A phone order is a verbal order: its own section, and the prescriber signs it within the time your policy sets.', src: MA1 + 'slides 13–14 & 54–55' },
  { id: 's-arrest', k: 'sec', q: 'In a cardiac arrest the doctor calls out “adrenaline 1 mg IV” and you draw it up and give it.', a: 'Verbal orders',
    why: 'An order given aloud in an emergency is a verbal order — written up and signed afterwards.', src: MA1 + 'slides 13–14' },
  { id: 's-paraprn', k: 'sec', q: 'Paracetamol 1 g PO q4–6h PRN pain — max 4 g/24 h.', a: 'PRN (as required)', why: 'Given only when needed, with its reason and its 24-hour maximum.', src: MA1 + 'slides 54–55' },
  { id: 's-ator', k: 'sec', q: 'Atorvastatin 40 mg PO nocte.', a: 'Regular medicines', why: 'A scheduled dose every night — a regular medicine.' },
  { id: 's-cefaz', k: 'sec', q: 'Cefazolin 2 g IV q8h.', a: 'Regular medicines', why: 'An IV medicine given on a schedule is still a regular medicine; the fluids section is for fluids and infusions.' },
  { id: 's-nacl', k: 'sec', q: 'Sodium chloride 0.9% 1000 mL IV over 8 hours.', a: 'Fluid & infusion orders', why: 'IV fluids are ordered in the fluid & infusion section.', src: MA1 + 'slides 54–55' },
  { id: 's-o2', k: 'sec', q: 'Oxygen via nasal prongs 2 L/min, target SpO₂ 92–96%.', a: 'Oxygen & medical gases', why: 'Oxygen is a medicine, prescribed in its own section.', src: MA1 + 'slides 54–55' },
  { id: 's-entonox', k: 'sec', q: 'Entonox (nitrous oxide and oxygen), self-administered for dressing changes.', a: 'Oxygen & medical gases', why: 'A medical gas.', src: MA1 + 'slides 54–55' },
  { id: 's-salb', k: 'sec', q: 'Salbutamol 5 mg NEB q4h PRN wheeze.', a: 'PRN (as required)',
    why: 'Salbutamol is a medicine given as a mist, when needed — a PRN order. The oxygen section is for the gas itself.' },
  { id: 's-ondstat', k: 'sec', q: 'Ondansetron 4 mg IV stat.', a: 'Once-only (stat)', why: 'stat = one dose, now.' },
  { id: 's-dex', k: 'sec', q: 'Glucose 5% 500 mL IV over 6 hours.', a: 'Fluid & infusion orders', why: 'An IV fluid.' },
  { id: 'c-xray', k: 'code', q: 'Mr T’s 0800 metoprolol is due, but he is down in X-ray.', a: 'A — Absent', why: 'He is off the ward. Follow it up when he is back.' },
  { id: 'c-theatre', k: 'code', q: 'Mrs K is nil by mouth for theatre, and the anaesthetist has said her 0800 tablets are not to be given.', a: 'F — Fasting', why: 'Withheld because she is fasting — code F.' },
  { id: 'c-leave', k: 'code', q: 'Sione has gone home for the weekend on approved leave.', a: 'L — On leave', why: 'Away from hospital on leave.' },
  { id: 'c-pharm', k: 'code', q: 'The new antibiotic has not come up from pharmacy yet.', a: 'N — Not available', why: 'Not available — chase it and tell the prescriber; a missed antibiotic dose matters.' },
  { id: 'c-refuse', k: 'code', q: 'Aroha understands what it is for, but says she does not want her sleeping tablet tonight.', a: 'R — Refused',
    why: 'A competent refusal: explain, document the reason, inform the prescriber and the next shift, and discard the dose.', src: MA1 + 'slide 39' },
  { id: 'c-self', k: 'code', q: 'The patient uses her own inhaler and records her doses herself, as ward policy allows.', a: 'S — Self-administered', why: 'Self-administered.' },
  { id: 'c-vomit', k: 'code', q: 'Mr L has vomited twice this morning and his 0800 tablets are due.', a: 'V — Vomiting', why: 'An oral dose would not stay down — tell the prescriber; another route may be needed.' },
  { id: 'c-hr', k: 'code', q: 'The order says “withhold if HR < 60”. The apical pulse is 54.', a: 'W — Withheld', why: 'Withheld for a clinical reason: code W, the reason in the notes, and tell the RN or prescriber.' },
  { id: 'c-sbp', k: 'code', q: 'An antihypertensive says “withhold if SBP < 100”. The BP is 92/58.', a: 'W — Withheld', why: 'The systolic (92) is under 100 — withheld, documented and reported.' },
  { id: 'r-blank', k: 'mcq', q: 'The allergy box on the chart is blank. Before giving the first dose you…',
    opts: ['Ask the patient, and get it documented first', 'Take it to mean no known allergies', 'Give it and watch closely for a reaction', 'Write NKDA in the box yourself'],
    why: 'A blank box is not “no allergies” — it means nobody has asked. Allergies, or confirmation of none, must be documented, and the nurse still asks.', src: MA1 + 'slide 43' },
  { id: 'r-window', k: 'mcq', q: 'A regular medicine is charted for 0800. The latest you should give it is…', opts: ['0830', '0900', '1000', 'Any time before midday'],
    why: 'Regular medicines are given within 30 minutes of the scheduled time.', src: MA1 + 'slide 32' },
  { id: 'r-noroute', k: 'mcq', q: 'An order has the medicine, dose and frequency — but no route. You…',
    opts: ['Withhold it and contact the prescriber', 'Give it by the usual route for that medicine', 'Ask another nurse which route to use', 'Give it by mouth and document that'],
    why: 'No route documented = withhold and clarify. A nurse cannot complete or change a prescription.', src: MA1 + 'slide 36' },
  { id: 'r-hr64', k: 'mcq', q: 'Metoprolol 25 mg PO BD — “withhold if HR < 60”. The heart rate is 64. You…',
    opts: ['Give it — 64 is not under 60', 'Withhold it — 64 is too close to 60', 'Give half the dose to be safe', 'Withhold it and write W'],
    why: '< 60 means under 60. At 64 the hold parameter is not met, so the dose is given (and the obs recorded).' },
  { id: 'r-prn1800', k: 'mcq', q: 'Paracetamol 1 g PO q4h PRN, max 4 g/24 h. Doses were given at 0600, 1000 and 1400. At 1800 the patient asks for more. You can…',
    opts: ['Give 1 g — 4 hours have passed and it makes exactly 4 g', 'Not give it — the total would go over the 4 g maximum', 'Give only 500 mg, to stay safely under the maximum', 'Not give it — PRN doses are limited to two a day'],
    why: '1800 − 1400 = 4 hours, and 3 g + 1 g = 4 g: the maximum, not over it. (Check the regular section and any combination products too.)' },
  { id: 'r-prn2000', k: 'mcq', q: 'Same patient: 1 g at 0600, 1000, 1400 and 1800. At 2000 they ask again. You…',
    opts: ['Not give it — they have had the 4 g maximum in 24 hours', 'Give 1 g — a PRN dose can be given whenever they ask', 'Give 500 mg, half a dose, to be on the safe side', 'Give 1 g if their pain score is over 5 out of 10'],
    why: '4 g in 24 hours is the maximum, whatever the pain score — tell the RN or prescriber and look at other options.' },
  { id: 'r-student', k: 'mcq', q: 'As a student nurse you give a dose with your RN watching. On the chart…',
    opts: ['You sign it, and your RN adds their check initial', 'You leave it blank for your RN to sign later on', 'You sign it on your own — you gave the dose', 'You write S (for student) in the dose box'],
    why: 'The course: student nurses also need the “check” initial.', src: MA1 + 'slide 55' },
  { id: 'r-cease', k: 'mcq', q: 'An order is ruled through, dated and signed “cease”. The patient asks for it. You…',
    opts: ['Do not give it — it has been stopped', 'Give it — the doses are still in the drawer', 'Give it if they are in pain', 'Give it and tell the prescriber after'],
    why: 'Ceased means stopped. If the patient needs it, the prescriber writes a new order.' },
  { id: 'r-before', k: 'mcq', q: 'When do you sign for a dose?', opts: ['Straight after you have given it', 'When you prepare it, so you don’t forget', 'At the end of the round', 'At the end of the shift'],
    why: 'Record immediately after giving it — never before.', src: MA1 + 'slide 41' },
  { id: 'r-illeg', k: 'mcq', q: 'You cannot read the dose on an order. You…',
    opts: ['Ask the prescriber to clarify it first', 'Give the dose it looks most like', 'Ask a colleague what they think it says', 'Give the usual dose listed in the NZF'],
    why: 'Never guess — “do not try to decipher illegible writing”. Insisting on proper prescribing is a legal duty.', src: 'Med Admin (2) 2026 slide 6; Legal & Ethical slide 16' },
];

/* Spot the danger: one order, exactly ONE dangerous way of writing it (the build fails if a line has any other
   token on the danger list). tk: [text, 1 if it is the dangerous one]. d = the danger-list term it teaches. */
export const DANGERS = [
  { id: 'd-trail', tk: [['Morphine'], ['5.0 mg', 1], ['subcut'], ['4-hourly'], ['PRN']], d: 'trail',
    risk: 'The point gets missed and 5.0 is read as 50 mg — ten times the dose, of an opioid.', fix: 'Morphine 5 mg subcut 4-hourly PRN' },
  { id: 'd-naked', tk: [['Colchicine'], ['.5 mg', 1], ['PO'], ['BD']], d: 'naked',
    risk: 'Without the leading zero, .5 mg is read as 5 mg — ten times the dose.', fix: 'Colchicine 0.5 mg PO BD' },
  { id: 'd-U', tk: [['Insulin aspart'], ['10U', 1], ['subcut'], ['with meals']], d: 'U',
    risk: 'The U reads as a 0: 10U becomes 100 units of insulin.', fix: 'Insulin aspart 10 units subcut with meals' },
  { id: 'd-IU', tk: [['Heparin'], ['5000 IU', 1], ['subcut'], ['BD']], d: 'IU',
    risk: 'IU can be read as IV — or as 10 (50,000).', fix: 'Heparin 5000 units subcut BD' },
  { id: 'd-ug', tk: [['Levothyroxine'], ['100 µg', 1], ['PO'], ['mane']], d: 'ug',
    risk: 'A handwritten µ looks like an m: 100 mg — a thousand times the dose.', fix: 'Levothyroxine 100 microgram PO mane' },
  { id: 'd-cc', tk: [['Lactulose'], ['20 cc', 1], ['PO'], ['BD']], d: 'cc',
    risk: 'cc can be read as a 0 or two: 20 cc becomes 200 or 2000.', fix: 'Lactulose 20 mL PO BD' },
  { id: 'd-QD', tk: [['Amlodipine'], ['5 mg'], ['PO'], ['QD', 1]], d: 'QD',
    risk: 'QD is read as QID — four doses a day instead of one.', fix: 'Amlodipine 5 mg PO daily' },
  { id: 'd-OD', tk: [['Cilazapril'], ['2.5 mg'], ['PO'], ['OD', 1]], d: 'od',
    risk: 'OD is also Latin for the right eye — a tablet order has been read as eye drops (and eye drops as tablets).', fix: 'Cilazapril 2.5 mg PO daily' },
  { id: 'd-QOD', tk: [['Hydroxocobalamin'], ['1 mg'], ['IM'], ['QOD', 1]], d: 'QOD',
    risk: 'QOD is read as QD or QID — daily, or four times a day, instead of every second day.', fix: 'Hydroxocobalamin 1 mg IM every second day' },
  { id: 'd-SC', tk: [['Enoxaparin'], ['40 mg'], ['SC', 1], ['daily']], d: 'sc',
    risk: 'A handwritten SC can look like SL — an injection read as “under the tongue”. (Your course list writes SC, so read it — but write “subcut”.)', fix: 'Enoxaparin 40 mg subcut daily' },
  { id: 'd-SQ', tk: [['Insulin glargine'], ['20 units'], ['SQ', 1], ['nocte']], d: 'SQ',
    risk: 'The Q can be read as “5 every” or a zero — the route and the dose both go wrong.', fix: 'Insulin glargine 20 units subcut nocte' },
  { id: 'd-IN', tk: [['Mometasone'], ['2 sprays'], ['IN', 1], ['daily']], d: 'IN',
    risk: 'IN looks like IM or IV — a nasal spray read as an injection.', fix: 'Mometasone 2 sprays intranasal daily' },
  { id: 'd-OS', tk: [['Chloramphenicol 0.5%'], ['1 drop'], ['OS', 1], ['QID']], d: 'OS',
    risk: 'OS (left eye) is confused with OD (right eye) and with AS (left ear).', fix: 'Chloramphenicol 0.5% 1 drop left eye QID' },
  { id: 'd-x3d', tk: [['Amoxicillin'], ['500 mg'], ['PO'], ['TDS'], ['×3d', 1]], d: 'x3d',
    risk: 'Three days, or three doses? A course cut short, or a lot more doses than intended.', fix: 'Amoxicillin 500 mg PO TDS for 3 days' },
  { id: 'd-MS', tk: [['MSO4', 1], ['10 mg'], ['PO'], ['4-hourly'], ['PRN']], d: 'MS',
    risk: 'MSO4 (morphine sulfate) and MgSO4 (magnesium sulfate) have been swapped — never abbreviate a medicine’s name.', fix: 'Morphine sulfate 10 mg PO 4-hourly PRN' },
  { id: 'd-DC', tk: [['Hydrocortisone'], ['100 mg'], ['IV'], ['6-hourly'], ['D/C', 1]], d: 'DC',
    risk: 'D/C: stop it, or send the patient home on it? Two opposite actions.', fix: 'Hydrocortisone 100 mg IV 6-hourly — cease (dated, signed)' },
  { id: 'd-HS', tk: [['Temazepam'], ['10 mg'], ['PO'], ['HS', 1]], d: 'HS',
    risk: 'HS is “at bedtime” — and also “half-strength”.', fix: 'Temazepam 10 mg PO nocte' },
];
