/* 📈 Obs & labs — the numbers you check before you give — and 🗒 notes shorthand, the rest of the chart.
   Normal ranges are typical adult values to make a chart readable, never a trigger: every lab prints its own
   range, and the ward’s early-warning chart sets when to escalate. */
const O = { c: 'obs' };
const N = { c: 'notes' };

export const TERMS = [
  /* ── vital signs ── */
  { ...O, s: 'vital', id: 'obs', t: 'obs', m: 'Observations — the vital signs', x: 'BP, heart rate, breathing rate, oxygen saturation, temperature and level of consciousness. “4/24 obs” = every 4 hours.', cf: ['ews'] },
  { ...O, s: 'vital', id: 'bp', t: 'BP', m: 'Blood pressure (mmHg)', x: 'Systolic over diastolic, e.g. 120/80. Check it before blood-pressure medicines — many carry a hold parameter such as “withhold if SBP < 100”.', cf: ['map', 'hr'] },
  { ...O, s: 'vital', id: 'sbp', t: 'SBP', m: 'Systolic blood pressure — the top number', cf: ['dbp', 'map'] },
  { ...O, s: 'vital', id: 'dbp', t: 'DBP', m: 'Diastolic blood pressure — the bottom number', cf: ['sbp', 'map'] },
  { ...O, s: 'vital', id: 'map', t: 'MAP', m: 'Mean arterial pressure — the average pressure through one heartbeat', x: 'Mostly used in HDU and ICU, where a minimum MAP is often set (commonly 65 mmHg).', cf: ['sbp'] },
  { ...O, s: 'vital', id: 'hr', t: 'HR', a: ['P', 'pulse'], m: 'Heart rate (beats per minute)',
    x: 'Typical adult resting range 60–100. Check it before heart-rate-slowing medicines such as beta blockers.', w: 'On an obs chart, PR means pulse rate too — and PR on a medicine order means rectally.', cf: ['rr', 'bp'] },
  { ...O, s: 'vital', kd: 'term', id: 'apical', t: 'apical pulse', m: 'Heart rate counted with a stethoscope over the heart for a full minute',
    x: 'Taken before some heart medicines (e.g. digoxin) because a wrist pulse can miss beats.', cf: ['hr'] },
  { ...O, s: 'vital', id: 'rr', t: 'RR', m: 'Respiratory rate (breaths per minute)', x: 'Typical adult range 12–20. Check it before opioids and sedatives — slow, shallow breathing is the danger sign.', cf: ['hr', 'spo2'] },
  { ...O, s: 'vital', id: 'spo2', t: 'SpO₂', a: ['SpO2', 'sats'], m: 'Oxygen saturation from a pulse oximeter (%)', x: 'Read it with the oxygen the patient is on: “94% on RA” means on room air.', cf: ['fio2', 'rr'] },
  { ...O, s: 'vital', id: 'ra', t: 'RA', m: 'Room air — no added oxygen', w: 'In the notes RA also means rheumatoid arthritis.', cf: ['spo2'] },
  { ...O, s: 'vital', id: 'temp', t: 'T', a: ['Temp', 'T°'], m: 'Temperature (°C)', x: 'Checked before and after an antipyretic like paracetamol, to see if it worked.', cf: ['bp'] },
  { ...O, s: 'vital', id: 'gcs', t: 'GCS', m: 'Glasgow Coma Scale — level of consciousness, 3 to 15', x: 'Eyes, voice and movement; 15 = fully alert. A falling GCS after an opioid or sedative is an emergency.', cf: ['ews', 'sedscore'] },
  { ...O, s: 'score', id: 'ews', t: 'EWS', a: ['NEWS', 'NZEWS'], m: 'Early warning score — the vital signs added up to flag deterioration',
    x: 'NZ hospitals use a national vital-signs chart with an early warning score; a high score means escalate, and the chart says to whom.', cf: ['gcs'] },
  { ...O, s: 'score', kd: 'term', id: 'painscore', t: 'pain score', m: 'The patient’s own 0–10 rating of how much it hurts', k: 'deck', src: 'Med Admin (1) 2026 slides 32 & 41',
    x: 'Before a PRN pain medicine and again once it has had time to work — the assessment and the evaluation the course says every PRN dose needs.', cf: ['sedscore'] },
  { ...O, s: 'score', kd: 'term', id: 'sedscore', t: 'sedation score', m: 'How drowsy the patient is — checked with opioids',
    x: 'Rising sleepiness comes BEFORE the breathing slows, so it is the earlier warning sign.', cf: ['painscore', 'gcs'] },
  /* ── in and out ── */
  { ...O, s: 'io', id: 'inout', t: 'I/O', a: ['I&O', 'FB'], m: 'Intake and output — fluid balance',
    x: 'Everything in (drinks, IV, feeds) and everything out (urine, vomit, drains) — watched with diuretics and IV fluids.', w: 'FBC can mean fluid balance chart OR full blood count — read the context.', cf: ['pu', 'bo'] },
  { ...O, s: 'io', id: 'bo', t: 'BO', m: 'Bowels open', x: '“BO ×1” = one bowel motion. Checked before laxatives, and watched with opioids (they constipate).', cf: ['pu'] },
  { ...O, s: 'io', id: 'pu', t: 'PU', m: 'Passed urine', cf: ['bo'] },
  /* ── glucose ── */
  { ...O, s: 'gluc', id: 'bgl', t: 'BGL', a: ['BSL', 'CBG', 'BG'], m: 'Blood glucose level (mmol/L)', x: 'A finger-prick test — before insulin and many diabetes medicines.', cf: ['hba1c'] },
  { ...O, s: 'gluc', id: 'hba1c', t: 'HbA1c', m: 'Average blood glucose over the last 2–3 months', x: 'Reported in mmol/mol in NZ.', cf: ['bgl'] },
  { ...O, s: 'gluc', kd: 'term', id: 'hypo', t: 'hypo', m: 'Low blood glucose — under 4 mmol/L',
    x: '“4 is the floor.” Treat it by your hospital’s hypo protocol; insulin may need to be withheld and the prescriber told.', cf: ['hyper'] },
  { ...O, s: 'gluc', kd: 'term', id: 'hyper', t: 'hyper', m: 'High blood glucose', cf: ['hypo'] },
  /* ── blood tests ── */
  { ...O, s: 'lab', id: 'fbc', t: 'FBC', a: ['CBC'], m: 'Full blood count', x: 'Haemoglobin, white cells and platelets.', w: 'On some wards FBC also means fluid balance chart — read the context.', cf: ['ue', 'lft'] },
  { ...O, s: 'lab', id: 'hb', t: 'Hb', m: 'Haemoglobin — oxygen-carrying protein (g/L)', x: 'NZ reports it in g/L, e.g. 135 g/L.', cf: ['wcc', 'plt'] },
  { ...O, s: 'lab', id: 'wcc', t: 'WCC', a: ['WBC'], m: 'White cell count — raised in infection and inflammation', cf: ['hb', 'crp'] },
  { ...O, s: 'lab', id: 'plt', t: 'Plt', a: ['PLT'], m: 'Platelets — the cells that start clotting', x: 'Watched with heparin and enoxaparin: a falling count can be a reaction to heparin.', cf: ['inr', 'hb'] },
  { ...O, s: 'lab', id: 'inr', t: 'INR', m: 'How long the blood takes to clot — the warfarin test',
    x: 'International normalised ratio. Warfarin is dosed day by day against it, usually aiming for 2–3.', cf: ['aptt', 'plt'] },
  { ...O, s: 'lab', id: 'aptt', t: 'APTT', m: 'The clotting test that IV heparin is adjusted to', cf: ['inr'] },
  { ...O, s: 'lab', id: 'ue', t: 'U&E', a: ['UEC', 'renal function'], m: 'Urea and electrolytes — kidney function and salts', x: 'Sodium, potassium, urea and creatinine. Kidney function decides the dose of many medicines.', cf: ['lft', 'fbc'] },
  { ...O, s: 'lab', id: 'creat', t: 'Cr', a: ['creat'], m: 'Creatinine — a blood marker of kidney function',
    x: 'Measured in µmol/L in NZ. Creatinine rising = kidneys doing worse = medicines cleared by the kidneys build up.', cf: ['egfr'] },
  { ...O, s: 'lab', id: 'egfr', t: 'eGFR', m: 'Estimated glomerular filtration rate — how well the kidneys filter',
    x: 'Below about 60 = reduced kidney function; many doses are lowered or stopped.', cf: ['creat', 'crcl'] },
  { ...O, s: 'lab', id: 'crcl', t: 'CrCl', m: 'Creatinine clearance — kidney function worked out for drug dosing', cf: ['egfr'] },
  { ...O, s: 'lab', id: 'k', t: 'K⁺', a: ['K', 'K+', 'potassium'], m: 'Potassium',
    x: 'Typically about 3.5–5.0 mmol/L (labs vary). Checked before potassium supplements, diuretics such as furosemide, and digoxin — too high or too low both upset the heart’s rhythm.', cf: ['na', 'mag'] },
  { ...O, s: 'lab', id: 'na', t: 'Na⁺', a: ['Na', 'Na+', 'sodium'], m: 'Sodium', x: 'Typically about 135–145 mmol/L.', cf: ['k'] },
  { ...O, s: 'lab', id: 'mag', t: 'Mg²⁺', a: ['Mg', 'magnesium'], m: 'Magnesium', w: 'Capital M, small g = magnesium; small m, small g = milligram. Case matters on a chart.', cf: ['k'] },
  { ...O, s: 'lab', id: 'lft', t: 'LFTs', m: 'Liver function tests', x: 'The liver breaks most medicines down; several (paracetamol among them) are watched against LFTs.', cf: ['ue', 'fbc'] },
  { ...O, s: 'lab', id: 'crp', t: 'CRP', m: 'C-reactive protein — a marker of inflammation or infection', x: 'Tracked to see whether an infection is responding to antibiotics.', cf: ['wcc'] },
  { ...O, s: 'lab', id: 'mcs', t: 'MC&S', m: 'Microscopy, culture and sensitivity — which bug, and what kills it', x: 'e.g. a urine MC&S. Samples go off before the first antibiotic dose where possible.', cf: ['crp'] },
  { ...O, s: 'lab', kd: 'term', id: 'druglevel', t: 'drug level', m: 'A blood test of how much of a medicine is in the plasma', x: 'For medicines with a narrow therapeutic range. Timing is everything — a trough is taken just before the next dose.', cf: ['trough'] },
  { ...O, s: 'lab', id: 'ecg', t: 'ECG', m: 'Electrocardiogram — a trace of the heart’s electrical activity', cf: ['hr'] },

  /* ── history and plan ── */
  { ...N, s: 'hx', id: 'hx', t: 'Hx', m: 'History', cf: ['dx', 'tx'] },
  { ...N, s: 'hx', id: 'pmhx', t: 'PMHx', a: ['PMH'], m: 'Past medical history', cf: ['fhx', 'hpi'] },
  { ...N, s: 'hx', id: 'fhx', t: 'FHx', m: 'Family history', cf: ['pmhx'] },
  { ...N, s: 'hx', id: 'hpi', t: 'HPI', a: ['HPC'], m: 'History of the presenting illness (complaint)', cf: ['pmhx'] },
  { ...N, s: 'hx', id: 'co', t: 'c/o', m: 'Complains of', cf: ['oe'] },
  { ...N, s: 'hx', id: 'oe', t: 'O/E', m: 'On examination', cf: ['co', 'nad'] },
  { ...N, s: 'hx', id: 'nad', t: 'NAD', m: 'No abnormality detected', cf: ['oe'] },
  { ...N, s: 'hx', id: 'dx', t: 'Dx', m: 'Diagnosis', cf: ['ddx', 'tx'] },
  { ...N, s: 'hx', id: 'ddx', t: 'DDx', m: 'Differential diagnosis — what else it could be', cf: ['dx'] },
  { ...N, s: 'hx', id: 'ix', t: 'Ix', m: 'Investigations — the tests', cf: ['mx', 'tx'] },
  { ...N, s: 'hx', id: 'mx', t: 'Mx', m: 'Management — the plan', cf: ['ix', 'tx'] },
  { ...N, s: 'hx', id: 'tx', t: 'Tx', m: 'Treatment', cf: ['dx', 'mx'] },
  { ...N, s: 'hx', id: 'sx', t: 'Sx', m: 'Symptoms', cf: ['tx'] },
  { ...N, s: 'hx', id: 'rv', t: 'r/v', a: ['R/V'], m: 'Review', cf: ['fu'] },
  { ...N, s: 'hx', id: 'fu', t: 'f/u', a: ['F/U'], m: 'Follow up', cf: ['rv'] },
  { ...N, s: 'hx', id: 'query', t: '?', m: 'Query — possible, not confirmed', x: '“?UTI” = a possible urinary tract infection, not yet diagnosed.', cf: ['up'] },
  { ...N, s: 'hx', id: 'up', t: '↑', m: 'Increased / raised', cf: ['down'] },
  { ...N, s: 'hx', id: 'down', t: '↓', m: 'Decreased / lowered', cf: ['up'] },
  { ...N, s: 'hx', id: 'hash', t: '#', m: 'Fracture', x: '“#NOF” = fractured neck of femur — a hip fracture.', cf: ['query'] },
  { ...N, s: 'hx', id: 'nof', t: '#NOF', m: 'Fractured neck of femur — a hip fracture', cf: ['hash'] },
  { ...N, s: 'hx', id: 'nbm', t: 'NBM', a: ['NPO', 'nil by mouth'], m: 'Nil by mouth — nothing to eat or drink',
    x: 'e.g. before theatre (Latin nil per os). Ask which regular medicines still go with a sip of water; a dose withheld for fasting is coded F.', cf: ['adlib'] },
  { ...N, s: 'hx', id: 'pod', t: 'POD', m: 'Post-operative day', x: '“POD 2” = the second day after surgery.', cf: ['nbm'] },
  { ...N, s: 'hx', id: 'dnacpr', t: 'DNACPR', a: ['DNR', 'NFR'], m: 'Do not attempt CPR — not for resuscitation',
    x: 'A documented decision not to start CPR if the heart stops. It does NOT mean stop other treatment or medicines.', cf: ['icu'] },
  { ...N, s: 'hx', id: 'adls', t: 'ADLs', m: 'Activities of daily living — washing, dressing, eating…', cf: ['mobs'] },
  { ...N, s: 'hx', id: 'mobs', t: 'mobs', a: ['mob.'], m: 'Mobilising — walking and moving about', x: '“Mobs indep” = walks independently; “mobs with frame” = with a walking frame.', cf: ['adls'] },
  { ...N, s: 'hx', id: 'nok', t: 'NOK', m: 'Next of kin', cf: ['whanau'] },
  { ...N, s: 'hx', kd: 'term', id: 'whanau', t: 'whānau', m: 'Family — in the wide Māori sense, including extended family', cf: ['nok'] },
  { ...N, s: 'hx', id: 'pt', t: 'Pt', m: 'Patient', cf: ['nok'] },
  /* ── symptoms ── */
  { ...N, s: 'sym', id: 'sob', t: 'SOB', m: 'Short of breath', cf: ['soboe', 'nv'] },
  { ...N, s: 'sym', id: 'soboe', t: 'SOBOE', m: 'Short of breath on exertion', cf: ['sob'] },
  { ...N, s: 'sym', id: 'nv', t: 'N/V', a: ['N&V', 'N+V'], m: 'Nausea and vomiting', cf: ['sob'] },
  { ...N, s: 'sym', id: 'loc', t: 'LOC', m: 'Loss (or level) of consciousness', cf: ['gcs'] },
  { ...N, s: 'sym', id: 'overdose', t: 'OD', m: 'Overdose', w: 'On a medicine order OD means once daily — same letters, different chart.', cf: ['etoh'] },
  { ...N, s: 'sym', id: 'etoh', t: 'ETOH', a: ['EtOH'], m: 'Alcohol', x: '“ETOH use” = alcohol use — it changes how many medicines work.', cf: ['overdose'] },
  /* ── conditions you will see as the reason for a medicine ── */
  { ...N, s: 'dx', id: 'htn', t: 'HTN', m: 'Hypertension — high blood pressure', cf: ['ihd', 'hf'] },
  { ...N, s: 'dx', id: 'af', t: 'AF', m: 'Atrial fibrillation — an irregular heart rhythm', x: 'A common reason for anticoagulants such as warfarin.', cf: ['mi', 'hf'] },
  { ...N, s: 'dx', id: 'mi', t: 'MI', m: 'Myocardial infarction — a heart attack', cf: ['ihd', 'af'] },
  { ...N, s: 'dx', id: 'ihd', t: 'IHD', m: 'Ischaemic heart disease', cf: ['mi', 'hf'] },
  { ...N, s: 'dx', id: 'hf', t: 'CHF', a: ['HF', 'CCF'], m: 'Heart failure', cf: ['ihd', 'af'] },
  { ...N, s: 'dx', id: 'cva', t: 'CVA', a: ['stroke'], m: 'Cerebrovascular accident — a stroke', cf: ['tia'] },
  { ...N, s: 'dx', id: 'tia', t: 'TIA', m: 'Transient ischaemic attack — a “mini-stroke”', cf: ['cva'] },
  { ...N, s: 'dx', id: 'copd', t: 'COPD', m: 'Chronic obstructive pulmonary disease', cf: ['sob'] },
  { ...N, s: 'dx', id: 't1dm', t: 'T1DM', m: 'Type 1 diabetes — the body makes no insulin', cf: ['t2dm'] },
  { ...N, s: 'dx', id: 't2dm', t: 'T2DM', m: 'Type 2 diabetes — the body resists insulin', cf: ['t1dm'] },
  { ...N, s: 'dx', id: 'ckd', t: 'CKD', m: 'Chronic kidney disease', cf: ['aki'] },
  { ...N, s: 'dx', id: 'aki', t: 'AKI', m: 'Acute kidney injury', cf: ['ckd'] },
  { ...N, s: 'dx', id: 'uti', t: 'UTI', m: 'Urinary tract infection', cf: ['aki'] },
  { ...N, s: 'dx', id: 'dvt', t: 'DVT', m: 'Deep vein thrombosis — a clot in a deep vein, usually in the leg', cf: ['pe', 'vte'] },
  { ...N, s: 'dx', id: 'pe', t: 'PE', m: 'Pulmonary embolism — a clot in the lungs’ arteries', cf: ['dvt', 'vte'] },
  { ...N, s: 'dx', id: 'vte', t: 'VTE', m: 'Venous thromboembolism — DVT and PE together',
    x: '“VTE prophylaxis” is why so many inpatients get a daily enoxaparin injection.', cf: ['dvt', 'pe'] },
  { ...N, s: 'dx', id: 'gord', t: 'GORD', a: ['GERD'], m: 'Gastro-oesophageal reflux disease', cf: ['nv'] },
  { ...N, s: 'dx', id: 'oa', t: 'OA', m: 'Osteoarthritis', cf: ['rarth'] },
  { ...N, s: 'dx', id: 'rarth', t: 'RA', m: 'Rheumatoid arthritis', w: 'On an obs chart RA means room air.', cf: ['oa'] },
  { ...N, s: 'dx', id: 'ca', t: 'Ca', m: 'Cancer (carcinoma)', w: 'Ca is also calcium — read the context.', cf: ['mets'] },
  { ...N, s: 'dx', id: 'mets', t: 'mets', m: 'Metastases — cancer that has spread', cf: ['ca'] },
  /* ── places and people ── */
  { ...N, s: 'place', id: 'ed', t: 'ED', m: 'Emergency department', cf: ['icu', 'hdu'] },
  { ...N, s: 'place', id: 'icu', t: 'ICU', m: 'Intensive care unit', cf: ['hdu', 'ccu'] },
  { ...N, s: 'place', id: 'hdu', t: 'HDU', m: 'High dependency unit — a step below ICU', cf: ['icu'] },
  { ...N, s: 'place', id: 'ccu', t: 'CCU', m: 'Coronary care unit', cf: ['icu'] },
  { ...N, s: 'place', id: 'gp', t: 'GP', m: 'General practitioner — family doctor', cf: ['rmo'] },
  { ...N, s: 'place', id: 'rmo', t: 'RMO', m: 'Resident medical officer — a junior hospital doctor', cf: ['smo', 'ho'] },
  { ...N, s: 'place', id: 'ho', t: 'HO', m: 'House officer — a doctor in their first years', cf: ['reg', 'rmo'] },
  { ...N, s: 'place', id: 'reg', t: 'Reg', m: 'Registrar — a senior doctor in specialist training', cf: ['ho', 'smo'] },
  { ...N, s: 'place', id: 'smo', t: 'SMO', m: 'Senior medical officer — a consultant', cf: ['reg'] },
  { ...N, s: 'place', id: 'mdt', t: 'MDT', m: 'Multidisciplinary team', cf: ['sw', 'ot'] },
  { ...N, s: 'place', id: 'ot', t: 'OT', m: 'Occupational therapy (or therapist)', w: 'Some wards also write OT for operating theatre.', cf: ['sw', 'mdt'] },
  { ...N, s: 'place', id: 'sw', t: 'SW', m: 'Social worker', cf: ['ot'] },
];
