/* 🧪 Pharmacology words and 🏛 law, regulators & roles — the course’s own definitions, shortened to one line.
   Each names the deck and slide it comes from; the longer wording is in the Joan-format short answers
   (content/joan/*.js), which say the same thing in exam length. */
const P = { c: 'pharm', kd: 'term', k: 'deck' };
const L = { c: 'law', kd: 'term', k: 'deck' };
const C1 = 'Pharmacology Concepts (1) 2026, ';
const C2 = 'Pharmacology Concepts (2) 2026, ';
const PK1 = 'Pharmacokinetics (1) 2026, ';
const PK2 = 'Pharmacokinetics (2) 2026, ';
const PD = 'Pharmacodynamics 2026, ';
const EL = 'Elderly & Polypharmacy 2026, ';
const LE = 'Legal & Ethical Aspects 2026, ';
const DD = 'Drug Development & Marketing, ';

export const TERMS = [
  /* ── the basics ── */
  { ...P, s: 'basic', id: 'pharmacology', t: 'pharmacology', m: 'The study of drugs — their sources, nature, actions, effects and uses', src: C1 + 'slide 3', cf: ['toxicology', 'pharmther'] },
  { ...P, s: 'basic', id: 'pharmther', t: 'pharmacotherapeutics', m: 'Applying PK and PD to choose and give the right medicine to one patient', src: C1 + 'slides 20–25', cf: ['pharmacology'] },
  { ...P, s: 'basic', id: 'toxicology', t: 'toxicology', m: 'The study of the harmful effects of chemicals, including medicines', src: C1 + 'slides 20–25', x: 'It covers misuse, adverse effects and poisoning.', cf: ['pharmacology'] },
  { ...P, s: 'basic', id: 'generic', t: 'generic name', m: 'The official name of the active ingredient — one per medicine', src: C1 + 'slides 39–48',
    x: 'Teach patients the generic name: in Joan’s escape room, a man who knew his opioid only by its brand was given morphine twice.', cf: ['brand'] },
  { ...P, s: 'basic', id: 'brand', t: 'brand name', m: 'The company’s own name for its product — a medicine may have several', src: C1 + 'slides 39–48', cf: ['generic'] },
  { ...P, s: 'basic', id: 'bioequiv', t: 'bioequivalence', m: 'Two products put the same drug in the blood at the same rate and amount', src: C1 + 'slides 49–50',
    x: 'Why a pharmacy can swap in the funded generic for a brand.', cf: ['bioavail'] },
  { ...P, s: 'basic', id: 'excipient', t: 'excipient', m: 'An inactive ingredient in a tablet — filler, binder, colour, flavour', src: C2 + 'slides 62–63',
    x: 'e.g. the gelatine in a capsule shell — it matters to vegetarian, vegan and some religious patients.', cf: ['generic'] },
  { ...P, s: 'basic', id: 'moa', kd: 'abbr', t: 'MOA', m: 'Mechanism of action — how a medicine produces its effect', src: C2 + 'slides 5–10', cf: ['pd'] },
  { ...P, s: 'basic', id: 'otc', kd: 'abbr', t: 'OTC', m: 'Over the counter — bought without a prescription', src: C2 + 'slide 10',
    x: 'Restricted, pharmacy-only and general sale medicines are the ones commonly called OTC.', cf: ['cam'] },
  { ...P, s: 'basic', id: 'cam', kd: 'abbr', t: 'CAM', m: 'Complementary and alternative medicine', src: 'Rongoā 2026 deck, slides 2–3',
    x: 'Ask about it on admission — herbal and other remedies can interact with prescribed medicines.', cf: ['otc'] },
  { ...P, s: 'basic', id: 'rongoa', t: 'rongoā Māori', m: 'Traditional Māori healing — mirimiri, karakia and plant remedies', src: 'Rongoā 2026 deck, slides 9 & 12',
    x: 'Massage and body work, prayer, and native plant remedies. Responsibility rests with the tohunga or rongoā practitioner, not the nurse.', cf: ['cam'] },
  { ...P, s: 'basic', id: 'localfx', t: 'local effect', m: 'It acts right where the medicine is applied', src: C2 + 'slides 26–27', x: 'e.g. a cream on a rash, eye drops.', cf: ['sysfx'] },
  { ...P, s: 'basic', id: 'sysfx', t: 'systemic effect', m: 'Absorbed into the circulation and carried to where it acts', src: C2 + 'slides 26–27', x: 'e.g. a tablet swallowed for a headache.', cf: ['localfx'] },
  /* ── pharmacokinetics ── */
  { ...P, s: 'pk', id: 'pk', t: 'pharmacokinetics', a: ['PK'], m: 'What the body does to the drug', src: PK1 + 'slides 5–7', x: 'Absorption, distribution, metabolism and excretion — ADME.', cf: ['pd'] },
  { ...P, s: 'pk', id: 'adme', kd: 'abbr', t: 'ADME', m: 'Absorption, distribution, metabolism, excretion', src: PK1 + 'slides 5–7', cf: ['moa'] },
  { ...P, s: 'pk', id: 'absorption', t: 'absorption', m: 'Unchanged drug reaching the bloodstream after it is given', src: PK1 + 'slide 13', x: 'The IV route needs none — it is already in the blood.', cf: ['distribution', 'bioavail'] },
  { ...P, s: 'pk', id: 'distribution', t: 'distribution', m: 'The drug moving between the blood and the body’s tissues', src: PK1 + 'slides 5–7', cf: ['absorption', 'metabolism'] },
  { ...P, s: 'pk', id: 'metabolism', t: 'metabolism', a: ['biotransformation'], m: 'Enzymes (mostly in the liver) changing a drug into an inactive, excretable form', src: PK2 + 'slides 11–12', cf: ['excretion', 'elimination'] },
  { ...P, s: 'pk', id: 'excretion', t: 'excretion', m: 'Physically removing the drug or its waste from the body — mainly in urine', src: PK2 + 'slide 29', cf: ['metabolism', 'elimination'] },
  { ...P, s: 'pk', id: 'elimination', t: 'elimination', m: 'The body removing a drug from the blood — metabolism plus excretion', src: PK2 + 'slide 29', cf: ['excretion', 'clearance'] },
  { ...P, s: 'pk', id: 'clearance', t: 'clearance', m: 'How fast a drug is removed from the blood', src: PK2 + 'slides 29–31', x: 'Hepatic clearance (the liver) and renal clearance (the kidneys). Poor kidneys or liver = slower clearance = build-up.', cf: ['elimination'] },
  { ...P, s: 'pk', id: 'bioavail', t: 'bioavailability', m: 'How much of a dose actually reaches the bloodstream', src: PK1 + 'slide 34', x: 'IV = 100%. By mouth it is less: some is not absorbed, and the liver takes its share first.', cf: ['firstpass', 'absorption'] },
  { ...P, s: 'pk', id: 'firstpass', t: 'first-pass effect', m: 'The liver breaking down part of an oral dose before it reaches the body', src: PK1 + 'slides 35–36',
    x: 'Sublingual, transdermal, IV, IM and subcut routes avoid it.', cf: ['bioavail'] },
  { ...P, s: 'pk', id: 'dissolution', t: 'dissolution', m: 'A solid dose breaking up and dissolving so it can be absorbed', src: C2 + 'slide 61', x: 'Faster dissolution, faster absorption — liquids skip this step.', cf: ['absorption'] },
  { ...P, s: 'pk', id: 'protein', t: 'protein binding', m: 'Drug held on albumin in the plasma — only the free drug acts', src: PK1 + 'slides 37–38',
    x: 'Low albumin (e.g. a malnourished older adult) means more free drug — and more toxicity.', cf: ['distribution'] },
  { ...P, s: 'pk', id: 'bbb', t: 'blood–brain barrier', m: 'Tight vessel walls that keep many drugs out of the central nervous system', src: PK1 + 'slides 41–42', x: 'Oxygen and glucose get through; many drugs do not. A newborn’s is immature.', cf: ['protein'] },
  { ...P, s: 'pk', id: 'halflife', t: 'half-life (t½)', m: 'Time for the plasma drug level to drop to 50%', src: PK2 + 'slide 32',
    x: 'Not how long the drug lasts. After about 5 half-lives it is almost all gone.', cf: ['steady'] },
  { ...P, s: 'pk', id: 'steady', t: 'steady state', m: 'Drug going in equals drug going out — reached after about 3–5 half-lives', src: PK2 + 'slide 38', cf: ['halflife'] },
  { ...P, s: 'pk', id: 'therange', t: 'therapeutic range', a: ['therapeutic window'], m: 'The blood levels between too little to work and enough to harm', src: PK2 + 'slides 36–37; ' + PD + 'slide 32',
    x: 'A narrow one needs blood-level monitoring (TDM) — the course’s example is warfarin.', cf: ['mec', 'mtc'] },
  { ...P, s: 'pk', id: 'mec', kd: 'abbr', t: 'MEC', m: 'Minimum effective concentration — the lowest level that works', src: PD + 'slide 32', cf: ['mtc'] },
  { ...P, s: 'pk', id: 'mtc', kd: 'abbr', t: 'MTC', m: 'Minimum toxic concentration — the level where harm begins', src: PD + 'slide 32', cf: ['mec'] },
  { ...P, s: 'pk', id: 'tdm', kd: 'abbr', t: 'TDM', m: 'Therapeutic drug monitoring — blood levels to keep a medicine in range', src: PK2 + 'slides 36–37', cf: ['mec'] },
  { ...P, s: 'pk', id: 'peak', t: 'peak', m: 'The highest blood level after a dose', src: PK2 + 'slides 36–37', cf: ['trough'] },
  { ...P, s: 'pk', id: 'trough', t: 'trough', m: 'The lowest blood level — just before the next dose is due', src: PK2 + 'slides 36–37', x: 'That is why a trough level is taken right before a dose.', cf: ['peak'] },
  { ...P, s: 'pk', id: 'inducer', t: 'enzyme inducer', m: 'Speeds up metabolism, so another drug’s level falls', src: PK2 + 'slides 12 & 15', x: 'A higher dose of the other medicine may be needed. Smoking can do this.', cf: ['inhibitor'] },
  { ...P, s: 'pk', id: 'inhibitor', t: 'enzyme inhibitor', m: 'Slows metabolism, so another drug’s level rises', src: PK2 + 'slides 12 & 15', x: 'Toxicity risk.', cf: ['inducer'] },
  /* ── pharmacodynamics ── */
  { ...P, s: 'pd', id: 'pd', t: 'pharmacodynamics', a: ['PD'], m: 'What the drug does to the body', src: PD + 'slides 4–5', x: 'Where it acts, how, and what changes in the body as a result.', cf: ['pk'] },
  { ...P, s: 'pd', id: 'receptor', t: 'receptor', m: 'A protein a drug binds to, which changes what the cell does', src: PD + 'slides 18–22', cf: ['agonist'] },
  { ...P, s: 'pd', id: 'agonist', t: 'agonist', m: 'Binds to a receptor and switches it on', src: PD + 'slides 23–24', x: 'The key fits the lock and opens the door — e.g. salbutamol opening the airways.', cf: ['antagonist'] },
  { ...P, s: 'pd', id: 'antagonist', t: 'antagonist', m: 'Binds to a receptor and blocks it, with no response', src: PD + 'slides 23–24', x: 'The key fits but the door won’t open — e.g. a beta blocker.', cf: ['agonist'] },
  { ...P, s: 'pd', id: 'affinity', t: 'affinity', m: 'How strongly a drug binds to its target', src: PD + 'slides 14–16', cf: ['efficacy', 'potency'] },
  { ...P, s: 'pd', id: 'efficacy', t: 'efficacy', m: 'The biggest response a drug can produce, however high the dose', src: PD + 'slides 14–16', cf: ['potency', 'affinity'] },
  { ...P, s: 'pd', id: 'potency', t: 'potency', m: 'How much drug is needed for a given effect', src: PD + 'slides 14–16', x: 'More potent = the same effect at a lower dose.', cf: ['efficacy', 'affinity'] },
  { ...P, s: 'pd', id: 'selectivity', t: 'selectivity', m: 'How many different targets a drug binds to', src: PD + 'slides 11–13', cf: ['specificity'] },
  { ...P, s: 'pd', id: 'specificity', t: 'specificity', m: 'How many different effects a drug produces', src: PD + 'slides 11–13', cf: ['selectivity'] },
  { ...P, s: 'pd', id: 'upreg', t: 'upregulation', m: 'More receptors — the cell becomes more sensitive', src: PD + 'slide 25', x: 'e.g. rebound high blood pressure if a long-term beta blocker is stopped suddenly.', cf: ['downreg'] },
  { ...P, s: 'pd', id: 'downreg', t: 'downregulation', m: 'Fewer receptors — the cell responds less', src: PD + 'slide 25', x: 'e.g. long-term opioids: the same dose does less over time.', cf: ['upreg'] },
  { ...P, s: 'pd', id: 'tolerance', t: 'tolerance', m: 'Needing more of a drug over time for the same effect', src: PD + 'slide 25', cf: ['downreg'] },
  { ...P, s: 'pd', id: 'doseresp', t: 'dose–response', m: 'How giving more or less changes the size of the effect', src: PD + 'slide 31', cf: ['efficacy'] },
  /* ── harm and safety ── */
  { ...P, s: 'harm', id: 'adverse', t: 'adverse effect', a: ['side effect'], m: 'Harm suspected to be caused by a medicine — even one used correctly', src: PD + 'slides 43–44',
    x: 'The course’s preferred term for a side effect or adverse drug reaction. It can happen even when the medicine is used correctly.', cf: ['ade', 'mederror'] },
  { ...P, s: 'harm', id: 'ade', kd: 'abbr', t: 'ADE', m: 'Adverse drug event — harm linked to a drug, including from an error', src: PD + 'slides 43–44', cf: ['adverse', 'adr'] },
  { ...P, s: 'harm', id: 'mederror', t: 'medication error', m: 'A preventable event that may lead to wrong use or harm while the medicine is in someone’s control', src: 'Med Admin (2) 2026 slides 4–5',
    x: 'Harm from human action — most trace back to a lapse in the 8 Rights + 2 Checks. Report it at once; concealing one is misconduct.', cf: ['adverse'] },
  { ...P, s: 'harm', id: 'allergy', t: 'allergy', a: ['hypersensitivity'], m: 'An immune reaction to a substance — to a medicine, it rules that medicine out', src: 'Med Admin (1) 2026 slide 43', cf: ['anaphylaxis', 'contraind'] },
  { ...P, s: 'harm', id: 'anaphylaxis', t: 'anaphylaxis', m: 'A severe, life-threatening allergic reaction', src: 'ASCIA Action Plan for Anaphylaxis (2026)',
    x: 'Lay them flat, give adrenaline IM first, call 111. If in doubt, give the adrenaline.', cf: ['allergy'] },
  { ...P, s: 'harm', id: 'contraind', t: 'contraindication', m: 'A situation where a medicine must NOT be used because it may cause harm', src: C1 + 'slide 31 · Joan’s own exam example',
    x: 'Joan’s worked example of a short answer: “the meaning of contraindication, and give an example” — e.g. a known allergy to it.', cf: ['precaution', 'interaction'] },
  { ...P, s: 'harm', id: 'precaution', t: 'precaution', m: 'Use with extra care and monitoring — it may still be given', src: C1 + 'slide 31', x: 'e.g. reduced kidney function: a lower dose, watched closely.', cf: ['contraind'] },
  { ...P, s: 'harm', id: 'interaction', t: 'interaction', m: 'Another medicine, food, remedy or condition changes a medicine’s effect', src: C1 + 'slide 32', cf: ['contraind'] },
  { ...P, s: 'harm', id: 'teratogen', t: 'teratogen', m: 'Anything that can harm a baby developing in the womb', src: 'Lifespan 2026 slide 8', x: 'The risk is highest in the first trimester, while the organs form.', cf: ['contraind'] },
  { ...P, s: 'harm', id: 'polypharm', t: 'polypharmacy', m: 'Taking many medicines at once — usually five or more', src: EL + 'slides 34–36',
    x: 'Raises the risk of interactions, adverse effects, falls, missed doses and death.', cf: ['cascade', 'deprescribe'] },
  { ...P, s: 'harm', id: 'cascade', t: 'prescribing cascade', m: 'A drug’s side effect mistaken for a new illness — and treated with another drug', k: 'ward', src: 'named in ' + EL + 'slide 40 (definition is the tool’s)', cf: ['polypharm'] },
  { ...P, s: 'harm', id: 'deprescribe', t: 'deprescribing', m: 'Planned stopping or reducing of medicines that no longer help', k: 'ward', src: 'named in ' + EL + 'slide 43 (definition is the tool’s)', cf: ['cascade'] },
  { ...P, s: 'harm', id: 'beers', t: 'Beers Criteria', m: 'A list of medicines to avoid or use carefully in older adults', src: EL + 'slide 18', cf: ['deprescribe'] },
  { ...P, s: 'harm', id: 'placebo', t: 'placebo', m: 'A dummy treatment with no active drug', src: DD + 'slide 17', x: 'Used in trials to show what the real drug adds.', cf: ['bioequiv'] },
  { ...P, s: 'harm', id: 'teachback', t: 'teach-back', m: 'Asking the patient to explain it to you in their own words', src: 'Med Admin (2) 2026 slides 25–29',
    x: 'Step 3 (Check) of Ask, Build, Check. It tests how clearly YOU explained it, not the patient’s intelligence.', cf: ['adherence'] },
  { ...P, s: 'harm', id: 'adherence', t: 'adherence', m: 'Taking medicines the way that was agreed with the prescriber', k: 'ward', src: 'Med Admin (2) 2026 slide 46 (definition is the tool’s)', cf: ['teachback'] },

  /* ── regulators, references and reporting ── */
  { ...L, s: 'reg', id: 'medsafe', t: 'Medsafe', m: 'NZ’s medicines regulator — approves medicines as safe and of good quality', src: C1 + 'slides 36–37', cf: ['pharmac'] },
  { ...L, s: 'reg', id: 'pharmac', t: 'PHARMAC', m: 'Decides which medicines are publicly funded', src: C1 + 'slides 36–37', cf: ['medsafe'] },
  { ...L, s: 'reg', id: 'carm', kd: 'abbr', t: 'CARM', m: 'Centre for Adverse Reactions Monitoring — where NZ reports suspected reactions', src: PD + 'slide 48; ' + LE + 'slide 10',
    x: 'Health professionals, patients and whānau can all report.', cf: ['medsafe'] },
  { ...L, s: 'reg', id: 'nzf', kd: 'abbr', t: 'NZF', m: 'New Zealand Formulary — the free reference for doses and interactions', src: C2 + 'slides 18–21',
    x: 'Adult and child sections, normal doses, whether PHARMAC funds it, and an interactions checker. Check it before giving anything new to you.', cf: ['cmi', 'datasheet'] },
  { ...L, s: 'reg', id: 'cmi', kd: 'abbr', t: 'CMI', m: 'Consumer Medicine Information — the leaflet written for patients', src: C2 + 'slides 18–21', cf: ['datasheet'] },
  { ...L, s: 'reg', id: 'datasheet', t: 'data sheet', m: 'Medsafe’s detailed product information, written for health professionals', src: C2 + 'slides 18–21', cf: ['cmi'] },
  /* ── the law ── */
  { ...L, s: 'act', id: 'medact', t: 'Medicines Act 1981', m: 'The law behind the prescription, restricted, pharmacy-only and general sale classes', src: LE + 'slides 6–8', cf: ['moda'] },
  { ...L, s: 'act', id: 'moda', t: 'Misuse of Drugs Act 1975', m: 'The law that controls Class A, B and C substances', src: LE + 'slides 12–14', cf: ['medact'] },
  { ...L, s: 'act', id: 'rxmed', t: 'prescription medicine', m: 'Only supplied or given on a prescriber’s order or a standing order', src: C2 + 'slide 10', x: 'e.g. amoxicillin.', cf: ['restricted'] },
  { ...L, s: 'act', id: 'restricted', t: 'restricted medicine', a: ['pharmacist-only medicine'], m: 'Sold only by a pharmacist, who must explain it', src: C2 + 'slide 10', x: 'e.g. clotrimazole cream.', cf: ['pharmonly', 'rxmed'] },
  { ...L, s: 'act', id: 'pharmonly', t: 'pharmacy-only medicine', m: 'Sold only in a pharmacy (or a hospital)', src: C2 + 'slide 10', x: 'e.g. oxymetazoline nasal spray.', cf: ['restricted', 'gensale'] },
  { ...L, s: 'act', id: 'gensale', t: 'general sale medicine', m: 'Can be sold in any shop', src: C2 + 'slide 10', x: 'e.g. paracetamol and ibuprofen in a supermarket.', cf: ['pharmonly'] },
  { ...L, s: 'act', id: 'cd', kd: 'abbr', t: 'CD', m: 'Controlled drug — restricted by the Misuse of Drugs Act', src: LE + 'slides 12–14',
    x: 'All controlled drugs are prescribed, but not all prescribed drugs are controlled. Kept locked, counted, and signed out with a second checker.', cf: ['classb'] },
  { ...L, s: 'act', id: 'classa', t: 'Class A (controlled drug)', m: 'Very high risk of harm — never prescribed (e.g. heroin, methamphetamine)', src: LE + 'slide 14', cf: ['classb', 'classc'] },
  { ...L, s: 'act', id: 'classb', t: 'Class B (controlled drug)', m: 'High risk of harm — prescribing restricted, kept in a double-locked safe (e.g. morphine)', src: LE + 'slide 14', cf: ['classa', 'classc'] },
  { ...L, s: 'act', id: 'classc', t: 'Class C (controlled drug)', m: 'Moderate risk of harm — prescribed normally, still locked away (e.g. codeine)', src: LE + 'slide 14', cf: ['classb', 'classa'] },
  { ...L, s: 'act', id: 'standing', t: 'standing order', m: 'A prescriber’s written instruction letting others give set medicines without a prescription each time', src: 'Med Admin (1) 2026 slides 13–14',
    x: 'An RN may administer under a standing order; it names the medicines, doses and the situations it covers.', cf: ['secverbal'] },
  /* ── who can do what ── */
  { ...L, s: 'who', id: 'authpresc', t: 'authorised prescriber', m: 'Doctor, nurse practitioner, dentist, optometrist or midwife', src: 'Med Admin (1) 2026 slide 4', cf: ['despresc'] },
  { ...L, s: 'who', id: 'despresc', t: 'designated prescriber', m: 'e.g. a pharmacist or RN, with extra training, within set limits', src: 'Med Admin (1) 2026 slide 4', cf: ['authpresc'] },
  { ...L, s: 'who', id: 'nurseprac', kd: 'abbr', t: 'NP', m: 'Nurse practitioner — an authorised prescriber', src: 'Med Admin (1) 2026 slide 4', w: 'NP also means nasal prongs — read the context.', cf: ['rn'] },
  { ...L, s: 'who', id: 'rn', kd: 'abbr', t: 'RN', m: 'Registered nurse', k: 'ward', cf: ['en', 'hca'] },
  { ...L, s: 'who', id: 'en', kd: 'abbr', t: 'EN', m: 'Enrolled nurse — works under an RN’s direction', k: 'ward', cf: ['rn', 'hca'] },
  { ...L, s: 'who', id: 'hca', kd: 'abbr', t: 'HCA', m: 'Healthcare assistant — not a regulated health practitioner', src: LE + 'slides 29–31', cf: ['en'] },
  { ...L, s: 'who', id: 'hpcaa', kd: 'abbr', t: 'HPCAA', m: 'Health Practitioners Competence Assurance Act 2003 — keeps practitioners competent', src: LE + 'slides 29–31', cf: ['ncnz'] },
  { ...L, s: 'who', id: 'ncnz', kd: 'abbr', t: 'NCNZ', m: 'Nursing Council of New Zealand — registers and regulates nurses', src: LE + 'slide 90', cf: ['nzno', 'hpcaa'] },
  { ...L, s: 'who', id: 'nzno', kd: 'abbr', t: 'NZNO', m: 'New Zealand Nurses Organisation — the nurses’ union', src: LE + 'slide 90', cf: ['ncnz'] },
  { ...L, s: 'who', id: 'apc', kd: 'abbr', t: 'APC', m: 'Annual practising certificate', src: LE + 'slides 29–31', cf: ['hpcaa'] },
  { ...L, s: 'who', id: 'scope', t: 'scope of practice', m: 'What a nurse is educated, competent and authorised to do', src: LE + 'slides 7, 20 & 30–31', x: 'Prescribing and dispensing are outside an RN’s scope (unless a designated prescriber).', cf: ['hpcaa'] },
  { ...L, s: 'who', id: 'dispense', t: 'dispensing', m: 'Preparing and labelling a medicine for a patient — the pharmacist’s job', src: LE + 'slides 20 & 30–31', cf: ['scope'] },
  { ...L, s: 'who', id: 'hdec', kd: 'abbr', t: 'HDEC', m: 'Health and Disability Ethics Committees — approve a trial’s ethics', src: DD + 'slide 9', cf: ['scott'] },
  { ...L, s: 'who', id: 'scott', kd: 'abbr', t: 'SCOTT', m: 'Standing Committee on Therapeutic Trials — checks a trial’s science', src: DD + 'slide 9', cf: ['hdec'] },
];
