/* 💉 Routes and 💊 forms & release types. */
const R = { c: 'route' };
const F = { c: 'form' };
const C2 = 'Pharmacology Concepts (2) 2026, ';

export const TERMS = [
  /* ── routes: the course list first ── */
  { ...R, s: 'mouth', id: 'po', t: 'PO', a: ['po', 'p.o.'], m: 'By mouth (swallowed)', k: 'must',
    x: 'Latin per os. Enteral — absorbed from the gut, and it passes through the liver before reaching the body (the first-pass effect), which is why oral doses are often bigger than IV ones.',
    cf: ['pr', 'sl'] },
  { ...R, s: 'mouth', id: 'sl', t: 'SL', a: ['s/l'], m: 'Under the tongue (sublingual)', k: 'must',
    x: 'Dissolves under the tongue and goes straight into the blood, skipping the liver — fast. The deck’s example: GTN spray for angina.', src: 'Must Know list; ' + C2 + 'slide 31',
    cf: ['bucc', 'sc'] },
  { ...R, s: 'mouth', id: 'bucc', t: 'BUCC', a: ['buccal'], m: 'Between the cheek and gum (buccal)', k: 'deck', src: C2 + 'slide 31',
    x: 'Absorbed through the lining of the cheek. The deck’s example: nicotine gum.', cf: ['sl'] },
  { ...R, s: 'inj', id: 'sc', t: 'SC', a: ['subcut', 'S/C', 'SUBCUT', 'sc', 'subcut.'], m: 'Under the skin (subcutaneous)', g: 'subcut', k: 'must', also: ['safe'],
    x: 'Into the fatty tissue just under the dermis — e.g. insulin and enoxaparin. Slower and less reliable than IM, small volumes only.',
    w: 'The course list writes SC, so you must read it — but handwritten SC can look like SL (under the tongue). Many charting standards ask for “subcut”.',
    cf: ['sl', 'im', 'id'] },
  { ...R, s: 'inj', id: 'im', t: 'IM', a: ['i.m.'], m: 'Into a muscle (intramuscular)', k: 'must',
    x: 'Absorbed from the blood vessels running through the muscle. The deck’s examples: a Depo-Provera injection, and an adrenaline auto-injector into the thigh.', cf: ['iv', 'sc'] },
  { ...R, s: 'inj', id: 'iv', t: 'IV', a: ['i.v.'], m: 'Into a vein (intravenous)', k: 'must',
    x: 'Straight into the bloodstream: no absorption needed, 100% bioavailable, onset immediate — and very hard to take back once it is in.', cf: ['im', 'io'] },
  { ...R, s: 'inj', id: 'id', t: 'ID', a: ['intradermal'], m: 'Into the skin itself (intradermal)', k: 'deck', src: C2 + 'slide 42',
    x: 'Into the dermis, just under the epidermis. The deck’s examples: allergy antigen testing and the TB vaccine.', cf: ['sc'] },
  { ...R, s: 'spine', id: 'it', t: 'IT', a: ['intrathecal'], m: 'Into the fluid around the spinal cord (intrathecal)', k: 'deck', src: C2 + 'slide 44',
    x: 'Into the subarachnoid space, bypassing the blood–brain barrier — e.g. spinal anaesthesia. Specialists only.', cf: ['epid'] },
  { ...R, s: 'spine', id: 'epid', t: 'EPID', a: ['epidural'], m: 'Into the space outside the spinal membranes (epidural)', k: 'deck', src: C2 + 'slide 44',
    x: 'e.g. labour or post-op pain relief through a fine catheter. Not the same space as intrathecal.', cf: ['it'] },
  { ...R, s: 'inj', id: 'io', t: 'IO', m: 'Into the bone marrow (intraosseous)',
    x: 'A needle into the marrow of a bone, in an emergency when no vein can be found — anything that can go IV can go IO.', cf: ['iv'] },
  { ...R, s: 'inj', id: 'ia', t: 'IA', m: 'Into a joint (intra-articular)',
    x: 'e.g. a steroid injection into a knee. IA is also used for intra-arterial, which is why it is safer written in full.', cf: ['im'] },
  { ...R, s: 'other', id: 'pr', t: 'PR', a: ['p.r.'], m: 'Into the rectum', k: 'must',
    x: 'Latin per rectum — suppositories and enemas.',
    w: 'Same letters, different chart: on an obs chart PR means pulse rate.', cf: ['pv', 'po'] },
  { ...R, s: 'other', id: 'pv', t: 'PV', a: ['p.v.'], m: 'Into the vagina',
    x: 'Latin per vaginam — pessaries and creams. In the notes, “PV bleed” = vaginal bleeding.', cf: ['pr'] },
  { ...R, s: 'lung', id: 'inh', t: 'INH', a: ['inhal.', 'inhaled'], m: 'Breathed in from an inhaler', k: 'deck', src: C2 + 'slide 49',
    x: 'The lungs have a huge surface with capillaries right beside the alveoli, so absorption is fast. The medicine has to be a gas or a fine mist.', cf: ['neb'] },
  { ...R, s: 'lung', id: 'neb', t: 'NEB', a: ['neb', 'nebs', 'nebulised'], m: 'Breathed in as a mist from a nebuliser',
    x: 'A machine turns a liquid (from a nebule) into a mist, breathed in through a mask or mouthpiece over several minutes — e.g. in an asthma attack.', cf: ['inh'] },
  { ...R, s: 'tube', id: 'ng', t: 'NG', a: ['via NG', 'NGT'], m: 'Down a tube through the nose into the stomach',
    x: 'Nasogastric. Only liquids or medicines a pharmacist has cleared for crushing go down it, flushed before and after.', cf: ['peg', 'nj'] },
  { ...R, s: 'tube', id: 'nj', t: 'NJ', m: 'Down a tube through the nose into the small bowel',
    x: 'Nasojejunal — past the stomach into the jejunum. Check with the pharmacist: some medicines need the stomach to work.', cf: ['ng', 'peg'] },
  { ...R, s: 'tube', id: 'peg', t: 'PEG', m: 'Down a tube through the belly wall into the stomach',
    x: 'Percutaneous endoscopic gastrostomy — a long-term feeding tube. Same crushing and flushing rules as an NG tube.', cf: ['ng', 'nj'] },
  { ...R, s: 'skin', id: 'top', t: 'TOP', a: ['top.', 'topical'], m: 'Onto the skin or a mucous membrane (topical)', k: 'deck', src: C2 + 'slides 26–27',
    x: 'Creams, ointments, eye and ear drops — mostly a local effect at the site.', cf: ['td'] },
  { ...R, s: 'skin', id: 'td', t: 'TD', a: ['transdermal'], m: 'Through the skin from a patch, into the blood (transdermal)',
    x: 'A systemic effect that skips the liver. Record where and when each patch went on, and take the old one off.', cf: ['top'] },
  { ...R, s: 'group', kd: 'term', id: 'enteral', t: 'enteral', m: 'Through the gut (the GI tract)', k: 'deck', src: C2 + 'slides 26–27',
    x: 'The oral route and tube feeds (NG, PEG) are enteral. The course’s five route groups: oral (enteral), parenteral, rectal, inhalation and topical.', cf: ['parenteral'] },
  { ...R, s: 'group', kd: 'term', id: 'parenteral', t: 'parenteral', m: 'Not through the gut — usually by injection', k: 'deck', src: C2 + 'slides 26–27',
    x: 'IV, IM, subcut, intradermal, intrathecal and epidural are all parenteral.', cf: ['enteral'] },

  /* ── forms ── */
  { ...F, s: 'solid', id: 'tab', t: 'tab', a: ['tabs', 'tab.'], m: 'Tablet', k: 'deck', src: C2 + 'slides 62–63; Med Admin (1) slide 30',
    x: 'Compressed powder plus excipients (binders, fillers, disintegrators, lubricants). Only halve one that has a score line, with a tablet cutter.', cf: ['cap'] },
  { ...F, s: 'solid', id: 'cap', t: 'cap', a: ['caps'], m: 'Capsule', k: 'deck', src: C2 + 'slide 67',
    x: 'Medicine inside a gelatine shell — hard (a powder inside) or soft, a “softgel” (a liquid inside). The gelatine matters to vegetarian and some religious patients.', cf: ['tab'] },
  { ...F, s: 'solid', kd: 'term', id: 'scored', t: 'scored tablet', m: 'Has a break line — the only kind you may cut in half', k: 'deck', src: 'Med Admin (1) slide 30',
    x: 'Cut it with a tablet cutter, never a knife. And check with a pharmacist before crushing anything.', cf: ['ec'] },
  { ...F, s: 'solid', id: 'odt', t: 'ODT', a: ['wafer'], m: 'Melts on the tongue — no water needed',
    x: 'Orally disintegrating tablet. Handy for someone who is nauseated or cannot swallow tablets.', cf: ['disp', 'eff'] },
  { ...F, s: 'solid', id: 'disp', t: 'disp', a: ['dispersible'], m: 'Dispersible — stir into water first', cf: ['eff', 'odt'] },
  { ...F, s: 'solid', id: 'eff', t: 'eff', a: ['effervescent'], m: 'Effervescent — fizzes as it dissolves in water', cf: ['disp'] },
  { ...F, s: 'solid', id: 'loz', t: 'loz', a: ['lozenge'], m: 'Lozenge — dissolved slowly in the mouth', cf: ['odt'] },
  { ...F, s: 'liquid', id: 'susp', t: 'susp', m: 'Suspension — particles floating in liquid; shake it first', k: 'deck', src: C2 + 'slide 61',
    x: 'The drug does not dissolve — shake well before measuring or the dose will be wrong.', cf: ['soln', 'syr'] },
  { ...F, s: 'liquid', id: 'soln', t: 'soln', a: ['sol.'], m: 'Solution — drug fully dissolved in a liquid', cf: ['susp'] },
  { ...F, s: 'liquid', id: 'syr', t: 'syr', m: 'Syrup — a sweet, thick liquid', k: 'deck', src: C2 + 'slide 61', cf: ['elix', 'susp'] },
  { ...F, s: 'liquid', id: 'elix', t: 'elix', m: 'Elixir — a sweetened liquid containing alcohol', k: 'deck', src: C2 + 'slide 61',
    x: 'Fastest to absorb → slowest: elixirs and syrups → suspensions → powders → capsules → tablets → coated tablets. Liquids have nothing to break down first.', cf: ['syr'] },
  { ...F, s: 'liquid', id: 'mixt', t: 'mixt', a: ['mixture', 'liq', 'oral liquid'], m: 'Mixture — a liquid medicine to swallow', cf: ['soln'] },
  { ...F, s: 'other', id: 'supp', t: 'supp', m: 'Suppository — inserted into the rectum', cf: ['pess'] },
  { ...F, s: 'other', id: 'pess', t: 'pess', m: 'Pessary — inserted into the vagina', cf: ['supp'] },
  { ...F, s: 'other', id: 'oint', t: 'oint', a: ['ung'], m: 'Ointment — a greasy preparation', x: 'Greasier than a cream: stays on the skin longer. Eye ointments are common too.', cf: ['gtt'] },
  { ...F, s: 'other', id: 'gtt', t: 'gtt', a: ['gtts', 'gutt.'], m: 'Drops', k: 'deck', src: 'Medication Calculations 2026 slide 68 (gtt/mL, gtt/min)',
    x: 'Latin guttae. Eye drops were written “gutt.” on older charts; in drip-rate maths, gtt/min = drops per minute.', cf: ['oint'] },
  { ...F, s: 'inj', id: 'inj', t: 'inj', a: ['inj.'], m: 'Injection', cf: ['amp'] },
  { ...F, s: 'inj', id: 'amp', t: 'amp', a: ['ampoule', 'ampule'], m: 'Ampoule — a sealed, single-use glass container', cf: ['vial'] },
  { ...F, s: 'inj', kd: 'term', id: 'vial', t: 'vial', m: 'A rubber-topped bottle for injection — single or multi-dose', cf: ['amp'] },
  { ...F, s: 'inj', id: 'pfs', t: 'PFS', m: 'Prefilled syringe', x: 'Ready to give — e.g. enoxaparin comes this way.', cf: ['amp'] },
  { ...F, s: 'inj', kd: 'term', id: 'depot', t: 'depot', m: 'A long-acting injection that releases over weeks', k: 'deck', src: C2 + 'slides 38–41',
    x: 'Usually IM. The deck’s example: Depo-Provera, contraception for 13 weeks.', cf: ['la'] },
  { ...F, s: 'lung', id: 'mdi', t: 'MDI', a: ['pMDI', 'puffer'], m: 'Metered-dose inhaler — a “puffer”',
    x: 'A pressurised canister that sprays a measured dose each puff — works best through a spacer.', cf: ['dpi'] },
  { ...F, s: 'lung', id: 'dpi', t: 'DPI', m: 'Dry-powder inhaler', x: 'Breath-activated: the patient breathes the powder in fast and deep. No spacer.', cf: ['mdi'] },
  { ...F, s: 'lung', kd: 'term', id: 'spacer', t: 'spacer', m: 'A chamber fitted to a puffer so more of the dose reaches the lungs', cf: ['nebule'] },
  { ...F, s: 'lung', kd: 'term', id: 'nebule', t: 'nebule', m: 'A single-dose plastic ampoule of liquid, to be turned into a mist', cf: ['spacer'] },
  /* release: SR / MR / CR / XR all mean “slow” — never offered against each other (g: 'slow') */
  { ...F, s: 'release', id: 'ir', t: 'IR', m: 'Immediate release — the whole dose at once',
    x: 'The opposite of SR/MR. Some medicines come in both, so the chart must say which — an IR dose given as MR (or the reverse) is a real error.', cf: ['sr', 'ec'] },
  { ...F, s: 'release', id: 'sr', t: 'SR', m: 'Slow (sustained) release', g: 'slow',
    x: 'Releases the dose over many hours, so it can be given less often.', w: 'Never crush or chew: the whole dose comes out at once.', cf: ['ir', 'ec'] },
  { ...F, s: 'release', id: 'mr', t: 'MR', m: 'Modified release', g: 'slow',
    x: 'The umbrella term for a tablet built to release slowly or late.', w: 'Never crush or chew.', cf: ['ir', 'ec'] },
  { ...F, s: 'release', id: 'cr', t: 'CR', m: 'Controlled release', g: 'slow', w: 'Never crush or chew.', cf: ['ir', 'ec'] },
  { ...F, s: 'release', id: 'xr', t: 'XR', a: ['ER', 'XL'], m: 'Extended release', g: 'slow', w: 'Never crush or chew.', cf: ['ir', 'ec'] },
  { ...F, s: 'release', id: 'la', t: 'LA', m: 'Long-acting', g: 'slow',
    x: 'A long-acting tablet or injection. Careful: in the notes LA usually means local anaesthetic.', cf: ['ir', 'depot'] },
  { ...F, s: 'release', id: 'ec', t: 'EC', m: 'Enteric coated — dissolves in the intestine, not the stomach', k: 'deck', src: C2 + 'slide 66',
    x: 'The coating protects the drug from stomach acid, protects the stomach from the drug, or delays the action.', w: 'Never crush: it destroys the coating.', cf: ['sr', 'ir'] },
];
