/* ⚠️ The danger list, and 🩸 IV, lines, tubes & oxygen.
   Danger list: the abbreviations on the international error-prone list (ISMP), which is what most hospital
   “do not use” lists are built from. The NZ National Medication Chart user guide carries its own “do not use”
   appendix — your hospital’s list is the one that binds you. m = what the writer meant; w = how it goes wrong. */
const S = { c: 'safe', k: 'safe' };
const V = { c: 'iv' };

export const TERMS = [
  { ...S, s: 'unit', id: 'U', t: 'U', m: 'Units', g: 'units', w: 'Read as a 0 or a 4: “10U” has been given as 100 units. Write “units”.', cf: ['IU', 'ug'] },
  { ...S, s: 'unit', id: 'IU', t: 'IU', m: 'International units', g: 'units', w: 'Read as IV, or as 10. Write “units”.', cf: ['U', 'cc'] },
  { ...S, s: 'unit', id: 'ug', t: 'µg', a: ['ug'], m: 'Microgram', g: 'mcg', w: 'A handwritten µ looks like an m — the dose becomes 1000 times bigger. Write “microgram” or “mcg”.', cf: ['U', 'cc'] },
  { ...S, s: 'unit', id: 'cc', t: 'cc', m: 'Millilitre (cubic centimetre)', g: 'ml', w: 'Read as “u” or as 00. Write “mL”.', cf: ['ug', 'U'] },
  { ...S, s: 'num', kd: 'term', id: 'trail', t: 'trailing zero', m: 'A zero after a decimal point — “5.0 mg” can be read as 50 mg', k: 'deck', src: 'Med Admin (2) 2026 slide 6 (“check the decimal point — is it 0.1, 1.0 or 10?”)',
    w: 'The point gets missed on a smudged or faxed chart: a ten-fold overdose. Write “5 mg”.', cf: ['naked'] },
  { ...S, s: 'num', kd: 'term', id: 'naked', t: 'naked decimal', m: 'No zero before a decimal point — “.5 mg” can be read as 5 mg', k: 'deck', src: 'Med Admin (2) 2026 slide 6',
    w: 'Ten times the dose if the point is missed. Always put a leading zero: “0.5 mg”.', cf: ['trail'] },
  { ...S, s: 'freq', id: 'QD', t: 'QD', a: ['q.d.'], m: 'Every day (American)', g: 'once', w: 'Read as QID — four times a day. Write “daily”.', cf: ['QOD'] },
  { ...S, s: 'freq', id: 'QOD', t: 'QOD', a: ['q.o.d.'], m: 'Every other day (American)', g: 'altday', w: 'Read as QD or QID. Write “every second day”.', cf: ['QD'] },
  { ...S, s: 'freq', id: 'HS', t: 'HS', a: ['hs'], m: 'At bedtime — or half-strength', w: 'Two opposite meanings. Write “at night” (or nocte), or “half-strength”.', cf: ['DC'] },
  { ...S, s: 'route', id: 'SQ', t: 'SQ', a: ['sub q'], m: 'Subcutaneous (American)', g: 'subcut', w: 'The Q can be read as “5 every” or as a zero. Write “subcut”.', cf: ['IN'] },
  { ...S, s: 'route', id: 'IN', t: 'IN', m: 'Intranasal — into the nose', w: 'Looks like IM or IV. Write “intranasal”.', cf: ['SQ'] },
  { ...S, s: 'eye', id: 'OS', t: 'OS', m: 'Left eye', w: 'OD, OS and OU (eyes) get mixed up with each other and with AD, AS and AU (ears). Write “left eye”.', cf: ['OU', 'AS'] },
  { ...S, s: 'eye', id: 'OU', t: 'OU', m: 'Both eyes', w: 'Write “both eyes”.', cf: ['OS', 'AU'] },
  { ...S, s: 'eye', id: 'AD', t: 'AD', m: 'Right ear', w: 'Confused with OD (right eye). Write “right ear”.', cf: ['AS', 'AU'] },
  { ...S, s: 'eye', id: 'AS', t: 'AS', m: 'Left ear', w: 'Confused with OS (left eye). Write “left ear”.', cf: ['AD', 'OS'] },
  { ...S, s: 'eye', id: 'AU', t: 'AU', m: 'Both ears', w: 'Confused with OU (both eyes). Write “both ears”.', cf: ['OU', 'AD'] },
  { ...S, s: 'other', id: 'DC', t: 'D/C', m: 'Discontinue — or discharge', w: 'Two different meanings: stop the medicine, or send the patient home with it? Write “cease” or “discharge”.', cf: ['HS'] },
  { ...S, s: 'other', id: 'x3d', t: '×3d', m: 'For three days — or three doses', w: 'Ambiguous. Write “for 3 days”.', cf: ['DC'] },
  { ...S, s: 'sym', id: 'gt', t: '>', m: 'More than', w: 'Easily reversed with <. Read it slowly — writing “more than” in words is safer.', cf: ['lt'] },
  { ...S, s: 'sym', id: 'lt', t: '<', m: 'Less than', w: 'Easily reversed with >. On hold parameters (“withhold if HR < 60”) read it twice.', cf: ['gt'] },
  { ...S, s: 'sym', id: 'at', t: '@', m: 'At', w: 'Read as a 2. Write “at”.', cf: ['gt'] },
  { ...S, s: 'drug', id: 'MS', t: 'MS', a: ['MSO4', 'MgSO4'], m: 'Morphine sulfate — or magnesium sulfate', w: 'MS/MSO4 (morphine) and MgSO4 (magnesium) have been swapped, fatally. Never abbreviate a medicine’s name.', cf: ['DC'] },
  { ...S, s: 'drug', kd: 'term', id: 'tallman', t: 'Tall Man lettering', m: 'Capitals that tell look-alike names apart (predniSONE / prednisoLONE)',
    x: 'Used on labels, shelves and screens to stop look-alike names being picked by mistake.', cf: ['lasa'] },
  { ...S, s: 'drug', id: 'lasa', t: 'LASA', m: 'Look-alike, sound-alike medicines', x: 'Names or packs easily mistaken for each other — read the label at every one of the three checks.', cf: ['tallman'] },
  { ...S, s: 'drug', kd: 'term', id: 'illegible', t: 'illegible order', m: 'Never guess it — ask the prescriber to clarify', k: 'deck', src: 'Med Admin (2) 2026 slide 6; Legal & Ethical slide 16',
    x: '“Incorrectly deciphering handwriting” is one of the course’s examples of a medication error — and insisting on proper prescribing is a legal duty.', cf: ['lasa'] },
  { ...S, s: 'hi', kd: 'term', id: 'highalert', t: 'high-alert medicine', m: 'One where an error is more likely to cause serious harm',
    x: 'Remember A PINCH: Anti-infectives, Potassium (and other concentrated electrolytes), Insulin, Narcotics (opioids) and sedatives, Chemotherapy, Heparin (and other anticoagulants).', cf: ['lasa'] },
  /* A PINCH, letter by letter (a memory aid used in NZ and Australian hospitals) */
  { ...S, s: 'pinch', id: 'pA', t: 'A PINCH: A', m: 'Anti-infectives (antimicrobials)', k: 'ward', cf: ['pP', 'pI'] },
  { ...S, s: 'pinch', id: 'pP', t: 'A PINCH: P', m: 'Potassium and other concentrated electrolytes', k: 'ward', cf: ['pA', 'pH'] },
  { ...S, s: 'pinch', id: 'pI', t: 'A PINCH: I', m: 'Insulin', k: 'ward', cf: ['pH', 'pN'] },
  { ...S, s: 'pinch', id: 'pN', t: 'A PINCH: N', m: 'Narcotics (opioids) and sedatives', k: 'ward', cf: ['pC', 'pI'] },
  { ...S, s: 'pinch', id: 'pC', t: 'A PINCH: C', m: 'Chemotherapy (cytotoxic) medicines', k: 'ward', cf: ['pN', 'pA'] },
  { ...S, s: 'pinch', id: 'pH', t: 'A PINCH: H', m: 'Heparin and other anticoagulants', k: 'ward', cf: ['pP', 'pI'] },

  /* ── IV lines and devices ── */
  { ...V, s: 'line', id: 'pivc', t: 'PIVC', a: ['PIV', 'cannula', 'luer'], m: 'Peripheral IV cannula — a short plastic tube in a hand or arm vein',
    x: 'Nurses often just say “a luer”. Check the site every shift (VIP score) and note the date it went in — policy sets when it must be reviewed or replaced. Some wards write IVC, which is also the inferior vena cava.', cf: ['cvc', 'picc'] },
  { ...V, s: 'line', id: 'cvc', t: 'CVC', a: ['CVL', 'central line'], m: 'Central venous catheter — its tip sits in a big vein near the heart',
    x: 'Put in through the neck, chest or groin; used for irritant drugs, long courses and blood tests. Higher infection risk — strict aseptic care.', cf: ['picc', 'pivc'] },
  { ...V, s: 'line', id: 'picc', t: 'PICC', m: 'A central line put in through an arm vein',
    x: 'Peripherally inserted central catheter: it goes in at the arm but ends near the heart, and can stay for weeks to months.', cf: ['cvc', 'port'] },
  { ...V, s: 'line', kd: 'term', id: 'port', t: 'port', a: ['portacath', 'Port-a-Cath'], m: 'A reservoir implanted under the skin, joined to a central vein',
    x: 'Accessed with a special non-coring needle through the skin; common for chemotherapy.', cf: ['picc'] },
  { ...V, s: 'give', id: 'ivi', t: 'IVI', m: 'IV infusion — run in steadily over time', x: 'e.g. “IVI 125 mL/h”. Fluids and infusions have their own section of the chart.', cf: ['bolus'] },
  { ...V, s: 'give', id: 'bolus', t: 'IV bolus', a: ['IV push', 'slow IV'], m: 'A dose pushed into the line from a syringe',
    x: 'Given over the time the medicine’s guidance says (often minutes, not seconds). A “fluid bolus” is a quick volume of IV fluid given fast.', cf: ['ivi'] },
  { ...V, s: 'give', id: 'kvo', t: 'KVO', a: ['TKVO'], m: 'Keep vein open — a slow rate just to stop the line blocking', x: 'The order or policy sets the rate.', cf: ['ivi'] },
  { ...V, s: 'give', kd: 'term', id: 'flush', t: 'flush', m: 'A small push of sodium chloride 0.9% to clear or check a line',
    x: 'Before and after IV medicines: it checks the line works and clears the drug through.', cf: ['bolus'] },
  { ...V, s: 'kit', kd: 'term', id: 'givingset', t: 'giving set', m: 'The tubing from the bag to the patient — it fixes the drop factor', k: 'deck', src: 'Medication Calculations 2026 slide 68', cf: ['burette'] },
  { ...V, s: 'kit', kd: 'term', id: 'burette', t: 'burette', m: 'A small measuring chamber in the line, for small exact volumes',
    x: 'Usually on a 60 drops/mL (micro-drip) set — common for children.', cf: ['givingset'] },
  { ...V, s: 'kit', kd: 'term', id: 'pump', t: 'infusion pump', m: 'A machine that runs an IV at a set mL/h', cf: ['sdriver'] },
  { ...V, s: 'kit', kd: 'term', id: 'sdriver', t: 'syringe driver', m: 'A small battery pump that gives medicine steadily over 24 hours — often subcut, in palliative care',
    x: 'Gives medicines continuously over 24 hours, e.g. for pain and nausea at the end of life.', cf: ['pump', 'pca'] },
  { ...V, s: 'kit', id: 'pca', t: 'PCA', m: 'Patient-controlled analgesia — the patient presses for a set opioid dose',
    x: 'Has its own chart: the dose, the lockout time and an hourly limit. Only the patient presses the button.', cf: ['sdriver'] },
  { ...V, s: 'site', kd: 'term', id: 'phleb', t: 'phlebitis', m: 'Inflammation of the vein at a cannula site', x: 'Redness, pain and heat along the vein.', cf: ['infil'] },
  { ...V, s: 'site', kd: 'term', id: 'infil', t: 'infiltration', m: 'A non-irritant IV fluid leaking into the tissue around the vein', x: 'Swelling, coolness and pain at the site — stop it and re-site.', cf: ['extrav'] },
  { ...V, s: 'site', kd: 'term', id: 'extrav', t: 'extravasation', m: 'An irritant drug leaking out of the vein into the tissue', x: 'Can blister and kill tissue — stop the infusion and follow policy.', cf: ['infil'] },
  { ...V, s: 'site', id: 'vip', t: 'VIP', m: 'A 0–5 rating of a cannula site for phlebitis', x: 'Visual Infusion Phlebitis score — checked every shift; a rising score means act on it.', cf: ['phleb'] },
  /* ── IV fluids ── */
  { ...V, s: 'fluid', id: 'nacl', t: 'NaCl 0.9%', a: ['normal saline', 'NS', 'N/S', 'sodium chloride 0.9%'], m: 'Sodium chloride 0.9% — “normal saline”, the basic IV fluid', k: 'deck', src: 'Medication Calculations 2026 slides 70–74',
    x: 'An isotonic crystalloid: 0.9 g of salt in every 100 mL. Charts should use the full name.', cf: ['hartmanns', 'gluc5'] },
  { ...V, s: 'fluid', id: 'hartmanns', t: 'Hartmann’s', a: ['CSL', 'compound sodium lactate'], m: 'Compound sodium lactate — a balanced IV fluid', cf: ['nacl'] },
  { ...V, s: 'fluid', id: 'gluc5', t: 'glucose 5%', a: ['dextrose 5%', 'D5W'], m: '5 g of sugar in every 100 mL — an IV fluid', k: 'deck', src: 'Medication Calculations 2026 slides 72 & 102 (“Dextrose 5%”)',
    x: 'Once the glucose is used, it behaves like plain water. In a drip-rate question the 5% is a red herring.', cf: ['nacl'] },
  { ...V, s: 'fluid', kd: 'term', id: 'crystal', t: 'crystalloid', m: 'An IV fluid of water with dissolved salts or sugar', x: 'e.g. sodium chloride 0.9%, Hartmann’s, glucose 5%.', cf: ['colloid'] },
  { ...V, s: 'fluid', kd: 'term', id: 'colloid', t: 'colloid', m: 'An IV fluid with large molecules that stay in the blood vessels', x: 'e.g. albumin.', cf: ['crystal'] },
  { ...V, s: 'fluid', id: 'kcl', t: 'KCl', m: 'Potassium chloride',
    x: 'Dosed in mmol. A high-alert medicine (the P in A PINCH).', w: 'Concentrated potassium is never pushed IV — only diluted and run at a controlled rate, exactly as prescribed.', cf: ['nacl'] },
  { ...V, s: 'fluid', id: 'tpn', t: 'TPN', a: ['PN'], m: 'Total parenteral nutrition — all of a person’s nutrition given IV',
    x: 'Through a central line, with its own chart and close glucose checks.', cf: ['peg'] },
  /* ── tubes ── */
  { ...V, s: 'tube', id: 'idc', t: 'IDC', a: ['IUC', 'catheter'], m: 'Indwelling urinary catheter', x: 'A tube through the urethra into the bladder, held by a balloon; urine drains to a bag.', cf: ['spc'] },
  { ...V, s: 'tube', id: 'spc', t: 'SPC', m: 'Suprapubic catheter — into the bladder through the lower belly', cf: ['idc'] },
  { ...V, s: 'tube', id: 'ett', t: 'ETT', m: 'Endotracheal tube — a breathing tube in the windpipe', cf: ['ng'] },
  /* ── oxygen ── */
  { ...V, s: 'o2', id: 'np', t: 'NP', a: ['nasal prongs', 'NC', 'nasal cannula'], m: 'Nasal prongs — oxygen through two short tubes in the nostrils',
    x: 'Low flows, usually up to about 4 L/min.', w: 'NP also means nurse practitioner — read the context.', cf: ['hm', 'hfnp'] },
  { ...V, s: 'o2', id: 'hm', t: 'HM', a: ['Hudson mask', 'simple face mask'], m: 'Hudson mask — a simple oxygen face mask',
    x: 'Usually 5–10 L/min: below 5 L/min the patient can rebreathe their own carbon dioxide.', cf: ['nrb', 'np'] },
  { ...V, s: 'o2', id: 'nrb', t: 'NRB', m: 'Non-rebreather mask — high-concentration oxygen with a reservoir bag',
    x: 'Run at 10–15 L/min with the bag kept inflated — for a very unwell patient.', cf: ['hm'] },
  { ...V, s: 'o2', id: 'hfnp', t: 'HFNP', a: ['high-flow', 'Optiflow', 'HFNC'], m: 'High-flow nasal prongs — warm, humidified oxygen at high flow',
    x: 'Far higher flows than ordinary prongs, with special equipment and closer monitoring. (Optiflow is made in NZ, by Fisher & Paykel.)', cf: ['np'] },
  { ...V, s: 'o2', id: 'lmin', t: 'L/min', m: 'Litres per minute — an oxygen flow rate', cf: ['fio2'] },
  { ...V, s: 'o2', id: 'fio2', t: 'FiO₂', a: ['FiO2'], m: 'The fraction of oxygen in the air breathed in', x: 'Room air is 21% (FiO₂ 0.21).', cf: ['lmin'] },
  { ...V, s: 'o2', kd: 'term', id: 'targetsat', t: 'target SpO₂', a: ['target sats'], m: 'The saturation range an oxygen order aims for',
    x: 'Commonly 92–96%, or 88–92% for people at risk of retaining carbon dioxide (e.g. some with COPD). The range on the chart is the one that counts.', cf: ['fio2'] },
];
