/* ⚖️ Doses, units & rates, and 📋 the chart itself — its sections, the not-given codes and the charting rules. */
const U = { c: 'unit' };
const H = { c: 'chart' };
const CALC = 'Medication Calculations 2026, ';
const MA1 = 'Med Admin (1) 2026, ';

export const TERMS = [
  /* ── mass ── */
  { ...U, s: 'mass', id: 'mg', t: 'mg', m: 'Milligram — a thousandth of a gram', k: 'deck', src: CALC + 'slides 19–26',
    x: '1 g = 1000 mg. The course checklist: are the units the same? If not, convert before the formula.', cf: ['mcg', 'g'] },
  { ...U, s: 'mass', id: 'mcg', t: 'mcg', a: ['microgram', 'micrograms'], m: 'Microgram — a thousandth of a milligram', g: 'mcg', k: 'deck', src: CALC + 'slides 23–24',
    x: '1 mg = 1000 mcg. The deck’s example: digoxin 0.25 mg = 250 mcg, so 62.5 mcg tablets × 4.',
    w: 'Never write µg — a handwritten µ looks like an m, and the dose becomes 1000 times bigger.', cf: ['mg'] },
  { ...U, s: 'mass', id: 'g', t: 'g', a: ['gram', 'grams'], m: 'Gram — 1000 milligrams', k: 'deck', src: CALC + 'slides 25–26',
    x: 'Paracetamol 1 g = 1000 mg = two 500 mg tablets (the deck’s example).', cf: ['mg', 'kg'] },
  { ...U, s: 'mass', id: 'kg', t: 'kg', m: 'Kilogram — 1000 grams', x: 'Body weight in kg drives every per-kg dose, so the weight on the chart has to be a real one.', cf: ['g'] },
  /* ── volume ── */
  { ...U, s: 'vol', id: 'ml', t: 'mL', a: ['ml'], m: 'Millilitre — a thousandth of a litre', g: 'ml',
    x: 'Liquids and injections are measured in mL. Write mL, never cc.', cf: ['l'] },
  { ...U, s: 'vol', id: 'l', t: 'L', a: ['litre'], m: 'Litre — 1000 mL', k: 'deck', src: CALC + 'slides 73–74',
    x: 'The drip-rate formula needs mL, so convert first: 1 L = 1000 mL (the deck’s example).', cf: ['ml'] },
  /* ── other units ── */
  { ...U, s: 'other', id: 'mmol', t: 'mmol', m: 'Millimole — how electrolytes like potassium are dosed',
    x: 'e.g. potassium chloride is charted in mmol. Blood results come back in mmol/L (potassium 4.1 mmol/L, glucose 6.5 mmol/L).', cf: ['units'] },
  { ...U, s: 'other', id: 'units', t: 'units', m: 'The dose measure for insulin and heparin', g: 'units',
    x: 'Always written out in full.', w: 'Never “U” or “IU”: U can be read as 0 or 4, IU as IV or 10.', cf: ['mmol'] },
  /* ── per-weight and rates ── */
  { ...U, s: 'rate', id: 'mgkg', t: 'mg/kg', m: 'Milligrams for every kilogram of body weight', k: 'deck', src: CALC + 'slides 39–40',
    x: 'Read “/” as “per”. Dose = mg/kg × weight: the deck’s example, 10 mg/kg × 30 kg = 300 mg.', cf: ['mgkgday'] },
  { ...U, s: 'rate', id: 'mgkgday', t: 'mg/kg/day', m: 'The whole day’s dose per kg — then split into doses', k: 'deck', src: CALC + 'slides 48–49',
    x: 'Three steps: day’s dose, then single dose, then tablets. The deck’s example: 40 kg × 1 mg/kg/day = 40 mg a day; in 2 doses = 20 mg each; 5 mg tablets → 4 tablets.', cf: ['mgkg'] },
  { ...U, s: 'rate', id: 'mlh', t: 'mL/h', a: ['mL/hr', 'ml/hr'], m: 'Millilitres per hour — the rate an infusion pump is set to', k: 'deck', src: 'Medication Calculation Student Guide 2026 (Topics Covered)',
    x: 'Pumps run in mL/h. The Student Guide lists IV flow rate (mL/hr) as examinable, but the 2026 deck only teaches drops per minute — ask your kaiako.', cf: ['gttmin'] },
  { ...U, s: 'rate', id: 'gttmin', t: 'drops/min', a: ['gtt/min'], m: 'Drip rate — how fast the drip is set to run', k: 'deck', src: CALC + 'slides 66–69',
    x: 'Drops/min = (volume in mL × drop factor) ÷ (hours × 60). Do the top and the bottom first, then divide. Round it: .5 and above up, .4 and below down.', cf: ['gttml', 'mlh'] },
  { ...U, s: 'rate', id: 'gttml', t: 'drops/mL', a: ['gtt/mL'], m: 'Drop factor — the size of each drop, fixed by the giving set', k: 'deck', src: CALC + 'slide 68',
    x: 'Fixed by the type of giving set, and always given to you — the course’s examples use 20 and 60 drops/mL. You never calculate it.', cf: ['gttmin'] },
  /* ── strengths ── */
  { ...U, s: 'strength', id: 'pct', t: '%', a: ['% w/v'], m: 'Grams in every 100 mL',
    x: 'Glucose 5% = 5 g in every 100 mL; sodium chloride 0.9% = 0.9 g in every 100 mL. In a drip-rate question the % is a red herring.', cf: ['r1000'] },
  { ...U, s: 'strength', id: 'r1000', t: '1:1000', m: '1 mg in every 1 mL', k: 'deck', src: CALC + 'slides 57–63',
    x: 'Literally 1 g in 1000 mL = 1000 mg in 1000 mL = 1 mg/mL. The strength of adrenaline given IM for anaphylaxis.', cf: ['r10000', 'pct'] },
  { ...U, s: 'strength', id: 'r10000', t: '1:10 000', a: ['1:10,000', '1:10000'], m: '1 mg in every 10 mL (0.1 mg/mL)',
    x: 'Ten times weaker than 1:1000 — the adrenaline strength used IV in a cardiac arrest. Mixing the two up is a classic, sometimes fatal, error.', cf: ['r1000'] },
  /* ── calculation words (the course’s formula) ── */
  { ...U, s: 'calc', kd: 'term', id: 'stock', t: 'stock strength', m: 'What you have GOT — the medicine on hand, e.g. 500 mg per tablet', k: 'deck', src: CALC + 'slides 15–18',
    x: 'The course formula: (what you WANT ÷ what you have GOT) × VOLUME. Want = prescribed/charted; got = stock; volume = what the stock comes in (1 tablet, 5 mL).', cf: ['redherring'] },
  { ...U, s: 'calc', kd: 'term', id: 'redherring', t: 'red herring', m: 'A number in the question that plays no part in the sum', k: 'deck', src: CALC + 'slide 102',
    x: 'The deck’s two examples: the % of an IV fluid when you want a drip rate, and “tds” when you want one single dose.', cf: ['stock'] },
  { ...U, s: 'calc', kd: 'term', id: 'divided', t: 'divided doses', m: 'The day’s total split into equal parts', k: 'deck', src: CALC + 'slides 48–49', cf: ['mgkgday'] },
  { ...U, s: 'calc', id: 'bsa', t: 'BSA', m: 'Body surface area (m²) — used for some doses', k: 'deck', src: MA1 + 'slide 51',
    x: 'Worked out from height and weight; used for chemotherapy and some children’s doses. The chart records it when it matters.', cf: ['wt'] },

  /* ── the chart: who and what ── */
  { ...H, s: 'id', id: 'nmc', t: 'NMC', m: 'National Medication Chart — NZ’s standard hospital medicine chart', k: 'deck', src: MA1 + 'slides 51–55',
    x: 'Published by the Health Quality & Safety Commission. Some hospitals chart electronically instead; the same rules apply.', cf: ['emar'] },
  { ...H, s: 'id', id: 'nhi', t: 'NHI', m: 'National Health Index number — every NZ patient’s unique ID', k: 'deck', src: MA1 + 'slides 27 & 51',
    x: 'On the ID band and the chart. Part of the three-identifier check before any medicine.', cf: ['dob'] },
  { ...H, s: 'id', id: 'dob', t: 'DOB', a: ['D.O.B.'], m: 'Date of birth', cf: ['nhi'] },
  { ...H, s: 'id', id: 'adr', t: 'ADR', m: 'Adverse drug reaction', k: 'deck', src: MA1 + 'slide 51; Pharmacodynamics slides 43–44',
    x: 'The chart’s allergies & ADR box lists every known allergy and bad reaction — check it before every first dose.',
    w: 'A blank allergy box is not “no allergies” — it means nobody has asked yet.', cf: ['ade', 'nkda'] },
  { ...H, s: 'id', id: 'nka', t: 'NKA', m: 'No known allergies (of any kind)', k: 'must', x: 'Still confirm it with the patient before you give anything.', cf: ['nkda'] },
  { ...H, s: 'id', id: 'nkda', t: 'NKDA', m: 'No known drug allergies', k: 'must',
    x: 'Drug allergies only — the patient may still be allergic to food, latex or plasters. Confirm it by asking.', cf: ['nka'] },
  { ...H, s: 'id', id: 'wt', t: 'Wt', m: 'Weight (kg)', k: 'deck', src: MA1 + 'slide 51',
    x: 'Needed for every per-kg dose. Daily weights also track fluid, e.g. heart failure on diuretics.', cf: ['bsa'] },
  { ...H, s: 'id', id: 'emar', t: 'eMAR', m: 'Electronic medication (administration) record',
    x: 'A computer version of the chart — you scan and sign on screen. The same rights and checks apply.', cf: ['nmc'] },
  { ...H, s: 'id', id: 'rx', t: 'Rx', m: 'Prescription — or treatment', x: 'From Latin recipe, “take”. In the notes “Rx” often means the treatment plan.', cf: ['tx'] },

  /* ── the chart’s sections (Med Admin (1) slides 54–55: five special sections, plus the regular medicines) ── */
  { ...H, s: 'sec', kd: 'term', id: 'secreg', t: 'regular medicines', m: 'Doses given at set times every day, signed each time',
    x: 'The main part of the chart: each order has its times across the top and a box per dose to sign or code.', cf: ['secprn', 'seconce'] },
  { ...H, s: 'sec', kd: 'term', id: 'seconce', t: 'once-only section', m: 'Where stat and single doses are charted', k: 'deck', src: MA1 + 'slides 54–55', cf: ['secprn', 'secverbal'] },
  { ...H, s: 'sec', kd: 'term', id: 'secverbal', t: 'verbal order', m: 'Given by phone or in person — the prescriber signs it afterwards', k: 'deck', src: MA1 + 'slides 13–14 & 54–55',
    x: 'An RN may give a medicine on a verbal order, e.g. a phone order or in an emergency. It has its own section, and the prescriber must sign it within the time your hospital’s policy sets.', cf: ['seconce'] },
  { ...H, s: 'sec', kd: 'term', id: 'secprn', t: 'PRN section', m: 'Where as-needed medicines go, each with its reason and 24-hour max', k: 'deck', src: MA1 + 'slides 54–55', cf: ['secreg'] },
  { ...H, s: 'sec', kd: 'term', id: 'secfluid', t: 'fluid & infusion orders', m: 'Where drips and bags for a vein are prescribed, with volume and rate', k: 'deck', src: MA1 + 'slides 54–55', cf: ['seco2'] },
  { ...H, s: 'sec', kd: 'term', id: 'seco2', t: 'oxygen & medical gases', m: 'O₂ is a medicine, so it has its own section, with a target range', k: 'deck', src: MA1 + 'slides 54–55',
    x: 'Usually with a delivery device, a flow rate and a target saturation range.', cf: ['secfluid'] },
  { ...H, s: 'sec', kd: 'term', id: 'samplesig', t: 'sample signature', m: 'A specimen of each prescriber’s handwriting, so every order can be traced', k: 'deck', src: MA1 + 'slide 53', cf: ['checkinit'] },
  { ...H, s: 'sec', kd: 'term', id: 'checkinit', t: 'check initial', m: 'What the supervising RN writes beside a dose a student gave', k: 'deck', src: MA1 + 'slide 55',
    x: 'The course: student nurses also need the “check” initial.', cf: ['samplesig'] },

  /* ── not-given codes. Letters as on the national charts; YOUR chart prints its own key, and that key wins. ── */
  { ...H, s: 'code', kd: 'term', id: 'nonadmin', t: 'non-administration code', m: 'A letter in the dose box saying why a dose was not given', k: 'deck', src: MA1 + 'slide 55',
    x: 'Every dose box gets either a signature or a code — never left blank. The chart prints the key.', cf: ['withhold'] },
  { ...H, s: 'code', id: 'cA', t: 'A', m: 'Absent — the patient is off the ward', x: 'e.g. in X-ray or theatre when the dose is due. Follow it up when they are back.', cf: ['cL'] },
  { ...H, s: 'code', id: 'cF', t: 'F', m: 'Fasting — nil by mouth', x: 'e.g. before theatre. Check which medicines should still be given with a sip of water.', cf: ['cW'] },
  { ...H, s: 'code', id: 'cL', t: 'L', m: 'On leave', x: 'The patient is away from the hospital on approved leave.', cf: ['cA'] },
  { ...H, s: 'code', id: 'cN', t: 'N', m: 'Not available — get it, or tell the prescriber', x: 'Chase it (pharmacy, another ward) — a missed dose can matter.', cf: ['cR'] },
  { ...H, s: 'code', id: 'cR', t: 'R', m: 'Refused — tell the prescriber', x: 'Explain the consequences, document the reason, inform the prescriber and the next shift, and discard the dose.', src: MA1 + 'slide 39', cf: ['cW'] },
  { ...H, s: 'code', id: 'cS', t: 'S', m: 'Self-administered', x: 'The patient manages this medicine themselves, where policy allows.', cf: ['cN'] },
  { ...H, s: 'code', id: 'cV', t: 'V', m: 'Vomiting', x: 'An oral dose would not stay down. Tell the prescriber — another route may be needed.', cf: ['cF'] },
  { ...H, s: 'code', id: 'cW', t: 'W', m: 'Withheld — write the reason in the notes', x: 'e.g. a hold parameter was met (“withhold if HR < 60”). Document why and tell the RN or prescriber.', cf: ['cR', 'cF'] },

  /* ── charting rules and ward words ── */
  { ...H, s: 'rule', kd: 'term', id: 'charted', t: 'charted', a: ['written up'], m: 'Prescribed — written up by a prescriber',
    x: '“Is there any pain relief charted?” = has anything been prescribed? “Can you chart it?” = please prescribe it.', cf: ['cease'] },
  { ...H, s: 'rule', kd: 'term', id: 'cease', t: 'cease', m: 'Stopped by the prescriber — ruled off, dated and signed',
    x: 'A ceased order is never given again from that line, even if doses are still in the drawer. Write “cease” — not D/C.', cf: ['withhold'] },
  { ...H, s: 'rule', kd: 'term', id: 'withhold', t: 'withhold', a: ['held'], m: 'Do not give this dose — for a reason you document',
    x: 'e.g. a hold parameter is met, or the patient is nil by mouth. Code W, the reason in the notes, and tell someone if it matters.', cf: ['cease'] },
  { ...H, s: 'rule', kd: 'term', id: 'holdparam', t: 'hold parameters', m: 'Obs limits written on an order: outside them, the dose is withheld',
    x: 'e.g. “withhold if HR < 60 or SBP < 100” on a heart or blood-pressure medicine — take the obs before you give it.', cf: ['withhold'] },
  { ...H, s: 'rule', kd: 'term', id: 'indication', t: 'indication', m: 'The reason the medicine was prescribed', k: 'deck', src: MA1 + 'slide 40',
    x: 'Right indication is one of the 8 Rights — you must know why you are giving it, above all for PRN medicines.', cf: ['contraind'] },
  { ...H, s: 'rule', kd: 'term', id: 'max24', t: 'max … /24 h', m: 'The most that may be given in any 24 hours',
    x: 'On a PRN order: “max 4 g/24 h” = never more than 4 g in any 24-hour period. Add up every dose, from every section of the chart (and combination products), before giving another.', cf: ['indication'] },
  { ...H, s: 'rule', kd: 'term', id: 'timecrit', t: 'time-critical medicine', m: 'One where a late or missed dose can cause harm', k: 'deck', src: MA1 + 'slide 32',
    x: 'The deck’s example: insulin before meals. Most hospital lists also include Parkinson’s medicines, IV antibiotics, anticoagulants and anti-epileptics.', cf: ['window'] },
  { ...H, s: 'rule', kd: 'term', id: 'window', t: '30-minute rule', m: 'A regular medicine is given within half an hour of its charted time', k: 'deck', src: MA1 + 'slide 32',
    x: 'PRN timing is your clinical judgement instead — e.g. a pain assessment before analgesia.', cf: ['timecrit'] },
  { ...H, s: 'rule', kd: 'term', id: 'threechecks', t: 'three checks', m: 'Label against the chart: before preparing, after preparing, before putting it away', k: 'deck', src: MA1 + 'slides 28–29',
    x: 'And only give medicines you prepared yourself.', cf: ['threeids'] },
  { ...H, s: 'rule', kd: 'term', id: 'threeids', t: 'three identifiers', m: 'Name, date of birth and NHI — checked against the ID band first', k: 'deck', src: MA1 + 'slide 27',
    x: 'Ask the patient to state their full name and date of birth; don’t read it out for them to agree with.', cf: ['threechecks'] },
  { ...H, s: 'rule', kd: 'term', id: 'rights', t: '8 Rights + 2 Checks', m: 'Patient, medication, dose, time, route, to refuse, indication, documentation — plus expiry and allergies', k: 'deck', src: MA1 + 'slide 23',
    x: 'The course teaches 8 Rights and 2 Checks, and says the textbooks’ five rights are not enough to practise safely.', cf: ['threechecks'] },
  { ...H, s: 'rule', kd: 'term', id: 'secondcheck', t: 'second check', a: ['double check'], m: 'Another nurse independently verifies a high-risk dose before it is given',
    x: 'Your hospital’s policy lists which medicines need one — typically controlled drugs, insulin, IV medicines and anticoagulants — and whether a student can be the second checker (usually not).', cf: ['threechecks'] },
];
