/* ⏰ When & how often — frequency, time of day, meals, durations and 24-hour time.
   Schema (every file in content/terms/): see content/terms/index.js. Provenance k:
   'must' = the course's own Must-Know list (Must Know: Medication & Prescription Abbreviations 01.26,
   Concepts (2) slides 77–80) · 'deck' = a course deck, named in src · 'ward' = standard NZ ward usage,
   the tool's wording · 'safe' = the international error-prone lists (ISMP), the tool's summary. */
const W = { c: 'when' };

export const TERMS = [
  /* ── how often ── */
  { ...W, s: 'freq', id: 'od', t: 'OD', a: ['od', 'o.d.'], m: 'Once a day', g: 'once', k: 'must', also: ['safe'],
    x: 'Latin omni die, “every day”. It is on the course list, so you must be able to read it — but many charting standards now say write “daily” instead.',
    w: 'Error-prone: OD is also Latin for the right eye (oculus dexter), and in the notes “OD” means overdose. Write “daily”.',
    cf: ['bd', 'q4h'] },
  { ...W, s: 'freq', id: 'bd', t: 'BD', a: ['bd', 'bid', 'BID', 'b.d.', 'b.i.d.'], m: 'Twice a day', k: 'must',
    x: 'Latin bis die / bis in die. The NZ chart’s recommended times: 0800 and 2000. Not quite the same as q12h, which runs strictly by the clock.',
    eg: 'Metformin 500 mg PO BD', cf: ['tds', 'od', 'q12h'] },
  { ...W, s: 'freq', id: 'tds', t: 'TDS', a: ['tds', 'tid', 'TID', 't.d.s.', 't.i.d.'], m: 'Three times a day', k: 'must',
    x: 'Latin ter die sumendum, “to be taken three times a day”. The NZ chart’s recommended times: 0800, 1400 and 2000.',
    eg: 'Amoxicillin 500 mg PO TDS', cf: ['bd', 'qid', 'q8h'] },
  { ...W, s: 'freq', id: 'qid', t: 'QID', a: ['qid', 'qds', 'QDS', 'q.i.d.'], m: 'Four times a day', k: 'must',
    x: 'Latin quater in die. The NZ chart’s recommended times: 0600, 1200, 1800 and 2200 — nearly 6-hourly, but it ends at 2200 so the night is left alone. q6h runs by the clock: 0600, 1200, 1800 and 2400.',
    eg: 'Paracetamol 1 g PO QID', cf: ['q4h', 'tds', 'q6h'] },
  { ...W, s: 'freq', id: 'q4h', t: 'q4h', a: ['qqh', '4-hourly', '4 hrly', '4H'], m: 'Every 4 hours', k: 'must',
    x: 'q is Latin quaque, “every”; qqh is quaque quarta hora, “every fourth hour” — both on the course list. Around the clock, so up to 6 doses in 24 hours: on a PRN order, check the 24-hour maximum before every dose.',
    eg: 'Oxycodone 5 mg PO q4h PRN pain', cf: ['qid', 'q6h', 'q2h'] },
  { ...W, s: 'freq', id: 'q2h', t: 'q2h', a: ['2-hourly', '2 hrly'], m: 'Every 2 hours',
    x: 'By the clock. The same idea shows up in the notes as “turns 2/24” — reposition every 2 hours.', cf: ['q4h', 'hrly'] },
  { ...W, s: 'freq', id: 'q6h', t: 'q6h', a: ['6-hourly', '6 hrly'], m: 'Every 6 hours',
    x: 'By the clock, day and night — the NZ chart recommends 0600, 1200, 1800 and 2400 for 6-hourly antibiotics. QID is also four doses, but ends at 2200.',
    cf: ['qid', 'q4h', 'q8h'] },
  { ...W, s: 'freq', id: 'q8h', t: 'q8h', a: ['8-hourly', '8 hrly'], m: 'Every 8 hours',
    x: 'By the clock — the NZ chart recommends 0600, 1400 and 2200 for 8-hourly antibiotics, where keeping the blood level steady matters. q means “every”: q8h is 3 doses a day, not 8.',
    eg: 'Cefazolin 2 g IV q8h', cf: ['tds', 'q6h', 'q12h'] },
  { ...W, s: 'freq', id: 'q12h', t: 'q12h', a: ['12-hourly', '12 hrly'], m: 'Every 12 hours',
    x: 'By the clock — e.g. 0800 and 2000. BD is similar, but BD follows the ward’s set times.', cf: ['bd', 'q8h'] },
  { ...W, s: 'freq', id: 'hrly', t: 'hrly', a: ['1-hourly', 'q1h', 'hourly'], m: 'Every hour',
    x: 'Also a suffix: “4 hrly” = every 4 hours. “Hrly obs” = observations every hour.', cf: ['q2h', 'stat'] },
  { ...W, s: 'freq', id: 'prn', t: 'PRN', a: ['prn', 'p.r.n.'], m: 'When required — only if needed', k: 'must',
    x: 'Latin pro re nata, “as the occasion arises” (the course list: “if necessary”). A PRN order must say what it is for and the most you may give in 24 hours. You assess before you give it and evaluate after — and Joan called PRN an ethical problem, because “as necessary” rests on the nurse’s judgement.',
    eg: 'Paracetamol 1 g PO q4h PRN pain — max 4 g/24 h', src: 'Must Know list; Joan’s Legal & Ethical lecture 16 Sep 2026 [1:01:28]', cf: ['stat', 'od'] },
  { ...W, s: 'freq', id: 'stat', t: 'stat', a: ['STAT'], m: 'Immediately — one dose, now', k: 'must',
    x: 'Latin statim, “at once” (the course list: “immediately”). A one-off dose, written in the once-only section of the chart and given straight away.',
    eg: 'Adrenaline 0.5 mg IM stat', cf: ['prn', 'od'] },
  { ...W, s: 'freq', id: 'altdie', t: 'alt die', a: ['alternate days'], m: 'Every second day', g: 'altday',
    x: 'Latin alternis diebus. Clearest written out — “every second day”, or the actual days. The American form QOD is on the danger list.', cf: ['od', 'bd'] },

  /* ── time of day ── */
  { ...W, s: 'day', id: 'mane', t: 'mane', a: ['MANE', 'o.m.'], m: 'In the morning', k: 'must',
    x: 'Latin for “in the morning”. The NZ chart’s recommended time: 0800.', eg: 'Furosemide 40 mg PO mane', cf: ['nocte', 'midi'] },
  { ...W, s: 'day', id: 'midi', t: 'midi', m: 'At midday',
    x: 'The midday round, e.g. 1200. Seen on NZ and Australian charts beside mane and nocte.', cf: ['mane', 'nocte'] },
  { ...W, s: 'day', id: 'nocte', t: 'nocte', a: ['NOCTE', 'o.n.'], m: 'At night', k: 'must',
    x: 'Latin for “at night”. The NZ chart recommends 1800 or 2000; your ward sets which.',
    eg: 'Atorvastatin 40 mg PO nocte', cf: ['mane', 'midi'] },

  /* ── food ── */
  { ...W, s: 'meal', id: 'ac', t: 'ac', a: ['a.c.', 'AC'], m: 'Before meals', k: 'must',
    x: 'Latin ante cibum, “before food” — often 30–60 minutes before eating, for medicines that absorb better on an empty stomach, or that have to be in place before food arrives (e.g. mealtime insulin, which is time-critical).',
    cf: ['pc'] },
  { ...W, s: 'meal', id: 'pc', t: 'pc', a: ['p.c.', 'PC'], m: 'After meals', k: 'must',
    x: 'Latin post cibum, “after food” — for medicines that upset an empty stomach or absorb better with food.', cf: ['ac'] },
  { ...W, s: 'meal', id: 'cum', t: 'c̄', m: 'With',
    x: 'Latin cum. “c̄ food” = with food. The bar over the c is easy to miss — clearer written as “with”.', cf: ['sine'] },
  { ...W, s: 'meal', id: 'sine', t: 's̄', m: 'Without',
    x: 'Latin sine. “s̄ food” = without food. Clearer written as “without”.', cf: ['cum'] },
  { ...W, s: 'meal', id: 'adlib', t: 'ad lib', a: ['ad libitum'], m: 'Freely — as much as wanted',
    x: 'Latin ad libitum. Mostly for food and drink: “fluids ad lib” means drink as much as you like.', cf: ['prn'] },

  /* ── how long / how far away: the NZ “/n” notation. The same number across all four so the digit gives nothing away ── */
  { ...W, s: 'dur', id: 'd24', t: '3/24', m: '3 hours',
    x: '“/24” counts hours: “review in 3/24” = in 3 hours. As a frequency it means that often: “obs 4/24” = 4-hourly observations, “turns 2/24” = every 2 hours.',
    cf: ['d7', 'd52', 'd12'] },
  { ...W, s: 'dur', id: 'd7', t: '3/7', m: '3 days',
    x: '“/7” counts days (out of a week): “amoxicillin × 5/7” = for 5 days; “day 2/7” = day 2 of 7.', cf: ['d24', 'd52', 'd12'] },
  { ...W, s: 'dur', id: 'd52', t: '3/52', m: '3 weeks',
    x: '“/52” counts weeks (out of a year): “review in 2/52” = in 2 weeks.', cf: ['d7', 'd12', 'd24'] },
  { ...W, s: 'dur', id: 'd12', t: '3/12', m: '3 months',
    x: '“/12” counts months: “follow-up in 6/12” = in 6 months; a “3/12 history” = 3 months’ history.', cf: ['d52', 'd7', 'd24'] },

  /* ── 24-hour time. The course: “Always use 24-hour time.” ── */
  { ...W, s: 'clock', id: 't0600', t: '0600', m: '6 am', k: 'deck', src: 'Med Admin (1) slide 32 (“Always use 24-hour time”)', cf: ['t1800'] },
  { ...W, s: 'clock', id: 't0800', t: '0800', m: '8 am', k: 'deck', src: 'Med Admin (1) slide 32', cf: ['t2000'] },
  { ...W, s: 'clock', id: 't1200', t: '1200', m: 'Midday (noon)', k: 'deck', src: 'Med Admin (1) slide 32', cf: ['t2400'],
    x: '1200 is midday; midnight is 2400 (or 0000). “12 am / 12 pm” is exactly the confusion 24-hour time exists to stop.' },
  { ...W, s: 'clock', id: 't1400', t: '1400', m: '2 pm', k: 'deck', src: 'Med Admin (1) slide 32', cf: ['t2200'],
    x: 'After 1200, take 12 away: 1400 − 12 = 2 pm.' },
  { ...W, s: 'clock', id: 't1800', t: '1800', m: '6 pm', k: 'deck', src: 'Med Admin (1) slide 32', cf: ['t0600'] },
  { ...W, s: 'clock', id: 't2000', t: '2000', m: '8 pm', k: 'deck', src: 'Med Admin (1) slide 32', cf: ['t0800'] },
  { ...W, s: 'clock', id: 't2200', t: '2200', m: '10 pm', k: 'deck', src: 'Med Admin (1) slide 32', cf: ['t1400'] },
  { ...W, s: 'clock', id: 't2400', t: '2400', a: ['0000'], m: 'Midnight', k: 'deck', src: 'Med Admin (1) slide 32', cf: ['t1200'],
    x: 'Midnight is written 2400 (the end of a day) or 0000 (the start of the next) — both mean the same moment.' },
];
