/* GENERATED by port-intro-pharm.mjs — do not edit by hand. Two sources:
   bank/intro-pharm.json (multi-choice questions written by the intro-pharm hub from the 14 lecture decks) and,
   for written questions, content/joan-saqs.js (hand-written in Joan's stated exam format).
   None are the lecturer's questions; each names the slide or lecture moment that supplies its answer. */
export const AUTHORED_MCQS = [
 {
  "quiz": "concepts1",
  "quizName": "M1 · What pharmacology is",
  "sys": "found",
  "q": "\"What the body does to the drug\" is the definition of:",
  "options": [
   "Pharmacodynamics",
   "Pharmacokinetics",
   "Pharmacotherapeutics",
   "Toxicology"
  ],
  "correct": 1,
  "why": "The deck uses this exact phrasing for pharmacokinetics, and pairs it with the four phases: absorption, distribution, metabolism, excretion. Pharmacodynamics is the mirror phrase — \"what the drug does to the body\".",
  "src": "Pharmacology Concepts (1) 2026 slides 21–22"
 },
 {
  "quiz": "concepts1",
  "quizName": "M1 · What pharmacology is",
  "sys": "found",
  "q": "A patient is prescribed omeprazole to reduce stomach acid so an ulcer can heal, although the underlying cause is not permanently fixed. Which purpose of a medication is this?",
  "options": [
   "To cure",
   "To prevent",
   "To treat",
   "To diagnose"
  ],
  "correct": 2,
  "why": "The deck uses this exact example for TREAT: \"Omeprazole treats a stomach ulcer by reducing stomach acid and promoting healing, but does not permanently cure the underlying cause.\"",
  "src": "Pharmacology Concepts (1) 2026 slide 13"
 },
 {
  "quiz": "concepts1",
  "quizName": "M1 · What pharmacology is",
  "sys": "found",
  "q": "Which body decides whether a medicine is subsidised in Aotearoa New Zealand?",
  "options": [
   "Medsafe",
   "PHARMAC — Te Pātaka Whaioranga",
   "The Health Research Council",
   "CARM"
  ],
  "correct": 1,
  "why": "PHARMAC decides which medications and medical products are funded within a fixed budget. Medsafe regulates safety and quality — a different question.",
  "src": "Pharmacology Concepts (1) 2026 slides 36–37"
 },
 {
  "quiz": "concepts1",
  "quizName": "M1 · What pharmacology is",
  "sys": "found",
  "q": "\"Panadol\", \"Pamol\" and \"Pacimol\" are examples of which kind of name?",
  "options": [
   "Chemical names",
   "Generic names",
   "Proprietary (brand) names",
   "Classification names"
  ],
  "correct": 2,
  "why": "These are trade names selected and copyrighted by the companies that market paracetamol; the generic name is paracetamol and the chemical name is 4-hydroxyacetanilide.",
  "src": "Pharmacology Concepts (1) 2026 slide 45"
 },
 {
  "quiz": "concepts1",
  "quizName": "M1 · What pharmacology is",
  "sys": "found",
  "q": "A medication should NOT be used at all because it may harm this person. This is a:",
  "options": [
   "Precaution",
   "Contraindication",
   "Drug interaction",
   "Adverse effect"
  ],
  "correct": 1,
  "why": "A contraindication is an absolute — the medication should not be used. A precaution means it may still be used, but with careful monitoring or dose adjustment.",
  "src": "Pharmacology Concepts (1) 2026 slide 31"
 },
 {
  "quiz": "concepts1",
  "quizName": "M1 · What pharmacology is",
  "sys": "found",
  "q": "The suffix \"-olol\" (atenolol, propranolol, metoprolol) signals which drug class?",
  "options": [
   "Cholesterol-lowering drugs",
   "Penicillin antibiotics",
   "Beta blockers",
   "Proton pump inhibitors"
  ],
  "correct": 2,
  "why": "The deck lists three suffixes: -olol beta blockers, -statin cholesterol-lowering, -cillin penicillin antibiotics.",
  "src": "Pharmacology Concepts (1) 2026 slide 42"
 },
 {
  "quiz": "concepts1",
  "quizName": "M1 · What pharmacology is",
  "sys": "found",
  "q": "Rongoā Māori is placed under which branch of pharmacology in this course?",
  "options": [
   "Toxicology",
   "Pharmacokinetics",
   "Pharmacotherapeutics",
   "Pharmacodynamics"
  ],
  "correct": 2,
  "why": "The deck states that indigenous medicines and practices \"also sit under the umbrella of pharmacotherapeutics\", and quotes the Ahuriri-Driscoll et al. (2008) definition of rongoā Māori.",
  "src": "Pharmacology Concepts (1) 2026 slide 24"
 },
 {
  "quiz": "concepts2",
  "quizName": "M1 · Drug names, sources & schedules",
  "sys": "found",
  "q": "Under the Medicines Act 1981, paracetamol and ibuprofen are classified as:",
  "options": [
   "Prescription",
   "Restricted (pharmacist-only)",
   "Pharmacy only",
   "General sales"
  ],
  "correct": 3,
  "why": "The deck's legal classification table gives paracetamol and ibuprofen as the general-sales examples — any other medicine not classified above, sellable from any retail outlet.",
  "src": "Pharmacology Concepts (2) 2026 slide 10"
 },
 {
  "quiz": "concepts2",
  "quizName": "M1 · Drug names, sources & schedules",
  "sys": "found",
  "q": "Which oral formulation is absorbed FASTEST?",
  "options": [
   "Enteric-coated tablets",
   "Capsules",
   "Elixirs and syrups",
   "Powders"
  ],
  "correct": 2,
  "why": "The deck's rate-of-absorption table runs elixirs and syrups (fastest) → suspensions → powders → capsules → tablets → coated tablets (slowest). Liquids do not need to disintegrate first.",
  "src": "Pharmacology Concepts (2) 2026 slide 61 · Pharmacokinetics (1) 2026 slide 24"
 },
 {
  "quiz": "concepts2",
  "quizName": "M1 · Drug names, sources & schedules",
  "sys": "found",
  "q": "GTN spray for angina is given under the tongue so it enters the bloodstream directly and acts very quickly. This route is:",
  "options": [
   "Buccal",
   "Sublingual",
   "Enteral",
   "Intradermal"
  ],
  "correct": 1,
  "why": "Sublingual = under the tongue (GTN spray is the deck's own example). Buccal is through the mucosal lining of the cheek — the deck's example there is nicotine gum.",
  "src": "Pharmacology Concepts (2) 2026 slide 31"
 },
 {
  "quiz": "concepts2",
  "quizName": "M1 · Drug names, sources & schedules",
  "sys": "found",
  "q": "A tuberculosis vaccination or an allergy antigen test is injected just under the epidermis. This route is:",
  "options": [
   "Subcutaneous",
   "Intramuscular",
   "Intradermal",
   "Intrathecal"
  ],
  "correct": 2,
  "why": "Intradermal is injected into the dermis, just under the epidermis; the deck names antigen (allergy) testing and TB vaccination as the examples.",
  "src": "Pharmacology Concepts (2) 2026 slide 42"
 },
 {
  "quiz": "concepts2",
  "quizName": "M1 · Drug names, sources & schedules",
  "sys": "found",
  "q": "Which parenteral route bypasses the blood–brain barrier by injecting directly into the spinal subarachnoid space?",
  "options": [
   "Epidural",
   "Intrathecal",
   "Intra-articular",
   "Intraosseous"
  ],
  "correct": 1,
  "why": "Intrathecal is injection directly into the spinal subarachnoid space, bypassing the blood–brain barrier, e.g. spinal anaesthesia. Epidural is into the epidural space of the spinal canal.",
  "src": "Pharmacology Concepts (2) 2026 slide 44"
 },
 {
  "quiz": "concepts2",
  "quizName": "M1 · Drug names, sources & schedules",
  "sys": "found",
  "q": "\"tds\" on a medication chart means:",
  "options": [
   "Twice a day",
   "Three times a day",
   "Every three hours",
   "Immediately"
  ],
  "correct": 1,
  "why": "From the Must Know Abbreviations table: tds = three times a day. Twice a day is bd/bid; immediately is stat.",
  "src": "Must Know: Medication & Prescription Abbreviations 01.26 (PDF)"
 },
 {
  "quiz": "concepts2",
  "quizName": "M1 · Drug names, sources & schedules",
  "sys": "found",
  "q": "Which is NOT one of the four reasons the lecture gives for using an enteric coating?",
  "options": [
   "Prevents decomposition of sensitive drugs by gastric secretions",
   "Prevents nausea and vomiting induced by the drug in the stomach",
   "Provides delayed action of the drug",
   "Increases the total dose absorbed above 100%"
  ],
  "correct": 3,
  "why": "The four reasons are: prevent decomposition by gastric secretions, prevent dilution of the drug, prevent drug-induced nausea and vomiting, and provide delayed action. A coating cannot raise bioavailability above the dose given.",
  "src": "Pharmacology Concepts (2) 2026 slide 66"
 },
 {
  "quiz": "concepts2",
  "quizName": "M1 · Drug names, sources & schedules",
  "sys": "found",
  "q": "Which source does the lecture explicitly warn against because it \"uses patterns rather than science\"?",
  "options": [
   "The New Zealand Formulary",
   "Manufacturer information inserts",
   "Artificial intelligence",
   "Hospital intranet policies"
  ],
  "correct": 2,
  "why": "The \"sources to use with caution\" slide names AI directly with that wording, alongside .com websites, news releases and social media. Intranet policies, pharmacy, manufacturer inserts, current textbooks and dated journal articles are listed as APPROPRIATE sources.",
  "src": "Pharmacology Concepts (2) 2026 slides 22–23"
 },
 {
  "quiz": "calcs",
  "quizName": "M2 · Medication calculations",
  "sys": "calc",
  "q": "You are prescribed 1 g of paracetamol and have 500 mg capsules. Before using the formula you must:",
  "options": [
   "Round the prescribed dose down",
   "Convert 1 g to 1000 mg so the units match",
   "Divide the volume by 1",
   "Use the total bottle volume"
  ],
  "correct": 1,
  "why": "The unit of medication must be the same on the top and bottom of the formula. 1 g × 1000 = 1000 mg; then 1000 ÷ 500 × 1 capsule = 2 capsules.",
  "src": "Medication Calculations 2026 slides 25–26 (worked example 3)"
 },
 {
  "quiz": "calcs",
  "quizName": "M2 · Medication calculations",
  "sys": "calc",
  "q": "The drop factor of a giving set is:",
  "options": [
   "How fast the drops fall, calculated by the nurse",
   "How big the drops are, fixed by the manufacturer",
   "The total volume to be infused",
   "The time the infusion will take"
  ],
  "correct": 1,
  "why": "Drop factor = drops/mL — the SIZE of the drops, a fixed number set by the type of giving set. The nurse never calculates it. The drip rate (drops/min) is the speed, and that IS calculated.",
  "src": "Medication Calculations 2026 slide 68"
 },
 {
  "quiz": "calcs",
  "quizName": "M2 · Medication calculations",
  "sys": "calc",
  "q": "An IV drip rate calculates to 27.77 drops/min. What rate do you set?",
  "options": [
   "27 drops/min",
   "28 drops/min",
   "27.8 drops/min",
   "30 drops/min"
  ],
  "correct": 1,
  "why": "IV drip rates are rounded: .5 or higher rounds UP, so 27.77 → 28 drops/min. This is the deck's worked example 15 (Kohatu, Dextrose 5% 500 mL over 6 hours, drop factor 20).",
  "src": "Medication Calculations 2026 slides 69 & 72"
 },
 {
  "quiz": "calcs",
  "quizName": "M2 · Medication calculations",
  "sys": "calc",
  "q": "Adrenaline for injection 1:1000 means:",
  "options": [
   "1 g in 1 mL",
   "1 mg in 1 mL",
   "1 mcg in 1 mL",
   "1 mg in 1000 mL"
  ],
  "correct": 1,
  "why": "1:1000 literally means 1 g in 1000 mL; converting gives 1000 mg:1000 mL, which simplifies to 1 mg in 1 mL. The deck calls this \"the most important thing about ratios at this level\".",
  "src": "Medication Calculations 2026 slides 57 & 63"
 },
 {
  "quiz": "calcs",
  "quizName": "M2 · Medication calculations",
  "sys": "calc",
  "q": "Which of these should you NOT round?",
  "options": [
   "An IV drip rate of 83.33 drops/min",
   "An IV drip rate of 66.66 drops/min",
   "A calculated volume of 6.25 mL",
   "An IV drip rate of 55.55 drops/min"
  ],
  "correct": 2,
  "why": "Do not round medication volumes or tablet numbers — 6.25 mL is given as 6.25 mL. Drip rates ARE rounded, because you cannot count a fraction of a drop.",
  "src": "Medication Calculations 2026 slides 69 & 102"
 },
 {
  "quiz": "calcs",
  "quizName": "M2 · Medication calculations",
  "sys": "calc",
  "q": "You dilute a 1 mL ampoule of morphine 5 mg/mL with 9 mL of sterile water. The concentration in the syringe is now:",
  "options": [
   "5 mg/mL",
   "5 mg/10 mL",
   "1 mg/10 mL",
   "50 mg/10 mL"
  ],
  "correct": 1,
  "why": "The amount of drug is unchanged — 5 mg went in. The volume is 1 mL + 9 mL = 10 mL. So the syringe holds 5 mg in 10 mL.",
  "src": "Medication Calculations 2026 slides 95–96 (worked example 23)"
 },
 {
  "quiz": "calcs",
  "quizName": "M2 · Medication calculations",
  "sys": "calc",
  "q": "How many resits are available for the Medication Calculations Test in Semester 2, and what score is required?",
  "options": [
   "1 resit, 80% required",
   "2 resits, 90% required",
   "3 resits, 100% required",
   "Unlimited resits, 100% required"
  ],
  "correct": 2,
  "why": "The Student Guide: Semester 2 allows up to 3 resits, and 100% competency is required. Fail after the third attempt and you fail the course.",
  "src": "Student Guide Medication Calculation Process 2026 (pp. 1 & 3)"
 },
 {
  "quiz": "calcs",
  "quizName": "M2 · Medication calculations",
  "sys": "calc",
  "q": "Mele is prescribed pethidine 75 mg IM. Ampoules contain 100 mg in 2 mL. What volume do you draw up?",
  "options": [
   "0.75 mL",
   "1.5 mL",
   "2.7 mL",
   "3 mL"
  ],
  "correct": 1,
  "why": "75 mg ÷ 100 mg × 2 mL = 1.5 mL. This is the deck's worked example 6.",
  "src": "Medication Calculations 2026 slide 33 (worked example 6)"
 },
 {
  "quiz": "pk1",
  "quizName": "M3 · Pharmacokinetics (1)",
  "sys": "pkpd",
  "q": "Which route of administration does NOT require absorption?",
  "options": [
   "Sublingual",
   "Intramuscular",
   "Intravenous",
   "Rectal"
  ],
  "correct": 2,
  "why": "IV medications enter the bloodstream directly and do not need to be absorbed from the site they are given. Every other route requires absorption.",
  "src": "Pharmacokinetics (1) 2026 slide 13"
 },
 {
  "quiz": "pk1",
  "quizName": "M3 · Pharmacokinetics (1)",
  "sys": "pkpd",
  "q": "A 100 mg oral tablet: 20 mg is not absorbed, 80 mg reaches the liver, and the liver breaks down 60 mg on the first pass. The bioavailability is:",
  "options": [
   "80%",
   "60%",
   "20%",
   "100%"
  ],
  "correct": 2,
  "why": "Only 20 mg gets into the bloodstream to have effect, out of the 100 mg dose — a bioavailability of 20%. This is the deck's own worked example.",
  "src": "Pharmacokinetics (1) 2026 slide 36"
 },
 {
  "quiz": "pk1",
  "quizName": "M3 · Pharmacokinetics (1)",
  "sys": "pkpd",
  "q": "Only which fraction of a drug can leave the bloodstream and produce an effect?",
  "options": [
   "The protein-bound fraction",
   "The free (unbound) fraction",
   "The metabolised fraction",
   "The excreted fraction"
  ],
  "correct": 1,
  "why": "Only free (unbound) drug can move from the bloodstream into tissues to produce a pharmacological effect. Warfarin is about 99% protein-bound, so very little free drug is available.",
  "src": "Pharmacokinetics (1) 2026 slide 37"
 },
 {
  "quiz": "pk1",
  "quizName": "M3 · Pharmacokinetics (1)",
  "sys": "pkpd",
  "q": "The placental barrier is best described as:",
  "options": [
   "Highly selective — very few drugs cross",
   "Non-selective — many drugs cross, and lipid-soluble drugs cross easily",
   "Impermeable to all medications",
   "Permeable only to water-soluble drugs"
  ],
  "correct": 1,
  "why": "The lecture describes the placenta as a non-selective barrier that allows many different drugs to cross, with lipid-soluble drugs crossing easily. The blood–brain barrier is the selective one.",
  "src": "Pharmacokinetics (1) 2026 slide 42"
 },
 {
  "quiz": "pk1",
  "quizName": "M3 · Pharmacokinetics (1)",
  "sys": "pkpd",
  "q": "Where does most absorption of an oral medication occur?",
  "options": [
   "The stomach",
   "The small intestine",
   "The oesophagus",
   "The large intestine"
  ],
  "correct": 1,
  "why": "The small intestine is the main site of absorption — it has a very large surface area and abundant blood vessels. Absorption in the stomach is low (thick mucus, tight junctions, small surface area).",
  "src": "Pharmacokinetics (1) 2026 slide 18"
 },
 {
  "quiz": "pk1",
  "quizName": "M3 · Pharmacokinetics (1)",
  "sys": "pkpd",
  "q": "Movement of a drug across a membrane against its concentration gradient, using ATP, is:",
  "options": [
   "Passive transport",
   "Active transport",
   "Dissolution",
   "Filtration"
  ],
  "correct": 1,
  "why": "Active transport is movement against the concentration gradient using energy (ATP). Passive transport is movement along the gradient without energy.",
  "src": "Pharmacokinetics (1) 2026 slide 15"
 },
 {
  "quiz": "pk1",
  "quizName": "M3 · Pharmacokinetics (1)",
  "sys": "pkpd",
  "q": "Which tissue does the lecture pair with tetracycline, as a site where the drug becomes concentrated?",
  "options": [
   "Adipose tissue",
   "Thyroid gland",
   "Bone tissue",
   "Brain tissue"
  ],
  "correct": 2,
  "why": "Bone tissue — the deck notes tetracycline can discolour children's teeth. Adipose is paired with lipid-soluble drugs like diazepam, and the thyroid with iodine-containing medications.",
  "src": "Pharmacokinetics (1) 2026 slide 43"
 },
 {
  "quiz": "pk2",
  "quizName": "M3 · Pharmacokinetics (2)",
  "sys": "pkpd",
  "q": "Elimination is best defined as:",
  "options": [
   "Excretion only",
   "Metabolism only",
   "Metabolism + excretion",
   "Clearance × half-life"
  ],
  "correct": 2,
  "why": "The deck states elimination = metabolism + excretion. A drug is eliminated when it is metabolised into an inactive metabolite, even before it is physically excreted in the urine.",
  "src": "Pharmacokinetics (2) 2026 slide 29"
 },
 {
  "quiz": "pk2",
  "quizName": "M3 · Pharmacokinetics (2)",
  "sys": "pkpd",
  "q": "A patient starts a medication that is a potent enzyme INDUCER alongside their regular drug. The likely consequence for the regular drug is:",
  "options": [
   "Increased plasma levels and toxicity",
   "Decreased plasma levels, possibly requiring a higher dose",
   "No change",
   "Increased protein binding"
  ],
  "correct": 1,
  "why": "Enzyme inducers activate liver enzymes → accelerate metabolism → decrease the amount of drug reaching the bloodstream, so a higher dose may be needed. Inhibitors do the opposite and may increase toxicity.",
  "src": "Pharmacokinetics (2) 2026 slide 15"
 },
 {
  "quiz": "pk2",
  "quizName": "M3 · Pharmacokinetics (2)",
  "sys": "pkpd",
  "q": "Roughly how many half-lives does it take for most drugs at a constant dosing interval to reach steady state?",
  "options": [
   "1–2",
   "3–5",
   "8–10",
   "More than 20"
  ],
  "correct": 1,
  "why": "The deck: \"For most medications given at a constant dosing interval, it takes about 3-5 half-lives to reach steady state.\"",
  "src": "Pharmacokinetics (2) 2026 slide 38"
 },
 {
  "quiz": "pk2",
  "quizName": "M3 · Pharmacokinetics (2)",
  "sys": "pkpd",
  "q": "Which of these routes does NOT avoid hepatic first-pass metabolism?",
  "options": [
   "Sublingual",
   "Transdermal",
   "Oral",
   "Rectal"
  ],
  "correct": 2,
  "why": "The oral route is precisely the one that takes the first pass through the liver, because absorbed drug travels via the portal vein. Sublingual/buccal, IV, IM, SC, inhalation, intranasal, transdermal and rectal all avoid it.",
  "src": "Pharmacokinetics (2) 2026 slide 18"
 },
 {
  "quiz": "pk2",
  "quizName": "M3 · Pharmacokinetics (2)",
  "sys": "pkpd",
  "q": "Half-life is defined as the time taken for:",
  "options": [
   "The whole drug to leave the body",
   "The plasma drug concentration to fall by one-half",
   "Steady state to be reached",
   "Half the dose to be absorbed"
  ],
  "correct": 1,
  "why": "Half-life is the time for the plasma drug concentration to decrease by one-half. The Code of Conduct deck note makes the same point: it is not how long the whole drug stays in your system.",
  "src": "Pharmacokinetics (2) 2026 slide 32"
 },
 {
  "quiz": "pk2",
  "quizName": "M3 · Pharmacokinetics (2)",
  "sys": "pkpd",
  "q": "Which kind of drug is POORLY excreted by the kidneys because it is reabsorbed?",
  "options": [
   "Water-soluble drugs",
   "Lipid-soluble drugs",
   "Drugs given intravenously",
   "Drugs with a short half-life"
  ],
  "correct": 1,
  "why": "Lipid-soluble drugs are poorly excreted because they are reabsorbed. The kidneys are the main organ for eliminating water-soluble substances. Protein-bound drugs are not excreted while bound and circulate longer.",
  "src": "Pharmacokinetics (2) 2026 slide 24"
 },
 {
  "quiz": "pk2",
  "quizName": "M3 · Pharmacokinetics (2)",
  "sys": "pkpd",
  "q": "A higher-than-maintenance first dose, used to reach therapeutic plasma concentrations quickly, is a:",
  "options": [
   "Loading dose",
   "Trough dose",
   "Stat dose",
   "Divided dose"
  ],
  "correct": 0,
  "why": "A loading dose is particularly important for drugs with a long half-life, where regular dosing alone would take a prolonged period to reach an effective range.",
  "src": "Pharmacodynamics 2026 slide 40"
 },
 {
  "quiz": "pk2",
  "quizName": "M3 · Pharmacokinetics (2)",
  "sys": "pkpd",
  "q": "Paracetamol's elimination half-life is given in the Medsafe data sheet as:",
  "options": [
   "Under 30 minutes",
   "1–3 hours",
   "8–12 hours",
   "24 hours"
  ],
  "correct": 1,
  "why": "The deck quotes the Medsafe Pacimol data sheet: the elimination half-life varies from 1–3 hours, and most of each dose is excreted in the urine within 24 hours.",
  "src": "Pharmacokinetics (2) 2026 slide 45"
 },
 {
  "quiz": "pd",
  "quizName": "M4 · Pharmacodynamics",
  "sys": "pkpd",
  "q": "Selectivity refers to the number of ___ ; specificity refers to the number of ___ .",
  "options": [
   "effects; targets",
   "targets; effects",
   "doses; responses",
   "receptors; enzymes"
  ],
  "correct": 1,
  "why": "The deck has a slide dedicated to this pair: \"Specificity = number of effects. Selectivity = number of targets.\"",
  "src": "Pharmacodynamics 2026 slide 13"
 },
 {
  "quiz": "pd",
  "quizName": "M4 · Pharmacodynamics",
  "sys": "pkpd",
  "q": "A drug that has affinity for a receptor BUT NO efficacy is:",
  "options": [
   "An agonist",
   "An antagonist",
   "A transporter",
   "A non-specific drug"
  ],
  "correct": 1,
  "why": "The key fits the lock, but the door will not open. An agonist has affinity AND efficacy; an antagonist blocks access of the endogenous substance without eliciting a response.",
  "src": "Pharmacodynamics 2026 slide 24"
 },
 {
  "quiz": "pd",
  "quizName": "M4 · Pharmacodynamics",
  "sys": "pkpd",
  "q": "Amlodipine relaxes blood vessels by blocking the movement of calcium into muscle cells. Its drug target is:",
  "options": [
   "A transporter",
   "An ion channel",
   "An enzyme",
   "A receptor"
  ],
  "correct": 1,
  "why": "Ion channels are membrane pores that let ions move across an electrochemical gradient; amlodipine is the deck's own ion-channel example.",
  "src": "Pharmacodynamics 2026 slide 20"
 },
 {
  "quiz": "pd",
  "quizName": "M4 · Pharmacodynamics",
  "sys": "pkpd",
  "q": "Ibuprofen inhibits COX to block the pathway causing pain, fever and inflammation. Its drug target is:",
  "options": [
   "A receptor",
   "An ion channel",
   "An enzyme",
   "A transporter"
  ],
  "correct": 2,
  "why": "Enzymes are biological catalysts; most drugs acting on enzymes inhibit them, and ibuprofen inhibiting COX is the deck's enzyme example.",
  "src": "Pharmacodynamics 2026 slide 21"
 },
 {
  "quiz": "pd",
  "quizName": "M4 · Pharmacodynamics",
  "sys": "pkpd",
  "q": "Rebound hypertension after suddenly stopping a long-term beta-blocker is explained by:",
  "options": [
   "Receptor downregulation",
   "Receptor upregulation",
   "Enzyme induction",
   "Reduced protein binding"
  ],
  "correct": 1,
  "why": "Repeatedly blocking receptors causes upregulation — more receptors, greater sensitivity. Stopping the drug suddenly leaves the body over-responsive to endogenous signals.",
  "src": "Pharmacodynamics 2026 slide 25"
 },
 {
  "quiz": "pd",
  "quizName": "M4 · Pharmacodynamics",
  "sys": "pkpd",
  "q": "Chronic opioid use leads to needing more drug for the same effect. This tolerance is caused by:",
  "options": [
   "Upregulation",
   "Downregulation and desensitisation",
   "Increased potency",
   "Increased affinity"
  ],
  "correct": 1,
  "why": "Repeated stimulation of receptors causes downregulation — fewer receptors, less responsive — so patients respond less to the same dose over time.",
  "src": "Pharmacodynamics 2026 slide 25"
 },
 {
  "quiz": "pd",
  "quizName": "M4 · Pharmacodynamics",
  "sys": "pkpd",
  "q": "A drug that achieves the same effect at a LOWER dose than another is said to have higher:",
  "options": [
   "Efficacy",
   "Affinity",
   "Potency",
   "Selectivity"
  ],
  "correct": 2,
  "why": "Potency is the amount of drug required to produce a given effect. Efficacy is the size of the maximal response, which is a different question.",
  "src": "Pharmacodynamics 2026 slide 16"
 },
 {
  "quiz": "pd",
  "quizName": "M4 · Pharmacodynamics",
  "sys": "pkpd",
  "q": "A patient is given the wrong dose because of a transcription error and is injured. This is best described as:",
  "options": [
   "An adverse effect",
   "An adverse drug event",
   "A contraindication",
   "A drug interaction"
  ],
  "correct": 1,
  "why": "An adverse drug event is an injury related to the drug but not always due to the drug — including errors in prescribing, dispensing or administration. An adverse effect is caused by the medicine itself.",
  "src": "Pharmacodynamics 2026 slide 44"
 },
 {
  "quiz": "pd",
  "quizName": "M4 · Pharmacodynamics",
  "sys": "pkpd",
  "q": "Which pair of drugs does the lecture use to illustrate an ADDITIVE pharmacodynamic interaction?",
  "options": [
   "Metoprolol and salbutamol",
   "Warfarin and aspirin",
   "Fluoxetine and amlodipine",
   "Ibuprofen and paracetamol"
  ],
  "correct": 1,
  "why": "Warfarin and aspirin → increased bleeding risk, as both inhibit clotting in different ways (additive). Metoprolol and salbutamol is the OPPOSING example — agonist versus antagonist at beta receptors.",
  "src": "Pharmacodynamics 2026 slide 45"
 },
 {
  "quiz": "admin",
  "quizName": "M5 · Medication administration",
  "sys": "admin",
  "q": "How many Rights plus checks of safe medication administration does this course teach?",
  "options": [
   "5 rights",
   "6 rights + 1 check",
   "8 rights + 2 checks",
   "10 rights"
  ],
  "correct": 2,
  "why": "The deck teaches 8 Rights (patient, medication, dose, time, route, right to refuse, indication, documentation) plus 2 Checks (expiry, allergies), and explicitly notes the textbooks' five \"do not cover all Rights you need to practice safely\". The essay brief uses the same wording.",
  "src": "Med Admin (1) 2026 slides 22–23 · Assignments.pdf (Canvas)"
 },
 {
  "quiz": "admin",
  "quizName": "M5 · Medication administration",
  "sys": "admin",
  "q": "A regular medication is scheduled for 0800. Within what window should it be given?",
  "options": [
   "Within 10 minutes",
   "Within 30 minutes",
   "Within 1 hour",
   "Within 2 hours"
  ],
  "correct": 1,
  "why": "\"Regular medications should be given within 30 mins of scheduled time.\" prn medications instead require clinical judgement, e.g. a pain assessment.",
  "src": "Med Admin (1) 2026 slide 32"
 },
 {
  "quiz": "admin",
  "quizName": "M5 · Medication administration",
  "sys": "admin",
  "q": "A prescription states the medication, dose and frequency, but no route. The nurse should:",
  "options": [
   "Give it by the most usual route for that drug",
   "Ask another nurse which route to use",
   "Withhold the medication and contact the prescriber",
   "Give it orally and document the change"
  ],
  "correct": 2,
  "why": "If no route is documented the nurse must withhold the medication and contact the prescriber for clarification. A nurse cannot modify a prescription.",
  "src": "Med Admin (1) 2026 slides 13 & 36"
 },
 {
  "quiz": "admin",
  "quizName": "M5 · Medication administration",
  "sys": "admin",
  "q": "A medication is repackaged by a pharmacist and shows only a dispensing date. It should be kept no longer than:",
  "options": [
   "1 month",
   "6 months",
   "12 months",
   "Until the manufacturer's original expiry"
  ],
  "correct": 2,
  "why": "Repackaged medications may only carry a dispensing date, not an expiry date; the deck states these should be kept no longer than 12 months after the dispensing date.",
  "src": "Med Admin (1) 2026 slide 42"
 },
 {
  "quiz": "admin",
  "quizName": "M5 · Medication administration",
  "sys": "admin",
  "q": "A patient competently refuses a prescribed medication. Which action is NOT correct?",
  "options": [
   "Explain the consequences of not taking it",
   "Document the reason for refusal",
   "Return the medication to the container for later use",
   "Inform the next shift RN and the prescriber"
  ],
  "correct": 2,
  "why": "Refused medications must be DISCARDED, not stored. The other three actions are all required.",
  "src": "Med Admin (1) 2026 slide 39"
 },
 {
  "quiz": "admin",
  "quizName": "M5 · Medication administration",
  "sys": "admin",
  "q": "When must a medication be documented as given?",
  "options": [
   "Before administering, so it is not forgotten",
   "Immediately after administration",
   "At the end of the medication round",
   "At the end of the shift"
  ],
  "correct": 1,
  "why": "Record immediately after administration — date, time, dose, who administered. \"Never document before you have actually administered it to the person.\"",
  "src": "Med Admin (1) 2026 slide 41"
 },
 {
  "quiz": "admin",
  "quizName": "M5 · Medication administration",
  "sys": "admin",
  "q": "Which professional group can prescribe ONLY with an additional qualification, and otherwise operates under standing orders?",
  "options": [
   "Registered midwives",
   "Optometrists",
   "Pharmacists",
   "Dentists"
  ],
  "correct": 2,
  "why": "Pharmacists cannot prescribe unless they hold the extra qualification as a Pharmacist Prescriber; they otherwise operate under standing orders. Midwives, optometrists and dentists are all authorised prescribers.",
  "src": "Med Admin (1) 2026 slides 4 & 12"
 },
 {
  "quiz": "admin",
  "quizName": "M5 · Medication administration",
  "sys": "admin",
  "q": "A tablet may be cut in half:",
  "options": [
   "Any time a half dose is prescribed",
   "Only with a tablet cutter, and only if it has a score mark",
   "Only by a pharmacist",
   "Never"
  ],
  "correct": 1,
  "why": "The deck: \"Cut tablets in half with a tablet cutter (only if has a score mark).\" Separately, check with a pharmacist before crushing any tablet.",
  "src": "Med Admin (1) 2026 slide 30"
 },
 {
  "quiz": "admin",
  "quizName": "M5 · Medication administration",
  "sys": "admin",
  "q": "\"NKDA\" documented in the medication chart means:",
  "options": [
   "No known drug allergies",
   "No known dose adjustment",
   "Not known, do not administer",
   "Nurse-checked, doctor advised"
  ],
  "correct": 0,
  "why": "NKDA = no known drug allergies; NKA = no known allergies. Both are from the Must Know Abbreviations table, and both must still be confirmed by asking the patient.",
  "src": "Med Admin (1) 2026 slide 43 · Must Know Abbreviations 01.26"
 },
 {
  "quiz": "educ",
  "quizName": "M5 · Patient education",
  "sys": "admin",
  "q": "A medication error is best defined as:",
  "options": [
   "Any harmful effect caused by a medicine",
   "Any preventable event that may cause or lead to inappropriate medication use or patient harm",
   "Any unexpected drug interaction",
   "Any dose given outside the therapeutic range"
  ],
  "correct": 1,
  "why": "This is the NCC MERP definition the deck quotes. An adverse effect is harm caused by the medicine itself; a medication error is a preventable event, often from human action.",
  "src": "Med Admin (2) 2026 slide 4"
 },
 {
  "quiz": "educ",
  "quizName": "M5 · Patient education",
  "sys": "admin",
  "q": "What is the FIRST step after realising you have made a medication error?",
  "options": [
   "Complete an incident report",
   "Acknowledge the error immediately",
   "Document it in the patient notes",
   "Tell the patient's family"
  ],
  "correct": 1,
  "why": "The sequence is: acknowledge immediately → report promptly to the appropriate person → document accurately and objectively → implement measures to minimise harm → complete an incident report.",
  "src": "Med Admin (2) 2026 slide 7"
 },
 {
  "quiz": "educ",
  "quizName": "M5 · Patient education",
  "sys": "admin",
  "q": "Which question best fits Step 3 (Check) of the health literacy model?",
  "options": [
   "\"Do you understand?\"",
   "\"Any questions?\"",
   "\"Can you tell me what you have to do, so I can check I explained it properly?\"",
   "\"You'll be fine with this, won't you?\""
  ],
  "correct": 2,
  "why": "That is teach-back, and it is phrased so responsibility sits with the nurse. The deck explicitly says to avoid closed questions like \"Do you understand?\" and not to rely on nodding.",
  "src": "Med Admin (2) 2026 slides 25–28"
 },
 {
  "quiz": "educ",
  "quizName": "M5 · Patient education",
  "sys": "admin",
  "q": "Which set of Te Tiriti principles does the Nursing Council use, per this course?",
  "options": [
   "Partnership, Participation, Protection",
   "Tino Rangatiratanga, Mana Taurite, Whakamarumarutia, Kōwhiringa, Pātuitanga",
   "Autonomy, Beneficence, Non-maleficence, Justice",
   "Ask, Build, Check"
  ],
  "correct": 1,
  "why": "The deck lists the five NCNZ (2025) principles and notes in its own speaker notes that the \"three Ps\" of 1986 are OUTDATED.",
  "src": "Med Admin (2) 2026 slide 33"
 },
 {
  "quiz": "educ",
  "quizName": "M5 · Patient education",
  "sys": "admin",
  "q": "Mana Taurite is best described as:",
  "options": [
   "Self-determination",
   "Equity",
   "Active protection",
   "Partnership"
  ],
  "correct": 1,
  "why": "Mana Taurite = Equity — removing barriers and adapting communication so understanding is equitable. Equity is unequal distribution for equal outcome.",
  "src": "Med Admin (2) 2026 slides 33 & 36"
 },
 {
  "quiz": "educ",
  "quizName": "M5 · Patient education",
  "sys": "admin",
  "q": "Which is NOT advice the deck gives about giving medicines to children?",
  "options": [
   "Store medicines out of reach and out of sight",
   "Use a proper measuring cup, spoon or syringe",
   "Tell the child the medicine is lollies so they take it",
   "Check with your pharmacist before crushing or cutting tablets"
  ],
  "correct": 2,
  "why": "Never tell a child their medicine is lollies — the deck flags it as an overdose risk, and Case Study 1 turns on exactly this point.",
  "src": "Med Admin (2) 2026 slides 42 & 44"
 },
 {
  "quiz": "educ",
  "quizName": "M5 · Patient education",
  "sys": "admin",
  "q": "A patient taking the combined oral contraceptive pill reports also taking St John's Wort. The documented risk is:",
  "options": [
   "Increased clotting risk",
   "Breakthrough bleeding and contraception failure",
   "Reduced absorption of iron",
   "Serotonin syndrome only"
  ],
  "correct": 1,
  "why": "The deck's Case Study 2 speaker note, citing the NZ Formulary interactions checker: \"Risks include breakthrough bleeding and contraception failure\" — St John's Wort is an enzyme inducer.",
  "src": "Med Admin (2) 2026 slide 49 (speaker notes)"
 },
 {
  "quiz": "elderly",
  "quizName": "M6 · The older adult",
  "sys": "life",
  "q": "People over 65 are about 12% of the NZ population. What share of prescribed medications do they consume?",
  "options": [
   "12%",
   "20%",
   "31%",
   "50%"
  ],
  "correct": 2,
  "why": "The deck: people over 65 constitute about 12% of the population but consume 31% of prescribed medications.",
  "src": "Elderly & Polypharmacy 2026 slide 8"
 },
 {
  "quiz": "elderly",
  "quizName": "M6 · The older adult",
  "sys": "life",
  "q": "In an older adult, reduced total body water means a water-soluble drug will have a:",
  "options": [
   "Longer, weaker effect",
   "Shorter, stronger effect",
   "Longer, stronger effect",
   "Unchanged effect"
  ],
  "correct": 1,
  "why": "Less body water means the same dose sits at a higher concentration — \"like a stronger cordial\" in the deck's own note — giving a shorter, stronger effect. Increased body FAT is what gives fat-soluble drugs a longer effect.",
  "src": "Elderly & Polypharmacy 2026 slide 14"
 },
 {
  "quiz": "elderly",
  "quizName": "M6 · The older adult",
  "sys": "life",
  "q": "Which age-related pharmacokinetic change is described in the lecture as \"often not clinically significant\"?",
  "options": [
   "Reduced renal excretion",
   "Slowed absorption",
   "Reduced protein binding",
   "Slowed hepatic metabolism"
  ],
  "correct": 1,
  "why": "Slowed gastric emptying, reduced motility and decreased intestinal surface area delay absorption, \"but often not clinically significant\". Reduced excretion and metabolism are what actually drive accumulation and toxicity.",
  "src": "Elderly & Polypharmacy 2026 slide 13"
 },
 {
  "quiz": "elderly",
  "quizName": "M6 · The older adult",
  "sys": "life",
  "q": "Polypharmacy is usually defined as the concurrent use of:",
  "options": [
   "2 or more medications",
   "3 or more medications",
   "5 or more medications",
   "10 or more medications"
  ],
  "correct": 2,
  "why": "Polypharmacy is the concurrent use of multiple medications, usually 5 or more. Ten or more is hyperpolypharmacy.",
  "src": "Elderly & Polypharmacy 2026 slides 34 & 38"
 },
 {
  "quiz": "elderly",
  "quizName": "M6 · The older adult",
  "sys": "life",
  "q": "Under the Beers Criteria, chronic use of NSAIDs such as ibuprofen in older adults should be:",
  "options": [
   "Encouraged as first-line analgesia",
   "Avoided",
   "Doubled in dose",
   "Given only intravenously"
  ],
  "correct": 1,
  "why": "The Beers table in the deck: NSAIDs — \"avoid chronic use\", because of gastritis, gastrointestinal bleeding and ulceration.",
  "src": "Elderly & Polypharmacy 2026 slide 18"
 },
 {
  "quiz": "elderly",
  "quizName": "M6 · The older adult",
  "sys": "life",
  "q": "Which is an error of OMISSION rather than commission?",
  "options": [
   "Taking the wrong dose",
   "Storing medication incorrectly",
   "Forgetting to take medication",
   "Taking expired medication"
  ],
  "correct": 2,
  "why": "Errors of omission are errors of not doing — forgetting to take medication, taking too low a dose, forgetting instructions, or taking a dose at the wrong time. The other three are errors of commission.",
  "src": "Elderly & Polypharmacy 2026 slide 29"
 },
 {
  "quiz": "elderly",
  "quizName": "M6 · The older adult",
  "sys": "life",
  "q": "A medication may be crushed:",
  "options": [
   "Whenever the patient has difficulty swallowing",
   "Only if a pharmacist advises it does not compromise the medication AND it is in the patient's best interest",
   "Only if it is enteric coated",
   "Only by the prescriber"
  ],
  "correct": 1,
  "why": "Both conditions must hold. Crushing can make a medication less effective, ineffective or dangerous — an enteric-coated tablet that is crushed becomes rapidly absorbed.",
  "src": "Elderly & Polypharmacy 2026 slide 22"
 },
 {
  "quiz": "elderly",
  "quizName": "M6 · The older adult",
  "sys": "life",
  "q": "The term that has replaced \"compliance\" in describing whether a patient takes their medication as intended is:",
  "options": [
   "Concordance",
   "Adherence",
   "Conformity",
   "Persistence"
  ],
  "correct": 1,
  "why": "The deck notes directly that adherence has replaced the older term \"compliance\".",
  "src": "Elderly & Polypharmacy 2026 slide 26"
 },
 {
  "quiz": "lifespan",
  "quizName": "M6 · Across the lifespan",
  "sys": "life",
  "q": "The highest-risk period for teratogenic effects is:",
  "options": [
   "The first trimester (weeks 0–12)",
   "The second trimester",
   "The third trimester",
   "Labour and delivery"
  ],
  "correct": 0,
  "why": "The deck: \"Highest risk is during first trimester (week 0 – 12).\" Cocaine is the one example in the table whose critical period is the 2nd–3rd trimester.",
  "src": "Lifespan 2026 slides 8 & 10"
 },
 {
  "quiz": "lifespan",
  "quizName": "M6 · Across the lifespan",
  "sys": "life",
  "q": "Which is a Pregnancy Category A medication in the lecture's example?",
  "options": [
   "Isotretinoin",
   "Paracetamol",
   "Tetracycline",
   "Cocaine"
  ],
  "correct": 1,
  "why": "Category A drugs have been taken by a large number of pregnant people without any proven increase in malformations or other harmful effects — paracetamol is the deck's example. Category X is the contraindicated end of the scale.",
  "src": "Lifespan 2026 slide 15"
 },
 {
  "quiz": "lifespan",
  "quizName": "M6 · Across the lifespan",
  "sys": "life",
  "q": "Renal excretion in pregnancy:",
  "options": [
   "Decreases, so lower doses are needed",
   "Increases, so higher or more frequent doses may be required",
   "Is unchanged",
   "Stops entirely for renally cleared drugs"
  ],
  "correct": 1,
  "why": "Increased renal blood flow increases elimination of renally cleared drugs, which may require higher or more frequent doses.",
  "src": "Lifespan 2026 slide 14"
 },
 {
  "quiz": "lifespan",
  "quizName": "M6 · Across the lifespan",
  "sys": "life",
  "q": "A neonate has an immature blood–brain barrier. The main consequence is:",
  "options": [
   "Reduced drug absorption",
   "Higher CNS toxicity risk",
   "Faster renal clearance",
   "Lower body water"
  ],
  "correct": 1,
  "why": "The deck lists immature BBB → higher CNS toxicity risk, alongside immature enzymes (reduced metabolism) and immature kidneys (slower clearance, prolonged half-life).",
  "src": "Lifespan 2026 slide 27"
 },
 {
  "quiz": "lifespan",
  "quizName": "M6 · Across the lifespan",
  "sys": "life",
  "q": "Hepatic metabolism in children is:",
  "options": [
   "Slower than adults until about 10 years",
   "Faster than adults until about 10 years, so higher mg/kg doses may be needed",
   "The same as adults from birth",
   "Absent until 12 months"
  ],
  "correct": 1,
  "why": "Hepatic metabolism is faster until about 10 years, which may require higher mg/kg doses. It is the NEONATE whose enzymes are immature and metabolism reduced.",
  "src": "Lifespan 2026 slide 28"
 },
 {
  "quiz": "lifespan",
  "quizName": "M6 · Across the lifespan",
  "sys": "life",
  "q": "Which drugs concentrate most in breastmilk?",
  "options": [
   "Water-soluble drugs that do not affect the nervous system",
   "Lipid-soluble drugs that affect the nervous system, e.g. morphine or codeine",
   "Drugs that are highly protein bound",
   "Drugs given intravenously"
  ],
  "correct": 1,
  "why": "The deck: drugs that affect the nervous system and are lipid-soluble concentrate more in breastmilk, and can cause infant sedation and a reduced suckling reflex with poor feeding.",
  "src": "Lifespan 2026 slide 19"
 },
 {
  "quiz": "lifespan",
  "quizName": "M6 · Across the lifespan",
  "sys": "life",
  "q": "Tetracycline antibiotics taken after 20 weeks of pregnancy are associated with:",
  "options": [
   "Hydrocephalus and CNS abnormalities",
   "Premature labour and intracranial bleeding",
   "Stained teeth and bone growth defects",
   "Fetal alcohol syndrome"
  ],
  "correct": 2,
  "why": "From the teratogen table: tetracycline antibiotics, >20 weeks, stained teeth and bone growth defects. Hydrocephalus/CNS is isotretinoin; premature labour/intracranial bleeding is cocaine.",
  "src": "Lifespan 2026 slide 10"
 },
 {
  "quiz": "lifespan",
  "quizName": "M6 · Across the lifespan",
  "sys": "life",
  "q": "A neonate is defined as:",
  "options": [
   "Less than 4 weeks old",
   "5 weeks to 1 year",
   "Born before 36 weeks gestation",
   "1 to 12 years"
  ],
  "correct": 0,
  "why": "Neonate/newborn = less than 4 weeks old. 5 weeks to 1 year is an infant; before 36 weeks gestation is preterm; 1–12 years is a child.",
  "src": "Lifespan 2026 slide 26"
 },
 {
  "quiz": "legal",
  "quizName": "M7 · Legal & ethical",
  "sys": "law",
  "q": "Morphine is which class of controlled drug under the Misuse of Drugs Act 1975?",
  "options": [
   "Class A",
   "Class B",
   "Class C",
   "Uncontrolled"
  ],
  "correct": 1,
  "why": "Class B includes drugs of dependence, carries a high risk of harm, has restrictions on prescribing and dispensing, and must be kept in a double-locked safe — morphine and methylphenidate are the deck's examples.",
  "src": "Legal & Ethical 2026 slide 14"
 },
 {
  "quiz": "legal",
  "quizName": "M7 · Legal & ethical",
  "sys": "law",
  "q": "Which Act requires Registered Nurses to hold an Annual Practising Certificate?",
  "options": [
   "The Medicines Act 1981",
   "The Misuse of Drugs Act 1975",
   "The Health Practitioners Competence Assurance Act 2003",
   "The Medicines Regulations 1984"
  ],
  "correct": 2,
  "why": "The HPCAA 2003 requires a scope of practice set by the Nursing Council, annual practising certificates, clinical and cultural competence, and provides legal accountability.",
  "src": "Legal & Ethical 2026 slides 30–31"
 },
 {
  "quiz": "legal",
  "quizName": "M7 · Legal & ethical",
  "sys": "law",
  "q": "Cultural safety is determined by:",
  "options": [
   "The nurse providing the care",
   "The person or family receiving the care",
   "The Nursing Council",
   "The employing organisation"
  ],
  "correct": 1,
  "why": "The NCNZ definition: \"the effective nursing practice of a person or family from another culture, and is determined by that person or family.\"",
  "src": "Legal & Ethical 2026 slide 41"
 },
 {
  "quiz": "legal",
  "quizName": "M7 · Legal & ethical",
  "sys": "law",
  "q": "Which is NOT one of the six pou of the NCNZ Standards of Competence?",
  "options": [
   "Māori Health",
   "Cultural Safety",
   "Kaitiakitanga and Sustainability",
   "Rangatiratanga and Leadership"
  ],
  "correct": 2,
  "why": "The six pou are Māori Health; Cultural Safety; Whanaungatanga and Communication; Pūkengatanga and Evidence-Informed Nursing Practice; Manaakitanga and People-Centred Care; Rangatiratanga and Leadership. Kaitiakitanga is an NZNO Code of Ethics value, not a pou.",
  "src": "Legal & Ethical 2026 slides 38 & 64"
 },
 {
  "quiz": "legal",
  "quizName": "M7 · Legal & ethical",
  "sys": "law",
  "q": "A nurse withholds a patient's prognosis because the patient has explicitly asked not to be told. This is an exception to:",
  "options": [
   "Confidentiality",
   "Veracity",
   "Beneficence",
   "Fidelity"
  ],
  "correct": 1,
  "why": "Veracity is the duty to tell the truth; the three exceptions are therapeutic privilege, patient preference, and emergencies.",
  "src": "Legal & Ethical 2026 slide 78"
 },
 {
  "quiz": "legal",
  "quizName": "M7 · Legal & ethical",
  "sys": "law",
  "q": "\"Treating people fairly and equitably (not equally)\" is the definition of which Western value?",
  "options": [
   "Autonomy",
   "Beneficence",
   "Justice",
   "Fidelity"
  ],
  "correct": 2,
  "why": "Justice — be fair; treat people fairly and equitably, ensure fair access to care and unbiased decision-making. The deck explicitly contrasts equitably with equally.",
  "src": "Legal & Ethical 2026 slide 76"
 },
 {
  "quiz": "legal",
  "quizName": "M7 · Legal & ethical",
  "sys": "law",
  "q": "Which document is a GUIDELINE rather than an enforceable standard?",
  "options": [
   "The HPCAA 2003",
   "NCNZ Standards of Competence",
   "NCNZ Code of Conduct",
   "NZNO Code of Ethics"
  ],
  "correct": 3,
  "why": "From the summary table: the NZNO Code of Ethics \"is a guideline, but expected to be used by all RNs\". The other three are enforceable — by law, by APC requirement, and by NCNZ discipline respectively.",
  "src": "Legal & Ethical 2026 slide 90"
 },
 {
  "quiz": "legal",
  "quizName": "M7 · Legal & ethical",
  "sys": "law",
  "q": "Checking whether gelatin capsules conflict with a patient's beliefs is an example of which Code of Conduct principle?",
  "options": [
   "Principle 1 — dignity and individuality",
   "Principle 2 — cultural needs and values",
   "Principle 5 — privacy and confidentiality",
   "Principle 8 — public trust"
  ],
  "correct": 1,
  "why": "Principle 2 is to respect the cultural needs and values of health consumers, and gelatin capsules are the deck's own example.",
  "src": "Legal & Ethical 2026 slide 56"
 },
 {
  "quiz": "legal",
  "quizName": "M7 · Legal & ethical",
  "sys": "law",
  "q": "In the 2013 case, what did the Nursing Council identify in addition to giving the wrong medication?",
  "options": [
   "She was not wearing an ID badge",
   "She took two days to report the error",
   "She was working a double shift",
   "She had no APC"
  ],
  "correct": 1,
  "why": "Nurse D did not check the medication was appropriate nor check pulse or blood pressure, realised 20 minutes later, and took two days to report the error. She was found guilty of professional misconduct, suspended and fined $12,000.",
  "src": "Legal & Ethical 2026 slides 26–27"
 },
 {
  "quiz": "devmkt",
  "quizName": "M7 · Drug development & marketing",
  "sys": "law",
  "q": "Roughly how many of 5000 compounds progress to human testing?",
  "options": [
   "500",
   "50",
   "5",
   "1500"
  ],
  "correct": 2,
  "why": "\"According to USA statistics only 5 in 5000 compounds progress to human testing.\" Development also costs millions and takes 10–20 years.",
  "src": "Drug Development & Marketing slide 4"
 },
 {
  "quiz": "devmkt",
  "quizName": "M7 · Drug development & marketing",
  "sys": "law",
  "q": "Which clinical trial phase focuses on SAFETY AND DOSAGE with 20–100 participants?",
  "options": [
   "Phase 1",
   "Phase 2",
   "Phase 3",
   "Phase 4"
  ],
  "correct": 0,
  "why": "Phase 1: safety and dosage, 20–100 participants (healthy or with the condition), several months, ~70% progress. Phase 2 is efficacy and side effects in several hundred participants.",
  "src": "Drug Development & Marketing slide 10"
 },
 {
  "quiz": "devmkt",
  "quizName": "M7 · Drug development & marketing",
  "sys": "law",
  "q": "Which body assesses the science, safety and appropriateness of a proposed trial DESIGN in NZ?",
  "options": [
   "Medsafe",
   "SCOTT",
   "HDEC",
   "PHARMAC"
  ],
  "correct": 1,
  "why": "SCOTT — the Standing Committee on Therapeutic Trials. Medsafe reviews preclinical studies, PK/PD, chemical stability and quality; HDEC checks ethical compliance.",
  "src": "Drug Development & Marketing slide 9"
 },
 {
  "quiz": "devmkt",
  "quizName": "M7 · Drug development & marketing",
  "sys": "law",
  "q": "An advertisement that mentions only the drug name, without saying what it treats, is a:",
  "options": [
   "Direct-to-consumer ad",
   "Health-seeking ad",
   "Reminder ad",
   "Professional/journal ad"
  ],
  "correct": 2,
  "why": "Reminder ads mention the drug name only, without stating what it treats. Health-seeking ads educate about a condition; direct-to-consumer ads promote a specific branded prescription medicine.",
  "src": "Drug Development & Marketing slide 26"
 },
 {
  "quiz": "devmkt",
  "quizName": "M7 · Drug development & marketing",
  "sys": "law",
  "q": "Which drug was originally developed for blood pressure and is now used as a topical hair-restoring agent?",
  "options": [
   "Sildenafil",
   "Minoxidil",
   "Penicillin",
   "Isotretinoin"
  ],
  "correct": 1,
  "why": "Minoxidil was originally developed for blood pressure. Sildenafil was developed for angina and high blood pressure and is now used for impotence; penicillin was discovered from a mould.",
  "src": "Drug Development & Marketing slide 5"
 },
 {
  "quiz": "devmkt",
  "quizName": "M7 · Drug development & marketing",
  "sys": "law",
  "q": "Which statement about a nurse and medicine advertising is CORRECT?",
  "options": [
   "Advertising rules apply only to printed media",
   "Verbal recommendation of a brand can count as advertising",
   "Nurses are exempt from all advertising rules",
   "Advertising unapproved medicines to health professionals is permitted"
  ],
  "correct": 1,
  "why": "Advertising is defined broadly and includes verbal advertising, so praising one brand over another is caught. The rules apply across all media, and advertising unapproved medicines is prohibited even to health professionals.",
  "src": "Drug Development & Marketing slides 30 & 32"
 },
 {
  "quiz": "devmkt",
  "quizName": "M7 · Drug development & marketing",
  "sys": "law",
  "q": "Placebo use in a trial is ethically acceptable when:",
  "options": [
   "The trial sponsor requires it",
   "No proven treatment exists, or it is necessary for methodology without causing serious harm",
   "Participants are reimbursed",
   "The condition is life-threatening"
  ],
  "correct": 1,
  "why": "Placebo use is problematic if recipients risk harm or worsening of their condition; it is acceptable when no proven treatment exists, or where necessary for methodology without causing serious harm.",
  "src": "Drug Development & Marketing slide 17"
 },
 {
  "quiz": "allergy",
  "quizName": "M8 · Anaphylaxis (ASCIA plan)",
  "sys": "imm",
  "q": "What is step 1 of the ASCIA anaphylaxis action plan?",
  "options": [
   "Give the adrenaline device",
   "Phone an ambulance",
   "Lay the person flat",
   "Give an antihistamine"
  ],
  "correct": 2,
  "why": "Step 1 is to lay the person flat and NOT allow them to stand or walk. The adrenaline device is step 2, and phoning the ambulance is step 3.",
  "src": "ASCIA Action Plan for Anaphylaxis (2026), p.1"
 },
 {
  "quiz": "allergy",
  "quizName": "M8 · Anaphylaxis (ASCIA plan)",
  "sys": "imm",
  "q": "A person with known asthma and a food allergy has sudden wheeze after a suspected exposure. You should give:",
  "options": [
   "The asthma reliever puffer first, then adrenaline",
   "The adrenaline device first, then the asthma reliever puffer",
   "An antihistamine only",
   "Nothing until skin symptoms appear"
  ],
  "correct": 1,
  "why": "\"ALWAYS GIVE ADRENALINE DEVICE FIRST, then asthma reliever puffer.\" Anaphylaxis can occur without skin symptoms, so waiting for a rash is not safe.",
  "src": "ASCIA Action Plan for Anaphylaxis (2026), p.1"
 },
 {
  "quiz": "allergy",
  "quizName": "M8 · Anaphylaxis (ASCIA plan)",
  "sys": "imm",
  "q": "After giving adrenaline with no response, how long before further adrenaline may be given?",
  "options": [
   "1 minute",
   "5 minutes",
   "15 minutes",
   "30 minutes"
  ],
  "correct": 1,
  "why": "Step 5 of the plan: further adrenaline may be given if there is no response after 5 minutes. Step 6 is transfer to hospital for at least 4 hours of observation.",
  "src": "ASCIA Action Plan for Anaphylaxis (2026), p.1"
 },
 {
  "quiz": "allergy",
  "quizName": "M8 · Anaphylaxis (ASCIA plan)",
  "sys": "imm",
  "q": "A pregnant person is unconscious from anaphylaxis. They should be placed:",
  "options": [
   "Sitting upright",
   "In the recovery position on the left side",
   "Flat on their back with legs raised",
   "Standing supported"
  ],
  "correct": 1,
  "why": "If unconscious or pregnant, place in the recovery position — on the LEFT side if pregnant.",
  "src": "ASCIA Action Plan for Anaphylaxis (2026), p.1"
 },
 {
  "quiz": "allergy",
  "quizName": "M8 · Anaphylaxis (ASCIA plan)",
  "sys": "imm",
  "q": "Abdominal pain and vomiting are signs of ANAPHYLAXIS (rather than a mild-to-moderate reaction) in which situation?",
  "options": [
   "Food allergy",
   "Medication allergy",
   "Insect allergy",
   "Latex allergy"
  ],
  "correct": 2,
  "why": "The plan annotates abdominal pain and vomiting with \"these are signs of anaphylaxis for insect allergy\" in both columns.",
  "src": "ASCIA Action Plan for Anaphylaxis (2026), p.1"
 }
];
