/* Daniel Kerr — decompensated liver disease, a long stay. Teaches: a RECHARTED chart (Date Recharted on the front);
   Special Care — hepatic impairment; a VARIABLE dose (lactulose 10–30 mL, titrated to his stools — the dose given
   goes in the Dose column); N when the drug is not on the ward yet (the reason goes in the notes); a PRN maximum
   that is not the textbook one (paracetamol 2 g, because of his liver) — a round where the right move is to give
   nothing; D when a blood result crosses the line on the order. */
export default {
  id: 'liver', t: 'Daniel Kerr, 48', sub: 'Liver disease — ascites and confusion, 11 days in',
  story: 'Daniel has cirrhosis from alcohol and came in eleven days ago with a swollen abdomen and confusion (hepatic encephalopathy). His first chart ran out, so this one was rewritten on Monday. The plan: lactulose titrated to two or three soft stools a day, rifaximin (started last night — pharmacy is still sourcing it), spironolactone for the fluid, propranolol for his varices. His INR is high, so no enoxaparin. Paracetamol is kept to 2 g a day for his liver. It is Wednesday, 0730.',
  start: [26, 10, 2026], now: '3@0730', recharted: 1,
  patient: { family: 'KERR', given: 'Daniel', gender: 'M', dob: '23/01/1978', nhi: 'ZMD6405', weight: 81, height: 180 },
  prescribers: [
    { id: 'gs', name: 'SINGH, Gurpreet · Gastro Registrar', sig: 'GSingh', reg: '40318' },
    { id: 'lb', name: 'BROWN, Lucy · House Officer', sig: 'LBrown', reg: '54102' },
  ],
  nurses: [
    { name: 'WALKER, Huia · RN', init: 'HW', reg: '218840' },
    { name: 'KAWHIA, Rangi · RN', init: 'RK', reg: '236675' },
    { name: 'MORRIS, Jade · RN', init: 'JM', reg: '240553' },
    { name: 'TIPENE, Dan · RN', init: 'DT', reg: '229104' },
  ],
  allergies: [], allergyBy: 'gs',
  adverse: [{ med: 'FUROSEMIDE', rx: 'Sodium fell to 124', by: 'gs' }],
  special: ['hep'], supplementary: [],
  vte: { by: 'gs', day: 1, anticoag: false, none: 'bleed', stockings: true, ipc: false },
  regular: [
    { L: 'I', day: 1, startT: '0800', med: 'LACTULOSE', dose: '20', range: '10 – 30', units: 'mL', route: 'PO', freq: 'TDS', times: '0800 1400 2000', by: 'gs', inst: 'Titrate to 2–3 soft stools a day',
      given: { '1@0800': '0810 HW dose=20mL', '1@1400': '1405 HW dose=20mL', '1@2000': 'JM dose=20mL', '2@0800': '0805 HW dose=20mL', '2@1400': '1410 HW dose=10mL', '2@2000': 'JM dose=10mL',
        '3@2000': 'JM dose=20mL' } },
    { L: 'J', day: 2, startT: '2000', med: 'RIFAXIMIN', dose: '550', units: 'mg', route: 'PO', freq: 'BD', times: '0800 2000', by: 'gs', inst: 'New — pharmacy to supply',
      given: { '2@2000': 'N', '3@2000': 'JM' } },
    { L: 'K', day: 1, startT: '0800', med: 'SPIRONOLACTONE', dose: '100', units: 'mg', route: 'PO', freq: 'mane', times: '0800', by: 'gs', inst: 'Withhold if K+ > 5.5 — tell dr',
      given: { '1@0800': '0810 HW', '2@0800': '0805 HW' } },
    { L: 'L', day: 1, startT: '0800', med: 'PROPRANOLOL', dose: '20', units: 'mg', route: 'PO', freq: 'BD', times: '0800 2000', by: 'gs', inst: 'Withhold if HR < 55 or SBP < 90',
      given: { '1@0800': '0810 HW', '1@2000': 'JM', '2@0800': '0805 HW', '2@2000': 'JM', '3@2000': 'JM' } },
    { L: 'M', day: 1, startT: '0800', med: 'THIAMINE', dose: '100', units: 'mg', route: 'PO', freq: 'mane', times: '0800', by: 'gs',
      given: { '1@0800': '0810 HW', '2@0800': '0805 HW' } },
  ],
  prn: [
    { L: 'A', day: 1, med: 'PARACETAMOL', dose: '1', units: 'g', route: 'PO', freq: 'q6h', max: '2 g', gapH: 6, maxAmount: 2, ind: 'Pain', by: 'gs', inst: 'LIVER: max 2 g in 24 h',
      given: ['2@1500 1g PO JM', '3@0200 1g PO DT', '3@1600 1g PO JM'] },
    { L: 'B', day: 1, med: 'ONDANSETRON', dose: '4', units: 'mg', route: 'PO', freq: 'q8h', max: '12 mg', gapH: 8, maxAmount: 12, ind: 'Nausea', by: 'gs', given: [] },
  ],
  once: [
    { day: 1, at: '1@0900', med: 'PHYTOMENADIONE (VIT K)', dose: '10', units: 'mg', route: 'IV', by: 'gs', inst: 'Slowly over 3 min. INR 2.4', given: { at: '1@1030', giv: 'HW', chk: 'RK' } },
  ],
  questions: [
    { id: 'paramax', tag: 'PRN', q: 'Paracetamol’s usual maximum is 4 g a day. What is Daniel’s?', a: '2 g in 24 hours — his order says so, for his liver',
      w: ['4 g — the usual adult maximum always applies', '3 g — the chart’s key sets that for everyone', 'None — PRN means as much as he needs'],
      show: ['prn.A.max', 'prn.A.inst'], why: 'Max dose/24hrs on the order: 2 g. The chart, not the textbook, sets the limit — and the Special Care box says why: hepatic impairment.' },
    { id: 'var', tag: 'Regular', q: 'How much lactulose was given at 1400 yesterday?', a: '10 mL — written in its Dose column',
      w: ['20 mL — the dose written on the order', '30 mL — the top of the dose range', 'None — the box was left empty'],
      show: ['reg.I.d2.s2.dose', 'reg.I.range'], why: 'A variable dose: the order gives a range (10–30 mL), and each box records what was actually given.' },
    { id: 'vteq', tag: 'Regular', q: 'Why is there no enoxaparin on Daniel’s chart?', a: 'The VTE box: high bleeding risk — stockings instead',
      w: ['It was forgotten — ask for it to be charted', 'It is on a separate heparin chart', 'He takes warfarin at home instead'],
      show: ['vte.bleed', 'vte.stock.y'], why: 'The VTE box on the Regular page: no anticoagulant, with the reason ticked (high bleeding risk — his INR), and compression stockings Yes.' },
  ],
  rounds: [
    { at: '3@0810', rn: 'HW', title: '0800 med round',
      brief: ['Your first morning with Huia Walker (RN, initials HW). You have not signed Daniel’s chart before.',
        'Obs at 0730: HR 72, BP 108/64. His potassium this morning is 4.9. He had one soft stool yesterday — under his target — so Huia says to give 30 mL of lactulose.',
        '0810 — with Huia checking, you give Daniel his 0800 medicines. The rifaximin is still not on the ward: pharmacy is sending it later this morning.'],
      ask: [{ id: 'r1var', tag: 'Regular', q: 'The lactulose order says 20 mL, with a range of 10–30 mL. You give 30 mL. Where does the 30 go?', a: 'In the Dose column beside the time — a variable dose',
        w: ['Nowhere — any dose in the range counts as the order', 'Cross out the 20 on the order and write 30 there', 'In the PRN record, because it is more than charted'],
        show: ['reg.I.range', 'reg.I.d2.s2.dose'], why: 'The chart’s own instruction: “For variable dose, record actual dose given.” Yesterday’s 1400 box shows how.' }],
      expect: [
        { do: 'reg' },
        { do: 'sign', c: 'reg.I.d3.s1', t: '0810', dose: ['30 mL', '30mL', '30'] },
        { do: 'code', c: 'reg.J.d3.s1', code: 'N', why: 'Not given because the drug is not on the ward yet: N — and Huia writes the reason in the notes and chases pharmacy.' },
        { do: 'sign', c: 'reg.K.d3.s1', t: '0810' },
        { do: 'sign', c: 'reg.L.d3.s1', t: '0810' },
        { do: 'sign', c: 'reg.M.d3.s1', t: '0810' },
      ] },
    { at: '3@1405', rn: 'HW', title: '1400',
      brief: ['Daniel has had three loose stools since breakfast — the top of his target. Huia says to give the bottom of the range: 10 mL.',
        '1405 — with Huia checking, you give Daniel 10 mL of lactulose.'],
      expect: [{ do: 'sign', c: 'reg.I.d3.s2', t: '1405', dose: ['10 mL', '10mL', '10'] }] },
    { at: '3@1410', rn: 'HW', title: 'A headache',
      brief: ['1410 — Daniel has a headache and asks for paracetamol. You check his chart with Huia.'],
      ask: [{ id: 'r3para', tag: 'PRN', q: 'Can Daniel have 1 g of paracetamol at 1410?', a: 'No — he has had his 2 g max in 24 h',
        w: ['Yes — the usual maximum is 4 g a day', 'Yes — his last dose was 12 hours ago', 'Yes — but only 500 mg, to be safe'],
        show: ['prn.A.max', 'prn.A.0.time', 'prn.A.1.time'], why: '1 g at 1500 yesterday and 1 g at 0200: 2 g in the last 24 hours, his maximum. From 1500 the first dose drops out of the 24 hours.' }],
      expect: [{ do: 'none', c: 'prn.A', what: 'Paracetamol (PRN A)', why: 'he has had his 2 g in the last 24 hours. Huia tells the doctor about the headache; from 1500 one dose falls out of the 24 hours.' }] },
    { at: '4@0810', rn: 'HW', title: 'Thursday: 0800 med round',
      brief: ['Thursday — your second morning with Daniel and Huia (HW). The rifaximin arrived yesterday afternoon.',
        'Obs at 0730: HR 70, BP 110/66. His potassium is 5.9 this morning, and Dr Brown says to withhold the spironolactone today.',
        'Two soft stools yesterday afternoon and evening — on target — so Huia says the usual 20 mL of lactulose.',
        '0810 — with Huia checking, you give Daniel his other 0800 medicines.'],
      ask: [{ id: 'r4k', tag: 'Regular', q: 'Daniel’s potassium is 5.9. Row K (spironolactone) says withhold if K+ > 5.5. What goes in the box?', a: 'D — withheld on the prescriber’s instruction',
        w: ['R — he did not take it this morning', 'N — not given, reason in the notes', 'Your initials — give it, then tell the doctor'],
        show: ['reg.K.inst'], why: 'The order’s own limit, and Dr Brown’s instruction: D, prescriber’s instructions.' }],
      expect: [
        { do: 'sign', c: 'reg.I.d4.s1', t: '0810', dose: ['20 mL', '20mL', '20'] },
        { do: 'sign', c: 'reg.J.d4.s1', t: '0810' },
        { do: 'code', c: 'reg.K.d4.s1', code: 'D', why: 'Withheld on the prescriber’s instruction (potassium 5.9): D.' },
        { do: 'sign', c: 'reg.L.d4.s1', t: '0810' },
        { do: 'sign', c: 'reg.M.d4.s1', t: '0810' },
      ] },
  ],
};
