/* Tom Brennan — Parkinson's disease, in with a urinary infection. Teaches: TIME-CRITICAL levodopa at his own times
   (written beside the printed rows, not circled — and the 30-minute window works both ways, so it goes before an
   X-ray, not after); an IV antibiotic his RN gives and signs, so the student signs nothing there; a refused
   laxative (R); metoclopramide on his Adverse Reactions, which a phone order runs into; a weight-based ED dose
   in the Dose calculation box. */
export default {
  id: 'pd', t: 'Tom Brennan, 74', sub: 'Parkinson’s disease — in with a urinary infection',
  story: 'Tom has had Parkinson’s for nine years; at home he takes his Sinemet at 0700, 1100, 1500 and 1900 and manages well. He came in through ED on Monday with a urinary infection and a fever — gentamicin in ED, then IV amoxicillin. He is more confused than usual and his tremor is worse when his Sinemet runs late, which it did once yesterday. It is Wednesday, 0650.',
  start: [19, 10, 2026], now: '3@0650',
  patient: { family: 'BRENNAN', given: 'Tom', gender: 'M', dob: '08/05/1952', nhi: 'ZJP3186', weight: 76, height: 178 },
  prescribers: [
    { id: 'ed', name: 'NGATA, Rewi · ED Registrar', sig: 'RNgata', reg: '44102' },
    { id: 'mc', name: 'CHEN, Michael · Med Registrar', sig: 'MChen', reg: '42219' },
    { id: 'hf', name: 'FRASER, Holly · House Officer', sig: 'HFraser', reg: '53877' },
  ],
  nurses: [
    { name: 'WONG, Mia · RN (ED)', init: 'MW', reg: '232871' },
    { name: 'POMARE, Luke · RN (ED)', init: 'LP', reg: '241630' },
    { name: 'KALU, Ngozi · RN', init: 'NK', reg: '239918' },
    { name: 'VEA, Sam · RN', init: 'SV', reg: '237745' },
    { name: 'REID, Chris · RN', init: 'CR', reg: '226950' },
    { name: 'TUALA, Ana · RN', init: 'AT', reg: '214406' },
  ],
  allergies: [{ med: 'TRIMETHOPRIM', rx: 'Rash', by: 'mc' }],
  adverse: [{ med: 'METOCLOPRAMIDE', rx: 'Rigidity, worse tremor', by: 'mc' }],
  special: [], supplementary: [],
  vte: { by: 'mc', day: 1, anticoag: true, stockings: false, ipc: false },
  regular: [
    { L: 'I', day: 1, startT: '1500', med: 'LEVODOPA + CARBIDOPA 100/25', dose: '1', units: 'tab', route: 'PO', freq: 'QID', times: '0700 1100 1500 1900', by: 'mc', inst: 'TIME CRITICAL — within 30 min of the time. His own times',
      given: { '1@1500': '1510 NK', '1@1900': '1905 NK', '2@0700': '0705 CR', '2@1100': '1100 AT', '2@1500': '1535 NK', '2@1900': '1900 NK' } },
    { L: 'J', day: 1, startT: '1400', med: 'AMOXICILLIN', dose: '1', units: 'g', route: 'IV', freq: 'q8h', times: '0600 1400 2200', by: 'mc', inst: 'IV over 3–5 min',
      given: { '1@1400': '1430 MW/LP', '1@2200': 'SV', '2@0600': 'CR', '2@1400': 'AT', '2@2200': 'SV', '3@0600': 'CR' } },
    { L: 'K', day: 1, startT: '1400', med: 'ASPIRIN', dose: '100', units: 'mg', route: 'PO', freq: 'mane', times: '0800', by: 'mc', inst: 'With food',
      given: { '2@0800': '0810 AT' } },
    { L: 'L', day: 1, startT: '1400', med: 'MACROGOL 3350', dose: '1', units: 'sachet', route: 'PO', freq: 'mane', times: '0800', by: 'mc', inst: 'In 125 mL of water',
      given: { '2@0800': '0810 AT' } },
    { L: 'M', day: 1, startT: '1400', med: 'ATORVASTATIN', dose: '40', units: 'mg', route: 'PO', freq: 'nocte', times: '2000', by: 'mc',
      given: { '1@2000': 'NK', '2@2000': 'NK' } },
    { L: 'N', day: 1, startT: '1400', med: 'ENOXAPARIN', dose: '40', units: 'mg', route: 'SC', freq: 'daily', times: '1800', by: 'mc',
      given: { '1@1800': 'NK', '2@1800': 'NK' } },
  ],
  prn: [
    { L: 'A', day: 1, med: 'PARACETAMOL', dose: '1', units: 'g', route: 'PO', freq: 'q4h', max: '4 g', gapH: 4, maxAmount: 4, ind: 'Pain / fever', by: 'mc',
      given: ['1@2300 1g PO SV', '2@1600 1g PO NK', '3@0520 1g PO CR'] },
    { L: 'B', day: 1, med: 'ONDANSETRON', dose: '4', units: 'mg', route: 'PO/IV', freq: 'q8h', max: '12 mg', gapH: 8, maxAmount: 12, ind: 'Nausea', by: 'mc', inst: 'NOT metoclopramide — Parkinson’s',
      given: ['2@0200 4mg PO SV'] },
  ],
  once: [
    { day: 1, at: '1@1300', med: 'GENTAMICIN', dose: '380', units: 'mg', route: 'IV', calc: '5 mg/kg (76 kg)', by: 'ed', inst: 'In 100 mL NaCl 0.9% over 30 min',
      given: { at: '1@1335', giv: 'MW', chk: 'LP' } },
  ],
  fluids: [
    { day: 1, at: '1@1300', time: '1300', vol: 1000, fluid: 'SODIUM CHLORIDE 0.9%', route: 'IV', rate: 125, by: 'ed', started: { at: '1@1310', by: 'MW', chk: 'LP' }, done: { at: '1@2110', vol: 1000 } },
  ],
  questions: [
    { id: 'meto', tag: 'Front page', q: 'Tom feels sick, and the house officer on the phone says “give him some metoclopramide”. What do you say?', a: 'It’s on his Adverse Reactions and worsens Parkinson’s — ask for ondansetron',
      w: ['Fine — metoclopramide is on his PRN page, so it can be given straight away', 'Give it — an adverse reaction is not an allergy, so it is safe to give him', 'Give half the usual dose, and watch his tremor closely for the next hour'],
      show: ['adr.0.med', 'adr.0.rx', 'prn.B.inst'], why: 'Adverse Reactions: METOCLOPRAMIDE — rigidity, worse tremor. It blocks dopamine, the very thing his Sinemet replaces; his PRN ondansetron order even says so.' },
    { id: 'late', tag: 'Regular', q: 'Look at Tom’s 1500 Sinemet on Tuesday (20/10). Was it on time?', a: 'No — given at 1535, 35 minutes late for a time-critical medicine',
      w: ['Yes — 1535 is in the same hour, and anything in the hour counts', 'Yes — Parkinson’s medicines can be given at any time of the day', 'It was not given — the box shows a not-given code instead'],
      show: ['reg.I.d2.s2.t', 'reg.I.inst'], why: 'The Time column beside Tuesday’s 1500 line says 1535. His order says within 30 minutes of the time.' },
    { id: 'gent', tag: 'Once Only', q: 'How was Tom’s gentamicin dose in ED worked out?', a: '5 mg/kg × 76 kg = 380 mg — the Dose calculation box',
      w: ['A standard adult dose of 380 mg for everyone', '4 mg/kg × 95 kg, his ideal body weight', 'It is not written anywhere on this chart'],
      show: ['once.0.calc', 'once.0.dose'], why: 'Dose calculation (eg. mg/kg per dose) on the Once Only order — and his weight is on page 2.' },
    { id: 'times', kind: 'tap', tag: 'Regular', q: 'Tom’s Sinemet times are not the printed ones. Tap where his 1100 dose time is written.', accept: ['reg.I.s1'],
      why: 'The “Circle or actual time” column: no printed row says 1100, so 1100 is written in the box beside the 0800 row.' },
  ],
  rounds: [
    { at: '3@0705', rn: 'AT', title: '0700: time-critical',
      brief: ['Your first morning with Ana Tuala (RN, initials AT). You have not signed Tom’s chart before.',
        '0700 — handover is still going, but Tom’s Sinemet is due at 0700. Ana steps out with you, and at 0705 you give it, Ana checking.'],
      ask: [{ id: 'r1tc', tag: 'Judgement', q: 'Tom’s Sinemet is due at 0700, in the middle of handover. When should it be given?', a: 'On time — within 30 minutes of 0700, handover or not',
        w: ['After handover, when the med round reaches him', 'With his 0800 tablets, to save a second trip', 'Only if his tremor is bad this morning'],
        show: ['reg.I.inst', 'reg.I.s0'], why: 'TIME CRITICAL on the order. Late levodopa can leave someone with Parkinson’s stiff, unable to swallow or to walk.' }],
      expect: [
        { do: 'reg' },
        { do: 'sign', c: 'reg.I.d3.s0', t: '0705' },
      ] },
    { at: '3@0810', rn: 'AT', title: '0800 med round',
      brief: ['0810 — with Ana checking, you give Tom his aspirin with breakfast.',
        '0810 — he refuses the macrogol: “My bowels are fine — I went yesterday.”'],
      expect: [
        { do: 'sign', c: 'reg.K.d3.s1', t: '0810' },
        { do: 'code', c: 'reg.L.d3.s1', code: 'R', why: 'He refused it: R. Tell Ana, too — constipation slows how well levodopa is absorbed.' },
      ] },
    { at: '3@1045', rn: 'AT', title: 'Off to X-ray',
      brief: ['1040 — an orderly arrives to take Tom for a chest X-ray; he will be away about an hour. His Sinemet is due at 1100.',
        '1045 — you and Ana give it before he goes.'],
      ask: [{ id: 'r3xr', tag: 'Judgement', q: 'Tom is off to X-ray at 1045 for an hour, and his Sinemet is due at 1100. What is the safe plan?', a: 'Give it now — 1045 is within 30 minutes of 1100',
        w: ['Send him, and give it when he is back at 1145', 'Send the tablet with him for the radiographer', 'Write U — he will be unavailable at 1100'],
        show: ['reg.I.s1', 'reg.I.inst'], why: 'The 30-minute window works both ways, so 1045 is on time. U is for a dose that could not be given — this one can.' }],
      expect: [{ do: 'sign', c: 'reg.I.d3.s1', t: '1045' }] },
    { at: '3@1410', rn: 'AT', title: '1400',
      brief: ['1400 — Ana gives Tom’s IV amoxicillin herself, and signs for it.',
        '1405 — Tom’s temperature is 38.4 °C and he has a headache. After checking his chart with Ana, you give him paracetamol 1 g PO at 1410.'],
      ask: [{ id: 'r4para', tag: 'PRN', q: 'Can Tom have paracetamol at 1410?', a: 'Yes — last given at 0520; 2 g in 24 hours',
        w: ['No — he had some at 0520, so not until tomorrow', 'No — a fever needs the doctor, not paracetamol', 'Yes — but only 500 mg with his Parkinson’s'],
        show: ['prn.A.freq', 'prn.A.max', 'prn.A.2.time'], why: 'q4h and 4 g on the order; the record shows 1600 yesterday and 0520 today — 2 g in the last 24 hours.' }],
      expect: [
        { do: 'rn', c: 'reg.J.d3.s2', t: '1400', what: 'IV amoxicillin (row J)', why: 'Ana gave it, so Ana signs it — you only ever sign for a dose you gave.' },
        { do: 'prn', L: 'A', dose: ['1g', '1 g', '1000mg', '1000 mg'], route: 'PO', t: '1410' },
      ] },
    { at: '3@1500', rn: 'AT', title: '1500: Sinemet, and nausea',
      brief: ['1450 — Tom feels sick. On the phone the house officer says “give him some metoclopramide”; Ana reads out his Adverse Reactions box, and the house officer agrees to his ondansetron instead.',
        '1500 — with Ana checking, you give Tom his Sinemet and ondansetron 4 mg PO.'],
      ask: [{ id: 'r5meto', tag: 'Front page', q: 'Why not metoclopramide for Tom?', a: 'It blocks dopamine — it is on his Adverse Reactions (rigidity)',
        w: ['It only works if it is given by injection, and he has no IV', 'It must never be taken at the same time as aspirin', 'Metoclopramide is only for nausea after an operation'],
        show: ['adr.0.med', 'adr.0.rx'], why: 'Levodopa replaces dopamine; metoclopramide blocks it. His chart records what it did to him: rigidity and a worse tremor.' }],
      expect: [
        { do: 'sign', c: 'reg.I.d3.s2', t: '1500' },
        { do: 'prn', L: 'B', dose: ['4mg', '4 mg', '4'], route: 'PO', t: '1500' },
      ] },
  ],
};
