/* Frank Russell — a pulmonary embolism and new atrial fibrillation. Teaches: a treatment-dose enoxaparin worked out
   in the Dose calculation box (mg/kg), BD at 0800/2000; digoxin with an apical-pulse limit — held one day (D), given
   the next; two loading doses on the Once Only page; a PRN order cancelled and replaced by another (read the cancel
   box, give from the new order); a second oxygen line after the first was stopped. */
export default {
  id: 'pe', t: 'Frank Russell, 69', sub: 'Clot in the lung (PE) and a new fast heart rhythm',
  story: 'Frank came in on Monday short of breath with sharp chest pain on breathing in. A CT scan showed a clot in his lungs (a pulmonary embolism), and his heart was in a new, fast, irregular rhythm (atrial fibrillation). He is on a treatment dose of enoxaparin, worked out from his weight, and was loaded with digoxin to slow his heart. Oral morphine made him drowsy, so on Tuesday it was cancelled and oxycodone charted instead. He came off the oxygen mask onto nasal prongs on Tuesday morning. It is Wednesday, 0730.',
  start: [23, 11, 2026], now: '3@0730',
  patient: { family: 'RUSSELL', given: 'Frank', gender: 'M', dob: '11/12/1956', nhi: 'ZGB5530', weight: 84, height: 181 },
  prescribers: [
    { id: 'ed', name: 'NGATA, Rewi · ED Registrar', sig: 'RNgata', reg: '44102' },
    { id: 'rm', name: 'MURRAY, Rachel · Med Registrar', sig: 'RMurray', reg: '43958' },
    { id: 'lb', name: 'BROWN, Lucy · House Officer', sig: 'LBrown', reg: '54102' },
  ],
  nurses: [
    { name: 'WALKER, Huia · RN', init: 'HW', reg: '218840' },
    { name: 'KAWHIA, Rangi · RN', init: 'RK', reg: '236675' },
    { name: 'MORRIS, Jade · RN', init: 'JM', reg: '240553' },
    { name: 'TIPENE, Dan · RN', init: 'DT', reg: '229104' },
    { name: 'KEREOPA, Tui · RN', init: 'TK', reg: '238802' },
  ],
  allergies: [], allergyBy: 'rm',
  adverse: [{ med: 'ASPIRIN', rx: 'Stomach bleed (2019)', by: 'rm' }],
  special: [], supplementary: [],
  vte: { by: 'rm', day: 1, anticoag: true, stockings: false, ipc: false },
  o2: { target: '92–96', rows: [
    { start: 1, device: 'Hudson mask', flow: '6 L/min', by: 'ed', stop: 2, stopAt: '2@0900' },
    { start: 2, startAt: '2@0900', device: 'Nasal prongs', flow: '2 L/min', by: 'rm' },
  ] },
  regular: [
    { L: 'I', day: 1, at: '1@1500', startT: '2000', med: 'ENOXAPARIN', dose: '80', units: 'mg', route: 'SC', freq: 'BD', times: '0800 2000', calc: '1 mg/kg (84 kg), rounded', by: 'rm', inst: 'Treatment dose. Check platelets and creatinine',
      given: { '1@2000': 'JM', '2@0800': '0810 HW', '2@2000': 'JM', '3@2000': 'JM' } },
    { L: 'J', day: 2, at: '2@1000', startT: '0800', med: 'DIGOXIN', dose: '125', units: 'mcg', route: 'PO', freq: 'mane', times: '0800', by: 'rm', inst: 'Apical HR for a full minute: withhold if < 60, tell dr' },
    { L: 'K', day: 1, at: '1@1500', startT: '1800', med: 'PARACETAMOL', dose: '1', units: 'g', route: 'PO', freq: 'QID', times: '0600 1200 1800 2200', by: 'rm', inst: 'Max 4 g in 24 h from all sources',
      given: { '1@1800': 'JM', '1@2200': 'DT', '2@0600': 'DT', '2@1200': '1210 HW', '2@1800': 'JM', '2@2200': 'DT', '3@0600': 'DT', '3@1800': 'JM', '3@2200': 'DT', '4@0600': 'DT' } },
    { L: 'L', day: 1, at: '1@1500', startT: '2000', med: 'ATORVASTATIN', dose: '40', units: 'mg', route: 'PO', freq: 'nocte', times: '2000', by: 'rm',
      given: { '1@2000': 'JM', '2@2000': 'JM', '3@2000': 'JM' } },
  ],
  prn: [
    { L: 'A', day: 1, at: '1@1500', med: 'MORPHINE (ORAL SOLUTION)', dose: '5', units: 'mg', route: 'PO', freq: 'q4h', max: '30 mg', gapH: 4, maxAmount: 30, ind: 'Pleuritic pain', by: 'rm',
      given: ['1@1700 5mg PO HW/RK', '1@2300 5mg PO DT/TK'], cease: { at: '2@1000', by: 'rm' } },
    { L: 'B', day: 2, at: '2@1000', med: 'OXYCODONE', dose: '2.5', range: '2.5 – 5', units: 'mg', route: 'PO', freq: 'q4h', max: '20 mg', gapH: 4, maxAmount: 20, ind: 'Pleuritic pain', by: 'rm', inst: 'Controlled drug. Replaces morphine (PRN A)',
      given: ['2@1400 2.5mg PO HW/RK', '3@0200 2.5mg PO DT/TK', '3@2100 2.5mg PO JM/DT'] },
  ],
  once: [
    { day: 1, at: '1@1500', med: 'DIGOXIN', dose: '500', units: 'mcg', route: 'PO', by: 'rm', inst: 'Loading dose 1 of 2', given: { at: '1@1545', giv: 'HW', chk: 'RK' } },
    { day: 1, at: '1@1500', med: 'DIGOXIN', dose: '250', units: 'mcg', route: 'PO', by: 'rm', inst: 'Loading dose 2 of 2 — 6 h after the first', given: { at: '1@2150', giv: 'JM', chk: 'DT' } },
  ],
  questions: [
    { id: 'calc', tag: 'Regular', q: 'How was Frank’s enoxaparin dose worked out?', a: '1 mg/kg × 84 kg, rounded — Dose calculation',
      w: ['A standard 40 mg dose, doubled for a clot', 'It is written on a heparin chart, not here', '2 mg/kg × 40 kg, his ideal body weight'],
      show: ['reg.I.calc', 'reg.I.dose', 'wt.0'], why: 'The Dose calculation box (eg. mg/kg per dose) on the order, and his weight on the Once Only page. 84 mg rounds to the 80 mg syringe.' },
    { id: 'load', tag: 'Once Only', q: 'How much digoxin did Frank have as his loading doses?', a: '750 mcg — 500, then 250 six hours later',
      w: ['125 mcg — the dose on row J', '500 mcg — the second dose was never given', '1 mg — two doses of 500 mcg each'],
      show: ['once.0.dose', 'once.1.dose', 'once.1.dosedt'], why: 'Two orders on the Once Only page, each with its own date and time of dose, given and checked.' },
    { id: 'aspadr', tag: 'Front page', q: 'Why is there no aspirin on Frank’s chart for his heart?', a: 'An adverse reaction to it: a stomach bleed',
      w: ['Aspirin is never given alongside digoxin', 'It is on a separate supplementary chart', 'He takes it at home, so it is not charted here'],
      show: ['adr.0.med', 'adr.0.rx'], why: 'Adverse Reactions, front page: ASPIRIN — stomach bleed (2019). On a full-dose anticoagulant, that history matters even more.' },
  ],
  rounds: [
    { at: '3@0810', rn: 'HW', title: '0800 med round',
      brief: ['Your first morning with Huia Walker (RN, initials HW). You have not signed Frank’s chart before.',
        '0800 — you count his apical heart rate for a full minute: 56. Huia rings the registrar, who says to withhold this morning’s digoxin.',
        '0810 — with Huia checking, you give Frank his enoxaparin injection, 80 mg SC, into his abdomen.'],
      ask: [{ id: 'r1dig', tag: 'Regular', q: 'Row J (digoxin) says withhold if apical HR < 60. It is 56. What goes in the box?', a: 'D — withheld on the prescriber’s instruction',
        w: ['Your initials — 56 is close enough to 60', 'R — he did not want it this morning', 'N — not given, with the reason in the notes'],
        show: ['reg.J.inst'], why: 'The limit on the order, and the registrar’s instruction: D, prescriber’s instructions.' }],
      expect: [
        { do: 'reg' },
        { do: 'sign', c: 'reg.I.d3.s1', t: '0810' },
        { do: 'code', c: 'reg.J.d3.s1', code: 'D', why: 'Withheld on the prescriber’s instruction (apical HR 56, under the order’s limit of 60).' },
      ] },
    { at: '3@1210', rn: 'HW', title: 'Midday',
      brief: ['1210 — with Huia checking, you give Frank his 1200 paracetamol.'],
      ask: [{ id: 'r2o2', tag: 'Oxygen', q: 'Frank came in on a Hudson mask. What oxygen is he on now?', a: 'Nasal prongs 2 L/min — no stop date',
        w: ['Hudson mask, 6 L/min — the first line', 'Both — a mask and prongs together', 'None — oxygen is not on this chart'],
        show: ['o2.0.stop', 'o2.1.device', 'o2.1.flow'], why: 'Oxygen Therapy & Medical Gases: the first line has a stop date; the second, started the same morning, does not.' }],
      expect: [{ do: 'sign', c: 'reg.K.d3.s2', t: '1210' }] },
    { at: '3@1300', rn: 'HW', title: 'Pleuritic pain',
      brief: ['1255 — Frank has sharp pain when he breathes in, and asks for “the morphine I had on Monday”.',
        '1300 — after checking his chart with Huia, you give him oxycodone 2.5 mg PO. It is a controlled drug, so Huia checks it with you.'],
      ask: [{ id: 'r3prn', tag: 'PRN', q: 'He asks for the morphine he had on Monday. What does the PRN page say?', a: 'Morphine (A) is cancelled — oxycodone (B) replaced it',
        w: ['Give the morphine — it is still on the PRN page', 'Give both, for pleuritic pain', 'Neither — no pain relief is charted'],
        show: ['prn.A.cancel', 'prn.B.inst'], why: 'PRN A is crossed through with its cancel box signed; PRN B says it replaces it.' }],
      expect: [
        { do: 'none', c: 'prn.A', what: 'Morphine (PRN A)', why: 'cancelled on Tuesday at 1000 — crossed through, cancel box signed.' },
        { do: 'prn', L: 'B', dose: ['2.5mg', '2.5 mg', '2.5'], route: 'PO', t: '1300' },
      ] },
    { at: '4@0810', rn: 'HW', title: 'Thursday: 0800 med round',
      brief: ['Thursday — your second morning with Frank and Huia (HW).',
        '0800 — his apical heart rate is 72 for a full minute.',
        '0810 — with Huia checking, you give his digoxin and his enoxaparin injection.'],
      ask: [{ id: 'r4dig', tag: 'Regular', q: 'Yesterday’s digoxin was held for an apical HR of 56. Today it is 72. What now?', a: 'Give it — 72 is above the limit of 60',
        w: ['Hold it again — it was held yesterday', 'Give a double dose to catch up', 'Hold it until the registrar has seen him'],
        show: ['reg.J.inst', 'reg.J.d3.s1.gc'], why: 'Each dose is decided on that morning’s count. Never double up to make up a missed dose.' }],
      expect: [
        { do: 'sign', c: 'reg.J.d4.s1', t: '0810' },
        { do: 'sign', c: 'reg.I.d4.s1', t: '0810' },
      ] },
  ],
};
