/* Aroha Kingi — the day after a caesarean, breastfeeding. Teaches: Special Care — breastfeeding (every medicine
   checked for it; codeine avoided); an allergy found during the stay, recorded under "New on this admission" while the
   admission "No" box stays ticked; midwives (RM) as the checkers; an IV dose the midwife gives and signs herself, so
   the student writes nothing there; a PRN dose range; a first enoxaparin dose held on the prescriber's instruction. */
export default {
  id: 'csection', t: 'Aroha Kingi, 31', sub: 'Day 1 after a caesarean — breastfeeding',
  story: 'Aroha had an emergency caesarean on Monday afternoon after a long labour, under a spinal anaesthetic. Her son is well and she is breastfeeding him. In theatre she came out in hives after the cefazolin, so that is now recorded as an allergy. Her haemoglobin is a little low, so she is on iron. Overnight she needed oxycodone twice for wound pain. It is Tuesday, 0730.',
  start: [16, 11, 2026], now: '2@0730',
  patient: { family: 'KINGI', given: 'Aroha', gender: 'F', dob: '04/08/1995', nhi: 'ZRT4471', weight: 88, height: 168 },
  prescribers: [
    { id: 'ob', name: 'SHARMA, Priya · O&G Registrar', sig: 'PSharma', reg: '43390' },
    { id: 'an', name: 'LEWIS, Oliver · Anaesthetist', sig: 'OLewis', reg: '31187' },
  ],
  nurses: [
    { name: 'WILLIAMS, Kate · RM', init: 'KW', reg: '251204' },
    { name: 'HARRIS, Jo · RM', init: 'JH', reg: '249873' },
    { name: 'MAHE, Pua · RM', init: 'PM', reg: '253316' },
    { name: 'KOROHEKE, Tia · RM', init: 'TK', reg: '247720' },
  ],
  allergies: [{ med: 'CEFAZOLIN', rx: 'Hives in theatre', by: 'an', new: '1@1415' }], allergyBy: 'ob',
  adverse: [], adverseBy: 'ob',
  special: ['bf'], supplementary: [],
  vte: { by: 'ob', day: 1, anticoag: true, stockings: true, ipc: false },
  regular: [
    { L: 'I', day: 1, at: '1@1600', startT: '1800', med: 'PARACETAMOL', dose: '1', units: 'g', route: 'PO', freq: 'QID', times: '0600 1200 1800 2200', by: 'an', inst: 'Max 4 g in 24 h from all sources',
      given: { '1@1800': 'JH', '1@2200': 'PM', '2@0600': 'PM' } },
    { L: 'J', day: 1, at: '1@1600', startT: '2000', med: 'IBUPROFEN', dose: '400', units: 'mg', route: 'PO', freq: 'TDS', times: '0800 1400 2000', by: 'an', inst: 'With food. Fine while breastfeeding',
      given: { '1@2000': 'JH' } },
    { L: 'K', day: 1, at: '1@1600', startT: '1800', med: 'ENOXAPARIN', dose: '40', units: 'mg', route: 'SC', freq: 'daily', times: '1800', by: 'ob', inst: 'First dose 17/11 — after the spinal',
      given: { '1@1800': 'D' } },
    { L: 'L', day: 1, at: '1@1600', startT: '0800', med: 'FERROUS SULFATE', dose: '325', units: 'mg', route: 'PO', freq: 'mane', times: '0800', by: 'ob', inst: 'Hb 94. Not with tea or milk' },
    { L: 'M', day: 1, at: '1@1600', startT: '2000', med: 'DOCUSATE + SENNOSIDES', dose: '2', units: 'tab', route: 'PO', freq: 'nocte', times: '2000', by: 'ob',
      given: { '1@2000': 'JH' } },
  ],
  prn: [
    { L: 'A', day: 1, at: '1@1600', med: 'OXYCODONE', dose: '5', range: '5 – 10', units: 'mg', route: 'PO', freq: 'q4h', max: '40 mg', gapH: 4, maxAmount: 40, ind: 'Pain', by: 'an', inst: 'Controlled drug. Breastfeeding: watch baby for drowsiness',
      given: ['1@2100 10mg PO JH/PM', '2@0130 5mg PO PM/TK', '2@0520 10mg PO PM/TK'] },
    { L: 'B', day: 1, at: '1@1600', med: 'ONDANSETRON', dose: '4', units: 'mg', route: 'PO/IV', freq: 'q8h', max: '12 mg', gapH: 8, maxAmount: 12, ind: 'Nausea', by: 'an',
      given: ['1@1700 4mg IV JH'] },
  ],
  fluids: [
    { day: 1, time: '1500', vol: 1000, fluid: 'PLASMA-LYTE 148', route: 'IV', rate: 125, by: 'an', started: { at: '1@1520', by: 'JH', chk: 'KW' }, done: { at: '2@0320', vol: 1000 } },
  ],
  questions: [
    { id: 'rm', tag: 'Front page', q: 'Aroha’s doses are checked by midwives. In the register, what does “RM” after a name mean?', a: 'Registered midwife',
      w: ['Registered medical officer', 'Recovery room nurse', 'Resident manager'],
      show: ['siga.0.name'], why: 'The Sample Initials register lists everyone who signs the chart, with their designation — on a maternity ward, mostly midwives.' },
    { id: 'enox1', tag: 'Regular', q: 'Monday’s 1800 enoxaparin box shows D. Why?', a: 'Prescriber’s instruction — first dose is Tuesday',
      w: ['She refused the injection on Monday evening', 'The drug was not on the ward on Monday', 'Enoxaparin is never given after a caesarean'],
      show: ['reg.K.d1.s3.gc', 'reg.K.inst'], why: 'D, prescriber’s instructions: the order’s own note says the first dose is 17/11, after the spinal anaesthetic.' },
  ],
  rounds: [
    { at: '2@0810', rn: 'KW', title: '0800 med round',
      brief: ['Your first morning on the maternity ward, with Kate Williams — a registered midwife (RM, initials KW). You have not signed Aroha’s chart before.',
        '0750 — Aroha vomited as she sat up. Kate gave her ondansetron 4 mg IV and signed for it.',
        '0810 — the nausea has settled and she has eaten some toast. With Kate checking, you give Aroha her 0800 medicines.'],
      ask: [{ id: 'r1bf', tag: 'Front page', q: 'The Special Care box says breastfeeding. What does that change for you?', a: 'Check each medicine is safe while breastfeeding',
        w: ['Nothing — only the prescriber needs to know that', 'Give every dose after a feed, never before one', 'Stop all her medicines until the baby is weaned'],
        show: ['sc.bf'], why: 'Special Care Required, front page. Most medicines are fine while breastfeeding, some are not — so each one is checked (your NZ Formulary and pharmacist know).' }],
      expect: [
        { do: 'reg' },
        { do: 'rn', L: 'B', dose: ['4mg'], route: 'IV', t: '0750', what: 'Ondansetron IV (PRN B)', why: 'Kate gave it, so Kate signs it — you only ever sign for a dose you gave.' },
        { do: 'sign', c: 'reg.J.d2.s1', t: '0810' },
        { do: 'sign', c: 'reg.L.d2.s1', t: '0810' },
      ] },
    { at: '2@0930', rn: 'KW', title: 'Pain',
      brief: ['0925 — Aroha’s wound pain is 7/10 when she tries to feed, and she asks for something stronger.',
        '0930 — after checking the chart with Kate, you give her 5 mg of oxycodone PO. It is a controlled drug, so Kate checks it with you.'],
      ask: [{ id: 'r2can', tag: 'PRN', q: 'Can Aroha have oxycodone at 0930?', a: 'Yes — last at 0520 (4-hourly); 25 mg of 40 mg in 24 h',
        w: ['No — she had 10 mg at 0520, so not until 1320', 'No — oxycodone can’t be given while breastfeeding', 'Only with the anaesthetist on the ward in person'],
        show: ['prn.A.freq', 'prn.A.max', 'prn.A.2.time'], why: 'q4h and 40 mg on the order. Since 0930 yesterday: 10 + 5 + 10 = 25 mg. The order itself says what to watch for while breastfeeding.' }],
      expect: [{ do: 'prn', L: 'A', dose: ['5mg', '5 mg', '5'], route: 'PO', t: '0930' }] },
    { at: '2@1205', rn: 'KW', title: 'Midday',
      brief: ['1205 — with Kate checking, you give Aroha her 1200 paracetamol.',
        'Her sister is visiting, and says codeine “worked wonders” after her own baby. Aroha asks if she can have some.'],
      ask: [{ id: 'r3cod', tag: 'Judgement', q: 'Codeine isn’t on Aroha’s chart. Why is it avoided while breastfeeding?', a: 'In some mothers it becomes morphine fast, and reaches the baby',
        w: ['It is far too weak to help after a caesarean section', 'It is written in her allergy box, next to cefazolin', 'It only comes as an injection, and her IV is out'],
        show: ['sc.bf', 'alg.new'], why: 'Codeine becomes morphine in the body; in some people very quickly, and it passes into breast milk. So it is avoided while breastfeeding — Kate will ask the team about her pain plan instead.' }],
      expect: [{ do: 'sign', c: 'reg.I.d2.s2', t: '1205' }] },
    { at: '2@1405', rn: 'KW', title: '1400',
      brief: ['1400 — Aroha has just finished her lunch.',
        '1405 — with Kate checking, you give her 1400 ibuprofen.'],
      ask: [{ id: 'r4alg', tag: 'Front page', q: 'Before a first dose of anything new, where do you check for an allergy found during this stay?', a: '“New on this admission”, in the Allergies box',
        w: ['The main lines of the Allergies box — nothing else', 'The PRN page, beside the oxycodone order', 'Nowhere — allergies are only asked about at admission'],
        show: ['alg.new', 'alg.none'], why: 'The Allergies box has a section for exactly this. Aroha’s “No” was ticked on admission — the cefazolin hives came later, so they are written under “New on this admission”.' }],
      expect: [{ do: 'sign', c: 'reg.J.d2.s2', t: '1405' }] },
  ],
};
