/* Ropata Hēnare — a stroke, nil by mouth, then an NG tube. Teaches: a change of route is a new order on a new line
   (aspirin PR crossed through, aspirin NG written below it); a CR tablet that cannot be crushed for the tube, held on
   the prescriber's word and then rewritten; the VTE box with calf pumps (IPC) and the reason written under Other; a
   PRN that allows two routes, where the route used is recorded each time; a bag that finishes with no next bag
   written — so nothing goes up. */
export default {
  id: 'stroke', t: 'Ropata Hēnare, 71', sub: 'Stroke — nil by mouth, then an NG tube',
  story: 'Ropata had a stroke on Monday morning: his right side is weak and his speech and swallow are affected. The CT showed a clot, not a bleed, but he arrived too late for clot-busting treatment. He failed his swallow screen, so he is nil by mouth. Aspirin went in as a suppository at first; on Tuesday afternoon a nasogastric (NG) tube was placed (position confirmed on X-ray), and his medicines are being rewritten into forms that can go down it. It is Wednesday, 0730.',
  start: [9, 11, 2026], now: '3@0730',
  patient: { family: 'HĒNARE', given: 'Ropata', gender: 'M', dob: '17/02/1955', nhi: 'ZFW8813', weight: 82, height: 175 },
  prescribers: [
    { id: 'ed', name: 'NGATA, Rewi · ED Registrar', sig: 'RNgata', reg: '44102' },
    { id: 'mc', name: 'CHEN, Michael · Med Registrar', sig: 'MChen', reg: '42219' },
    { id: 'hf', name: 'FRASER, Holly · House Officer', sig: 'HFraser', reg: '53877' },
  ],
  nurses: [
    { name: 'WONG, Mia · RN (ED)', init: 'MW', reg: '232871' },
    { name: 'POMARE, Luke · RN (ED)', init: 'LP', reg: '241630' },
    { name: 'KALU, Ngozi · RN', init: 'NK', reg: '239918' },
    { name: 'VEA, Sam · RN', init: 'SV', reg: '237745' },
    { name: 'REID, Chris · RN', init: 'CR', reg: '226950' },
    { name: 'TUALA, Ana · RN', init: 'AT', reg: '214406' },
  ],
  allergies: [], allergyBy: 'mc', adverse: [], adverseBy: 'mc',
  special: [], supplementary: [],
  vte: { by: 'mc', day: 1, anticoag: false, other: 'Acute stroke — calf pumps (IPC)', stockings: false, ipc: true },
  regular: [
    { L: 'I', day: 2, at: '2@0730', startT: '0800', med: 'ASPIRIN', dose: '300', units: 'mg', route: 'PR', freq: 'daily', times: '0800', by: 'mc', inst: 'Suppository — nil by mouth',
      given: { '2@0800': '0810 AT' }, cease: { at: '2@1500', by: 'hf' } },
    { L: 'J', day: 2, at: '2@1500', startT: '0800', med: 'ASPIRIN (DISPERSIBLE)', dose: '300', units: 'mg', route: 'NG', freq: 'daily', times: '0800', by: 'hf', inst: 'Dissolve in water. Flush NG before and after' },
    { L: 'K', day: 2, at: '2@1500', startT: '2000', med: 'ATORVASTATIN', dose: '80', units: 'mg', route: 'NG', freq: 'nocte', times: '2000', by: 'hf', inst: 'Crush. Flush NG before and after',
      given: { '2@2000': 'NK', '3@2000': 'NK' } },
    { L: 'L', day: 1, at: '1@1300', startT: '0800', med: 'METOPROLOL SUCCINATE CR', dose: '47.5', units: 'mg', route: 'PO', freq: 'mane', times: '0800', by: 'mc', inst: 'CR tablet — do NOT crush',
      given: { '2@0800': 'D' }, cease: { at: '3@0900', by: 'hf' } },
    { L: 'M', day: 3, at: '3@0900', startT: '2000', med: 'METOPROLOL TARTRATE', dose: '25', units: 'mg', route: 'NG', freq: 'BD', times: '0800 2000', by: 'hf', inst: 'Immediate-release: crush. Replaces row L',
      given: { '3@2000': 'NK' } },
  ],
  prn: [
    { L: 'A', day: 1, med: 'PARACETAMOL', dose: '1', units: 'g', route: 'NG/PR', freq: 'q6h', max: '4 g', gapH: 6, maxAmount: 4, ind: 'Pain / fever', by: 'mc', inst: 'PR until the NG tube is in',
      given: ['1@2200 1g PR SV', '2@0600 1g PR CR', '3@0400 1g NG SV', '4@0200 1g NG SV'] },
  ],
  once: [
    { day: 1, at: '1@1300', med: 'ASPIRIN', dose: '300', units: 'mg', route: 'PR', by: 'mc', inst: 'CT: no bleed. Nil by mouth', given: { at: '1@1420', giv: 'NK', chk: '' } },
  ],
  fluids: [
    { day: 1, time: '1300', vol: 1000, fluid: 'SODIUM CHLORIDE 0.9%', route: 'IV', rate: 80, by: 'ed', started: { at: '1@1310', by: 'MW', chk: 'LP' }, done: { at: '2@0140', vol: 1000 } },
    { day: 2, time: '0140', vol: 1000, fluid: 'SODIUM CHLORIDE 0.9%', route: 'IV', rate: 80, by: 'mc', started: { at: '2@0145', by: 'SV', chk: 'CR' }, done: { at: '2@1415', vol: 1000 } },
    { day: 2, time: '1415', vol: 1000, fluid: 'PLASMA-LYTE 148', route: 'IV', rate: 42, by: 'hf', started: { at: '2@1420', by: 'AT', chk: 'NK' } },
  ],
  questions: [
    { id: 'newline', tag: 'Regular', q: 'Aspirin on row I (PR) is crossed through, and row J (NG) is new. Why a new line, not a change to row I?', a: 'To change therapy, stop the order and prescribe on a new line',
      w: ['Row I had run out of boxes, so it needed a new line', 'The pharmacist rewrote it to make the chart neater', 'Every change of nurse needs the order written again'],
      show: ['reg.I.cancel', 'reg.J.med', 'reg.J.route'], why: 'The chart’s own instruction 4: to alter therapy, stop the original order and prescribe on a new line. A new route is a new order.' },
    { id: 'crush', tag: 'Regular', q: 'Why can’t the metoprolol on row L go down the NG tube?', a: 'It is a CR tablet — crushed, the whole dose lands at once',
      w: ['NG tubes can only take liquids that come ready-made', 'Metoprolol can only ever be given by mouth', 'It can — crush it and flush it down with water'],
      show: ['reg.L.inst', 'reg.L.med'], why: 'CR (controlled-release) tablets release slowly by design. Crushed, the whole dose arrives at once — so the prescriber rewrote it as immediate-release metoprolol on a new line.' },
    { id: 'ipc', tag: 'Regular', q: 'Why is there no enoxaparin on Ropata’s chart?', a: 'The VTE plan after his stroke is calf pumps (IPC)',
      w: ['It was forgotten — ask for it to be charted', 'It is on a separate heparin chart', 'He takes warfarin at home instead'],
      show: ['vte.other', 'vte.ipc.y'], why: 'The VTE box: no anticoagulant, the reason written under “Other”, and Intermittent pneumatic compression devices — Yes.' },
    { id: 'prroute', tag: 'PRN', q: 'How was Ropata’s 0600 paracetamol given on Tuesday?', a: 'PR — the Route column says so',
      w: ['NG — the tube was already in place', 'IV — paracetamol is always IV after a stroke', 'PO — with a sip of water'],
      show: ['prn.A.1.route'], why: 'The order allows NG or PR, and the chart’s instruction 3 says to record the route actually used. Tuesday 0600 was before the tube went in.' },
  ],
  rounds: [
    { at: '3@0810', rn: 'AT', title: '0800 med round',
      brief: ['Your first morning with Ana Tuala (RN, initials AT). You have not signed Ropata’s chart before.',
        'Ropata is nil by mouth: everything goes down his NG tube, and Ana has checked its position.',
        '0810 — with Ana checking, you give the aspirin down the tube.',
        'His metoprolol (row L) is a CR tablet that cannot be crushed, and the order says PO. Ana rings the house officer, who says to withhold it until it is rewritten.'],
      ask: [{ id: 'r1line', tag: 'Regular', q: 'Two aspirin lines: row I (PR) and row J (NG). Which one do you sign?', a: 'Row J — the NG line; row I is crossed through',
        w: ['Row I — the suppository was the first order', 'Both — it is the same aspirin dose', 'Neither — aspirin goes on the once-only page'],
        show: ['reg.I.cancel', 'reg.J.route'], why: 'Row I was stopped yesterday at 1500 and crossed through; row J is the order in use.' }],
      expect: [
        { do: 'reg' },
        { do: 'sign', c: 'reg.J.d3.s1', t: '0810' },
        { do: 'code', c: 'reg.L.d3.s1', code: 'D', why: 'Withheld on the prescriber’s instruction: a CR tablet cannot be crushed for the tube, and the order says PO.' },
        { do: 'none', c: 'reg.I.d3', what: 'Aspirin PR (row I)', why: 'stopped yesterday at 1500 and crossed through — the NG line (row J) replaced it.' },
      ] },
    { at: '3@1110', rn: 'AT', title: 'A temperature',
      brief: ['1100 — Ropata’s temperature is 38.1 °C. Ana asks you to give his PRN paracetamol.',
        '1110 — after checking his chart with Ana, you give paracetamol 1 g down the NG tube, and flush it.'],
      ask: [{ id: 'r2route', tag: 'PRN', q: 'The paracetamol order allows NG or PR. Where does the route you used go?', a: 'In the Route column of the PRN record: NG',
        w: ['Nowhere — the order already says NG/PR', 'On the order line, by crossing out PR', 'In the notes only, not on the chart'],
        show: ['prn.A.route', 'prn.A.2.route'], why: 'Instruction 3 printed inside the chart: for a variable route, record the actual route used.' }],
      expect: [{ do: 'prn', L: 'A', dose: ['1g', '1 g', '1000mg', '1000 mg'], route: 'NG', t: '1110' }] },
    { at: '3@1410', rn: 'AT', title: 'The last bag',
      brief: ['1410 — the Plasma-Lyte (IV fluids line 3) has finished: all 1000 mL in.',
        'His NG feed is now running at its full rate, and Dr Fraser has stopped the IV fluids.'],
      ask: [{ id: 'r3bag', tag: 'Fluids', q: 'The bag has finished. What do you do on the fluid chart?', a: 'Record its time and volume; hang nothing',
        w: ['Hang another bag of the same fluid at the same rate', 'Leave the completion boxes blank until the next bag', 'Write the next bag in yourself, at the same rate'],
        show: ['fl.2.tend', 'fl.2.avol'], why: 'Completion time and actual volume close the line. A bag goes up only when a prescriber has written it — and nothing is written below line 3.' }],
      expect: [{ do: 'fluidend', i: 2, t: '1410', vol: 1000 }] },
    { at: '4@0810', rn: 'AT', title: 'Thursday: 0800 med round',
      brief: ['Thursday — your second morning with Ropata and Ana (AT).',
        'Yesterday the house officer rewrote his metoprolol as an immediate-release tablet that can be crushed (row M).',
        '0810 — Ana has checked the tube’s position. With her checking, you give his 0800 medicines down it.'],
      ask: [{ id: 'r4ng', tag: 'Judgement', q: 'Before anything goes down an NG tube, what do you check?', a: 'Its position — aspirate pH and the mark at the nose',
        w: ['Nothing — once the X-ray was done it stays put', 'Only that the feed pump is switched off', 'That the patient can swallow the tablets'],
        show: ['reg.J.route', 'reg.M.inst'], why: 'Tubes move. Check the position every time before use (your hospital’s policy sets how — usually the pH of what you draw back, and the length at the nose), and flush before and after.' }],
      expect: [
        { do: 'sign', c: 'reg.J.d4.s1', t: '0810' },
        { do: 'sign', c: 'reg.M.d4.s1', t: '0810' },
        { do: 'none', c: 'reg.L.d4', what: 'Metoprolol CR (row L)', why: 'stopped yesterday and crossed through — row M replaced it.' },
      ] },
  ],
};
