/* Sione Taufa — the day after a bowel resection. Teaches: TWO supplementary charts ticked (his morphine PCA and his
   insulin live elsewhere, so there is no PRN opioid here); D for a hold the prescriber wrote on the order itself;
   a BP limit on the order read and passed; an aspirin allergy that matters for NSAIDs; two antiemetics — the
   8-hour gap decides which one; a fluid bag with potassium added, finished and replaced. */
export default {
  id: 'bowel', t: 'Sione Taufa, 58', sub: 'Day 1 after bowel surgery — PCA running',
  story: 'Sione had part of his large bowel removed on Monday morning. He is on a morphine PCA (its own chart) and his diabetes is managed on the insulin chart while he is not eating; his metformin is on hold until he is eating and drinking normally. He has asthma, and aspirin makes him wheeze. Overnight he needed ondansetron at 0600 for nausea. He is on clear fluids, IV fluids running. It is Tuesday, 0730.',
  start: [2, 11, 2026], now: '2@0730',
  patient: { family: 'TAUFA', given: 'Sione', gender: 'M', dob: '30/06/1968', nhi: 'ZPX2418', weight: 98, height: 176 },
  prescribers: [
    { id: 'ak', name: 'KAPOOR, Anika · Surgical Registrar', sig: 'AKapoor', reg: '41567' },
    { id: 'tm', name: 'MOORE, Tim · House Officer', sig: 'TMoore', reg: '54390' },
  ],
  nurses: [
    { name: 'MAKA, Bella · RN', init: 'BM', reg: '233012' },
    { name: 'WATENE, Kiri · RN', init: 'KW', reg: '238411' },
    { name: 'HOHAIA, Rua · RN', init: 'RH', reg: '221786' },
    { name: 'KAUFUSI, Leilani · RN', init: 'LK', reg: '216593' },
  ],
  allergies: [{ med: 'ASPIRIN', rx: 'Wheeze, tight chest', by: 'ak' }],
  adverse: [], adverseBy: 'ak',
  special: [], supplementary: ['analgesia', 'insulin'],
  vte: { by: 'ak', day: 1, anticoag: true, stockings: true, ipc: true },
  o2: { target: '92–96', rows: [{ start: 1, device: 'Nasal prongs', flow: '2 L/min', by: 'ak' }] },
  regular: [
    { L: 'I', day: 1, startT: '1800', med: 'PARACETAMOL', dose: '1', units: 'g', route: 'PO', freq: 'QID', times: '0600 1200 1800 2200', by: 'ak', inst: 'Max 4 g in 24 h from all sources',
      given: { '1@1800': 'KW', '1@2200': 'KW', '2@0600': 'RH' } },
    { L: 'J', day: 1, startT: '1800', med: 'ENOXAPARIN', dose: '40', units: 'mg', route: 'SC', freq: 'daily', times: '1800', by: 'ak',
      given: { '1@1800': 'KW' } },
    { L: 'K', day: 1, startT: '0800', med: 'METFORMIN', dose: '1', units: 'g', route: 'PO', freq: 'BD', times: '0800 1800', by: 'ak', inst: 'WITHHOLD until eating and drinking normally',
      given: { '1@0800': 'D', '1@1800': 'D' } },
    { L: 'L', day: 1, startT: '0800', med: 'AMLODIPINE', dose: '5', units: 'mg', route: 'PO', freq: 'mane', times: '0800', by: 'ak',
      given: { '1@0800': 'D' } },
    { L: 'M', day: 1, startT: '0800', med: 'OMEPRAZOLE', dose: '20', units: 'mg', route: 'PO', freq: 'mane', times: '0800', by: 'ak',
      given: { '1@0800': 'D' } },
    { L: 'N', day: 1, startT: '0800', med: 'CILAZAPRIL', dose: '5', units: 'mg', route: 'PO', freq: 'mane', times: '0800', by: 'ak', inst: 'Withhold if SBP < 110',
      given: { '1@0800': 'D' } },
  ],
  prn: [
    { L: 'A', day: 1, med: 'ONDANSETRON', dose: '4', units: 'mg', route: 'PO/IV', freq: 'q8h', max: '12 mg', gapH: 8, maxAmount: 12, ind: 'Nausea', by: 'ak',
      given: ['1@1600 4mg IV KW', '2@0600 4mg IV RH'] },
    { L: 'B', day: 1, med: 'CYCLIZINE', dose: '50', range: '25 – 50', units: 'mg', route: 'PO/IV', freq: 'q8h', max: '150 mg', gapH: 8, maxAmount: 150, ind: 'Nausea (2nd line)', by: 'ak', given: [] },
    { L: 'C', day: 1, med: 'SALBUTAMOL', dose: '200', units: 'mcg', route: 'INH', freq: 'q4h', max: '1200 mcg', gapH: 4, maxAmount: 1200, ind: 'Wheeze', by: 'ak', inst: '2 puffs via spacer', given: [] },
  ],
  fluids: [
    { day: 1, time: '1200', vol: 1000, fluid: 'PLASMA-LYTE 148', route: 'IV', rate: 100, by: 'ak', started: { at: '1@1230', by: 'KW', chk: 'LK' }, done: { at: '1@2230', vol: 1000 } },
    { day: 1, time: '2230', vol: 1000, fluid: 'PLASMA-LYTE 148', route: 'IV', rate: 100, by: 'tm', started: { at: '1@2235', by: 'KW', chk: 'RH' } },
    { day: 2, at: '2@0700', time: '0830', vol: 1000, fluid: 'SODIUM CHLORIDE 0.9% + KCl 20 mmol', route: 'IV', rate: 83, by: 'tm' },
  ],
  questions: [
    { id: 'nsaid', tag: 'Front page', q: 'The registrar suggests ibuprofen for Sione’s pain. What does his chart tell you?', a: 'His allergy is aspirin (wheeze) — ibuprofen can do the same; query it',
      w: ['Nothing — ibuprofen is a completely different drug from aspirin', 'Give it — the allergy is only a wheeze, so it cannot be serious', 'Give it with food — the allergy box is about stomach upset'],
      show: ['alg.0.med', 'alg.0.rx'], why: 'Allergies: ASPIRIN — wheeze, tight chest. In someone with asthma whom aspirin makes wheeze, other anti-inflammatories (NSAIDs) can set it off too — so it goes back to the prescriber.' },
    { id: 'dmon', tag: 'Regular', q: 'Monday’s 0800 boxes all say D. Why?', a: 'He was nil by mouth for theatre — held on the anaesthetist’s instruction',
      w: ['He refused every one of his tablets before he went to theatre', 'The pharmacy had not yet sent up any of his usual medicines', 'He took his own tablets from home, so the ward did not give them'],
      show: ['reg.L.d1.s1.gc', 'reg.M.d1.s1.gc', 'reg.N.d1.s1.gc'], why: 'D is prescriber’s instructions — here the anaesthetist’s, for theatre. Refused would be R; not on the ward would be N.' },
  ],
  rounds: [
    { at: '2@0810', rn: 'LK', title: '0800 med round',
      brief: ['Your first morning with Leilani Kaufusi (RN, initials LK). You have not signed Sione’s chart before.',
        'Obs at 0730: BP 132/78, HR 84. He is on clear fluids only — not eating yet.',
        '0810 — with Leilani checking, you give Sione his 0800 tablets with sips of water — all except the metformin, which his chart says to hold until he is eating and drinking normally.'],
      ask: [
        { id: 'r1bp', tag: 'Regular', q: 'His BP is 132/78. Row N (cilazapril) says withhold if SBP < 110. What do you do?', a: 'Give it — his systolic is 132, above 110',
          w: ['Hold it — he only had surgery yesterday', 'Hold it and write D in the box', 'Give half, and recheck his BP in an hour'],
          show: ['reg.N.inst'], why: 'The limit on the order decides it: 132 is above 110, so it is given.' },
        { id: 'r1met', tag: 'Codes', q: 'Row K (metformin) says withhold until eating and drinking normally. He is on clear fluids. What goes in the box?', a: 'D — the prescriber’s instruction on the order',
          w: ['R — he is not eating yet, so he refused it', 'N — not given, with the reason in the notes', 'Nothing — leave the box empty until he eats'],
          show: ['reg.K.inst', 'reg.K.d1.s3.gc'], why: 'The prescriber’s instruction, written on the order itself: D — the same as last night’s box.' },
      ],
      expect: [
        { do: 'reg' },
        { do: 'code', c: 'reg.K.d2.s1', code: 'D', why: 'Held on the prescriber’s written instruction: withhold until eating and drinking normally.' },
        { do: 'sign', c: 'reg.L.d2.s1', t: '0810' },
        { do: 'sign', c: 'reg.M.d2.s1', t: '0810' },
        { do: 'sign', c: 'reg.N.d2.s1', t: '0810' },
      ] },
    { at: '2@0840', rn: 'LK', title: 'A new bag',
      brief: ['0835 — the Plasma-Lyte (IV fluids line 2) has finished: all 1000 mL in.',
        '0840 — you and Leilani check the next bag against his fluid chart and hang it.'],
      ask: [{ id: 'r2kcl', tag: 'Fluids', q: 'The next bag has potassium chloride added. What do you check before hanging it?', a: 'That the bag matches line 3: fluid, 20 mmol KCl, rate',
        w: ['Nothing extra — any bag of fluid can go up on any line', 'Only the rate — the pump works out the rest by itself', 'Just that it is warm — cold fluid is uncomfortable'],
        show: ['fl.2.fluid', 'fl.2.rate'], why: 'Line 3 of the IV fluid record: SODIUM CHLORIDE 0.9% + KCl 20 mmol at 83 mL/hr. Potassium is a high-risk additive — the bag, the order and the rate must all match.' }],
      expect: [
        { do: 'fluidend', i: 1, t: '0835', vol: 1000 },
        { do: 'fluid', i: 2, t: '0840' },
      ] },
    { at: '2@1015', rn: 'LK', title: 'Nausea',
      brief: ['1010 — Sione feels sick. His last ondansetron was at 0600.',
        '1015 — after checking his chart with Leilani, you give him cyclizine 50 mg PO.'],
      ask: [{ id: 'r3emesis', tag: 'PRN', q: 'Sione feels sick at 1010. Which antiemetic can he have?', a: 'Cyclizine (B) — ondansetron was only 4 hours ago',
        w: ['Ondansetron — nausea overrides the 8-hour gap', 'Both, to be sure — they work differently', 'Neither — nausea is expected after surgery'],
        show: ['prn.A.freq', 'prn.A.1.time', 'prn.B.med'], why: 'Ondansetron is q8h and was given at 0600 — not before 1400. His chart has a second-line antiemetic for exactly this.' }],
      expect: [
        { do: 'none', c: 'prn.A', what: 'Ondansetron (PRN A)', why: 'given at 0600 and 8-hourly — not before 1400.' },
        { do: 'prn', L: 'B', dose: ['50mg', '50 mg', '50'], route: 'PO', t: '1015' },
      ] },
    { at: '2@1205', rn: 'LK', title: 'Midday',
      brief: ['1200 — Sione’s pain is 6/10 and he asks for “something stronger”. His PCA handset is beside him; Leilani shows him again how to use it, and rings the acute pain team.',
        '1205 — with Leilani checking, you give him his 1200 paracetamol.'],
      ask: [{ id: 'r4pca', tag: 'Front page', q: 'Sione asks for “something stronger”. There is no PRN opioid on his chart. Why?', a: 'His opioid is the morphine PCA — on its own chart',
        w: ['Opioids are never given after bowel surgery', 'It was left off by mistake — give oxycodone anyway', 'He is allergic to opioids, so none are charted'],
        show: ['sup.analg'], why: 'Supplementary Charts, front page: Specialised analgesia is ticked. The PCA has its own chart, and the acute pain team runs it.' }],
      expect: [{ do: 'sign', c: 'reg.I.d2.s2', t: '1205' }] },
  ],
};
