/* Betty Anderson — a fall, a broken wrist, and three once-a-week medicines. Teaches: WEEKLY orders — methotrexate
   (Mondays only, a high-risk medicine), alendronate (Wednesdays, 0600, before food and upright) and folic acid
   (Thursdays, never on the methotrexate day) — with every other day ruled off on the chart, so the skill is reading
   which day it is and signing nothing where nothing is due; a VTE box with "Low risk" ticked. */
export default {
  id: 'weekly', t: 'Betty Anderson, 79', sub: 'A fall and a broken wrist — three weekly medicines',
  story: 'Betty tripped on her back step early on Monday morning and broke her left wrist; it is in plaster. She has rheumatoid arthritis, treated with methotrexate once a week (on Mondays) and folic acid once a week (on Thursdays), and osteoporosis, treated with alendronate once a week (on Wednesdays, first thing, before food). The rest of her medicines are daily. She is walking about and her VTE risk is low. It is Wednesday, 0730.',
  start: [30, 11, 2026], now: '3@0730',
  patient: { family: 'ANDERSON', given: 'Elizabeth', called: 'Betty', gender: 'F', dob: '22/09/1947', nhi: 'ZHQ2096', weight: 61, height: 158 },
  prescribers: [
    { id: 'hr', name: 'RURU, Hana · Ortho Registrar', sig: 'HRuru', reg: '48812' },
    { id: 'sp', name: 'PATEL, Sam · House Officer', sig: 'SPatel', reg: '51234' },
  ],
  nurses: [
    { name: 'WALSH, Ben · RN', init: 'BW', reg: '240116' },
    { name: 'HALL, Jess · RN', init: 'JH', reg: '233870' },
    { name: 'KEREAMA, Aroha · RN', init: 'AK', reg: '231907' },
    { name: 'MOANA, Pita · RN', init: 'PM', reg: '226341' },
    { name: 'TANE, Lisa · RN', init: 'LT', reg: '198443' },
  ],
  allergies: [{ med: 'SULFASALAZINE', rx: 'Rash', by: 'hr' }],
  adverse: [], adverseBy: 'hr',
  special: [], supplementary: [],
  vte: { by: 'hr', day: 1, anticoag: false, none: 'low', stockings: false, ipc: false },
  regular: [
    { L: 'I', day: 1, at: '1@0500', startT: '0800', days: [1, 8], med: 'METHOTREXATE', dose: '10', units: 'mg', route: 'PO', freq: 'WEEKLY — Mon', times: '0800', by: 'hr', inst: 'ONCE A WEEK — MONDAYS ONLY',
      given: { '1@0800': '0815 LT' } },
    { L: 'J', day: 1, at: '1@0500', startT: '0800', days: [4], med: 'FOLIC ACID', dose: '5', units: 'mg', route: 'PO', freq: 'WEEKLY — Thu', times: '0800', by: 'hr', inst: 'Weekly, never on the methotrexate day' },
    { L: 'K', day: 1, at: '1@0500', startT: '0600', days: [3], med: 'ALENDRONATE', dose: '70', units: 'mg', route: 'PO', freq: 'WEEKLY — Wed', times: '0600', by: 'hr', inst: 'Before food, full glass of water, upright 30 min',
      given: { '3@0600': '0600 AK' } },
    { L: 'L', day: 1, at: '1@0500', startT: '0800', med: 'PREDNISONE', dose: '5', units: 'mg', route: 'PO', freq: 'mane', times: '0800', by: 'hr', inst: 'With food',
      given: { '1@0800': '0815 LT', '2@0800': '0810 LT' } },
    { L: 'M', day: 1, at: '1@0500', startT: '0800', med: 'OMEPRAZOLE', dose: '20', units: 'mg', route: 'PO', freq: 'mane', times: '0800', by: 'hr',
      given: { '1@0800': '0815 LT', '2@0800': '0810 LT' } },
    { L: 'N', day: 1, at: '1@0500', startT: '0600', med: 'PARACETAMOL', dose: '1', units: 'g', route: 'PO', freq: 'QID', times: '0600 1200 1800 2200', by: 'hr', inst: 'Max 4 g in 24 h from all sources',
      given: { '1@0600': 'AK', '1@1200': '1210 LT', '1@1800': 'BW', '1@2200': 'BW', '2@0600': 'AK', '2@1200': '1205 LT', '2@1800': 'BW', '2@2200': 'BW', '3@0600': 'AK', '3@1800': 'BW', '3@2200': 'BW', '4@0600': 'AK' } },
  ],
  prn: [
    { L: 'A', day: 1, at: '1@0500', med: 'OXYCODONE', dose: '2.5', range: '2.5 – 5', units: 'mg', route: 'PO', freq: 'q4h', max: '15 mg', gapH: 4, maxAmount: 15, ind: 'Wrist pain', by: 'hr', inst: 'Controlled drug',
      given: ['1@0520 2.5mg PO AK/PM', '1@1400 2.5mg PO LT/JH', '2@2200 2.5mg PO BW/JH', '3@0500 2.5mg PO AK/PM'] },
  ],
  questions: [
    { id: 'alen', tag: 'Regular', q: 'Why was Betty’s alendronate given at 0600, before breakfast?', a: 'Food stops it working — and she must stay upright',
      w: ['So the night nurse could give it, not the day nurse', 'It keeps her awake, so it must be early', 'It works only while the patient is asleep'],
      show: ['reg.K.inst', 'reg.K.d3.s0.gc'], why: 'The order’s instructions: before food, with a full glass of water, and upright for 30 minutes — food blocks it, and lying down lets it burn the gullet.' },
    { id: 'mtxlast', tag: 'Regular', q: 'When was Betty’s methotrexate last given?', a: 'Monday 30/11 at 0815 — it is weekly',
      w: ['This morning at 0815, with her other tablets', 'Every day this week at 0800', 'It has not been given on this chart'],
      show: ['reg.I.d1.s1.t', 'reg.I.d1.s1.gc'], why: 'Row I: one signature, on Monday. Every other day is ruled off — the next dose is Monday 7/12.' },
  ],
  rounds: [
    { at: '3@0810', rn: 'LT', title: '0800 med round',
      brief: ['Your first morning with Betty and Lisa Tane (RN, initials LT). You have not signed Betty’s chart before.',
        'Betty had her alendronate at 0600 with the night nurse, and has sat up since. Her breakfast has just arrived.',
        '0810 — with Lisa checking, you give Betty every medicine due at 0800 today.'],
      ask: [{ id: 'r1mtx', tag: 'Regular', q: 'Row I (methotrexate) has an 0800 time. Is it due today, Wednesday?', a: 'No — Mondays only; today is ruled off',
        w: ['Yes — it is charted for 0800 every day', 'Yes — give it now, and again on Monday', 'Only if her joints are painful today'],
        show: ['reg.I.freq', 'reg.I.inst', 'reg.I.d3.s1.gc'], why: 'Weekly methotrexate given daily by mistake has killed people. Its Frequency and instructions say Mondays only, and every other day is ruled off.' }],
      expect: [
        { do: 'reg' },
        { do: 'sign', c: 'reg.L.d3.s1', t: '0810' },
        { do: 'sign', c: 'reg.M.d3.s1', t: '0810' },
        { do: 'none', c: 'reg.I.d3', what: 'Methotrexate (row I)', why: 'weekly, on Mondays only — today is ruled off.' },
        { do: 'none', c: 'reg.J.d3', what: 'Folic acid (row J)', why: 'weekly, on Thursdays — today is ruled off.' },
      ] },
    { at: '3@1210', rn: 'LT', title: 'Midday',
      brief: ['1205 — with Lisa checking, you give Betty her 1200 paracetamol.',
        '1210 — her wrist throbs (6/10) after the plaster check. After checking her chart with Lisa, you give oxycodone 2.5 mg PO.'],
      ask: [{ id: 'r2oxy', tag: 'PRN', q: 'Can Betty have oxycodone at 1210?', a: 'Yes — last at 0500; 5 mg of 15 mg in 24 h',
        w: ['No — she had some at 0500, so not until tomorrow', 'No — she has had her 15 mg maximum', 'Yes — but only if she is asleep afterwards'],
        show: ['prn.A.max', 'prn.A.2.time', 'prn.A.3.time'], why: 'q4h on the order: 0500 + 4 h = 0900. Since 1210 yesterday: 2200 and 0500, 2.5 mg each.' }],
      expect: [
        { do: 'sign', c: 'reg.N.d3.s2', t: '1205' },
        { do: 'prn', L: 'A', dose: ['2.5mg', '2.5 mg', '2.5'], route: 'PO', t: '1210' },
      ] },
    { at: '4@0810', rn: 'LT', title: 'Thursday: 0800 med round',
      brief: ['Thursday — your second morning with Betty and Lisa (LT).',
        '0810 — with Lisa checking, you give Betty every medicine due at 0800 today.'],
      ask: [{ id: 'r3fol', tag: 'Regular', q: 'Folic acid (row J) is weekly. Is it due today, Thursday?', a: 'Yes — Thursdays; the other days are ruled off',
        w: ['No — it goes with the methotrexate on Monday', 'No — folic acid is only ever given at night', 'Yes — it is due every day at 0800'],
        show: ['reg.J.freq', 'reg.J.inst'], why: 'Its Frequency says Thursday, and the instructions say never on the methotrexate day. Today’s box is the only one left open this week.' }],
      expect: [
        { do: 'sign', c: 'reg.J.d4.s1', t: '0810' },
        { do: 'sign', c: 'reg.L.d4.s1', t: '0810' },
        { do: 'sign', c: 'reg.M.d4.s1', t: '0810' },
        { do: 'none', c: 'reg.I.d4', what: 'Methotrexate (row I)', why: 'weekly, on Mondays only — ruled off today.' },
        { do: 'none', c: 'reg.K.d4', what: 'Alendronate (row K)', why: 'weekly, on Wednesdays — it was given yesterday at 0600.' },
      ] },
  ],
};
